### ISSUE TITLE
azure: use DNS labels to glue IPs to LBs

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#100]
Based on a suggestion from MS folks. This mapping allows more flexibility for when the load balancer IP address changes. Their DNS service will automatically update those records.

The current implementation is probably better to make this function the same across multiple providers, but I'd put this in the "make it work natively on the platform" bucket.

**Comment by cehoffman** [comment]
I was looking at doing this. Is the idea that the record in the tectonic dns zone for example `<cluster-name>-k8s.<base_domain>` would be a CNAME pointing to the public ip `<dns label>.<region>.cloudapp.azure.com`? I'm not seeing special fields on a DNS record for linking to a public ip. I also don't see what this has to do with the LB other than a LB uses the created public ip.
