### ISSUE TITLE
Ensure hostPort works with Calico/CNI with k8s 1.7

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#1000]
See discussion here:
https://github.com/kubernetes/kubernetes/issues/23920

Once kubernetes 1.7 is released.

**Comment by philips** [comment]
This is testable now via 1.7 alpha releases.

**Comment by sym3tri** [comment]
@aaronlevy @s-urbaniak @abhinavdahiya Can any of you confirm if this is working? If so please close the issue.

**Comment by aaronlevy** [comment]
I won't be able to look into this, and @abhinavdahiya is back in school.
