### ISSUE TITLE
etcd operator is creating gce persistent disk for potential backup regardless of platforms

### ISSUE THREAD

**Issue by yifan-gu** [coreos/tectonic-installer#1008]
## What keywords did you search in tectonic-installer issues before filing this one?

etcd operator, backup.

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

* Tectonic version (current master 2bd6bb8317af8c63b1eacf38f2a7ce2683f331db):
* Terraform version (`Terraform v0.9.6`):
* Platform (aws):

## What happened?

After launching the cluster, the backup storage of etcd shows type as gce-pd

## What you expected to happen?

It should be platform specific.

## How to reproduce it (as minimally and precisely as possible)?

1. Create a cluster on aws platform
2. Run `kubectl get storageclass`, you will get 
```shell
NAME                 TYPE
etcd-backup-gce-pd   kubernetes.io/gce-pd   
```

## Anything else we need to know?

This probably happens to bootkube as well.

/cc @aaronlevy @alekssaul @hongchaodeng @s-urbaniak @sym3tri @xiang90

**Comment by alekssaul** [comment]
At a quick glance, it looks like GCE-PD is the default selection for the configuration flag; https://github.com/coreos/etcd-operator/blob/bbef7817b34bbea08d018ad686dac37c0f2bf179/cmd/operator/main.go#L76 . Perhaps bootkube deployment assets need to be adjusted based on cloud platform?

**Comment by chuckbutler** [comment]
Thats insightful. I can confirm I see the same behavior with a 1.6.4 deployed tectonic  post => 1.6.7 upgrade path.
