### ISSUE TITLE
S3 configuration bucket doesn't have logging and versioning activated

### ISSUE THREAD

**Issue by pollosp** [coreos/tectonic-installer#1009]
## What keywords did you search in tectonic-installer issues before filing this one?

* S3
* S3 Configuration bucket
* S3 Config bucket

## FEATURE REQUEST

Right now we have realise that config bucket doesn't have `Versioning` and `Logging` activated, in our opinion will be nice if it cloud have versioning and logging at least optionally in the tectonic installer.
We can do a post installation task in our scripts, but we think that would be nice to include this in the main distribution. 

## Versions

* Tectonic version 1.6.2
* Terraform version 0.94
* Platform AWS

## What you expected to happen?

Have logging and versioning into the configuration bucket

## How to reproduce it (as minimally and precisely as possible)?

Check s3 create during the bootstrap

## Anything else we need to know?

🦑

**Comment by robszumski** [comment]
What type of information are you looking to audit? How do you use this info with other buckets in S3?

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
