### ISSUE TITLE
openstack - support spreading the cluster across multiple AZs

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#101]
Customer is interested in using Openstack Availability Zone metadata to spread Tectonic cluster to multiple AZs. Customer currently treats each rack as an availability zone.

Ideally allow Tectonic tiers (etcd/worker/controller planes) to be spread to multiple AZs. Also allow exposure of the data so the applications can be deployed to multiple AZs. 

Terraform seem to have the Availability Zone argument in; https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#availability_zone . Per customer the data is available via Openstack metadata;http://169.254.169.254/latest/meta-data/placement/availability-zone and thru API in https://docs.openstack.org/developer/glance/metadefs-concepts.html . I believe this information is also imported when --cloud-provider=openstack is enabled ; https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L483-L496

**Comment by s-urbaniak** [comment]
openstack implies a very high variance of configuration options. I am unsure if we want to support all of them other than having two sample configurations.

Is it feasible to add a local `platforms/openstac/az` flavor in the customer's fork rather than extending the current ones?

**Comment by sym3tri** [comment]
We're currently working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. We'll post a link to the new repo in the README once it's ready.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
