### ISSUE TITLE
Hostname mismatch causes conformance failures on AWS

### ISSUE THREAD

**Issue by ethernetdan** [coreos/tectonic-installer#1018]
Running conformance tests on Tectonic AWS results in the following failures:
```
Networking Granular Checks: Pods should function for node-pod communication: http
Networking Granular Checks: Pods should function for intra-pod communication: udp
Networking Granular Checks: Pods should function for node-pod communication: udp
Networking Granular Checks: Pods should function for intra-pod communication: http	
```
https://jenkins-tectonic-installer.prod.coreos.systems/job/tectonic-conformance/65/console

These failures are caused by an assumption in the upstream networking which expects that the label `kubernetes.io/hostname` on a Node will always match it's name. The framework [attempts to create a Pod](https://github.com/coreos/kubernetes/blob/v1.6.4+coreos.0/test/e2e/common/networking.go#L34) to perform tests in using the [label as a NodeSelector](https://github.com/coreos/kubernetes/blob/v1.6.4+coreos.0/test/e2e/framework/networking_utils.go#L357). Since on Tectonic AWS the selector never matches a Node the Pod timesout being created resulting in the error message returned:
```
Expected error:
<*errors.errorString | 0xc420420940>: {
      s: "timed out waiting for the condition",
}
timed out waiting for the condition
not to have occurred
```

These tests pass on upstream GCE and bootkube because the Node name matches the hostname as returned by `hostname`, however on the cloud provider integration for AWS sets the Nodes to their full AWS host including region. For example on Tectonic AWS, `hostname`="ip-10-0-5-95" while Node name="ip-10-0-5-95.us-west-2.compute.internal"

**Possible resolutions:**
1. Modify upstream tests to target Nodes in a different way. For example, directly specifying `nodeName` rather than using `nodeSelector`. Downside is an upstream change.
2. Manually override Node name in our tests to match the Nodes hostname. Downside is testing a configuration different than what is being deployed.

Of the options I prefer 1.

**Comment by ethernetdan** [comment]
In the merge queue, looks like this should make 1.7. I'll keep this open until we put out a 1.7 release and run conformance.

**Comment by ethernetdan** [comment]
Merged!

**Comment by squat** [comment]
@ethernetdan great work getting this upstream. Do we need to modify the hostname label we assign our nodes now or is this done?

**Comment by ethernetdan** [comment]
@squat done!
