### ISSUE TITLE
modules/*: Add ability to instantiate a jumpbox

### ISSUE THREAD

**Issue by justaugustus** [coreos/tectonic-installer#1029]
(there was some discussion of this for Azure on #991 and #1013)

There are a few instances where it would be nice to be able to create a jumpbox which has access to the Tectonic cluster, whether it be a restrictive client environment or for internal testing.

We currently have some work on this downstream for a customer on Azure.
The intent would be to clean this up for upstream, and then per @s-urbaniak & @alexsomesan's suggestions, extend this feature to each platform.

**Comment by squat** [comment]
cc @robszumski

**Comment by sym3tri** [comment]
Will consider for converged platform.

https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
