### ISSUE TITLE
AWS: Upload entire Ignition config rather than individual files

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#103]
Instead of uploading individual files (i.e. kubeconfig, init-master.sh) to S3 and pulling them back individually, we should upload the whole Ignition stack to S3. The reason is that eventually, even if we continue uploading these files, we will end up hitting the UserData size limit again. It is also much more complex to manage and maintain.

- Adding support for straight up S3 pulls in Ignition (so it can pull the S3 object directly)
- Adding a new Terraform resource for creating Signed S3 URLs (so the object can be provided to Ignition as a https:// link, which it supports)

**Comment by alexsomesan** [comment]
Iginition can already pull from remote HTTP sources.
S3 pre-signed URLs are meant to be accessed by plain HTTP clients (hence the need for pre-signing them).
So if we generate pre-signed URLs we don't need to implement S3 support specificaly in Ignition.
Also, if we implement S3 support in Ignition, we don't need to use pre-signed URLs anymore.

On the other hand, pre-signed URLs are time bound. They expire after a maximum of 7 days, after wich they can no longer be used. That means that launching instances in a cluster created longer than 7 days before would fail. That's currently a hard limitation in S3 and can't be circumvented.

Seems that S3 support for ignition is the only way to go.

**Comment by alexsomesan** [comment]
Explanation of the AWS signature process is here: http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

See `X-Amz-Expires` parameter for details on the 7 days limit.

**Comment by Quentin-M** [comment]
> Iginition can already pull from remote HTTP sources.
> S3 pre-signed URLs are meant to be accessed by plain HTTP clients (hence the need for pre-signing them).
> So if we generate pre-signed URLs we don't need to implement S3 support specificaly in Ignition.

That's what I meant, yes.

> On the other hand, pre-signed URLs are time bound. They expire after a maximum of 7 days, after wich they can no longer be used. That means that launching instances in a cluster created longer than 7 days before would fail. That's currently a hard limitation in S3 and can't be circumvented.

I was not aware of this but had my doubts yeah. It doesn't described on the documentation page about the S3 Pre-Signed URL.

> Seems that S3 support for ignition is the only way to go.

Sounds good. It is a better approach anyways.

**Comment by Quentin-M** [comment]
Discussed with @crawford and suggested my help. This is part of their road-map and will likely be ready in about a month. I will make the changes on the Terraform side of things once ready.

**Comment by Quentin-M** [comment]
Blocked on https://github.com/coreos/ignition/pull/382.

**Comment by Quentin-M** [comment]
S3 Support in Ignition is in v0.17.1, which is in CoreOS 1465.0.0 - currently Alpha! https://github.com/coreos/ignition/pull/382
