### ISSUE TITLE
aws: Amazon assigns 100 IOPS to gp2 storage device causing terraform to destroy etcd on apply after create

### ISSUE THREAD

**Issue by badbeeker** [coreos/tectonic-installer#1035]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

* Tectonic version: master commit e99319a
* Terraform version (`terraform version`): v0.9.4
* Platform (aws|azure|openstack|metal): aws

## What happened?
After creating a new cluster via terraform apply, performing a terraform plan shows that the ectd instances will be destroyed due to the root_block_device iops being set to 0.  

The defaults for the root_block_device for ectd nodes are:
etcd_root_volume_type: gp2
etcd_root_volume_size: 30
etcd_root_volume_iops: 100

## What you expected to happen?
No changes to the etcd nodes if no variables have changed in terraform.tfvars from the user.

## How to reproduce it (as minimally and precisely as possible)?
1. Create a new cluster via terraform apply with defaults for root_volumes for etcd
2. After create, perform a terraform plan

## Anything else we need to know?
It seems that the etcd_node resource in `modules/aws/etcd/nodes.tf` develops a bug once a cluster exists:

```
resource "aws_instance" "etcd_node" {
  count = "${length(var.external_endpoints) == 0 ? var.instance_count : 0}"
  ami   = "${data.aws_ami.coreos_ami.image_id}"

  instance_type          = "${var.ec2_type}"
  subnet_id              = "${element(var.subnets, count.index)}"
  key_name               = "${var.ssh_key}"
  user_data              = "${data.ignition_config.etcd.*.rendered[count.index]}"
  vpc_security_group_ids = ["${var.sg_ids}"]

  lifecycle {
    # Ignore changes in the AMI which force recreation of the resource. This
    # avoids accidental deletion of nodes whenever a new CoreOS Release comes
    # out.
    ignore_changes = ["ami"]
  }

  tags = "${merge(map(
      "Name", "${var.cluster_name}-etcd-${count.index}",
      "kubernetes.io/cluster/${var.cluster_name}", "owned",
      "tectonicClusterID", "${var.cluster_id}"
    ), var.extra_tags)}"

  root_block_device {
    volume_type = "${var.root_volume_type}"
    volume_size = "${var.root_volume_size}"
    iops        = "${var.root_volume_type == "io1" ? var.root_volume_iops : 0}"
  }
}
```

Amazon assigns 100 iops for general purpose root devices (at least on t2.mediums).  The config here set's it to zero if the user chooses to use gp2.  This causes terraform to destroy the instance and recreate it.  The user can't even set the variable to 100 for the match to override it due to the conditional setting it to 0.  The user would need to modify this file and replace 0 to 100 so that terraform sees it as not changed.

Even though this same logic is used for the master and worker nodes, in those situations the installer is creating a launch configuration which seems to hold the value at 0; therefore no changes are made.  Due to actually launching etcd instances without an auto-scaling-group, terraform sees that the root_block_device is 100 and therefore needs to destroy the instance to set it back to zero.

Is there a reason why the etcd nodes are not in a ASG (not an ectd expert, perhaps a bigger discussion)?  Quick solution would be to change 0 to 100 if the user is using the general purpose ssd.

**Comment by Quentin-M** [comment]
Thanks for the report. We have actually seen that recently and this needs to be addressed ASAP.

Running an etcd cluster in an ASG is non-trivial and generally not recommended. Extra logic and care is needed for scaling operations.

cc @s-urbaniak @alexsomesan

**Comment by Quentin-M** [comment]
Repro'd with a tfvars file that did not specify specifying `root_volume_type`:

```
-/+ module.etcd.aws_instance.etcd_node
    ami:                                       "ami-c72a32a1" => "ami-c72a32a1"
    associate_public_ip_address:               "false" => "<computed>"
    availability_zone:                         "eu-west-1a" => "<computed>"
    ebs_block_device.#:                        "0" => "<computed>"
    ephemeral_block_device.#:                  "0" => "<computed>"
    instance_state:                            "running" => "<computed>"
    instance_type:                             "t2.medium" => "t2.medium"
    ipv6_address_count:                        "0" => "<computed>"
    ipv6_addresses.#:                          "0" => "<computed>"
    key_name:                                  "qmachu" => "qmachu"
    network_interface.#:                       "0" => "<computed>"
    network_interface_id:                      "eni-828ed4bf" => "<computed>"
    placement_group:                           "" => "<computed>"
    primary_network_interface_id:              "eni-828ed4bf" => "<computed>"
    private_dns:                               "ip-10-0-57-237.eu-west-1.compute.internal" => "<computed>"
    private_ip:                                "10.0.57.237" => "<computed>"
    public_dns:                                "" => "<computed>"
    public_ip:                                 "" => "<computed>"
    root_block_device.#:                       "1" => "1"
    root_block_device.0.delete_on_termination: "true" => "true"
    root_block_device.0.iops:                  "100" => "0" (forces new resource)
    root_block_device.0.volume_size:           "30" => "30"
    root_block_device.0.volume_type:           "gp2" => "gp2"
    security_groups.#:                         "0" => "<computed>"
    source_dest_check:                         "true" => "true"
    subnet_id:                                 "subnet-4be74602" => "subnet-4be74602"
    tags.%:                                    "3" => "3"
    tags.Name:                                 "qmachu-etcd-0" => "qmachu-etcd-0"
    tags.kubernetes.io/cluster/qmachu:         "owned" => "owned"
    tags.tectonicClusterID:                    "97264c7d-6920-b66e-f60c-adc0a5eb9703" => "97264c7d-6920-b66e-f60c-adc0a5eb9703"
    tenancy:                                   "default" => "<computed>"
    user_data:                                 "8c30f12050145b032116d638ebdc9d02bb0bc9d4" => "8c30f12050145b032116d638ebdc9d02bb0bc9d4"
    volume_tags.%:                             "0" => "<computed>"
    vpc_security_group_ids.#:                  "1" => "1"
    vpc_security_group_ids.938187537:          "sg-cec633b6" => "sg-cec633b6"

~ module.etcd.aws_route53_record.etc_a_nodes
    records.#: "" => "<computed>"
```

**Comment by Quentin-M** [comment]
I just created https://github.com/coreos/tectonic-installer/issues/1167 in order to make sure we will create a test that will catch any idempotency issues early on.

**Comment by badbeeker** [comment]
Thanks for the updates @Quentin-M.  Glad to see this getting traction 👍

**Comment by Quentin-M** [comment]
@badbeeker Sorry for the delay, it somehow got lost in the flow of GitHub issues!
