### ISSUE TITLE
remove operators from experimental flag

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#1037]
- [ ] Move self-hosted etcd to be its own option on the etcd screen of the installer
- [ ] Deploy all other operators by default
- [ ] Remove all monitoring manifests that are currently conditionally deployed if the experimental flag is _off_ (b/c they will get deployed by the Prometheus operators)
- [ ] Remove experimental checkbox from the UI

**Comment by Quentin-M** [comment]
This involves both Terraform and frontend changes. They can be executed in parallel as long as we agree on a variable name, such as "tectonic_etcd_self_hosted" (bool).

I started hacking on the Terraform side of things but anyone should feel free to tackle this if they feel comfortable. @ggreer Do you feel like you'll be able to pull this off or maybe @kans can give it a shot? This is high priority for this sprint.

**Comment by Quentin-M** [comment]
Edited my comment above regarding to varible name change.

**Comment by Quentin-M** [comment]
The decision for now is to remove everything from the experimental flag BUT self-hosted etcd. After the code freeze, we will add a feature flag for self-hosted etcd specifically.
