### ISSUE TITLE
smoke tests should be easily runnable outside of jenkins

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#1038]
As a Tectonic developer or open-source developer there should be an easy way to run _all_ smoke tests from a laptop given the appropriate credentials. i.e. We should not _need_ to rely on Jenkins to run the tests. 

This should only need to be 1 or 2 commands that are documented clearly.

**Comment by justaugustus** [comment]
@s-urbaniak In addition, it would be really nice to have a cheatsheet on how to sanity test each component of a Tectonic cluster, as well as quick fixes for common errors.

**Comment by Quentin-M** [comment]
Documenting how to do that should help with resolving:
- https://github.com/coreos/tectonic-installer/issues/1054
- https://github.com/coreos/tectonic-installer/issues/1017
Which are top priority.

**Comment by robszumski** [comment]
I think this has merged, re-open if needed.
