### ISSUE TITLE
Create framework and add 1 Integration test from our QA checklist

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#1040]
Choose the lowest hanging easiest one.

**Comment by Quentin-M** [comment]
As discussed, this can be included in the sanity code base for now, and gated with an env variable. This will allow us to iterate quickly and get these done. There is no need for creating a full-blown framework.

**Comment by squat** [comment]
@rithujohn191 and I are splitting up this task. @Quentin-M is creating a new issue to track progress of automating the qa checklist.

**Comment by Quentin-M** [comment]
The QA Automation checklist is now on the _Tectonic Master Plan_ spreadsheet.

**Comment by squat** [comment]
PR #1150 created a lil framework for this and added the first automated QA test. Closing.
