### ISSUE TITLE
Upstream Terraform repo restructure (upcoming)

### ISSUE THREAD

**Issue by lblackstone** [coreos/tectonic-installer#1047]
FYI, [upstream Terraform](https://github.com/hashicorp/terraform) will be splitting providers out into [separate repos](https://github.com/terraform-providers). This will probably break the existing install process, as various cloud providers will not be included by default.

See [this blog post](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/) for more details.

**Comment by alexsomesan** [comment]
Thanks @lblackstone!
We've been tracking that story internally and doing test builds with the beta releases. So far everythings works as it should. 
We expect to be able to update to TF 0.10 soon after it will be released.

**Comment by jasminSPC** [comment]
@alexsomesan it seems that  terraform (Terraform v0.10.0-dev) will not work with UI installer. I just tried this and I got this error message:

```
Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.
```

Solution would be to either add `init` to `/terraform/apply` or a new endpoint `/terraform/init`. would be the solution to this.

**Comment by jasmingacic** [comment]
Terraform version 0.10.0 has been released two hours ago https://github.com/hashicorp/terraform/releases/tag/v0.10.0

**Comment by mrwacky42** [comment]
Since we already have Terraform up and running in our environment, implementing Tectonic is something of a chore because of the version mismatch. The sooner Tectonic installer can use stock Terraform and a custom plugin, the better.

**Comment by edevenport** [comment]
@mrwacky42 Terraform v0.10.0 support has been added in PR #1660 and compatibility is looking good. You can pull master or try release [v1.7.3-tectonic.1-rc.2](https://github.com/coreos/tectonic-installer/releases/tag/1.7.3-tectonic.1-rc.2). Please feel free to report any [issues](https://github.com/coreos/tectonic-installer/issues) you might encounter.

**Comment by alexsomesan** [comment]
@edevenport @mrwacky42 The complete support for TF 0.10.x in the UI installer is still being worked on. A follow-up to #1660 will soon introduce the missing piece related to bare-metal installations.
You can still make use of Terraform 0.10.x via the CLI workflow, for every platform but bare-metal.

**Comment by mrwacky42** [comment]
@alexsomesan - I dropped in the `tectonic-1.7.3-tectonic.1-rc.2` release on top of `tectonic-1.7.1-tectonic.2` Terraform tree I am testing. It looks like quite a few resources were renamed from `some-thing` to `some_thing`, causing plenty of resource churn. This doesn't appear to present a very good upgrade path.
