### ISSUE TITLE
request: Auto generate known-issues

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#1049]
We generate Known Issues in Tectonic releases, see: https://github.com/coreos/tectonic-installer/pull/810

Proposing creation of labels in github issues for Tectonic Installer and Tectonic Issues repositories. Based on a `known-issues` (and maybe `workaround`) label, we can auto generate documentation 

As a quick demonstration

`curl -s https://api.github.com/repos/coreos/tectonic-installer/issues | jq '.[] | select(.labels[].name=="kind/documentation") | .title + " - [" + (.number|tostring)  + "](" + .html_url + ")"' |  tr -d '"'`

command finds all issues/PRs labeled as `kind/documentation` and will generate a string such as 
```
docs: updating master node label. - [1046](https://github.com/coreos/tectonic-installer/pull/1046)
docs: updating VPC peering note. - [1041](https://github.com/coreos/tectonic-installer/pull/1041)
smoke tests should be easily runnable outside of jenkins - [1038](https://github.com/coreos/tectonic-installer/issues/1038)
docs: adding pointer to requirements doc. - [1032](https://github.com/coreos/tectonic-installer/pull/1032)
```

**Comment by sym3tri** [comment]
interesting idea, but now that most docs issues are tracked in internally i'll close this out. maybe discuss directly w/docs team?
