### ISSUE TITLE
Restore Windows support

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#1051]
We should try to add back Windows binaries into our releases sooner rather than later to minimize the amount of work required to repair the support.

However, this should absolutely come hand to hand with testing (https://github.com/coreos/tectonic-installer/issues/460). Without tests, the installer will likely break without us noticing (again) and the story (https://github.com/coreos/tectonic-installer/pull/495, https://github.com/coreos/tectonic-installer/pull/709, https://github.com/coreos/tectonic-installer/pull/730) will repeat.

**Comment by Quentin-M** [comment]
Let's discuss of requirements / plan / timeline for this.

**Comment by alekssaul** [comment]
@Quentin-M , wanted to note that we use `/dev/null` for few variables throughout the repo. I am not sure if this belong here, but I imagine those will break in a Windows environment.

**Comment by sym3tri** [comment]
This is now tracked in jira
