### ISSUE TITLE
Split DNS not working when using existing VPC

### ISSUE THREAD

**Issue by everydaynerd** [coreos/tectonic-installer#1058]
## Versions

* Tectonic version: 1.6.4 
* Terraform version: v0.9.6
* Platform: aws

## What happened?
When using an existing VPC, I followed the directions here:  [Using an existing VPC](https://coreos.com/tectonic/docs/latest/install/aws/requirements.html#using-an-existing-vpc) 

After `terraform apply` the bootkube service would not start. After troubleshooting, noticed that the etcd service wasn't started - with errors of name resolution.  

SSH into etcd, master or worker node, and was unable to `nslookup` any address when setting the name server to one of the NS in the private DNS zone.  If set to a public DNS NS, worked it was able to resolve, but not records in the private DNS zone.

Found the [AWS documentation](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html) for split DNS, and it requires:

```
To use private hosted zones, you must set the following Amazon VPC settings to true:
- enableDnsHostnames
- enableDnsSupport
```

## What you expected to happen?
I expected the [documentation](https://coreos.com/tectonic/docs/latest/install/aws/requirements.html#using-an-existing-vpc)  to indicate that the VPC settings must be set if using an existing VPC

## How to reproduce it (as minimally and precisely as possible)?
Create a VPC, and do **not** set the DNS Hostname to yes (default behaviour) 
Create the subnets, routing tables, internet gateway and nat gateway as needed for Tectonic installer.
Use the installer, specify existing VPC, and to use the Private DNS zone.

Bootkube service will not start, nor will DNS resolution work correctly.

**Comment by alekssaul** [comment]
@s-urbaniak , I believe we should tag this as documentation. Essentially, it's a VPC setting that needs to be enabled when end users join an existing VPC. This information is lacking from the documentation.

**Comment by sym3tri** [comment]
Fixed in master. Will be in the Sept release.
