### ISSUE TITLE
Proposal: Consolidate openstack installers

### ISSUE THREAD

**Issue by lblackstone** [coreos/tectonic-installer#1062]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

To minimize maintenance complexity, I'd suggest consolidating the `nova` and `neutron` installers into a single installer. Extra features that may not be commonly installed in OpenStack environments could be toggled with feature flags.

Known issues that should be fixed prior to removing the `nova` installer:

- [x] https://github.com/coreos/tectonic-installer/issues/1055
- [X] https://github.com/coreos/tectonic-installer/issues/1061

**Comment by s-urbaniak** [comment]
I agree with this proposal and the removal of the `nova` platform. Neutron is getting wider adoption as times moves forward, hence maintaining a pure nova platform is less and less desirable.

**Comment by lblackstone** [comment]
@s-urbaniak It appears that multi-node external etcd is currently broken on both openstack installers (#1055). Are you ok proceeding with the merge and then sorting out that bug once they have been consolidated into a single installer?

**Comment by s-urbaniak** [comment]
@lblackstone sorry for the late reaction, but we have been traveling for meetups/presentations. I am definitely ok with the merge, i.e. remove `nova` and pull the `neutron` folder up. I can tackle this unless you want to do it :-)

**Comment by lblackstone** [comment]
@s-urbaniak Sure, I'll let you handle this since you're offering :) You probably have a better idea of docs, etc that might need to be updated.

**Comment by s-urbaniak** [comment]
@lblackstone ack, I will remove nova so we can concentrate on neutron.
