### ISSUE TITLE
remove `[...]` when passing list variables in terraform templates

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/tectonic-installer#1071]
Today we found the first precedence where terraform explicitly needed to have `[ ... ]` qualifiers to be *removed* from templates in https://github.com/coreos/tectonic-installer/pull/1026#discussion_r121675480.

This is strange since we use this construct everywhere. Having said that with the introduction of types it should not be necessary to declare list variables like that anymore, hence we should remove these qualifiers all over the code base.

/cc @alexsomesan @discordianfish

**Comment by jasminSPC** [comment]
@s-urbaniak I've just checked this with Hashicorp and according to them with or without `[]` will result in same. There has been some limitation introduced with 0.8 and 0.9 but now both version are supported. I will have to check with one more guy in Hashicorp to confirm. 

I trie to use both ways on some examples and both would result work finet. Like this: (this is a sandbox TF infrastructure I played with)

variables.tfvars
```
testlist = ["1", "2", "3"]
```

main.tf
```
variable "testlist" {
  type = "list"
  default = []
}

resource "..." "test" {
...
    ssh_key_path = ["${var.testlist}"]
...
}
```

**Comment by jasminSPC** [comment]
So I've got an answer from Hashicorp they are saying that with version 0.11.0 the "old way" which needed extra brackets and introduce one way of declaring lists and maps. But for the time being either way is valid. 

With upcoming versions it will be possible to validate the syntax with `terraform validate`.

**Comment by edevenport** [comment]
The unnecessary brackets have been removed from the provider templates and the related PRs merged. A new issue should be opened if new locations are identified.
