### ISSUE TITLE
docs: clarify usage of ssh-agent with the installer

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#1078]
Documentation and/or GUI is not clear about the usage of the ssh-agent for the installer. The only mention is on the [BM with TF guide](https://coreos.com/tectonic/docs/latest/install/bare-metal/metal-terraform.html) and in the BM installer screen

> ![image](https://user-images.githubusercontent.com/755540/27107216-cae54666-504b-11e7-92e0-341987689a68.png)

> A SSH keypair whose private key is present in your system's ssh-agent.

Improvements:
 - link to what an SSH agent is
 - section in docs on how to add your key, start it and verify it is running

Related issues: https://github.com/coreos/tectonic-forum/issues/139 https://github.com/coreos/tectonic-installer/issues/537

**Comment by zbwright** [comment]
is this what you're looking for, @robszumski ?
link to ssh agent: https://linux.die.net/man/1/ssh-agent or https://en.wikipedia.org/wiki/Ssh-agent
how to add the key and etc. (although I don't think we should link to this page): https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

**Comment by zbwright** [comment]
we're going to add a note to the bare metal installation requirements.md - just trying to figure out exactly what that note should be.

**Comment by robszumski** [comment]
Related: https://github.com/coreos/tectonic-installer/issues/800

**Comment by ErnestG4** [comment]
@zbwright   Something like:

"Check if a key already exists in the installer machine's ssh agent using `ssh-add -l`. If a key needs to be added to the agent, use `ssh-add Path/ToYour/KeyFile`. Note that on OSX it may be necessary to re-add keys from your keyring to the agent on each login.

**Comment by robszumski** [comment]
That sounds good to me. @ErnestG4 do you think this requires its own doc?

**Comment by ErnestG4** [comment]
What is the current vision for the users' documentation experience?

I think it's best to have a single doc for a new user to reference if possible. I'd like to have one unified doc for each platform (baremetal, aws, azure) with this included as an "infrastructure" requirement along with PXE, DNS, etc. after the hardware requirements. As it stands the hardware requirements are broken out.

As such I'm against splitting the docs in general, but I'm on board if you guys have a different plan.

**Comment by zbwright** [comment]
I agree, and was planning to have this added to the requirements.md for bare metal. We'll also list it in the Prerequisites section of metal-terraform.md, and point back to requirements.md from there.

**Comment by vtlrazin** [comment]
I agree too about documentation update. But additional way may be add ssh_private_key_path variable to 
terraform.tfvars template.

**Comment by zbwright** [comment]
https://github.com/coreos/tectonic-installer/pull/1190

**Comment by zbwright** [comment]
doc updated. closing.
