### ISSUE TITLE
vmware: support for datastore clusters

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#1087]
## Versions

* Tectonic version 
1.6.X
* Terraform version (`terraform version`):
0.9.6
* Platform (aws|azure|openstack|metal):
vmware 

## What happened?
Upstream terraform for VMware doesn't support datastore clusters. This stops users from provisioning to datastore clusters. 

## What you expected to happen?
Storage clusters to be supported as a datastore.

## How to reproduce it (as minimally and precisely as possible)?
Attempt to use datastore cluster for; `tectonic_vmware_datastore` variable.

## Anything else we need to know?
This is an upstream issue tracked in; https://github.com/terraform-providers/terraform-provider-vsphere/issues/2#issue-235555835

https://github.com/coreos/tectonic-installer/pull/1082 works around this by setting formatting to storagedatastore\datastore .

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
