### ISSUE TITLE
vmware: make tectonic license and pull secret optional

### ISSUE THREAD

**Issue by bboerst** [coreos/tectonic-installer#1111]
## Versions

* Tectonic version:  1.6.X
* Terraform version:  0.9.6
* Platform:  vmware

## What happened?
When setting `tectonic_vanilla_k8s = true`, terraform is not ignoring the `tectonic_pull_secret_path` and `tectonic_license_path`.

The following errors are triggered:
```
* module.tectonic.template_dir.tectonic: 1 error(s) occurred:
* module.tectonic.template_dir.tectonic: file: open : no such file or directory in:
${base64encode(file(var.pull_secret_path))}
```
and
```
* module.tectonic.template_dir.tectonic: 1 error(s) occurred:
* module.tectonic.template_dir.tectonic: file: open : no such file or directory in:
${base64encode(file(var.license_path))}
```

## What you expected to happen?
terraform should ignore the `tectonic_pull_secret_path` and `tectonic_license_path` variables.

## How to reproduce it (as minimally and precisely as possible)?
For platform vmware, set `tectonic_vanilla_k8s = true` and leave `tectonic_license_path = ""` and `tectonic_pull_secret_path = ""`

## Anything else we need to know?
The issue is with these two lines:
https://github.com/coreos/tectonic-installer/blob/a3bc031ac452ae64d4ebd31cea8cff3db54c21d6/platforms/vmware/tectonic.tf#L51-L52

They should be modified to match what has already been fixed in #723 :
```
license_path     = "${var.tectonic_vanilla_k8s ? "/dev/null" : pathexpand(var.tectonic_license_path)}"
pull_secret_path = "${var.tectonic_vanilla_k8s ? "/dev/null" : pathexpand(var.tectonic_pull_secret_path)}"
```

I can get a PR submitted when I get a chance.

**Comment by squat** [comment]
thanks for catching this, @bboerst! I just created #1112 to address this.
