### ISSUE TITLE
TLS support for self hosted etcd cluster

### ISSUE THREAD

**Issue by xiang90** [coreos/tectonic-installer#1113]
etcd operator already supports TLS for self hosted cluster. And we are finishing up the TLS support for bootkube: https://github.com/kubernetes-incubator/bootkube/pull/592.

Since tectonic installer does not use bootkube render directly, we still need to make changes in tectonic installer to support TLS.

/cc @hongchaodeng @robszumski @s-urbaniak

**Comment by hongchaodeng** [comment]
ref https://github.com/kubernetes-incubator/bootkube/issues/582
The render code are in step 1, 2

**Comment by Quentin-M** [comment]
Assigning this to you @s-urbaniak as you've been working on it for the statically provisioned etcd. Tell me if you'd like someone else to do it :)

**Comment by Quentin-M** [comment]
Tentatively adding release blocker. Will see how it goes.
