### ISSUE TITLE
Update to Kubernetes/Bootkube/Hyperkube to v1.6.6

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#1114]

**Comment by diegs** [comment]
In case you didn't see, we released new hyperkube on Friday.

https://github.com/coreos/kubernetes/releases/tag/v1.6.6%2Bcoreos.0
https://quay.io/repository/coreos/hyperkube?tag=latest&tab=tags

**Comment by Quentin-M** [comment]
Thanks @diegs!
