### ISSUE TITLE
Make sure resources are all tagged

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#1115]
Tracking the issue mentioned in https://github.com/coreos/tectonic-installer/pull/218#issuecomment-308591039.

The fix should be in the next release.

**Comment by Quentin-M** [comment]
Would there be a way to add an automated test for that one?

**Comment by robszumski** [comment]
Automated tests would be great. Manually booting 1.6.4 release shows that these items are tagged with custom tags:

 - security groups
 - VPC
 - Subnets

Not tagged with custom tags:

 - EC2 vms
 - ELBs
 - ASGs

Not tagged at all:

 - EBS volumes
 - Internet Gateways
 - Security groups

**Comment by Quentin-M** [comment]
Assigning to @estroz avec discussed offline! Thanks!

**Comment by estroz** [comment]
Tags by Resource Types as of 1.6.4:

*: Only some were tagged, not all

Resource Type | ClusterID | Extra tags
:--- | :---: | :---:
Instance | x | x*
ELB | x | x
Security Group | x | x 
Route53 HostedZone | x | x
Route Table | x | 
Subnet | x |
VPC | x | x
Internet Gateway |  | 
Volume |  |
S3 Bucket |  | 
Autoscaling Group | x | 

Note:
- ASG-controlled instances do not get extra tags

**Comment by rithujohn191** [comment]
Needs more investigation for desired user experience.

**Comment by robszumski** [comment]
In the planning meeting we discussed:

 - upstream Terraform doesn't support tagging for all resource types
 - we could ship a binary that uses the raw APIs to accomplish this

I have reached out to our AWS contacts to see if they can lend any resources to improving the terraform support.

Shipping a separate binary or requiring users to interact with the raw providers API does not meet our UX requirements.

@estroz what was the limitation around tagging the auto-scaled instances?

**Comment by estroz** [comment]
All resource types that support tagging in AWS can be tagged by Terraform
if explicitly created. However, default resources, ex. network interfaces
created when creating an EC2 instance, or a resource created when creating
a parent, cannot be tagged in certain cases.

Regarding volumes of auto-scaled instances, `root_block_device` volumes
specified by launch configurations cannot be tagged by Terraform, according
to https://github.com/hashicorp/terraform/issues/14558.

**Comment by sym3tri** [comment]
This is complete. Just need to document the caveats for which i created a separate issue.

**Comment by ggreer** [comment]
Autoscaling groups still aren't getting tagged correctly. (Merged in #1314 and reverted in #1341)
