### ISSUE TITLE
Hook grafiti in every PRs

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#1116]
In addition to running Grafiti daily, we should replace our Jenkin's failure hook by Grafiti, therefore we will be able to garbage collect any resource regardless of Terraform's state.

**Comment by kans** [comment]
We were not previously running grafiti in every region, which I believe has been fixed or will be fixed shortly.

**Comment by Quentin-M** [comment]
This depends on https://github.com/coreos/tectonic-installer/issues/1115.
