### ISSUE TITLE
Investigate Dex's failure w/ GitHub login

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#1117]
Tracking https://github.com/coreos-inc/tectonic-issues/issues/264.

**Comment by rithujohn191** [comment]
Investigated further and found out that the user had set their email id on GitHub to private which was preventing Dex from authenticating the user into tectonic.

**Comment by Quentin-M** [comment]
Thank you for digging!

**Comment by rithujohn191** [comment]
Opened one now https://github.com/coreos/dex/pull/972
