### ISSUE TITLE
docs request: AWS BYO VPC - ELB Integration

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#1127]
## Versions
Any

## What happened?
When users deploy Tectonic into their own VPC and attempt to create a Kubernetes Service with type Load Balancer, ELB gets created however does not get attached to all subnets.

In order to fully utilize AWS ELB / Kubernetes integration, users must tag their AWS subnets with; `kubernetes.io/cluster/my-cluster-name = owned` tag. 

Kindly requesting the @coreos/team-docs  team to assist with documentation. Happy to submit a PR if you can provide an appropriate page/location.

**Comment by chancez** [comment]
@alekssaul I don't think it necessarily needs the `owned` value, it can also be `shared` I think, but would need confirmation. I'm not 100% sure on the difference the value has, but I know the subnet's we setup use `shared`.

**Comment by zbwright** [comment]
question: how often will this be an issue? that is, does this belong in the main doc? or in FAQ?

I don't see ELBs get called out specifically in the coreos docs - I think this gets added to the [Terraform Variables page](https://coreos.com/tectonic/docs/latest/variables/aws.html), as people using that page are most likely to be involved with setting up VPCs with Load Balancer services, no?

**Comment by alekssaul** [comment]
I believe https://coreos.com/tectonic/docs/latest/install/aws/requirements.html#using-an-existing-vpc section would be the best fit. 

ELBs will get spun out automatically when user create a service with LoadBalancer type, but when a user brings their own VPC, the need to make sure that the VPC subnets are tagged (because Tectonic installer skips the steps to tag VPC object)

**Comment by zbwright** [comment]
ah - nice call. get confirmation on the shared vs. owned, and you or I can do the PR. I would add the following line to the end of that section:

When creating a Kubernetes service with type Load Balancer,  tag AWS subnets with `kubernetes.io/cluster/my-cluster-name = owned tag`.

**Comment by alekssaul** [comment]
According to the [code](https://github.com/kubernetes/kubernetes/blob/release-1.6/pkg/cloudprovider/providers/aws/tags.go#L30-L51) 

`kubernetes.io/cluster/my-cluster-name = owned` : "is the value we use when tagging resources to indicate that the resource is considered owned and managed by the cluster, and in particular that the lifecycle is tied to the lifecycle of the cluster."
`kubernetes.io/cluster/my-cluster-name = shared` : "is the value we use when tagging resources to indicate that the resource is shared between multiple clusters, and should not be destroyed if the cluster is destroyed."

It sounds like "kubernetes.io/cluster/my-cluster-name = shared" would be more appropriate?
 @chancez any thoughts?

**Comment by alekssaul** [comment]
[Looks like](https://github.com/coreos/tectonic-installer/blob/master/modules/aws/vpc/vpc-public.tf#L46) we tag them with `shared` in Tectonic. 

@zbwright , does that sounds good? Let me know if I can assist (or need me to submit a doc change PR)

**Comment by zbwright** [comment]
done. Thanks, @alekssaul! https://github.com/coreos/tectonic-installer/pull/1201

**Comment by sym3tri** [comment]
fixed in https://github.com/coreos/tectonic-installer/pull/1201
