### ISSUE TITLE
make-update-payload.sh is probably not doing the correct thing

### ISSUE THREAD

**Issue by kans** [coreos/tectonic-installer#1132]
We have recently been [cleaning up our bash](https://github.com/coreos/tectonic-installer/commit/c5b698a2ccc71c4ce7140ea88b6e7ead6dd646d5), and some things in make-update-payload.sh look broken.

[I don't think this gives you an array](https://github.com/coreos/tectonic-installer/blob/master/modules/update-payload/make-update-payload.sh#L56)

```bash
bash-3.2$ unset a
bash-3.2$ a+=('a')
bash-3.2$ echo ${a}
a
bash-3.2$ a+=('b')
bash-3.2$ echo ${a}
a
```

This [hack](https://github.com/coreos/tectonic-installer/blob/master/modules/update-payload/make-update-payload.sh#L25) should be documented:
```bash
while true; do echo "place_holder_for_terraform_input"; done | terraform apply ./
```

I don't know if its broken, but [this looks quite suspicious](https://github.com/coreos/tectonic-installer/blob/master/modules/update-payload/make-update-payload.sh#L61)
```bash
if [[ ${#tmpfiles[*]} > 0 ]]; then
```

I don't think [this](https://github.com/coreos/tectonic-installer/blob/master/modules/update-payload/make-update-payload.sh#L52) is safe if one of the files has a space:
```bash
for f in ${deployments[*]}; do
```

**Comment by yifan-gu** [comment]
@kans Thanks for the issue. I think `echo ${a[*]}` will print the whole list. `${a}` just print the first element.

Another thing is I think it's reasonable for us to assume there is no space in the file name (cuz it's vendored by us), but I will add comments for that.

**Comment by yifan-gu** [comment]
Another better solution is to move the operator manifest to a dedicated directory, as well as the app version manifests.
I commented in the code of my PR #1125

**Comment by Quentin-M** [comment]
Moving around the manifests is out of reach for this release. Are we currently expecting this script to work properly for the staging push that will happen on Friday/Wednesday?

**Comment by yifan-gu** [comment]
@Quentin-M Yeah, this is working fine now.

**Comment by Quentin-M** [comment]
Closing for now then.. Thanks!
