### ISSUE TITLE
vmware: parameterize VM disk provisioning types

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#1139]
Currently, VMware module uses "Thin" [provisioning] for Virtual Machine disks.This is a safe [default] for recent generation VMware vSphere deployments with recent generation hardware. 

However users may want to choose a different setting based on their operational requirements.  Ideally this should be parameterized. 

[provisioning]: https://github.com/coreos/tectonic-installer/blob/master/modules/vmware/node/nodes.tf#L18
[default]: https://blogs.vmware.com/vsphere/2014/05/thick-vs-thin-disks-flash-arrays.html

**Comment by sym3tri** [comment]
Will consider for the converged platform.

https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
