### ISSUE TITLE
Feature Request: show resource quotas in Namespace

### ISSUE THREAD

**Issue by hhoover** [coreos/tectonic-installer#1140]
FEATURE REQUEST

The namespace administration screen in the Tectonic console has an area for role bindings but does not show the quotas associated. It would be a nice feature to have a tab that shows users what resource quotas are set in that namespace. Example:

![tectonic console](https://user-images.githubusercontent.com/579484/27344267-5e70597a-55ab-11e7-9f47-e8302c875d9c.png)

**Comment by sym3tri** [comment]
@hhoover Thanks for the request. We actually track Console issues separately from the installer repo. I'll send you the private issue tracker.
