### ISSUE TITLE
Create a dedicated variable to the self hosted etcd feature

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#1144]
In https://github.com/coreos/tectonic-installer/pull/1136, we enabled by default every features that were considered experimental back then, except self-hosted etcd.

We'd like to have self-hosted etcd behind its own feature flag rather than behind the experimental flag. Ideally, we would also have everything behind their own flag. In order to limit the number of variables we have and ease the versioning of our configuration file, we should create a map that will contain all required feature flags, rather than having individual variables.

**Comment by squat** [comment]
@Quentin-M agreed. This would simplify our lives and allow us to condition all features that depend on self-hosted etcd on a single, more future-proof flag, e.g. https://github.com/coreos/tectonic-installer/pull/1192, which needs to know the flavor of etcd.
