### ISSUE TITLE
vmware: resource tagging

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#1147]
Per; https://github.com/hashicorp/terraform/issues/7515#issuecomment-253926828 VMware custom configuration parameters support resource tagging. 

Investigate potential of tagging resources similar to cloud platforms

**Comment by alekssaul** [comment]
Note: provided option in the terraform issue doesn't seem to surface vmware tags. Will need upstream work.

**Comment by sym3tri** [comment]
We'll consider this for the converged platform.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
