### ISSUE TITLE
Feature Request - AWS: Parameterize S3 Bucket Name

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#1164]
## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
1.6.X
* Terraform version (`terraform version`):
0.9.6
* Platform (aws|azure|openstack|metal):
aws

## What happened?
User evaluating tectonic requested ability to specify S3 bucket name due to their Security controls. 
This seem to be set in; https://github.com/coreos/tectonic-installer/blob/master/platforms/aws/s3.tf#L9

**Comment by sym3tri** [comment]
Fixed in #1991
