### ISSUE TITLE
Tectonic UI not showing Roles / Role Binding UI even though user has access to view it

### ISSUE THREAD

**Issue by sir-rob** [coreos/tectonic-installer#1165]
* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.6.4-tectonic.1
* Terraform version (`terraform version`): v0.9.4
* Platform (aws|azure|openstack|metal): AWS

## What happened?
Users with access to view all resources is not able to see Roles / ClusterRoles in the Tectonic UI even though they can view them via the CLI using kubectl

## What you expected to happen?
Tectonic UI should let users see the Roles / ClusterRoles if they have view access and Tectonic UI should be consistent with kubectl with regards to access to the cluster.

## How to reproduce it (as minimally and precisely as possible)?
Create a static user, create a role that provides view access to all resources, create a role binding that maps the static user to the role. Login with static user, try to view roles (you will not have the option in the UI). Download the static user's kube-config file and run the command ```kubectl get clusterroles``` and you will see it via CLI.

## Anything else we need to know?

**Comment by sym3tri** [comment]
Closing b/c not an installer issue, this is a Console issue. Please file internal bugs here:
https://coreosdev.atlassian.net/projects/FR/issues
