### ISSUE TITLE
Test flakes to address

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#1194]
- [ ] Jenkins dies
- [ ] AWS limits
- [ ] TF destroy issues with timeouts or dependencies
- [ ] Some smoke tests are flaky
- [ ] Smoke tests timeout waiting for Tectonic components to come up
- [ ] Creating EIPs for NAT Gateways (associating the EIPs to the NAT Gateways)

**Comment by Quentin-M** [comment]
As for the AWS limits, every time we hit a quota over the past two weeks, I raised our limits on AWS significantly. Runnin grafiti every 12 hours and https://github.com/coreos/tectonic-installer/pull/1198 should help significantly.

**Comment by sym3tri** [comment]
combined into https://github.com/coreos/tectonic-installer/issues/1054 so this is a dupe now
