### ISSUE TITLE
Node not ready eventually cause self-hosted etcd to lose quorum

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#1208]
Mirroring https://github.com/coreos-inc/tectonic-issues/issues/268 in this repository with the appropriate `release-blocker/1.6.6-tectonic.1` tag in order to guarantee we won't miss implementing the changes that are required to make self-hosted etcd reliable on AWS.

/cc @amrutac @sym3tri

**Comment by Quentin-M** [comment]
As of today, there are some solutions that are designed / being tested (e.g. https://github.com/coreos/etcd-operator/pull/1224) but no accepted solution yet.

**Comment by sym3tri** [comment]
@Quentin-M looks like etcd operator doesn't have the fix in yet. Remove the "release blocker" label for now?

**Comment by amrutac** [comment]
I checked with @Quentin-M  about this and he said it was resolved by his PRs.

**Comment by Quentin-M** [comment]
https://github.com/coreos/tectonic-installer/pull/1224 will do for AWS until the etcd operator has another/more durable solution.

**Comment by bison** [comment]
@Quentin-M No cluster with this patch at the moment, but will be spinning up a dev / staging cluster with self-hosted etcd based on latest release soon. So, we'll see how that goes. Thanks.
