### ISSUE TITLE
etcd TLS: ignoring ServerName for user-provided CA

### ISSUE THREAD

**Issue by lblackstone** [coreos/tectonic-installer#1219]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 79cceb0df9c154e79e6e611212ab78991ebf051b
* Terraform version (`terraform version`): Terraform v0.9.9
* Platform (aws|azure|openstack|metal): openstack (probably all platforms)

## What happened?
Saw the following error in the bootkube.service unit logs on master0:
```
...
bootkube[5]: All self-hosted control plane components successfully started
bootkube[5]: Migrating to self-hosted etcd cluster...
bootkube[5]: I0628 14:08:15.391082       5 log.go:19] warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
...
```

## What you expected to happen?
No deprecation warning should be present.

## How to reproduce it (as minimally and precisely as possible)?
Boot a cluster with `tectonic_experimental=true` and check the bootkube logs on the `master0` node with `journalctl -u bootkube`.

## Anything else we need to know?
This warning was not present prior to 5a49da5ba134e571718a28f5b1b1cb19e30e09fd
I'm pretty sure it was introduced by that commit.

**Comment by sym3tri** [comment]
The experimental flag is not supported and will not continue to be developed.
