### ISSUE TITLE
ui installer should link to metal docs.

### ISSUE THREAD

**Issue by coresolve** [coreos/tectonic-installer#1222]
If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
* Terraform version (`terraform version`): 0.9.6
* Platform metal

## What happened?
The user flow for bare metal install doesn't highlight the requirements right after picking metal install. 

This causes some confusion. The ui installer should give you an overview of the requirements and then link you to the appropriate documentation to get the pre reqs done before proceeding.

**Comment by coresolve** [comment]
@robszumski @dghubble

**Comment by robszumski** [comment]
Agreed that it makes sense to link these. Note that the overall bare metal docs do mention these requirements and resources.

**Comment by sym3tri** [comment]
migrated this to internal tracker
