### ISSUE TITLE
docs: document master node recovery.

### ISSUE THREAD

**Issue by zbwright** [coreos/tectonic-installer#1226]
(This is to supplant an outdated pivotal issue.)

@coresolve and I are going to document how to recover after a master node failure.

doc will live in the AWS troubleshooting section, and will using the new bootkube changes for the recovery process, 
will reference  existing doc on control plane recovery (https://gist.github.com/soggiest/fead136ce1be6927c338d84e18105b3b), 
and Duffie's head.

original call transcript: https://docs.google.com/document/d/15oAy5iorzWsDAog7hdMSf9s7NtL4Jzp32i_cwZoeRV8/edit

@duffiec says he thinks the right thing is the document is this: https://gist.github.com/xiang90/9295981937d83bb386ea6da193551861

**Comment by robszumski** [comment]
Sounds like some of this might be underway in https://github.com/radhikapc/tectonic-installer/blob/167c2cb5a2f469fa08dfa5e517e9931fe9548946/Documentation/troubleshooting/etcd_op_recovery.md#recovering-from-a-failed-or-total-control-plane-outage

**Comment by zbwright** [comment]
I believe @radhikapc has taken this task over. closing.
