### ISSUE TITLE
Investigate Azure Application Gateways

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/tectonic-installer#1240]
Currently in the Azure platform all traffic goes via public resources, i.e. the Azure [Load Balancer](https://docs.microsoft.com/en-us/azure/load-balancer/). We would like to separate internal control-plane traffic from the public one similar to AWS.

Unfortunately Azure Load Balancers have limitations that prevent a meaningful private-public separation, so we are investigating [Application Gateways](https://docs.microsoft.com/en-us/azure/application-gateway/).

**Comment by metral** [comment]
FWIW, MSFT DX advised against the use of AppGateways in favor for vanilla nginx proxies instead. This is the same route we took for one of our Azure customers.

**Comment by alexsomesan** [comment]
Hey, Mike!
Can you share a bit of detail around the reasons why MS advised against AppGw? I'm missing that context.
Also, would love to review then nginx solution. Where can I find the code for that?
