### ISSUE TITLE
Azure: Consider making resource names (VM, disk  images etc) (more) unique

### ISSUE THREAD

**Issue by discordianfish** [coreos/tectonic-installer#1243]
The OS disks for the azure VMs only use the VM name to build the disk url:

https://github.com/coreos/tectonic-installer/blob/master/modules/azure/worker-as/workers.tf#L72

That makes it impossible to create a new node before the old one is not only terminated but it's disk is detached and deleted. This can take a while, so replacing an instance can be really slow and prevents using create_before_destroy lifecycle.

Instead we could add a UUID or something related to the deployment to make sure the disk image is unique even when used for a VM named the same.

**Comment by cehoffman** [comment]
It isn't just the OS disk then, the VM name needs to have something unique too since you can't have two VMs with the same name in the resource group. It is because of the VM needing to be different haven't tried to make use of create_before_destroy.

**Comment by discordianfish** [comment]
@cehoffman Good point! Didn't know about the limitation but yeah, makes sense.

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
