### ISSUE TITLE
There should be a way to tell if tectonic was installed from an official release

### ISSUE THREAD

**Issue by aaronlevy** [coreos/tectonic-installer#1251]
Right now an installation could have been built from HEAD and we don't have a very good way of determining that (that I know of). This can make trouble-shooting issues sometimes difficult.

**Comment by sym3tri** [comment]
Any suggestions on how you'd like to see this accomplished?

**Comment by Quentin-M** [comment]
I added the ability to do that when I submitted https://github.com/coreos/tectonic-installer/commit/68c4adbdf492f97d728b9c5a04b51e5343d16a04, as it was used by the `--version` command. We removed that command to replace it with @amrutac's header, which does not show the commit (see https://github.com/coreos/tectonic-installer/blob/07f835bb0d5a24874e987a9178a278830c4caa5e/installer/frontend/components/header.jsx). I am pretty confident we can either: display the short SHA, or at least show a tooltip with it.

**Comment by Quentin-M** [comment]
I am trying to make a small PR for it..

**Comment by aaronlevy** [comment]
Ideally this isn't just the installer, but the actual running cluster too...

**Comment by Quentin-M** [comment]
@aaronlevy This specific request is tracked by https://github.com/coreos/tectonic-installer/issues/445.
