### ISSUE TITLE
Use hyperkube that includes fix of pod upgrade

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/tectonic-installer#1252]
Currently there is a problem for pod upgrades in k8s 1.6 . See:
-  https://github.com/kubernetes/kubernetes/issues/47933
- https://github.com/coreos/etcd-operator/issues/1211

The fix is this commit https://github.com/kubernetes/kubernetes/pull/46267 . We need to either cherry-pick or wait upstream to merge this (for 1.6): https://github.com/kubernetes/kubernetes/pull/47989 . And then we need to build another release of hyperkube, and update the hyperkube image in Tectonic too.

**Comment by aaronlevy** [comment]
Once https://github.com/kubernetes/kubernetes/pull/47989 merges, we can carry the same patch. @hongchaodeng could you open a pr against https://github.com/coreos/kubernetes (patch should be against branch `coreos-hyperkube-v1.6.6`)

**Comment by Quentin-M** [comment]
This should be backported to v1.6.6 and thus be marked as a release blocker for tracking purposes.

**Comment by sym3tri** [comment]
@aaronlevy @Quentin-M status on this?

**Comment by amrutac** [comment]
Patch has been included in 1.6.7 and will be released.
