### ISSUE TITLE
azure: have terraform create DNS Records

### ISSUE THREAD

**Issue by jimzim** [coreos/tectonic-installer#126]
Instead of manually setting up DNS in Azure, we should automate it with Terraform.

Terraform Docs: https://www.terraform.io/docs/providers/azurerm/r/dns_a_record.html
Microsoft Docs: https://docs.microsoft.com/en-us/azure/dns/dns-getstarted-cli

**Comment by sozercan** [comment]
#163

**Comment by justaugustus** [comment]
With #1154 merged, I believe this could be closed.

**Comment by sym3tri** [comment]
Should be done. Please reopen if there's anything missing.
