### ISSUE TITLE
certs hostmount: use /etc/ssl/certs instead of /usr/share/ca-certificates

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#1277]
## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
1.6.X
* Terraform version (`terraform version`):
NA
* Platform (aws|azure|openstack|metal):
all + RHEL

## What happened?
Some Pod specs uses `/usr/share/ca-certificates` from the host to mount certificates to trust. This causes issues for users who bring their own CA certificates similar to procedure in; https://coreos.com/os/docs/latest/adding-certificate-authorities.html and use HTTPS_PROXY for egress to internet. Some HTTPS_PROXIES require CA trust in order to allow egress access. Reported by the users, `tectonic-channel-operator` and `container linux operator` is not able to access internet because the certificate that the nodes trust is not mounted to the pods.

ex: https://github.com/coreos/tectonic-installer/blob/513ecd4d2562bf05ae2d1eb619b3a20ec4ad4e45/modules/tectonic/resources/manifests/updater/operators/tectonic-channel-operator.yaml#L46-L48

## What you expected to happen?
use `/etc/ssl/certs` instead of `/usr/share/ca-certificates` 

## Anything else we need to know?
[Quick search](https://github.com/coreos/tectonic-installer/search?utf8=%E2%9C%93&q=%2Fusr%2Fshare%2Fca-certificates&type=) reveals this is applied in few specs. 

Please also tag the issue platform-rhel (or similar) for easier tracking of issues that may be effecting RHEL platform.

**Comment by sym3tri** [comment]
We'll consider this for the converged platform.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
