### ISSUE TITLE
Spike: Testing framework to replace current bash scripts

### ISSUE THREAD

**Issue by mxinden** [coreos/tectonic-installer#1280]
Find a testing framework to replace the current bash scripts.

**Comment by mxinden** [comment]
I will look into:
* [goconvey](https://github.com/smartystreets/goconvey)
* [ginkgo](https://github.com/onsi/ginkgo)
* [godog](https://github.com/DATA-DOG/godog)

**Comment by squat** [comment]
@mxinden closing since you finished this spike.
