### ISSUE TITLE
Attach policy to generated S3 bucket during installation

### ISSUE THREAD

**Issue by zlangbert** [coreos/tectonic-installer#1286]
## What keywords did you search in tectonic-installer issues before filing this one?

s3 policy, bucket policy

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.6.4
* Terraform version (`terraform version`): 0.9.8
* Platform (aws|azure|openstack|metal): aws

## Description

We need to be able to attach a bucket policy to the generated S3 bucket. Given that it contains sensitive cluster credentials, access needs to be restricted. If one could provide a policy during the installation it would be much more convenient.

**Comment by eddieesquivel** [comment]
cc @robszumski @sym3tri

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
