### ISSUE TITLE
Create `bootkube recovery` user documentation and give a link from the Tectonic troubleshooting doc

### ISSUE THREAD

**Issue by radhikapc** [coreos/tectonic-installer#1288]
A pretty good doc exists on `bootkube recovery` at https://github.com/diegs/bootkube/blob/1090923ac1caeef3dfed6ceb1b533c36232cd0a1/Documentation/disaster-recovery.md. Rewrite to create a user doc and give a link from the tectonic troubleshooting doc.

**Comment by zbwright** [comment]
looks like this ticket is meant to supplant this: https://github.com/coreos/tectonic-installer/issues/1226 ?
If so, let's consolidate / close out the previous.
