### ISSUE TITLE
GUI: after delete, next button goes to "login to console" step

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#1311]
Once you successfully delete a cluster, the next step button is still active and goes to the "here's how you use your console" screen, but the is no more cluster.

Seems like the best place is to go back to the start of the installer? Ideally we remove it completely but we might have to keep there?

**Comment by kyoto** [comment]
I think this can best be fixed by disabling the Next Step button if the cluster is destroyed: #1505.
