### ISSUE TITLE
Allow backupPolicy to be set on self-hosted etcd clusters

### ISSUE THREAD

**Issue by jamiehannaford** [coreos/tectonic-installer#1318]
We'd like to back up our etcd state with a [BackupPolicy](https://github.com/coreos/etcd-operator/blob/master/pkg/spec/backup.go#L32) but the current manifest is [hard-coded](https://github.com/coreos/tectonic-installer/blob/master/modules/bootkube/resources/experimental/etcd/migrate-etcd-cluster.json#L8-L35). What would be the best way to parameterize this? 

I'm thinking we could maybe change the `template_dir` resource defined [here](https://github.com/coreos/tectonic-installer/blob/master/modules/bootkube/assets.tf#L24) to a series of `template_file` resources (one per file), and then load either `migrate-etcd-cluster.json` or `migrate-etcd-cluster-with-backup.json` based on a new bool var.

**Comment by robszumski** [comment]
@jamiehannaford You should be able to reconfigure the etcd cluster instance via kubectl to add the backup settings.

@xiang90 If @jamiehannaford wanted to programmatically do this, how do you accomplish that?

**Comment by xiang90** [comment]
@robszumski  wants to `parameterize` this configuration file. This is different than programmatically change it after the initial installation if I understand it correctly.

@jamiehannaford Tecthonic uses terraform for configuration templating. You need to add template parameters to enable that. I am not sure if our installer team has any plan on that. @sym3tri might answer your question better.

**Comment by jamiehannaford** [comment]
Yeah I'd prefer it to happen during bootstrap not post-install. My understanding is that the tectonic-installer already uses a feature in Terraform called `template_dir`:

https://github.com/coreos/tectonic-installer/blob/master/modules/bootkube/assets.tf#L24
https://www.terraform.io/docs/providers/template/r/dir.html

So to enable backupPolicy I think three things needs to happen:

- add a new file to the [template dir](https://github.com/coreos/tectonic-installer/tree/master/modules/bootkube/resources/experimental/etcd) called `migrate-etcd-cluster-with-backup.json`
- switch to loading individual files with `template_file` rather than the whole directory
- add new params for the backup policy 

What do you think @s-urbaniak?

**Comment by s-urbaniak** [comment]
@jamiehannaford that would introduce a lot of `template_file` declarations and would also introduce more `count` hacks to optionally enable/disable them individually.

I think the easier approach would be to always generate the asset (it doesn't hurt) and enable/disable it during bootstrap time in `bootkube.sh` simply proxying the `enable_etcd_backup`. The logic would be encapsulated inside the script and `bootkube.sh` could be parametrized. The asset is in `experimental` anyways and we already use logic inside `bootkube.sh` to enable/disable experimental assets.
