### ISSUE TITLE
etcd service needs to tolerate unready endpoints

### ISSUE THREAD

**Issue by xiang90** [coreos/tectonic-installer#1326]
See https://github.com/kubernetes-incubator/bootkube/pull/626 for more details.

**Comment by xiang90** [comment]
kubernetes-incubator/bootkube#626 is already merged. 

Once we enable this feature in tectonic installer, we probably also want to have an alpha feature tracker doc similar to https://github.com/hongchaodeng/bootkube/blob/107cd1aa61be0837d4ce6f7cfede745e2bbcd967/Documentation/alpha-features.md.

/cc @s-urbaniak @sym3tri

**Comment by xiang90** [comment]
ping @s-urbaniak @sym3tri

**Comment by s-urbaniak** [comment]
tentatively setting to the next milestone, but leaving @sym3tri the last word regarding planning.

**Comment by lblackstone** [comment]
Was this fixed? Maybe by https://github.com/coreos/etcd-operator/pull/1266?

**Comment by lblackstone** [comment]
@xiang90 Was this issue fixed? I don't see any resolution listed.
