### ISSUE TITLE
all: make tectonic license and pull secret optional

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#133]
The tectonic license and pull secret are required. If they aren't included we should simply not attempt to install the tectonic manifests. This will enable a few things:

- [ ] bootkube can use this repo for cluster spin-up and testing
- [ ] kubeadm could use this repo for testing across different environments

**Comment by philips** [comment]
cc @luxas would you be interested in using this repo for kubeadm self-hosted testing? It would be a good way to start testing that across different repos. Essentially it would be creation of a module like https://github.com/coreos/tectonic-installer/tree/master/modules/bootkube

**Comment by klausenbusk** [comment]
So with this issue resolved, the installer can be used for setting up a non-tectonic cluster like coreos-kubernetes does?

**Comment by s-urbaniak** [comment]
@klausenbusk yes, setting `tectonic_vanilla_k8s` to `true` will deploy a vanilla k8s cluster only and works for AWS and Azure.

It is still a bit bumpy as you need to point to empty files for `tectonic_license_path` and `tectonic_pull_secret_path` as tectonic assets are being provisioned (but not deployed) but the basic functionality is there. I will file a follow-up PR which will not require pointing to empty license files/pull secrets (and probably also omitting rendering the tectonic assets at all).
