### ISSUE TITLE
Allow QA/Internal Users to test payload (staging channel) without signing 

### ISSUE THREAD

**Issue by amrutac** [coreos/tectonic-installer#1334]
During 1.6.7-tectonic.1 release, it was difficult for QA/Internal team to test TCO/KVO updates, since the payload had to be signed and then uploaded to the staging channel. Signing the payload is non-trivial and there needs to be a way to test these updates easily in between RCs. We should only require signing the payload for the final release.

**Comment by yifan-gu** [comment]
The action item would be:
- Sign and upload the payload using the dummy key.
- Document how to use the dummy pub key for tco to verify the payload, it can just be a TFVAR in the tco config.
