### ISSUE TITLE
GUI: Start Install Screen - UX enhancements

### ISSUE THREAD

**Issue by meghanschofield** [coreos/tectonic-installer#1335]
This screen has a lot happening. Users struggle through this section especially if the install doesn't work. UX testing showed us some particularly difficult spots. 

### 1. If the user clicks Start Over, two things should occur:
- Keep all the information populated 
- Take users to Step 2 Define Cluster, AWS Credentials screen

In several cases, something small went awry (the wrong region was inputted, or they used a capital letter in a place they shouldn't) and it was clear to them, thanks to the logs. They really wanted to just fix the error and move on. We should allow for a quick fix, by keeping the inputs in place. 

### 2. If a user uploads a progress file:
- Take users to Step 2 Define Cluster, AWS Credentials screen.

**Comment by kyoto** [comment]
2. Was implemented by #1366.

**Comment by sym3tri** [comment]
closing in favor of getting a bigger picture UX flow documented
