### ISSUE TITLE
It took 15 min(170*5 sec) for Prometheus TPR to become available.

### ISSUE THREAD

**Issue by amrutac** [coreos/tectonic-installer#1353]
## Versions
* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
1.6.7-tectonic.1-rc.4 and probably older versions of tectonic

* Platform (aws|azure|openstack|metal):
Bare metal

## What happened?
During testing @ivan reported that it took 15 min(170*5 sec) for Prometheus TPR to become available.
`bootkube is complete, tectonic service is still running with "Jul 11 17:19:32 lab-4.lab.libcore.so bash[5458]: [ 1154.518815] hyperkube[5]: Error from server (NotFound): thirdpartyresources.extensions "prometheus.monitoring.coreos.com" not found
Jul 11 17:19:32 lab-4.lab.libcore.so bash[5458]: [ 1154.521320] hyperkube[5]: TPR prometheus.monitoring.coreos.com not available yet, retrying in 5 seconds (125)"`

The cluster eventually came up, but it took a lot of time.

## Anything else we need to know?
Tectonic service logs
```
core@lab-4 ~ $ journalctl -u tectonic -f
-- Logs begin at Tue 2017-07-11 17:00:27 UTC. --
Jul 11 17:10:29 lab-4.lab.libcore.so bash[5458]: [  611.882188] hyperkube[5]: Error from server (NotFound): thirdpartyresources.extensions "prometheus.monitoring.coreos.com" not found
Jul 11 17:10:29 lab-4.lab.libcore.so bash[5458]: [  611.884531] hyperkube[5]: TPR prometheus.monitoring.coreos.com not available yet, retrying in 5 seconds (20)
Jul 11 17:10:35 lab-4.lab.libcore.so bash[5458]: [  617.054678] hyperkube[5]: Error from server (NotFound): thirdpartyresources.extensions "prometheus.monitoring.coreos.com" not found
Jul 11 17:10:35 lab-4.lab.libcore.so bash[5458]: [  617.057130] hyperkube[5]: TPR prometheus.monitoring.coreos.com not available yet, retrying in 5 seconds (21)
Jul 11 17:10:40 lab-4.lab.libcore.so bash[5458]: [  622.228658] hyperkube[5]: Error from server (NotFound): thirdpartyresources.extensions "prometheus.monitoring.coreos.com" not found
Jul 11 17:10:40 lab-4.lab.libcore.so bash[5458]: [  622.231086] hyperkube[5]: TPR prometheus.monitoring.coreos.com not available yet, retrying in 5 seconds (22)
Jul 11 17:10:45 lab-4.lab.libcore.so bash[5458]: [  627.392174] hyperkube[5]: Error from server (NotFound): thirdpartyresources.extensions "prometheus.monitoring.coreos.com" not found
```

**Comment by s-urbaniak** [comment]
This may be related to slow downloads in baremetal, /cc @dghubble

**Comment by dghubble** [comment]
That slow hyperkube download issue isn't related. That was for the matchbox suite of test clusters (not Tectonic cluster, no prometheus, no TPRs) and was in the office lab (different test environment from Tectonic).
