### ISSUE TITLE
installer: support distinct TLS certificates for various interfaces

### ISSUE THREAD

**Issue by colhom** [coreos/tectonic-installer#1355]
The following interfaces should have TLS private key, certificate and CA configurable individually from each other.

* Kubernetes API server: key, cert and optional CA certificate. May be signed by public CA and not require explicit CA

* Tectonic Ingress: key, cert and optional CA certificate. May be signed by public CA and not require explicit CA

* Dex Client API: key, cert and optional CA certificate. 

For all these, we should also support auto-generating all the certificates from a self-signed CA as well. This is what the installer does today.

https://github.com/coreos-inc/bridge/pull/1581 -- Allows for CA to not be specified for OIDC, dex client and tectonic ingress/console

https://github.com/coreos-inc/bridge/pull/1582 -- Allows Dex client CA to be specified separately.

Bridge running in `in-cluster' defaults to using the Kubernetes CA from the default service account secret, so no explicit action is needed there.

**Comment by coresolve** [comment]
There has been some discussion around not exposing the api server through a different means. So that we can provide a user specified certificate for the api interface that is exposed publicly and use the internal ca to generate a cert for the internal api server. /cc @ericchiang

**Comment by ericchiang** [comment]
Yes this would be a good thing. We could accomplish this by generating sub CAs for the different systems from the same root CA too.

This complicates the TLS bootstrapping CSR story though. We'd have to have a mechanism to indicate which CA the CSR should be signed by.

I'd prefer we just use different O or OU values for these things. That'd probably be simpler.

**Comment by colhom** [comment]
> I'd prefer we just use different O or OU values for these things.

I think that 

I think it's perfectly reasonable to use a single CA for any TLS certificates that are __generated by the installer__. 

Suggestion: perhaps we keep the current behavior the

**Comment by colhom** [comment]
Woops sorry clicked the wrong button, accidentally closed issue.

> Yes this would be a good thing. We could accomplish this by generating sub CAs for the different systems from the same root CA too.

We don't necessarily have to do this. A single CA for any installer-generated certificates would be fine- as long as we allow user to specify alternate CA, cert and key for the ingress I think we'll be fine. I don't think there's any reason that dex client and Kubernetes in-cluster TLS shouldn't share a common CA.

**Comment by colhom** [comment]
And in the case that cert/key/CA are not specified explicitly for ingress, we should just generate that cert from the same CA as the rest.

**Comment by s-urbaniak** [comment]
just fyi, self-assigning this to me since I have been toying with let's encrypt and this seems to be a good canonical use case for this.

**Comment by colhom** [comment]
As a side note- as of this [PR](https://github.com/coreos-inc/tectonic-prometheus-operator/pull/81) tectonic-prometheus-operator will configure `tectonic-monitoring-ingress` TLS secret to match `tectonic-ingress` in the absence of explicit configuration.

I'm thinking we should establish a pattern in tectonic-installer of only explicitly configuring TLS for `tectonic-ingress` and any supplemental ingress resources should be expected to automatically reconcile via operator to match that configuration. @coresolve and I observed some seriously weird behavior if multiple ingress resources list differing TLS configuration for the same host.
