### ISSUE TITLE
Add Spotinst integration for worker nodes as alternative to ASG [AWS]

### ISSUE THREAD

**Issue by joshrosso** [coreos/tectonic-installer#1384]
## Feature Request: Add Spotinst support; AWS

Spotinst is a service that takes advantage of [Amazon's Spot Instance market](https://aws.amazon.com/ec2/spot/) to create cost-effective EC2 instances. Spotinst works by creating an elasticgroup and scaling through that rather than a conventional ASG. More details on elasticgroups can be found at https://spotinst.com/products/workload-management/elastigroup.

My group has swapped their ASGs out for Spotinst elasticgroups and have already seen 58% cost reduction on the worker compute pool. Another example of Spotinst usage in k8s can be found at http://blog.spotinst.com/2017/07/03/success-story-front-gate-tickets.

With the above, I feel it could be advantageous for Tectonic to provide _compatibility_ with Spotinst through the installer. Due to the [more] ephemeral nature of Spot Instances, this feature is only recommending this option for workers. Spotinst also features a cluster autoscaler that, like the standard autoscaler, request more nodes (in this case through elasticgroups) when capacity thresholds are reached.

### design

By design, this feature would introduce 1 *required* parameter: `tectonic_aws_spotinst_worker_pool`, defaulted to `false`. Setting this parameter to true would have the following impacts.

- Spotinst Elasticgroup is created
  - Due to limitations in the cluster_autoscaler, it will currently create 1 elasticgroup per AZ. This ensures the autoscaler always scale a node appropriate to satisfy scheduling needs. For example, a node that must be scheduled in a certain AZ since that's where pod(s) PV live that need to be scheduled.
  - Eventually we'll move away from this and use 1 elasticgroup containing all AZ/subnets.
- No ASG is created
- No LaunchConfiguration is created
  - user-data is now part of the elasticgroup and the launch config would not be used

### other notes

- This issue is related to https://github.com/coreos/tectonic-installer/issues/768 but favors Spotinst over conventional [Spot Fleet](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html) provided by AWS. 

/cc @robszumski @sym3tri

**Comment by tomdavidson** [comment]
What is incompatible? Does the ASG teardown what Spotinst sets up?

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
