### ISSUE TITLE
node-agent: create /etc/kubernetes/kubelet.env

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#139]
This is required for the node-agent to work and upgrades. Any platform wanting to move to beta MUST use this.

cc @aaronlevy

**Comment by aaronlevy** [comment]
Just to note - tectonic operators currently assume the (now deprecated) kubelet-wrapper flags: https://github.com/coreos/coreos-overlay/blob/master/app-admin/kubelet-wrapper/files/kubelet-wrapper#L29-L39

This should be switched to the new flags in the next release - but just need to make sure it is coordinated (/cc @derekparker )

**Comment by derekparker** [comment]
PR for new wrapper env vars is here: https://github.com/coreos/tectonic-installer/pull/179

**Comment by s-urbaniak** [comment]
We are using `/etc/kubernetes/kubelet.env` on master, hence I am closing this. Feel free to reopen if we missed a concern here.
