### ISSUE TITLE
docs: add output for all `get` module commands

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#1390]
Finding the solution to https://github.com/coreos/tectonic-installer/issues/1380 would have been way easier if the docs listed the output of:

```
$ terraform get ./platforms/<name>
```

This would allow you to see the names of each and match it up to the Terraform error that was listed.

**Comment by zbwright** [comment]
from asking @kbrwn:
1. the command listed above is not working with AWS
2. it looks like the question is answered with the command and output listed below.
3. I'll get confirmation from eng. on the list of modules
4. should we update the command? or were you looking for something different?

./platforms/aws is a dif with terraform files (edited)

 ```$ TERRAFORM_CONFIG=/home/kbrown/Support/twistlock/tectonic/.terraformrc /home/kbrown/Support/twistlock/tectonic/tectonic-installer/linux/terraform get ./platforms/aws/
Get: file:///home/kbrown/Support/twistlock/tectonic/modules/aws/vpc
Get: file:///home/kbrown/Support/twistlock/tectonic/modules/aws/etcd
Get: file:///home/kbrown/Support/twistlock/tectonic/modules/aws/ignition
Get: file:///home/kbrown/Support/twistlock/tectonic/modules/aws/master-asg
Get: file:///home/kbrown/Support/twistlock/tectonic/modules/aws/ignition
Get: file:///home/kbrown/Support/twistlock/tectonic/modules/aws/worker-asg
Get: file:///home/kbrown/Support/twistlock/tectonic/modules/bootkube
Get: file:///home/kbrown/Support/twistlock/tectonic/modules/tectonic```

**Comment by robszumski** [comment]
Yes, that looks correct. If you are currently in the directory, which our docs specify, I think you will not see any of these gross paths, which will be more understandable. If you add the binary to your $PATH as well, I think you won't have to have the long binary string. Adding it all together, it would look like:

```
$ terraform get ./platforms/aws/
Get: modules/aws/vpc
Get: modules/aws/etcd
Get: modules/aws/ignition
Get: modules/aws/master-asg
Get: modules/aws/ignition
Get: modules/aws/worker-asg
Get: modules/bootkube
Get: modules/tectonic
```

Can you verify that?

**Comment by zbwright** [comment]
I believe that what Rob is looking for is that we add the `terraform get` command and return to this page: https://coreos.com/tectonic/docs/latest/admin/bare-metal-scale.html#scaling-worker-nodes

**Comment by zbwright** [comment]
@robszumski currently in which directory? this ticket got lost in the shuffle, and now I don't remember which doc you were referencing.

**Comment by robszumski** [comment]
@zbwright No, this would be for all of the platform TF install docs. BM, Azure, AWS, etc.

**Comment by zbwright** [comment]
@robszumski your note said " If you are currently in the directory, which our docs specify," - Kyle and I cannot figure that one out. Which doc specifies which directory?

**Comment by robszumski** [comment]
oh, the current directory/working directory of the installer, vs having `file:///home/kbrown/Support/customer/tectonic/` in it.
