### ISSUE TITLE
docs: update etcd TLS language

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#1399]
Validate that all language related to TLS is up to date. I spotted this in the [bare metal requirements](https://github.com/coreos/tectonic-installer/blob/master/Documentation/install/bare-metal/requirements.md#network):

> Tectonic bare metal clusters store credentials in user-data, and etcd peer to peer communication **is not currently encrypted with TLS**. To restrict access to sensitive information, provision bare metal machines within a trusted network and ensure that a firewall exists between cluster controllers and the public internet.

**Comment by zbwright** [comment]
looks like that's the only markdown file in the tectonic-installer that even suggests TLS is not supported.  tiny change to address this issue.

Tectonic bare metal clusters store credentials in user-data. To restrict access to sensitive information, provision bare metal machines within a trusted network and ensure that a firewall exists between cluster controllers and the public internet.

**Comment by zbwright** [comment]
https://github.com/coreos/tectonic-installer/pull/1408
