### ISSUE TITLE
Test out new hyperkube with base image changed

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#1401]
There is an upstream PR which changes the Hyperkube base image. We need to run through our typical set of tests to ensure everything is functioning as expected with the new image. i.e. cluster installs properly, manual QA testing, kubernetes & all components function as expected.

See: https://github.com/kubernetes/kubernetes/pull/48365

If any issues are found we need to raise them in the upstream PR before it merges

**Comment by sym3tri** [comment]
@squat any progress on this? upstream is asking.

**Comment by squat** [comment]
@sym3tri still testing. I ran into some issues but they turned out to be operator error. Should have results soon.

**Comment by sym3tri** [comment]
@squat ok, might be worth commenting on the upstream issue.

**Comment by squat** [comment]
Completed testing and wrote results in upstream issue: https://github.com/kubernetes/kubernetes/pull/48365#issuecomment-317816295. Problems are addressed in #1497.
