### ISSUE TITLE
Pretty-print JSON in terraform.tfvars

### ISSUE THREAD

**Issue by estroz** [coreos/tectonic-installer#1411]
### Versions

* Tectonic version: 1.6.7
* Terraform version: 0.9.6
* Platform: all

### Description

Currently all data in `terraform.tfvars` is generated as a single line by the installer. A single line of complex JSON is difficult to read. Pretty-printing data in `terraform.tfvars` would make a much better user experience.

**Comment by alekssaul** [comment]
Think this was fixed via; https://github.com/coreos/tectonic-installer/issues/350 but (I believe) didn't make it to 1.6.7
