### ISSUE TITLE
support dedicated etcd machines

### ISSUE THREAD

**Issue by xiang90** [coreos/tectonic-installer#1415]
For large clusters, it make more sense to label machines as etcd node and taint them as `dedicated-etcd=ture`. Only etcd-operator and etcd will tolerate the taint. No other application pods will be placed on to these machines.

/cc @coresolve @sym3tri @philips

**Comment by s-urbaniak** [comment]
I am supportive of this idea. Practice shows that etcd is I/O sensitive (/cc @xiang90 do we have quantifiable data to back this?) and it does make sense to have dedicated machines for them. Having said that, the TF implementation should still allow "one master, one worker" setups for minimal clusters.

**Comment by coresolve** [comment]
I am +100 to this change for exactly those reasons.
