### ISSUE TITLE
Azure: sometimes integration tests don't start

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/tectonic-installer#1420]
Sometimes Azure tests don't kick off at all. CI says:
```
Steps SmokeTest: Azure
 
No steps
This stage has no steps
```

Example: https://jenkins-tectonic-installer.prod.coreos.systems/blue/organizations/jenkins/tectonic-installer/detail/PR-1403/1/pipeline/52

**Comment by mxinden** [comment]
For documentation purposes, this is a log output of one Azure test:
```
[Pipeline] [SmokeTest: Azure] { (Branch: SmokeTest: Azure)
[Pipeline] [SmokeTest: Azure] node
[SmokeTest: Azure] Running on EC2 Ubuntu (i-020b1f160c3b85319) in /home/ubuntu/workspace/tectonic-installer_PR-1403-4BRQ3EQ5NYKDTPN2VVDX7DM5CPG4FLM2QXYVLTC3QUFDGS3HMF6Q@4
[Pipeline] [SmokeTest: Azure] {
[Pipeline] [SmokeTest: Azure] withCredentials
[Pipeline] [SmokeTest: Azure] {
[Pipeline] [SmokeTest: Azure] }
[Pipeline] [SmokeTest: Azure] // withCredentials
[Pipeline] [SmokeTest: Azure] }
[Pipeline] [SmokeTest: Azure] // node
[Pipeline] [SmokeTest: Azure] }
[SmokeTest: Azure] Failed in branch SmokeTest: Azure
```
There are no failure reasons reported.

**Comment by cpanato** [comment]
I will take a look on that. But I did not find anything wrong till now :/

**Comment by mxinden** [comment]
@cpanato Updated most of the Jenkins plugins. Let's see if this fixed it. (Trying to find the needle in the Haystack)

**Comment by mxinden** [comment]
@cpanato As  discussed: I have not seen this occur again. So I will close here.

Please reopen if I am wrong or if it occurs again.
