### ISSUE TITLE
docs: document assets.zip as a reference page.

### ISSUE THREAD

**Issue by zbwright** [coreos/tectonic-installer#1423]
I think we should document assets.zip as its own thing, and point to to the doc, as appropriate.
1. what it is
2. how to use it
  list out all the things people need it for - destroying a cluster. anything else?
3. what's in it
  list everything included in the zip file

question: is this 'package' relatively stable?

assigning to Rob for evaluation and to pass to an appropriate dev to work with me.

**Comment by robszumski** [comment]
Isn't this already covered here? https://github.com/coreos/tectonic-installer/blob/master/Documentation/admin/assets-zip.md

**Comment by robszumski** [comment]
Or at least, should that just be added to?
