### ISSUE TITLE
doc: improve bootkube_recovery_tool.md

### ISSUE THREAD

**Issue by xiang90** [coreos/tectonic-installer#1428]
The doc lacks the cleanup phase before running bootkube recovery.

More specific we should talk about running the following steps on ALL master nodes:

1. stop kubelet service

2. remove docker state 

```
docker kill $(docker ps -q)
docker rm $(docker ps -a -q)
```

3. remove active Kubernetes active manifest (rm /etc/kubernetes/manifests/*)

4. remove self hosted etcd data (rm -rf /var/etcd/kube-*) if self hosted etcd is enabled

5. restart kubelet service

/cc @coresolve

**Comment by radhikapc** [comment]
The steps highlighted in another doc is as follows:

1. Stop kubelet on all masters and stop all containers on the masters. 

2. Clean out /var/run/kubelet/pods I think that's it.
3. Restore etcd. 
4. Verify etcd restored with etcdctl 
5. Verify if there are static manifests for api in inactive-manifests. If not generate them with bootkube recover.
6 Move checkpointer or validate the one in  /etc/kubernetes/manifests.
7. Start kubelet. 
    This should restore the apiserver. If not then use git.io/rescue-pod.sh

**Comment by xiang90** [comment]
@radhikapc 

the one you just mentioned mixed clean up and restore together. i want to make them separate steps. 

but we can add 2. Clean /var/run/kubelet/pods to clean up too.

**Comment by klausenbusk** [comment]
Shouldn't the bootkube [disaster-recovery.md](https://github.com/kubernetes-incubator/bootkube/blob/master/Documentation/disaster-recovery.md), get the same improvement? It took me some time, to realize all the needed steps (cleanup)..
Also see: https://github.com/kubernetes-incubator/bootkube/issues/651
