### ISSUE TITLE
AWS: use modules/dns/route53

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/tectonic-installer#1443]
In the face of DNS modularization, `modules/dns` got route53 support and can already be used in conjunction with openstack.

We should go the next step and factor `modules/aws` to use `modules/dns/route53` to finalize the DNS modularization.

/cc @alexsomesan

**Comment by alekssaul** [comment]
sorry to hi-jack the thread. Saw bunch of dns providers under dns. Currently in platform/vmware (and Baremetal), end user sets up the DNS. I was thinking of creating `platforms/vmware/dns.tf` with pseudo code such as;
```
module "dns-dnsmasq" {
  count = "${var.tectonic_vmware_dns_provider == "dnsmasq" ? 1 : 0}"

  /*
 Use dnsmasq module to register DNS
 */ 
}

module "dns-route53" {
  count = "${var.tectonic_vmware_dns_provider == "route53" ? 1 : 0}"

  /*
 Use route53 module to register DNS
 */ 
}
```
Would that be useful?
