### ISSUE TITLE
platform/azure: Out of public ip addresses

### ISSUE THREAD

**Issue by mxinden** [coreos/tectonic-installer#1454]
```
1 error(s) occurred:


* module.vnet.azurerm_public_ip.tectonic_api_ip: 1 error(s) occurred:


* azurerm_public_ip.tectonic_api_ip: network.PublicIPAddressesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="StaticPublicIPCountLimitReached" Message="Cannot create more than 20 public IP addresses with static allocation method for this subscription in this region." Details=[]
```
https://jenkins-tectonic-installer.prod.coreos.systems/blue/organizations/jenkins/tectonic-installer/detail/PR-1444/9/pipeline/54

Temporary fix: Clean up left over public ip addresses via portal.azure.com

**Comment by colemickens** [comment]
>Clean up left over...

Does that mean Terraform is leaking resources?

**Comment by mxinden** [comment]
@colemickens I can not confirm that for sure. It might have just been our test scripts that did not execute `terraform destroy` properly.

**Comment by dosko64** [comment]
As seen here https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits 
there is a limit in Reserved public IP addresses per LoadBalancer. 
Open a ticket in azure-support with a request to increase your limit. 
If i remember correctly the max limit is 30.

**Comment by colemickens** [comment]
Default is 5. Max is 30 through support. Higher limits can be worked out with some sort of special arrangement by escalating through support.

But I think this limit is per-load balancer, not per-subscription, so it's weird that it only happens some of the time. I'd expect always fail or success based on whether or not the test pass creates more than 5 services. (Or maybe there's parallelism such that more than 5 services are created, but there's usually only less than 5 concurrently?)
