### ISSUE TITLE
tests/azure: Make test environment on Azure reproducible

### ISSUE THREAD

**Issue by mxinden** [coreos/tectonic-installer#1461]
Currently we are using the existing resource groups
* test-ext-group
* pre_vnet
* pre-dns-zone
for our Azure test suit.

Can we make the creation of those resource groups including their required resources reproducible and check those scripts into SCM.

@alexsomesan can you help me with this next week?

**Comment by alexsomesan** [comment]
This is definitely the desired approach. Also what we're already doing for AWS.
We should implement this and get rid of the static resources.
