### ISSUE TITLE
external etcd should use secure connections

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#147]
Requires: https://github.com/coreos/tectonic-installer/issues/206

We just need to pass thru a user-provided CA & Client Cert as secrets used by the temporary API server and the permanent one.

**Comment by s-urbaniak** [comment]
@sym3tri I am working on this now, but to make it clear, this affects "bring your own" etcd only?

Can I assume that (at least for this issue) secure etcd communication for etcd clusters that we do provision can be tackled independently?

**Comment by sym3tri** [comment]
@s-urbaniak yes that's correct. We ultimately need to do both, but let's start with just the BYO case.
