### ISSUE TITLE
Support for AWS Elasticsearch

### ISSUE THREAD

**Issue by amitkumarj441** [coreos/tectonic-installer#1478]
## What keywords did you search in tectonic-installer issues before filing this one?
     AWS Elasticsearch

## Is this a BUG REPORT or FEATURE REQUEST?
     FEATURE REQUEST
Choose one: BUG REPORT or FEATURE REQUEST

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.
    AWS Elasticsearch isn't officially supported at this time. So to setup AWS ElasticSearch Service to quickly and easily run logging aggregation infrastructure with minimal overhead. We need to have Fluentd to collect and aggregate our logs

**Comment by robszumski** [comment]
@amitkumarj441 Are you familiar with the fluentd set up described in https://github.com/coreos/tectonic-installer/blob/master/Documentation/admin/logging.md and related logging guides? Is there something more we could add there?

**Comment by amitkumarj441** [comment]
Yeah @robszumski, I'm already familiar with the logging stack and fluentd set up given in coreos documentation and I'm currently a Google Summer of Code student for CNCF working on [Standardizing Kubernetes logs](https://github.com/amitkumarj441/gsoc17-cncf/blob/master/Proposal/CNCFGSoC17Proposal.pdf) and I would like to add a support for AWS Elasticsearch and want to add [here](https://github.com/coreos/tectonic-installer/blob/master/Documentation/admin/logging-destination.md) for AWS Support.
Please let me know where I can make PRs for AWS Elasticsearch.

**Comment by robszumski** [comment]
@chancez I believe you had originally looked at this. What did you run into that caused you to add the note on the bottom of that guide?

**Comment by chancez** [comment]
It's mostly that upstream doesn't publish and docker images with AWS ES, and so there's nothing quite out of the box that works. You can create a docker image with the `fluent-plugin-aws-elasticsearch-service` gem installed, based on the existing ES image, and then change your configuration for it, or you can use an AWS signing proxy (like https://github.com/cllunsford/aws-signing-proxy). I've used the signing proxy approach, but it's got a lot of overhead and performance issues, and I've not used the fluentd plugin for AWS ES yet. However, it was mostly a time constraint issue, and supporting AWS ES wasn't part of the original requirements.

We've only made very minor changes from the upstream https://github.com/fluent/fluentd-kubernetes-daemonset image, just as a matter of time/resources for maintenance. To add support would probably be a matter of adding the AWS ES gem into the docker image upstream (v0.12-debian-elasticsearch) and then we could update our images. After that all we need would be an example config, and docs like the rest of the backends.

**Comment by amitkumarj441** [comment]
Thanks @chancez for letting me know about the current status on AWS ES support. Could you please point me the path where I can start creating `fluentd-plugin-aws-elasticsearch-service` docker image and fluentd config for Kubernetes.

**Comment by chancez** [comment]
Our docker images are from the `tectonic_logging` branch of our [https://github.com/coreos/fluentd-kubernetes-daemonset](https://github.com/coreos/fluentd-kubernetes-daemonset/tree/tectonic_logging) fork.

To build the image would mean adding a `gem install fluentd-plugin-aws-elasticsearch-service` line under https://github.com/coreos/fluentd-kubernetes-daemonset/blob/tectonic_logging/templates/Dockerfile.erb#L38. This will modify the ruby template used to generate the Dockerfiles used for building.

Then, you would run make, and override some of the parameters so you can build the docker image with a custom image name (replace $yourquayuser with your quay.io username):

```
make release no-cache=yes DOCKERFILE=v0.12/debian-elasticsearch IMAGE_NAME=quay.io/$yourquayuser/fluentd-kubernetes
```

Once built, you can push it, and use it as your image in your fluentd daemonset/deployment.

After you've pushed the Docker image you can modify the Kubernetes manifests in the `Documentation/files/logging/` directory if this repo, and replace the output configuration with one for AWS Elasticsearch. Once you've got something working, then that configuration can be added into our [customizing logging destination documentation](https://github.com/coreos/tectonic-installer/blob/master/Documentation/admin/logging-destination.md) along with a PR to the coreos/fluentd-kubernetes-daemonset repo.

**Comment by amitkumarj441** [comment]
@chancez I just initiated a PR #1693 for this issue, but I haven't seen any template of Kubernetes deployment file ( to properly configure it for AWS ES ) and then a proper container for fluentd to use our config. 

Could you please point out where should I add the Kubernetes deployment file for AWS ES?

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift so we will not be adding this feature in this repo. Open Shift already has a logging solution you might be interested in.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
