### ISSUE TITLE
node-exporter: open port 9100 on aws

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#148]
the node-exporter is used by prometheus and lives on 9100 which isn't open on AWS. Fix thsi.

**Comment by s-urbaniak** [comment]
is there any way we can reproduce this? If I look at the prometheus graphs and service, all seems fine:
![screenshot from 2017-04-07 14-51-45](https://cloud.githubusercontent.com/assets/375856/24801155/3f43ce7a-1ba3-11e7-8539-70e60eab100f.png)

![screenshot from 2017-04-07 14-57-35](https://cloud.githubusercontent.com/assets/375856/24801167/4a8ad544-1ba3-11e7-9681-dd136c2c2574.png)

**Comment by philips** [comment]
This works because we allow all ports between all machines. This is OK but @sym3tri is filing a new issue to ensure we lock down the SGs better.
