### ISSUE TITLE
When using an existing etcd cluster the masters still start etcd-member locally.

### ISSUE THREAD

**Issue by coresolve** [coreos/tectonic-installer#1492]
## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
* Terraform version (`terraform version`): 1.6.7
* Platform (aws|azure|openstack|metal): metal

## What happened?
Brought the cluster up using an existing etcd cluster.
and etcd-member service was started anyway.

## What you expected to happen?
No local etcd pod would be started.
the etcd-member service would not be started.

## How to reproduce it (as minimally and precisely as possible)?
Bring up tectonic with an existing external etcd cluster. 
Note that the etcd-member service is started.

## Anything else we need to know?

**Comment by alexsomesan** [comment]
I'll look into this and post back the findings.

**Comment by Quentin-M** [comment]
Have you found anything? :)

**Comment by coresolve** [comment]
this is here:
https://github.com/coreos/tectonic-installer/blob/master/platforms/metal/cl/bootkube-controller.yaml.tmpl#L5

and here:
https://github.com/coreos/tectonic-installer/blob/master/platforms/metal/matchers.tf#L39

and the fact that in this case tectonic-experimental is false.
