### ISSUE TITLE
Tectonic installation on Azure failed - "etcd_cert_dns_names" not set

### ISSUE THREAD

**Issue by rajcheval** [coreos/tectonic-installer#1504]
## What keywords did you search in tectonic-installer issues before filing this one?

I found a similar issue in google group

https://groups.google.com/forum/#!searchin/coreos-user/etcd_cert_dns_names$20not$20set%7Csort:relevance/coreos-user/T0LduyuLqW0/B5er_0NrAwAJ

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

Tried to provision a new cluster in azure.
I did set every required variable in the documentation.
There was no reference to etcd_cert_dns_names.
When I ran terraform plan I got the error

* module root: module bootkube: required variable "etcd_cert_dns_names" not set

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
* Terraform version 1.6.7
* Platform: azure

## What happened?
terraform plan 
* module root: module bootkube: required variable "etcd_cert_dns_names" not set

## What you expected to happen?
expected terraform plan to work

## How to reproduce it (as minimally and precisely as possible)?
provision a new cluster in azure with the released version of installer

**Comment by robszumski** [comment]
Hi @rajcheval, this is a known issue that we'll get fixed for our next release. If you'd like to get unblocked immediately, you can use the master branch, which is already fixed/up to date.

**Comment by sym3tri** [comment]
I believe this should be fixed now in the latest release. Pleas reopen if you encounter this again.
