### ISSUE TITLE
Tectonic-installer leaves absolute paths in the statefile, which is problematic when handing off state to team members.

### ISSUE THREAD

**Issue by chuckbutler** [coreos/tectonic-installer#1507]
Related to: https://github.com/coreos/tectonic-installer/issues/1135    

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT 

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.6.4+ (undetermined if previous versions are affected.
* Terraform version (`terraform version`): 1.9.x
* Platform (aws|azure|openstack|metal): aws (But a grep reveals this to be in all substrate modules.)

## What happened? 

The use of `${path.module}` variable in the terraform files yields a statefile with absolute paths. This makes the terraform statefile basically useless on other developer systems if in a shared environment.

## What you expected to happen? 

The ability to share the state file for cluster destruction.

## How to reproduce it (as minimally and precisely as possible)?  

run the tectonic installer locally using terraform, and capture the `generated` directory plus statefiles and hand them off to another developer. Attempting to tear down the cluster using these assets will complain about template paths and block destruction of the cluster.

## Anything else we need to know?  

This can be mitigated with relative pathing in the modules, eg using `../` instead of `${path.module}`.  However I'm uncertain of the impact when users are executing the tectonic-installer in non-standard ways.

**Comment by coresolve** [comment]
@kmitts1

**Comment by coresolve** [comment]
@robszumski

**Comment by robszumski** [comment]
I will add this to the list of stuff tracked on https://github.com/coreos/tectonic-installer/issues/1363

Thank you for reporting @chuckbutler, we've been tracking this and know it is a pain.

**Comment by chuckbutler** [comment]
Was this abandoned or will this be in an upcoming tectonic-installer release? I'm curious where I can test if thats the case.

**Comment by jonmosco** [comment]
I was able to correct the path issues by doing a terraform refresh on the state file.
