### ISSUE TITLE
Make default prometheus spec.resources configurable (cpu memory requests & limits)

### ISSUE THREAD

**Issue by joshrosso** [coreos/tectonic-installer#1515]
## FEATURE REQUEST

Tectonic installations [provision a prometheus](https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/manifests/monitoring/prometheus-k8s.yaml) used by the Tectonic console.

Based on observations in production scenarios, we've found this spec.resource.limits to be under what's feasible for how our Prometheus is tuned. Regardless, it seems desirable to be able to set these limits from the installer so that prometheus is provisioned in your desired state OOTB.

This feature request includes the desire to make the following fields configurable in the prometheus `prometheus-k8s.yaml`.

- `spec.resources.limits.*`
- `spec.resources.requests.*`

## Versions

* Tectonic version [1.6.7-tectonic.1](https://github.com/coreos/tectonic-installer/releases/tag/1.6.7-tectonic.1)
* Terraform version (`*`)
* Platform (*)

**Comment by sym3tri** [comment]
this is now available
