### ISSUE TITLE
Clicking on left side nav components doesn't snap you to top of page

### ISSUE THREAD

**Issue by eddieesquivel** [coreos/tectonic-installer#1539]
BUG REPORT

## Versions

* Tectonic version: tectonic-1.7.1-tectonic.1-rc.2
* Platform: AWS

## What happened?

Clicking on several of the left hand side nav items doesn't snap you to the top of the page. Components with issues are: 
* dameon sets
* deployments
* replica sets
* replication controller
* config-map
* cluster-settings
* events
* my-account

## What you expected to happen?
I expected that clicking on cluster-settings would send me to the top of the cluster-settings page. Compare with how clicking on pods snaps you to top of page.

## How to reproduce it (as minimally and precisely as possible)?
Scroll down on Tectonic UI and click on cluster-settings

**Comment by eddieesquivel** [comment]
@Quentin-M

**Comment by sym3tri** [comment]
Not an installer issue, this is Console. Please file under: https://coreosdev.atlassian.net/projects/FR/issues
