### ISSUE TITLE
Navigating from Service Account to Roles gives 404

### ISSUE THREAD

**Issue by eddieesquivel** [coreos/tectonic-installer#1545]
BUG:

## Versions

* Tectonic version: 1.7.2 rc2

* Platform: AWS

## What happened?
I clicked on a service account I created:

<img width="1406" alt="screen shot 2017-08-01 at 11 49 36 am" src="https://user-images.githubusercontent.com/5018462/28841581-982c7e62-76af-11e7-97b5-1865cd80f475.png">

Then I clicked on the Roles side bar link and got a 404

<img width="1434" alt="screen shot 2017-08-01 at 11 49 55 am" src="https://user-images.githubusercontent.com/5018462/28841611-a45fee6c-76af-11e7-8e36-20633c3a8d34.png">

## What you expected to happen?
I expected to navigate to the roles page without a 404

## How to reproduce it (as minimally and precisely as possible)?
Create a service account (though this works for other default service accounts but doesn't happen 100% of the time), navigate to the service account and then click on roles.

**Comment by Quentin-M** [comment]
Can you try with Console 1.8.4?

**Comment by eddieesquivel** [comment]
@Quentin-M looks like its fixed in 1.8.4.

**Comment by Quentin-M** [comment]
Awesome, thanks!
