### ISSUE TITLE
Prometheus Operator Screen returning: the server does not allow this method on the requested resource

### ISSUE THREAD

**Issue by eddieesquivel** [coreos/tectonic-installer#1547]
## Versions

* Tectonic version: 1.7.1 rc 2
* Platform: aws

## What happened?
Attempted to create a prometheus instance via the operator screen. Got a **the server does not allow this method on the requested resource** error:

<img width="1425" alt="screen shot 2017-08-01 at 12 00 54 pm" src="https://user-images.githubusercontent.com/5018462/28842116-46de5aec-76b1-11e7-9d31-cfe3d6b4b944.png">

## What you expected to happen?
Expected to be able to create prometheus instances via operator screen

## How to reproduce it (as minimally and precisely as possible)?
Create a prometheus operator with following yaml:

> apiVersion: monitoring.coreos.com/v1alpha1
> kind: Prometheus
> metadata:
>   name: prometheus-hello-world
>   labels:
>     prometheus: "prometheus-hello-world"
> spec:
>   serviceAccountName: prometheus
>   alerting:
>     alertmanagers:
>     - namespace: default
>       name: alertmanager-helloworld
>       port: web
>   serviceMonitorSelector:
>     matchLabels:
>       team: hello-world
>   version: v1.6.3
>   resources:
>     requests:
>       memory: 400Mi
>   ruleSelector:
>     matchLabels:
>       role: prometheus-rulefiles
>       prometheus: prometheus-helloworld

**Comment by Quentin-M** [comment]
Is this one fixed by 1.8.4 @ggreer @kans ?

**Comment by eddieesquivel** [comment]
@Quentin-M this was fixed by console 1.8.4

**Comment by Quentin-M** [comment]
Cool, thanks!
