### ISSUE TITLE
ETCD Operator no longer an option

### ISSUE THREAD

**Issue by eddieesquivel** [coreos/tectonic-installer#1549]
##Versions

Tectonic 1.7.1 rc2
AWS

##What happened?

Etcd operator is no longer an option. It was visibile in 1.6.7 release

<img width="218" alt="screen shot 2017-08-01 at 12 38 38 pm" src="https://user-images.githubusercontent.com/5018462/28843566-82088ef8-76b6-11e7-9e8c-5efdfcf2fd84.png">

**Comment by amrutac** [comment]
@eddieesquivel: Did you choose self hosted etcd option when creating the  on 
your cluster? The etcd operator link is hidden if etcd operator is not not installed.

<img width="590" alt="screen shot 2017-08-01 at 12 47 53 pm" src="https://user-images.githubusercontent.com/523368/28843916-b977f576-76b7-11e7-84fc-2488eebd2bc4.png">

**Comment by eddieesquivel** [comment]
@amrutac I didn't install with self-hosted. Rob mentioned we're working on making etcd as a service an option even if you don't install with self hosted etcd.
