### ISSUE TITLE
Azure SkuNotAvailable error

### ISSUE THREAD

**Issue by mxinden** [coreos/tectonic-installer#1560]
We are repeatedly seeing the following error:
```
* module.etcd.azurerm_virtual_machine.etcd_node[0]: 1 error(s) occurred:


* azurerm_virtual_machine.etcd_node.0: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="SkuNotAvailable" Message="The requested tier for resource '/subscriptions/****/resourceGroups/tectonic-cluster-basic-pr-1558-10123456789012/providers/Microsoft.Compute/virtualMachines/basic-pr-1558-10123456789012-etcd-0' is currently not available in location 'centralus' for subscription '****'. Please try another tier or deploy to a different location."
```

This happened among others in:
* centralus
* eastus2
* northeurope

As pointed out by @alexsomesan this should be related to the SKU defined in `storage_image_reference` of a machine (See [here](https://github.com/coreos/tectonic-installer/blob/master/modules/azure/master-as/master.tf#L48)).

Running `az vm image list-skus -l northeurope  -o table -p CoreOS -f CoreOS` as documented [here](https://docs.microsoft.com/en-us/cli/azure/vm/image#list) returns all three channels:

```
Location     Name
-----------  ------
northeurope  Alpha
northeurope  Beta
northeurope  Stable
```
We are setting `tectonic_cl_channel = "stable"` in our tests.

**Comment by mxinden** [comment]
Does Azure differentiate between `Stable` and `stable`?

**Comment by squat** [comment]
This is happening because it resources are not getting destroyed. It's the equivalent of reaching the instance account limit on AWS but for a specific machine size. We need to clean up the account. I went through some regions last night and manually deleted resource groups but there's still tons of stuff there. Terraform is constantly timing out trying to destroy resources.

**Comment by mxinden** [comment]
I was testing this locally with empty locations (a.k.a regions) like `centralus` and I was still facing the same issue. @squat Are you sure this is due to account limits?

I will dig further into this tomorrow.

So far:
- This issue happens on e.g. `centralus` but not in `eastus` (Tested locally, can also be seen by looking at recent Jenkins build logs - `example.tfvars`, which is run in `eastus`, succeeds)
- Changing to current container linux version (1409.7.0) does not resolve the isssue

**Comment by mxinden** [comment]
The reason for this error message was, that our Azure subscription currently has no permission to start VMs in certain regions. We are working on regaining those permissions for those regions. As a temporary fix, we have moved the Azure tests to regions where we do have those permissions (See #1558).
