### ISSUE TITLE
tests: Create public-pr-trigger Jenkins job via Jenkins job DSL

### ISSUE THREAD

**Issue by mxinden** [coreos/tectonic-installer#1563]
Right now the `public-pr-trigger` Jenkins job is still manually configured via the UI. We should move this into a Groovy job DSL script inside the `tests/jenkins-jobs` folder, so it can be created by our Seed job.

A good example on how to configure the *GitHub Pull Request Builder Plugin* in a Jenkins Job DSL can be found in the [Prometheus operator Github repo](https://github.com/coreos/prometheus-operator/blob/master/Jenkinsfile).

**Comment by cpanato** [comment]
I will take this one
