### ISSUE TITLE
kube_dns: make HA when master_node count > 1

### ISSUE THREAD

**Issue by joshrosso** [coreos/tectonic-installer#1579]
## FEATURE REQUEST: kube_dns: make HA when master_node count > 1

When the quantity of master nodes in a Tectonic cluster exceed 1, Tectonic should deploy the same number of `kube_dns` pods to ensure high availability OOTB.

**Point to consider**:

- Today, we call out not to set the replica parameters as it won't be respected via the add on manager. However, I cannot see `kube-addon-manager` present in Tectonic clusters as of `1.6.7`. **Am I missing something?** A diff of what i'm describing follows.

    ```
    @@ -28,24 +28,29 @@ metadata:
         k8s-app: kube-dns
         kubernetes.io/cluster-service: "true"
    spec:
    -  # replicas: not specified here:
    -  # 1. In order to make Addon Manager do not reconcile this replicas parameter.
    -  # 2. Default is 1.
    -  # 3. Will be tuned in real time if DNS horizontal auto-scaling is turned on.
   +  replicas: ${master_count}
    ```

- When HA, we must ensure affinity works in the same respect as `kube-controller-manager` and `kube-scheduler`. Including the following behavior.
  - `kube-dns` pods exist on separate nodes.
  - updates still supported with affinity rules in place
    - specifically relevant for single-master clusters

- While the [dns-horizontal-autoscaler](https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/) may still be the preferred method for scaling `kube-dns`, this change would:
  - ensure sensible default is init on cluster boostrap
  - introduce an HA-dns for those who won't use this autoscaler

## Versions

* Tectonic version (d7ce8cddc7906b87947a7dcb94718c537ad80e8d):
* Terraform version (`Terraform v0.9.7`):
* Platform (*):

/cc @aaronlevy : do you see issues with this approach? Especially regarding updates/bootkube?

**Comment by aaronlevy** [comment]
Longer term I'd probably prefer that the autoscaler was used.

Often dns needs to be scaled for throughput not just HA -- so adding node based anti-affinity would restrict this to the number of nodes.

Additionally, DNS pods will get recreated if they die (even if there is only one copy).

Not necessarily opposed to this, but there are tradeoffs when dns-autoscaler is probably what you ultimately want.

**Comment by aaronlevy** [comment]
I'd actually recommend that anti-affinity is not used. Scaling DNS for throughput is pretty common - and this seems too restrictive.

**Comment by joshrosso** [comment]
Who's best to make the call on whether we can just add the [dns-horizontal-autoscaler](https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling) to Tectonic by default?

The PR can be easily adapted as such. @robszumski ?

**Comment by coresolve** [comment]
Another point of data. HA is a win because when the node hosting the dns pod takes an update dns will fail for existing apps until the dns pod is rescheduled. I think anti affinity makes sense here.

**Comment by joshrosso** [comment]
I'd like to propose the following modification to the PR that may find common ground.

1. Set the default replica count to `2`.
   1. It'll exist this way until the [dns-horizontal-autoscaler](https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling) is deployed.
1. Add a [PDB](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#how-disruption-budgets-work) for kube-dns that mitigates some scenarios (e.g. blocking a drain) to ensure we have at least 1 kube-dns instance running at a time. ie `spec.minAvailable: 1`
1. Switch to `preferredDuringSchedulingIgnoredDuringExecution`. I understand scaling based on throughput contends with this option a bit, but if not this, we need to find some solution to guarantee HA kube-dns.

@aaronlevy, @coresolve: let me know your thoughts and where my logic may be off. Thanks in advanced!

**Comment by sym3tri** [comment]
We'll consider this for the converged platform.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
