### ISSUE TITLE
azure: support kubenet + azure UDR for pod networking

### ISSUE THREAD

**Issue by colemickens** [coreos/tectonic-installer#1585]
## What keywords did you search in tectonic-installer issues before filing this one?

`azure kubenet`, `azure network plugin`

## Is this a BUG REPORT or FEATURE REQUEST?

**Feature Request**

It would be good to support `kubenet` for Azure:

1. Support a configuration similar to what Azure Container Service ships
2. Support a non-overlay (albeit Azure underlay) networking option
3. The `azure-vnet` CNI plugin is not really stable or encouraged right now (that is Issue #178)

This requires changes in:
1. `bootkube` module:
   * add `--configure-cloud-routes=true` when using `kubenet`
   * configure the `--network-plugin=[cni|kubenet]` flag

2. `azure` module:
   * add route table
   * configure each subnet to use the route table
   * enabling IP Forwarding on the VM NICs

Few comments when thinking through implementation:
1. Do we use `--configure-cloud-routes`, or do we statically assign the `/24`s
   to each node using Terraform? I've only used the former where K8s then
   calls into the Azure APIs on Node create/delete to update the route table. Is
   there any point in supporting both? (No one has ever asked for it, though
   I've seen some other less popular bringups use the pre-allocated method...)

2. How to expose this option? Just a new input variable on the top level
   `platform/azure` module? A bool named `useCNI`/`useKubenet`? Does Terraform
   allow one to specify "must be one of these values"?

Let me know thoughts. If this sounds okay I can take a crack at implementing it.

**Comment by colemickens** [comment]
Any idea of how desired this is? I have it working in a branch but it needs cleanup to be sent for PR. If it's desired, I can do the work and send a PR. If you're happy with CNI+Flannel and want to wait until CNI+AzureVnetPlugin is an option, that makes sense too.

**Comment by sym3tri** [comment]
We'll consider this for the converged platform.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
