### ISSUE TITLE
Docs have a few broken links

### ISSUE THREAD

**Issue by crawford** [coreos/tectonic-installer#1587]
[marker](https://crates.io/crates/marker) detected a number of broken links when run from the root of this project. The output is attached below (I did not test HTTP connectivity; just local references).

<details>

```
Found broken reference (etcd recommended hardware -> etcd recommended hardware) at ./Documentation/variables/aws.md:11
Found broken reference (CAVEAT -> CAVEAT) at ./Documentation/variables/azure.md:23
Found broken reference (Azure-specific NOTE -> Azure-specific NOTE) at ./Documentation/variables/config.md:11
Found broken reference (ALPHA -> ALPHA) at ./Documentation/variables/config.md:15
Found broken reference (coreos/tectonic-error-server -> coreos/tectonic-error-server) at ./images/tectonic-error-server/README.md:13
Found broken path      (Tectonic Installer -> ../installer) at ./images/tectonic-builder/README.md:6
```

**Comment by sym3tri** [comment]
The majority of this is from vendored code that should be ignored. Anything
under: "installer/frontend/node_modules/..." should be ignored.

Also it seems this tool does not handle external links properly.

i.e. the 1st one: "Found broken reference (etcd recommended hardware ->
etcd recommended hardware) at ./Documentation/variables/aws.md:11"
links to: https://coreos.com/etcd/docs/latest/op-guide/hardware.html which
is valid.

**Comment by crawford** [comment]
I updated the issue to reflect that shortly after opening it. The remaining six links do appear broken though.

> Also it seems this tool does not handle external links properly.

There is a space between the brackets and parenthesis. The result is that it renders as `[etcd recommended hardware] (https://coreos.com/etcd/docs/latest/op-guide/hardware.html)`.

**Comment by zbwright** [comment]
these markdown files are automatically generated from the variables.tf files for each platform. I'll create a PR to edit those original files.

**Comment by zbwright** [comment]
This information should be given to whichever developers are working on these files:
1. Don't use bracket formatting for anything other than links. For example `[CAVEAT]` results in a "broken link", but it's not really a link at all. I changed to `NOTE:`
2. To insert a link to a different text string, use the syntax [text string](link). No space between the bracketed text, and the parenthetical link URL.
3. I don't know how to fix this one. Looks like you want it to be included only in the Azure variables doc: `Found broken reference (Azure-specific NOTE -> Azure-specific NOTE) at ./Documentation/variables/config.md:11`
4. I also don't know how to fix this one, or even what the goal was: `Found broken reference (ALPHA -> ALPHA) at ./Documentation/variables/config.md:15`

**Comment by zbwright** [comment]
https://github.com/coreos/tectonic-installer/pull/1620

**Comment by zbwright** [comment]
2 broken links still broken, as listed in items #3 and #4 in the comment above. I'm not sure who should address those, but probably @sym3tri
