### ISSUE TITLE
Ensure tectonic-console and tectonic-identity schedule on separate nodes

### ISSUE THREAD

**Issue by joshrosso** [coreos/tectonic-installer#1615]
## FEATURE REQUEST: Ensure tectonic-console and tectonic-identity schedule on separate nodes

At this time, we set the replica count of the `tectonic-console` and `tectonic-identity` to `2`. We should add affinity rules that ensure they're schedule on unique nodes.

My preference is [requiredDuringSchedulingIgnoredDuringExecution](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature) in order to ensure pods exist on different nodes. Considering these pods land on worker nodes, it seems reasonable to assume most clusters will containe `> 1` workers.

However, I can understand if preference is to use `preferred`. I'm sure a case could be made around throughput. Although, again, I feel a stronger case could be made around HA-guarantees. 

## Versions

* Tectonic version (https://github.com/coreos/tectonic-installer/commit/9bd3835dde019c8c5a410c62596fb18e290e67ef)
* Terraform version (`Terraform v0.9.7`):
* Platform (*):

**Comment by robszumski** [comment]
I believe there are blockers around supporting single node and/or master clusters because you can't execute rolling updates, as they would never get scheduled.

**Comment by squat** [comment]
They will still get scheduled if we use
`preferedDuringSchedulingIgnoredDuringExecution`

**Comment by joshrosso** [comment]
@robszumski See convo in PR for more context on that.

**Comment by sym3tri** [comment]
We won't make this change b/c it's not relevant for the converged platform.

https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
