### ISSUE TITLE
Automate packet.net worker provisioning

### ISSUE THREAD

**Issue by mxinden** [coreos/tectonic-installer#1617]
Currently we are spinning up new packet.net workers manually. This should be automated via e.g. the jcloud plugin. This has already been in place before, but is currently not working.

**Comment by cpanato** [comment]
this is on Jenkins? Is the bare metal slaves?

I will look into

**Comment by mxinden** [comment]
This seems to be related: https://github.com/jclouds/jclouds/pull/1103

**Comment by Quentin-M** [comment]
This PR is simply pulling the history of the Packet.net plugin from the labs to the main repository.

**Comment by sym3tri** [comment]
moved https://coreosdev.atlassian.net/browse/INST-203
