### ISSUE TITLE
User with namespace Binding can't use the console

### ISSUE THREAD

**Issue by eddieesquivel** [coreos/tectonic-installer#1664]
BUG
## Versions

* Tectonic version: 1.7.1
* Platform: AWS

## What happened?

Created a namespace role binding for a user:

<img width="1086" alt="screen shot 2017-08-11 at 9 52 48 am" src="https://user-images.githubusercontent.com/5018462/29223276-e0a40052-7e7a-11e7-89f7-ad83eaf65813.png">

Once the role binding is created I log on with the user but can't access or work with my namespace:

<img width="1424" alt="screen shot 2017-08-11 at 9 50 14 am" src="https://user-images.githubusercontent.com/5018462/29223302-f4c956e0-7e7a-11e7-8844-aa3d80faa493.png">

## What you expected to happen?
I'd expect that as an admin user on that namespace I'd be able to view/edit deployments in my namespace.

## How to reproduce it (as minimally and precisely as possible)?
1) Integrate cluster with LDAP
2) Create a namespace binding for a user
3) Log on with the user

**Comment by sym3tri** [comment]
@eddieesquivel Thanks for the report but this is not an installer issue. Please file under: https://coreosdev.atlassian.net/projects/FR/issues
