### ISSUE TITLE
AWS access key IDs always begin with 'AK'

### ISSUE THREAD

**Issue by PickleChops** [coreos/tectonic-installer#1686]
## What keywords did you search in tectonic-installer issues before filing this one?

'AWS access key', 'begin with'

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

Tectonic: 1.7.1-tectonic.1 (5b67c4f)
Terraform: v0.9.6
Platform: AWS

## What happened?

Attempting to install using the installer.

The credentials I get back from an aws assume-role include an AccessKeyId that starts "ASIA.." 

On the AWS Credentials screen I am unable to add the temporary credentials as the field validation on Access Key ID shows "AWS access key IDs always being with 'AK'"

## What you expected to happen?

That the UI would accept my credentials.

## How to reproduce it (as minimally and precisely as possible)?

In my case just `aws sts assume-role` with appropriate role arn etc. and then attempt to add credentials to installer screen

## Anything else we need to know?

The same credentials work if I install a cluster with Terraform via the CLI. 

Thanks.

**Comment by robszumski** [comment]
This should have just merged in https://github.com/coreos/tectonic-installer/pull/1666

**Comment by squat** [comment]
Thanks for reporting this. We are tracking this issue and just fixed it in #1653. Our next releases will include this fix and building from master will work correctly as well. I am closing for now. Please reopen this issue if you continue to experience this problem.

**Comment by PickleChops** [comment]
Many thanks.
