### ISSUE TITLE
Make tectonic_pull_secret_path format clear in the example tfvars file

### ISSUE THREAD

**Issue by pst** [coreos/tectonic-installer#172]
In the [tfvars.example file](https://github.com/coreos/tectonic-installer/blob/master/platforms/aws/terraform.tfvars.example) it's not clear which format `tectonic_pull_secret_path` expects from the website. It seems to expect the dockercfg one, I provided the Kubernetes secret one. Picking the wrong one leaves you with a cluster with an empty tectonic-system namespace.

**Comment by robszumski** [comment]
@pst Two issues here, that we're in the process of cleaning up.

1. We never ended up using the Kubernetes version of the secret, that will be remove from the website.
2. The filename in this sample `config.json` matches what is downloaded, but the button still says `dockercfg` which was the older name that docker used for this. We need to change that as part of the web changes. Sorry about that.

**Comment by sym3tri** [comment]
Having hardcoded paths in the vars makes things fragile. We should just put the values inline for better portability.

**Comment by s-urbaniak** [comment]
@sym3tri pulling in the secret values instead of paths into the tfvars state file falls in the same discussion bucket as #710. Before we implement it that way I suggest to clarify the strategy in the referenced issue before we proceed as suggested.

**Comment by s-urbaniak** [comment]
actually reassigning to me, as we can at least make the documentation better in the config.tf description.

**Comment by sym3tri** [comment]
@s-urbaniak agreed. let's discuss.
