### ISSUE TITLE
Deleting etcd operator from console does not delete its Deployment

### ISSUE THREAD

**Issue by metral** [coreos/tectonic-installer#1721]
## What keywords did you search in tectonic-installer issues before filing this one?
etcd operator

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.7.1-tectonic.1
* Terraform version (`terraform version`): v0.9.10
* Platform (aws|azure|openstack|metal): aws

## What happened?
When deleting the etcd operator from the console, its Pod continues to be created because the Deployment never gets removed.

## What you expected to happen?
For the etcd operator pods and Deployment to be removed when removing it from the console.

## How to reproduce it (as minimally and precisely as possible)?
- Create an etcd operator in the console
- Then after its up, try removing it from the console
- In the etcd operators page it shows that there are no clusters, however the Deployment and Pods remain

**Comment by sym3tri** [comment]
@metral Please file this in the Field Requests backlog as this is not installer-specific. This is likely an issue with Console.
