### ISSUE TITLE
Bootkube fails to bring up control plane

### ISSUE THREAD

**Issue by dileepfrog** [coreos/tectonic-installer#1728]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

* Tectonic version 1.7.1-tectonic.2, 1.7.1-tectonic.1, 1.6.7-tectonic.2
* Terraform version (`terraform version`): v0.9.6 (tectonic installer bundled)
* Platform aws

## What happened?

We had a cluster running on 1.6.7-tectonic.2 humming along with no issues. After 1.7.1 went GA I did an automated update via the Console. After a while the control plane went down and none of the apiservers would start. I tried running a Terraform install of 1.7.1 on top of the cluster and it did not solve the problem. I destroyed the cluster, brought up a new one, and same problem. Much worse than that, I destroyed everything, brought up a fresh cluster using TF on 1.6.7-tectonic.2, and the problem still occurred - bootkube fails to bring up an apiserver on the bootkube master. It's entirely unclear what has happened to render Tectonic unusable as we have not changed any settings in the .tfvars for some time.

## What you expected to happen?

Bootkube should bootstrap the masters correctly and bring up a healthy cluster

## How to reproduce it (as minimally and precisely as possible)?

Follow the guide for any of the versions above https://coreos.com/tectonic/docs/1.6.7-tectonic.2/install/aws/aws-terraform.html

## Anything else we need to know?

https://gist.github.com/dileepfrog/e6637286fcd5834d2e83ec3c712879de
https://gist.github.com/dileepfrog/13da721459d1f6760034a63d2f4c3320
https://gist.github.com/dileepfrog/a41d7fe880c91f42fabe15fb62a85116

**Comment by dileepfrog** [comment]
I have found the root of this issue. We were supplying tectonic_aws_external_private_zone but installing to a new VPC. It is not documented that this field should only be supplied when installing to an existing VPC. Unlike kops, the tectonic installer is not smart enough to switch the vpc_id of the existing private zone to that of the new tectonic VPC (from the default VPC) and therefore no internal DNS can be resolved. This seems like a straightforward fix in Terraform - our use case is that we want a different DNS for the internal zone vs the public zone for the cluster.

**Comment by sym3tri** [comment]
Thanks for the report. This should be resolved in master and coming out in our next release. Please let us know if you run into this again.

**Comment by chancez** [comment]
I ran into the same issue as https://github.com/coreos/tectonic-installer/issues/1728#issuecomment-323483580 today. I believe the the example tfvars and docs need to be updated to inform users about using `tectonic_aws_external_private_zone` and that it means either also using an existing VPC associated with the existing private zone, or the zone must be manually associated with the newly created VPC, or perhaps terraform can associate the existing zone with the new VPC.
