### ISSUE TITLE
azure: make use of Azure CNI plugin

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#178]
I haven't had a chance to dig into this but it might be a good fit: https://github.com/Azure/acs-engine/pull/460

**Comment by philips** [comment]
Plugin code: https://github.com/Azure/azure-container-networking

**Comment by colemickens** [comment]
I'm hearing that the latest release of the azure vnet CNI plugin is stable enough to take a dependency on.

Ref: https://twitter.com/colemickens/status/898340847820742656 and https://github.com/Azure/acs-engine/pull/1259
