### ISSUE TITLE
openstack: security groups in novanet may be blocking vxlan communication

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#181]
During testing  on a particular environment we've come across an issue where tectonic-installer security group for master-nodes blocked vxlan transport. In-field workaround was the remove master nodes from the security groups as the default mode for the openstack environment allowed node-to-node communication.

Potential workaround long term may be to specify a UDP port for vxlan encapsulation and include it with security groups settings, however I didn't get a chance to test this.

/cc: @s-urbaniak

**Comment by lblackstone** [comment]
I think this should be fixed by https://github.com/coreos/tectonic-installer/pull/825

**Comment by alekssaul** [comment]
I believe it's fixed with the PR. I no longer have access to the same environment. 
@s-urbaniak I am good with closing the issue if that sounds reasonable.

**Comment by lblackstone** [comment]
@s-urbaniak Now that #851 has merged, I think this should be fixed for both openstack installers.

**Comment by s-urbaniak** [comment]
@lblackstone ack, thanks for the hint! I am closing this for now.
