### ISSUE TITLE
Tectonic console page turn to "Error Loading ... please try again" while accessing from places afar

### ISSUE THREAD

**Issue by brant4test** [coreos/tectonic-installer#1820]
Hi, Team,
I Installed Tectonic on AWS(Singapore) successfully.
But when I tried to access console page from California office, always telling me “Error Loading…”, then clicking “try again”, its content coming out as last. And accessing from Singapore office is fine. 
**How to improve this use experience?** “Each sub-menu page need a double fresh **accessing for places afar**”

![image](https://user-images.githubusercontent.com/7472674/29962185-de3d87a0-8f34-11e7-9f48-e4ee3420fca6.png)

Best wishes,
Brant

**Comment by sym3tri** [comment]
Sorry for the late reply. I'm not sure what the issue could be. It's actually a Tectonic Console issue, not an installer issue, so there's nothing we can do here in this repo.

You could try getting help here:
https://github.com/coreos/tectonic-forum/issues
