### ISSUE TITLE
clarification documentation VMware controller node

### ISSUE THREAD

**Issue by kgelinas** [coreos/tectonic-installer#1825]
## BUG REPORT

This is my first attempt in Tectonic maybe someone used to the environnement could better understand the terminology but following the documentation should be clear.

Variable in vmware does not describe what is the controller node used with the var tectonic_vmware_controller_domain

> The domain name which resolves to controller node(s)

https://github.com/coreos/tectonic-installer/blob/master/Documentation/install/vmware/vmware-terraform.md

I tried "Mycluster" and "Mycluster-k8s" but this does not seem to work.

Results
null_resource.bootstrap (remote-exec): A dependency job for tectonic.service failed. See 'journalctl -xe' for details.
Error applying plan:

1 error(s) occurred:

* null_resource.bootstrap: 1 error(s) occurred:

* Script exited with non-zero exit status: 1

## Versions
1.7.1-2

**Comment by alekssaul** [comment]
Hi @kgelinas ,

This is the fully qualified domain name of controller node(s). ex: kubernetesapi.company.com . 

If your cluster has a single controller, you can create a CNAME or A record that points to the controller name in DNS. In multi-master topology, general recommendation is to point this record in DNS to a Load Balancer VIP that load balances between controllers on TCP/443.

**Comment by kgelinas** [comment]
Hi @alekssaul,
thanks for the clarification
so the controller node is in the most case the master node?

**Comment by alekssaul** [comment]
@kgelinas 

Correct

**Comment by carlosaya** [comment]
I really don't think this should be closed until the documentation has been updated.  I just ran into the same thing in the tfvars file.

**Comment by kgelinas** [comment]
@carlosaya did you succeed to install techtonic on VMware?
I kept going with kubeadm for now will wait when it's out of alpha/beta for vmware...

**Comment by carlosaya** [comment]
@kgelinas only got the tfvars done on friday and then had to go.  will resume this week!

**Comment by carlosaya** [comment]
@kgelinas got it working with external etcd cluster and i think i am on the verge of getting it working with an internal etcd 👍 .  This is on vSphere 6.0, Build 7462485
