### ISSUE TITLE
Support for newer 1.7 releases?

### ISSUE THREAD

**Issue by jamiehannaford** [coreos/tectonic-installer#1828]
Do you folks have any plan to support 1.7.5 (or at least 1.7.4) in the near future? We're relying on some bug fixes in that release, and it'd be great if we didn't have to roll out our own custom hyperkube binary.

**Comment by sym3tri** [comment]
Yes. Our primary releases ship about once per month, and we ship kubernetes patch release for older minor versions as they become available.

**Comment by jamiehannaford** [comment]
@sym3tri So patch versions are released on a monthly cadence, or on an ad hoc basis? Do you have a RSS feed to track these releases?
