### ISSUE TITLE
Deploying to Azure fails when specifying Azure region display name instead of region name

### ISSUE THREAD

**Issue by cricci82** [coreos/tectonic-installer#1856]
BUG REPORT

## Versions

* Tectonic version: 1.7.1-tectonic.2
* Terraform version: Terraform v0.9.6
* Platform: Azure

## What happened?
Terraform Azure Provider allows you to specify the Azure Region using the displayName (e.g. Central US) or  Name (e.g centralus).  If using the displayName, the resources will get created in Azure, however, the kubelet will fail to start with the following error:

`Sep 06 14:09:47 swtctn2-master-0 kubelet-wrapper[1397]: E0906 14:09:47.261466    1397 kubelet_node_status.go:106] Unable to register node "swtctn2-master-0" with API server: Node "swtctn2-master-0" is invalid: metadata.labels: Invalid value: "Central US": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`

## What you expected to happen?
The cluster to start successfully.  

## How to reproduce it (as minimally and precisely as possible)?
Use the region's displayName like `East US` or `Central US` when specifying `tectonic_azure_location`

**Comment by cpanato** [comment]
@cricci82 thanks for the report, we will track this bug here https://coreosdev.atlassian.net/browse/INST-349

closing this issue
