### ISSUE TITLE
Feature proposal: Configurable NTP servers

### ISSUE THREAD

**Issue by lblackstone** [coreos/tectonic-installer#1866]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

I'd like to add a variable that allows NTP servers to be selected for time synchronization. This is an important feature for installs (e.g., private clouds) that may not have internet access to the default NTP servers.

The default behavior would not change.

I've already implemented this change downstream for OpenStack, but I think it would make sense across platforms.

**Comment by spiette** [comment]
As the pull request is blocked, I suggest this workaround:
1) install a dnsmasq server beside your tectonic cluster and override the IPs for the nameserver in `/etc/hosts`:
```192.168.0.1 .coreos.pool.ntp.org 1.coreos.pool.ntp.org 2.coreos.pool.ntp.org 3.coreos.pool.ntp.org```.
Just replace the IP with your internal time server.
2. Set `tectonic_openstack_dns_nameservers` to the IP of your dnsmasq server.

**Comment by lblackstone** [comment]
@spiette Thanks for the suggestion. I'm actually using the same patch set I submitted in the PR, and applying that downstream for now.
