### ISSUE TITLE
make flannel/cni configurable

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/tectonic-installer#187]
Currently the flannel configuration is static using `vxlan` without the possibility to replace it with another configuration or different CNI plugins.

We need a way to make this configurable.

xref #178

**Comment by jdconti** [comment]
Please consider allowing tectonic users to provide their own CNI instead of adding support for a fixed set of plugins.

**Comment by leecalcote** [comment]
Does Tectonic Installer support choice of network plugin or is flannel hard-coded?

**Comment by SEJeff** [comment]
@sym3tri did you mean to close this, or has this been fixed?
