### ISSUE TITLE
ignition provider 1.0.0 incompatible

### ISSUE THREAD

**Issue by lblackstone** [coreos/tectonic-installer#1905]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 950f66a4
* Terraform version (`terraform version`): Terraform v0.10.4
* Platform (aws|azure|openstack|metal): openstack

## What happened?
Get the following errors:
```
12 error(s) occurred:

* module.bootkube.data.ignition_systemd_unit.bootkube_path_unit: : invalid or unknown key: enable
* module.bootkube.data.ignition_systemd_unit.bootkube_service: : invalid or unknown key: enable
* module.ignition_masters.data.ignition_systemd_unit.docker_dropin: : invalid or unknown key: enable
* module.ignition_masters.data.ignition_systemd_unit.kubelet: : invalid or unknown key: enable
* module.ignition_masters.data.ignition_systemd_unit.kubelet_env: : invalid or unknown key: enable
* module.ignition_masters.data.ignition_systemd_unit.tx_off: : invalid or unknown key: enable
* module.ignition_workers.data.ignition_systemd_unit.docker_dropin: : invalid or unknown key: enable
* module.ignition_workers.data.ignition_systemd_unit.kubelet: : invalid or unknown key: enable
* module.ignition_workers.data.ignition_systemd_unit.kubelet_env: : invalid or unknown key: enable
* module.ignition_workers.data.ignition_systemd_unit.tx_off: : invalid or unknown key: enable
* module.tectonic.data.ignition_systemd_unit.tectonic_path: : invalid or unknown key: enable
* module.tectonic.data.ignition_systemd_unit.tectonic_service: : invalid or unknown key: enable
```

## What you expected to happen?
Terraform runs

## How to reproduce it (as minimally and precisely as possible)?
On a fresh cluster (i.e. no terraform providers downloaded), run `make apply`.

## Anything else we need to know?
This appears to be related to the [release](https://github.com/terraform-providers/terraform-provider-ignition/releases/tag/v1.0.0) of the ignition provider earlier today.

Here is the list of installed providers:
```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "tls" (0.1.0)...
- Downloading plugin for provider "ignition" (1.0.0)...
- Downloading plugin for provider "random" (0.1.0)...
- Downloading plugin for provider "aws" (0.1.4)...
- Downloading plugin for provider "local" (0.1.0)...
- Downloading plugin for provider "template" (0.1.1)...
- Downloading plugin for provider "openstack" (0.2.1)...
- Downloading plugin for provider "archive" (0.1.0)...
- Downloading plugin for provider "null" (0.1.0)...
```

**Comment by colemickens** [comment]
(Downgrading Terraform to 0.9.11 allowed me to get around this for now.)

**Comment by sstarcher** [comment]
https://github.com/terraform-providers/terraform-provider-ignition/issues/17

**Comment by robszumski** [comment]
FWIW We only support the version of Terraform bundled with the installer (which is 0.9.x currently) but will be upgrading to 0.10.x in the next release.

@alexsomesan is this fixed/handled by that work?

**Comment by s-urbaniak** [comment]
This problem will potentially appear in any plugin we use in the installer. I suggest to pin all plugins to their current versions until the ecosystem around ignition plugins stabilizes.

**Comment by sstarcher** [comment]
@robszumski looks like things are using 0.10.4 https://github.com/coreos/tectonic-installer/blob/1bed67c82a45b4be1f6fe8bd20897092428a6ac0/images/tectonic-installer/Dockerfile#L3

**Comment by robszumski** [comment]
@sstarcher yes you are correct, that work has just recently landed in master, but it not released yet

**Comment by rdeusser** [comment]
`enable` was changed to `enabled` in https://github.com/terraform-providers/terraform-provider-ignition/commit/9a7bb1a23b4ae416db3287114124fdcd65cd9e61.

**Comment by s-urbaniak** [comment]
@rdeusser ack, thanks for the hint. On master we are currently pinning to 0.1.0 of the ignition provider: https://github.com/coreos/tectonic-installer/blob/1c1d1ca/config.tf#L10

In a follow-up PR we will address the bump to 1.0.0 leveraging ignition 2.1.0 configuration.

**Comment by rdeusser** [comment]
👍
