### ISSUE TITLE
Need to support internal cluster model with tectonic-installer.

### ISSUE THREAD

**Issue by coresolve** [coreos/tectonic-installer#191]
https://coreos.com/tectonic/docs/latest/install/aws/requirements.html#configuring-an-internal-cluster

Needs to be supported in the tf installer as well.

**Comment by eddieesquivel** [comment]
@philips this is a requirement for both but the immediate need is with Azure

**Comment by alexsomesan** [comment]
This is already in place.

**Comment by philips** [comment]
@alexsomesan Can you link to docs for @coresolve to try out?

**Comment by sym3tri** [comment]
@coresolve @eddieesquivel are there specific things you are seeing that are not implemented?

**Comment by s-urbaniak** [comment]
This is solved using the simple boolean variable `tectonic_aws_external_vpc_public`, see https://github.com/coreos/tectonic-installer/blob/81cae3241a6044d055db3054a24e31d1086a7f59/platforms/aws/variables.tf#L42-L45 which defaults to `true`.

Setting this to `false` creates an internal cluster. I am adding an explicit mention of this fact into the variable documentation PR https://github.com/coreos/tectonic-installer/pull/308.
