### ISSUE TITLE
Add TerraForm version deps

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#192]
We must add https://www.terraform.io/docs/configuration/terraform.html so users do not try to use an unsupported version of TerraForm against the installer. This is extremely important since:
1) The installer does not support >0.9.x
2) We build plugins against 0.8.8 and the API number got bumped, rendering the plugins unusable with 0.9.x with a weird error.

**Comment by alexsomesan** [comment]
I suggest we go a step further and set modify the version string in "coreos/terraform" to be different than upstream and specify that as the version supported in the templates. This ensures that templates wouldn't even start building with upstream terraform which is missing the custom plugins and tags patch.

**Comment by s-urbaniak** [comment]
As the general consensus is to bundle stock upstream terraform, I will restrict the version to be exactly `=0.8.8` as things are moving swiftly in terraform itself and things like to break between versions.

**Comment by alexsomesan** [comment]
This makes sense in the context of vendoring individual plugins vs. a complete binary. Let's go with stock version numbers for now and see how things develop.
