### ISSUE TITLE
azure: don't use Terraform credentials as cluster credentials

### ISSUE THREAD

**Issue by colemickens** [coreos/tectonic-installer#1926]
It was discussed that this was already something in the back of peoples' minds.

As of today, the `azurerm` terraform module supports getting an authentication context from the local CLI, which is likely to be a much nicer UX for initially interacting with Terraform. This seems to be another good reasons to separate the credentials.

(Also, separating them out would be necessary to adopt Managed Identity in Azure [Terraform's not able to support all of the needed bits for that yet]).

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
