### ISSUE TITLE
Support VMWare Integrated OpenStack(VIO) Install

### ISSUE THREAD

**Issue by cyberious** [coreos/tectonic-installer#1940]
## What keywords did you search in tectonic-installer issues before filing this one?
Openstack, VIO, Floating IP Pool

## FEATURE REQUEST
Support the install of Techtonic on Openstack provided by VMWare with utilizing direct access to VM's running inside of a tenant rather than port forwarding and load balancing provided by Openstack. Also we do not use the Floating IP Pool as part of this and need instead to assign IP from available network assigned to tenant.

## Versions
* 1.6.9
* Platform openstack:

## What you expected to happen?
Install and configure accordingly with direct access to nodes rather than additional NAT from openstack.

## How to reproduce it (as minimally and precisely as possible)?
Install on VMWare Integrated Openstack with Floating IP Pool disabled.

## Anything else we need to know?
Not that I am aware of at this time.

**Comment by sym3tri** [comment]
We're currently working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. We'll post a link to the new repo in the README once it's ready.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
