### ISSUE TITLE
Support dynamic public ip addresses in Azure.

### ISSUE THREAD

**Issue by coresolve** [coreos/tectonic-installer#198]
When creating a public ip address. We are currently using the static method. 
We have received feedback from a prospective customer that they would like us to support the dynamic method as well. 

Here is where we are provisioning the [api lb ip.](https://github.com/coreos/tectonic-installer/blob/master/modules/azure/master/api-lb.tf#L1-L10) and the [console lb ip](https://github.com/coreos/tectonic-installer/blob/master/modules/azure/master/console-lb.tf#L1-L10)

and the [DNS](https://github.com/coreos/tectonic-installer/blob/master/modules/azure/dns/master.tf)

For more info on the difference:
[azure ip address overview](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-ip-addresses-overview-arm)

When creating a dynamic IP we can generate a domain_name_label and apply it like:
[terraform domain_name_label](https://www.terraform.io/docs/providers/azurerm/r/public_ip.html#domain_name_label
)

Here is the ui in azure
<img width="347" alt="screen shot 2017-04-07 at 12 53 34 pm" src="https://cloud.githubusercontent.com/assets/25213022/24820923/86aa0c0a-1ba0-11e7-83e5-85de1ff85f8f.png">

The other changes are that when creating the DNS record we would reference the `domainnamelabel.location.cloudapp.azure.com` pattern described in the azure doc and cname the external dns record to the azure one.

**Comment by sym3tri** [comment]
moving internal issue to our internal tracker
