### ISSUE TITLE
Terraform module: fatal "unexpected EOF" error on all TLS certs

### ISSUE THREAD

**Issue by kerin** [coreos/tectonic-installer#1995]
## What keywords did you search in tectonic-installer issues before filing this one?

terraform
tls eof
tls_self_signed_cert
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

* Tectonic version: [Terraform registry module](https://registry.terraform.io/modules/coreos/kubernetes/aws/1.7.5-tectonic.1-rc.1)
* Terraform version (`terraform version`): 0.10.6
* Platform (aws|azure|openstack|metal): AWS

## What happened?
When attempting to create a new cluster:

```
$ terraform apply
data.terraform_remote_state.env: Refreshing state...
data.template_file.flannel: Refreshing state...
data.template_file.docker_dropin: Refreshing state...
[...]
Error applying plan:

9 error(s) occurred:

* module.kubernetes.module.etcd_certs.tls_self_signed_cert.etcd_ca: Resource 'tls_private_key.etcd_ca' not found for variable 'tls_private_key.etcd_ca.algorithm'
* module.kubernetes.module.kube_certs.tls_self_signed_cert.kube_ca: 1 error(s) occurred:

* tls_self_signed_cert.kube_ca: unexpected EOF
* module.kubernetes.module.etcd_certs.tls_private_key.etcd_client: 1 error(s) occurred:

* tls_private_key.etcd_client: unexpected EOF
* module.kubernetes.module.kube_certs.tls_cert_request.apiserver: 1 error(s) occurred:

* tls_cert_request.apiserver: unexpected EOF
* module.kubernetes.module.kube_certs.tls_private_key.kubelet: 1 error(s) occurred:

* tls_private_key.kubelet: unexpected EOF
* module.kubernetes.module.etcd_certs.tls_private_key.etcd_server: 1 error(s) occurred:

* tls_private_key.etcd_server: unexpected EOF
* module.kubernetes.module.ingress_certs.tls_cert_request.ingress: 1 error(s) occurred:

* tls_cert_request.ingress: unexpected EOF
* module.kubernetes.module.bootkube.tls_private_key.service_account: 1 error(s) occurred:

* tls_private_key.service_account: unexpected EOF
* module.kubernetes.module.etcd_certs.tls_private_key.etcd_ca: unexpected EOF
```

## What you expected to happen?
Terraform should successfully create declared resources.

## How to reproduce it (as minimally and precisely as possible)?

Attempt to create a cluster with this module declaration:

```
module "kubernetes" {
  source = "coreos/kubernetes/aws"

  tectonic_admin_email = "kerin@example.com"
  tectonic_admin_password_hash = "$2a$10$VLuw7Vnwbv9l2Sm0s3pSlue.B5vwlLUACr4zwCU4gGyTCCdUwdcXi"
  tectonic_aws_etcd_ec2_type = "t2.medium"
  tectonic_aws_etcd_root_volume_iops = "100"
  tectonic_aws_etcd_root_volume_size = "30"
  tectonic_aws_etcd_root_volume_type = "gp2"
  tectonic_aws_external_master_subnet_ids = ["${data.terraform_remote_state.env.private_subnet_ids}"]
  tectonic_aws_external_vpc_id = "${data.terraform_remote_state.env.vpc_id}"
  tectonic_aws_external_worker_subnet_ids = ["${data.terraform_remote_state.env.private_subnet_ids}"]
  tectonic_aws_master_custom_subnets = "${data.terraform_remote_state.env.private_subnet_azs}"
  tectonic_aws_master_ec2_type = "t2.medium"
  tectonic_aws_master_root_volume_iops = "100"
  tectonic_aws_master_root_volume_size = "30"
  tectonic_aws_master_root_volume_type = "gp2"
  tectonic_aws_private_endpoints = false
  tectonic_aws_public_endpoints = true
  tectonic_aws_region = "eu-west-1"
  tectonic_aws_ssh_key = "${data.terraform_remote_state.env.ssh_key_name}"
  tectonic_aws_vpc_cidr_block = "10.0.0.0/16"
  tectonic_aws_worker_ec2_type = "t2.medium"
  tectonic_aws_worker_root_volume_iops = "100"
  tectonic_aws_worker_root_volume_size = "30"
  tectonic_aws_worker_root_volume_type = "gp2"
  tectonic_base_domain = "kerin.example.com"
  tectonic_calico_network_policy = false
  tectonic_cl_channel = "stable"
  tectonic_cluster_cidr = "10.2.0.0/16"
  tectonic_cluster_name = "k8s"
  tectonic_etcd_count = "3"
  tectonic_experimental = false
  tectonic_license_path = ""
  tectonic_master_count = "3"
  tectonic_pull_secret_path = ""
  tectonic_service_cidr = "10.3.0.0/16"
  tectonic_stats_url = "https://stats-collector.tectonic.com"
  tectonic_vanilla_k8s = true
  tectonic_worker_count = "3"
}
```

**Comment by robszumski** [comment]
Hi @kerin, can you attempt to use the version of Terraform bundled with the installer, which is v0.10.4? I just want to rule that out first.

**Comment by falfaro** [comment]
I am experiencing the same problem using Terraform bundled with the installer (0.10.4). I'm using Baremetal:

tectonic_base_domain = ""
tectonic_cluster_name = ""
tectonic_container_linux_version = "latest"
tectonic_etcd_count = "0"
tectonic_license_path = "/home/falfaro/tectonic-license.txt"
tectonic_master_count = "1"
tectonic_metal_controller_domain = "cluster.example.com"
tectonic_metal_controller_domains = ["node1.example.com"]
tectonic_metal_controller_macs = ["52:54:00:a1:9c:ae"]
tectonic_metal_controller_names = ["node1"]
tectonic_metal_ingress_domain = ""
tectonic_metal_matchbox_ca = "-----BEGIN CERTIFICATE-----\nMIIFDTCCAvWgAwIBAgIJAOjcRGC...-----END CERTIFICATE-----"
tectonic_metal_matchbox_client_cert = "-----BEGIN CERTIFICATE-----\nMIIEYDCCAkigAwIBAg...-----END CERTIFICATE-----"
tectonic_metal_matchbox_client_key = "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAuSPh4Y...-----END RSA PRIVATE KEY-----"
tectonic_metal_matchbox_http_url = "http://matchbox.example.com:8080"
tectonic_metal_matchbox_rpc_endpoint = "matchbox.example.com:8081"
tectonic_metal_worker_domains = ["node2.example.com", "node3.example.com"]
tectonic_metal_worker_macs = ["52:54:00:b2:2f:86", "52:54:00:c3:61:77"]
tectonic_metal_worker_names = ["node2", "node3"]
tectonic_pull_secret_path = "/home/falfaro/config.json"
tectonic_ssh_authorized_key = "ecdsa-sha2-nistp256 ..."
tectonic_tls_validity_period = "26280"
tectonic_vanilla_k8s = false
tectonic_worker_count = "3"

**Comment by falfaro** [comment]
crash.log contains:

...
2018/02/08 10:18:41 [TRACE] root.etcd_certs: eval: *terraform.EvalApplyPost
2018/02/08 10:18:41 [ERROR] root.etcd_certs: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* tls_private_key.etcd_server: unexpected EOF
2018/02/08 10:18:41 [ERROR] root.etcd_certs: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* tls_private_key.etcd_server: unexpected EOF
2018/02/08 10:18:41 [TRACE] [walkApply] Exiting eval tree: module.etcd_certs.tls_private_key.etcd_server
2018/02/08 10:18:41 [TRACE] dag/walk: upstream errored, not walking "module.etcd_certs.output.etcd_server_key_pem"
2018/02/08 10:18:41 [TRACE] root.etcd_certs: eval: *terraform.EvalGetProvider
2018/02/08 10:18:41 [TRACE] root.etcd_certs: eval: *terraform.EvalReadState
2018/02/08 10:18:41 [TRACE] dag/walk: upstream errored, not walking "module.etcd_certs.tls_cert_request.etcd_server"
2018/02/08 10:18:41 [TRACE] dag/walk: upstream errored, not walking "module.etcd_certs.tls_locally_signed_cert.etcd_server"
2018/02/08 10:18:41 [TRACE] dag/walk: upstream errored, not walking "module.etcd_certs.local_file.etcd_server_key"
2018/02/08 10:18:41 [TRACE] dag/walk: upstream errored, not walking "module.etcd_certs.local_file.etcd_server_crt"
2018/02/08 10:18:41 [TRACE] dag/walk: upstream errored, not walking "module.etcd_certs.output.etcd_server_crt_pem"
2018/02/08 10:18:41 [TRACE] root.etcd_certs: eval: terraform.EvalNoop
2018/02/08 10:18:41 [TRACE] [walkApply] Exiting eval tree: module.etcd_certs.output.etcd_peer_crt_pem
2018/02/08 10:18:41 [TRACE] root.etcd_certs: eval: *terraform.EvalValidateResource
2018/02/08 10:18:41 [TRACE] root.ingress_certs: eval: *terraform.EvalWriteDiff
2018/02/08 10:18:41 [TRACE] root.ingress_certs: eval: *terraform.EvalApplyPost
2018/02/08 10:18:41 [ERROR] root.ingress_certs: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* tls_cert_request.ingress: unexpected EOF
2018/02/08 10:18:41 [ERROR] root.ingress_certs: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* tls_cert_request.ingress: unexpected EOF
2018/02/08 10:18:41 [TRACE] root.etcd_certs: eval: *terraform.EvalWriteDiff
2018/02/08 10:18:41 [TRACE] root.etcd_certs: eval: *terraform.EvalDiff
2018/02/08 10:18:41 [TRACE] root.etcd_certs: eval: *terraform.EvalApplyPost
2018/02/08 10:18:41 [ERROR] root.etcd_certs: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* tls_cert_request.etcd_client: unexpected EOF
2018/02/08 10:18:41 [ERROR] root.etcd_certs: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* tls_cert_request.etcd_client: unexpected EOF
2018/02/08 10:18:41 [TRACE] [walkApply] Exiting eval tree: module.etcd_certs.tls_cert_request.etcd_client
2018/02/08 10:18:41 [TRACE] dag/walk: upstream errored, not walking "module.etcd_certs.tls_locally_signed_cert.etcd_client"
2018/02/08 10:18:41 [TRACE] [walkApply] Exiting eval tree: module.ingress_certs.tls_cert_request.ingress
2018/02/08 10:18:41 [TRACE] root.etcd_certs: eval: *terraform.EvalDiff
2018/02/08 10:18:41 [TRACE] root.etcd_certs: eval: *terraform.EvalDiff
...

**Comment by falfaro** [comment]
I think my problem was that some variables in *.tfvars file were not properly set:

tectonic_metal_ingress_domain = "tectonic.example.com"
tectonic_cluster_name = "my-cluster"

Now I am able to run "terraform apply" with no problems.

**Comment by sym3tri** [comment]
Seems like you figured it out. Thanks for following up.
