### ISSUE TITLE
Set eviction threshold on kubelet

### ISSUE THREAD

**Issue by lblackstone** [coreos/tectonic-installer#1996]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

To prevent undefined behavior caused by out of memory (OOM) conditions on a node, an [eviction threshold](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#schedulable-resources-and-eviction-policies) should be set on the kubelet based on the size of the node.

Without this setting, a node can get into an unresponsive state if a pod consumes too many resources and the operating system OOM-kills a critical service like networking.

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
