### ISSUE TITLE
Once you have the cluster running, if you change tectonic_aws_worker_ec2_type var it doesn't change

### ISSUE THREAD

**Issue by pollosp** [coreos/tectonic-installer#2020]
## What keywords did you search in tectonic-installer issues before filing this one?

`ASG` and `Launch config`

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

`aws_launch_configuration` and it doesn't rebuild the ASG, it this the expected behaviour ?

https://github.com/coreos/tectonic-installer/blob/1.6.2-tectonic.1/platforms/aws/main.tf#L142
https://github.com/coreos/tectonic-installer/blob/1.6.2-tectonic.1/modules/aws/worker-asg/worker.tf#L26

We think that if you change values in your tfvars them should be reflected in AWS, do it make sense?

As you may know there are patterns to force the a new resource when resource `aws_launch_configuration` is changed, for example here:
https://github.com/brikis98/terraform-up-and-running-code/blob/master/code/terraform/05-tips-and-tricks/zero-downtime-deployment/modules/services/webserver-cluster/main.tf#L28

Making dependent the ASG from the `aws_launch_configuration`

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.6.2-tectonic.1
* Terraform version (`terraform version`): 
* Platform (aws|azure|openstack|metal): AWS

**Comment by alexsomesan** [comment]
Hi @pollosp!
Thanks for using the installer and reporting this.

Can you please describe the exact steps that you did to update the worker instance type? We need to be able to reproduce your workflow as accurately as possible in order to understand what issues you may be encountering.

Thanks for taking the time to help us out.

**Comment by pierrebeaucamp** [comment]
1. Set `tectonic_aws_worker_ec2_type = "t2.medium"`
2. `terraform apply`
3. Set `tectonic_aws_worker_ec2_type = "t2.large"`
4. `terraform apply`

Replicated using tectonic 1.8.4

**Comment by pierrebeaucamp** [comment]
Essentially terraform updates the launch configuration of the instances, but the autoscaling group doesn't actually enforce that configuration on existing instances. 

A quick fix I tried was to swap `name` for `name_prefix` in the `aws_autoscaling_group` configs. That technically solves this issue, however it caused significant downtime. Basically terraform starts deleting the old instances immediately after the new ones have booted, unaware of any internal re-balancing / draining on kubernetes.

I will try out an approach using Cloudformation, as described in https://github.com/hashicorp/terraform/issues/1552#issuecomment-190864512

**Comment by pierrebeaucamp** [comment]
ok, so I'm able to work around this problem by using cloudfront to create an asg, like this:

```
data "template_file" "worker_stack_template" {
  template = <<EOF
    {
      "Resources": {
        "$${cluster_name}Workers": {
          "Type": "AWS::AutoScaling::AutoScalingGroup",
          "Properties": {
            "DesiredCapacity": "$${instance_count}",
            "MaxSize": "$${max_size}",
            "MinSize": "$${instance_count}",
            "LaunchConfigurationName": "$${launch_conf_name}",
            "VPCZoneIdentifier": $${vpc_zone_ids},
            "Tags": [
              {
                "Key": "Name",
                "Value": "$${cluster_name}-worker",
                "PropagateAtLaunch": "true"
              },
              {
                "Key": "kubernetes.io/cluster/$${cluster_name}",
                "Value": "owned",
                "PropagateAtLaunch": "true"
              },
              {
                "Key": "tectonicClusterID",
                "Value": "$${cluster_id}",
                "PropagateAtLaunch": "true"
              }
            ]
          },
          "UpdatePolicy": {
            "AutoScalingRollingUpdate": {
              "MinInstancesInService": "$${instance_count}",
              "PauseTime": "PT5M"
            }
          }
        }
      },
      "Outputs": {
        "name": {
          "Description": "The name of the auto scaling group",
          "Value": {
            "Ref": "$${cluster_name}Workers"
          }
        }
      }
    }
EOF

  vars {
    instance_count   = "${var.instance_count}"
    max_size         = "${var.instance_count * 3}"
    launch_conf_name = "${aws_launch_configuration.worker_conf.name}",
    vpc_zone_ids     = "${jsonencode(var.subnet_ids)}"
    cluster_name     = "${var.cluster_name}"
    cluster_id       = "${var.cluster_id}"
  }
}

resource "aws_cloudformation_stack" "workers_autoscaling_group" {
    name = "${var.cluster_name}-workers-asg"
    template_body = "${data.template_file.worker_stack_template.rendered}"
}
```

Now whenever the launch configuration changes, the asg will perform a rolling update of all instances.

I tried doing the same for master nodes, but it turns out that instances launched using the asg can't get bootstrapped. (See https://github.com/coreos/tectonic-installer/issues/2729)

**Comment by benzok** [comment]
We are having the same  problem, when changing the worker type nothing happens.

I repeat the question from pollosp, "Is this the expected behaviour ?"
What is the official way to change worker types ?

Please advise, perhaps @alexsomesan  can assist

**Comment by sym3tri** [comment]
Sorry for the late reply.

Although it intuitively seems like that should work, we don't actually support that use-case.

We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We're considering better approaches for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
