### ISSUE TITLE
Ability to support internal (non-public) container registry i.e. Artifactory

### ISSUE THREAD

**Issue by arybka** [coreos/tectonic-installer#203]
Ability to support internal (non-public) container registry i.e. Artifactory.

**Comment by philips** [comment]
Yes, this is a desirable feature for behind-the-firewall installs.

**Comment by sym3tri** [comment]
We've begun moving in the direction to support this, but the full-story is not yet complete.

See: https://github.com/coreos/tectonic-installer/blob/master/config.tf#L6-L30

**Comment by bodgit** [comment]
My scenario is I'm trying to install a cluster which is behind a firewall and internet access is via a proxy however I do have a private registry (also Artifactory) that is configured/blessed to be able to pull external images through it.

The recent changes to add HTTP proxy support help a little although it would be good to be able to use the internal registry for all container pulls and just leave the proxy settings for anything else. Either being able to set the registry host to something other than quay.io or even being able to inject a list of one or more mirrors for specific registry hosts could work however I've seen that docker currently has almost unusable registry mirror support particularly for anything other than the default docker hub registry.

**Comment by sym3tri** [comment]
We'll consider this for the converged platform but will not be continuing any efforts in _this_ repo.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
