### ISSUE TITLE
update operators are conditionally deployed on AWS

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#205]

**Comment by alexsomesan** [comment]
Is this the same scope as the present-day "enable experimental features" toggle in the UI?

**Comment by s-urbaniak** [comment]
I recursively diffed generated assets on the current installer and saw that indeed the updater seems to be the only "experimental" feature. I am currently working on enabling/disabling this then.

**Comment by s-urbaniak** [comment]
I recursively diffed generated assets on the current installer and saw that indeed the updater seems to be the only "experimental" feature. I am currently working on enabling/disabling this then.
