### ISSUE TITLE
kubernetes 1.6 on AWS

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#206]

**Comment by ericchiang** [comment]
Some action items:

- [ ] Update bootkube
- [ ] Migrate RBAC from `authorization.k8s.io/v1alpha1` to `authorization.k8s.io/v1beta1`

(Will expand list as things pop up)

**Comment by Quentin-M** [comment]
https://github.com/coreos/tectonic-installer/pull/246

**Comment by Quentin-M** [comment]
The console also needs to be updated for jobs and horizontal auto scalers.

**Comment by sym3tri** [comment]
@ericchiang @rithujohn191 do one of you have time to look into: 
"Migrate RBAC from `authorization.k8s.io/v1alpha1` to `authorization.k8s.io/v1beta1`"?

Are there any other RBAC related changes that need to happen for 1.6?

**Comment by Quentin-M** [comment]
@sym3tri @ericchiang @rithujohn191 If that only involved renaming the resources, it's already in https://github.com/coreos/tectonic-installer/pull/246.

**Comment by ericchiang** [comment]
@Quentin-M I think that covers it :+1:

**Comment by s-urbaniak** [comment]
as #246 is merged, I am closing this as being resolved.
