### ISSUE TITLE
AWS region info isn't saved in generated files

### ISSUE THREAD

**Issue by ggreer** [coreos/tectonic-installer#210]
If you run the installer and then want to destroy your cluster, `cd /tmp/tectonic635166312 && terraform destroy terraform/platforms/aws` always asks for a region.

Apparently it's looking at the AWS_REGION environment variable. That means someone could run `terraform destroy` from the command line and be very confused as to why their cloud assets aren't being deleted (assuming the env var is set for them).

I think it makes a lot more sense to put the region in tfvars. That way bringup/teardown always happens in the same region.

**Comment by sym3tri** [comment]
This has been an ongoing debate of where to put it. Maybe be just force it into the tfvars file when running via the UI?

**Comment by ggreer** [comment]
Fixed in https://github.com/coreos/tectonic-installer/pull/509.
