### ISSUE TITLE
Terraform Version Bump

### ISSUE THREAD

**Issue by rowleyaj** [coreos/tectonic-installer#2113]
#1841 updated terraform to use the 0.10.x series. I'm still on the tectonic 1.6 series so this doesn't affect me yet, but you may wish to bump the terraform version to 0.10.5 rather than 0.10.4 as it is now.

0.10.4 had a bug that removed the `(forces new resource)` annotations on attributes.

This was fixed in https://github.com/hashicorp/terraform/pull/16067 and released in 0.10.5.

https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0105-september-14-2017

**Comment by mrwacky42** [comment]
Fixed by 379fd19b79d3d26a1d2f29e2a6119c20f3febe2b?

**Comment by squat** [comment]
@rowleyaj thank you, we are already on 0.10.7 and require that for new clusters: https://github.com/coreos/tectonic-installer/blob/master/config.tf#L2
