### ISSUE TITLE
Booting an AWS cluster creates 3 or 5 etcd instances.

### ISSUE THREAD

**Issue by ggreer** [coreos/tectonic-installer#213]
Key line is https://github.com/coreos/tectonic-installer/blob/master/platforms/aws/main.tf#L18

We should be able to boot just one etcd.

**Comment by alexsomesan** [comment]
Why do we need to boot a single-instance etcd cluster?

**Comment by philips** [comment]
@alexsomesan the installer has supported this in the past

**Comment by philips** [comment]
The primary use case is small clusters to be used by dev/test and validation.
