### ISSUE TITLE
Error parsing  terraform.tfvars

### ISSUE THREAD

**Issue by tomweston** [coreos/tectonic-installer#2141]
### Tectonic Version 
1.7.5
### Environment

AWS / Terraform

### Expected Behavior

`terraform plan -var-file=build/${CLUSTER}/terraform.tfvars platforms/aws`

should provide a plan but fails to execute due to not liking the vpc_id syntax on line 56.
### Actual Behavior

`terraform plan -var-file=build/${CLUSTER}/terraform.tfvars platforms/aws`

invalid value "build/nameofmycluster/terraform.tfvars" for flag -var-file: Error parsing build/nameofmycluster/terraform.tfvars: At 56:30: nested object expected: LBRACE got: ASSIGN
Usage: terraform plan [options] [DIR-OR-PLAN]

### Contents of the terrafom.tfvars file
`55    Example: 'vpc-12345678'`
`56     tectonic_aws_external_vpc_id = "vpc-12345678"`

I have tried all of the following variations:
`56      tectonic_aws_external_vpc_id = "vpc-12345678"`
`56      tectonic_aws_external_vpc_id = "["vpc-12345678"]"`
`56      tectonic_aws_external_vpc_id = "[vpc-12345678]"`
`56      tectonic_aws_external_vpc_id = 'vpc-12345678'`

All of which produce the same output:

invalid value "build/nameofmycluster/terraform.tfvars" for flag -var-file: Error parsing build/nameofmycluster/terraform.tfvars: At 56:30: nested object expected: LBRACE got: ASSIGN
Usage: terraform plan [options] [DIR-OR-PLAN]

(**note:** actual vpc_id has been ommited)

**Comment by kbrwn** [comment]
This can be closed as there is a tectonic-forum post: https://github.com/coreos/tectonic-forum/issues/207
