### ISSUE TITLE
ETCD checks

### ISSUE THREAD

**Issue by rushins** [coreos/tectonic-installer#2149]
## What keywords did you search in tectonic-installer issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
* Terraform version (`terraform version`):
* Platform (aws|azure|openstack|metal):

## What happened?
checking ETCD member 

## What you expected to happen?
systemctl status etcd-member && journalctl etcd-member

## How to reproduce it (as minimally and precisely as possible)?
systemctl status etcd-member && journalctl etcd-member

## Anything else we need to know?
ETCD is running as container in master (control plane) but how to check ETCD

**Comment by rushins** [comment]
i dont see the following working in Tectonic 1.7 as ETCD is container 
systemctl status etcd-member && journalctl etcd-member


how to check ETCD health and remaining of ETCD>

**Comment by sym3tri** [comment]
There's not enough information here to be able to help you. Can you please reopen this issue here with more info if you're still having trouble:

https://github.com/coreos/tectonic-forum/issues
