### ISSUE TITLE
Allow non-RSA keys

### ISSUE THREAD

**Issue by kans** [coreos/tectonic-installer#216]
ca_key_alg is hard coded to RSA

**Comment by sym3tri** [comment]
@kans We don't allow overriding this in the current GUI right? If not I wouldn't put into this milestone as a blocker for stable.

**Comment by ggreer** [comment]
Looks like it's not supported by cloudformation: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html

I just tried with an ECDSA key and got this error: 
![screenshot from 2017-04-11 11-00-13](https://cloud.githubusercontent.com/assets/200121/24923346/12ccf456-1ea6-11e7-8e9d-a86e1bd38bd6.png)
