### ISSUE TITLE
azure deployment faills

### ISSUE THREAD

**Issue by jalberto** [coreos/tectonic-installer#2198]
## What keywords did you search in tectonic-installer issues before filing this one?
azure config malformed  bcrypt

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT
Choose one: BUG REPORT or FEATURE REQUEST

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.7.5-tectonic.1
* Terraform version (`terraform version`): 0.10.4
* Platform (aws|azure|openstack|metal): azure

## What happened?
After deployment, waith few minutes an can see this error:

```
❯ kubectl logs -f tectonic-identity-4116333579-4vkbs -n tectonic-system                                                                                       
error parse config file /etc/dex/config.yaml: error unmarshaling JSON: malformed bcrypt hash: crypto/bcrypt: hashedSecret too short to be a bcrypted password
```

## What you expected to happen?
every pod must be running

## How to reproduce it (as minimally and precisely as possible)?
deploy following docs, th eonly special thing is that I am using pre-created vnets

## Anything else we need to know?

This is a blocker, as the cluster never achieve working state.
I double checked bcrypt-tool output is properly  C&P

**Comment by justaugustus** [comment]
@jalberto are you still having issues with this?

**Comment by jalberto** [comment]
sorry, I have no time to test this again right now

**Comment by sym3tri** [comment]
Please reopen with more details on how to reproduce if you're still having issues.
