### ISSUE TITLE
Enable customization of Docker log rotation

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#221]
Right now we're relying on each customer to configure Docker log rotation. Example:

```
DOCKER_OPTS=--log-opt max-size=50m --log-opt max-file=3
```

We should set a sane default that doesn't grow forever, and then offer a way to easily customize. Not sure if it makes more sense as a top level variable or an easy to understand section within an Ignition config.

**Comment by colhom** [comment]
@robszumski I worry that allowing `max-file > 1` will not play well with the way many on-cluster log aggregators (ie: fluentd) currently work. Many use a regex to find all container log files in `/var/log/containers/*.log` and keep track of what logs have been spooled in based on filename. I feel that if we're doing rotation in this container log directory, aggregators with loose regexs may pick up the old log files and potentially re-spool those logs into the aggregator. I wouldn't be surprised if there are currently production deployments will assume all files in the set `/var/log/containers/*` are unique log files.

**Comment by robszumski** [comment]
I just grabbed an example, I have no attachment to 3 :)

**Comment by chancez** [comment]
I don't think that will be an issue. Upstream is doing the same in GCI. Additionally, since we use ignition, only new nodes in an existing cluster would have the config change applied, so we don't have to worry about an existing node's log files.

https://github.com/kubernetes/kubernetes/pull/40634/

**Comment by s-urbaniak** [comment]
log rotation landed in #244, hence I am closing this issue for now. Feel free to reopen if we missed anything.
