### ISSUE TITLE
Upgrading tectonic cluster from 1.6.4 to 1.6.7

### ISSUE THREAD

**Issue by annapurnam** [coreos/tectonic-installer#2214]
## What keywords did you search in tectonic-installer issues before filing this one?
upgrade
If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT 

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):1.6.4
* Terraform version (`terraform version`): >= 0.9.6
* Platform (aws|azure|openstack|metal): aws

## What happened?
Upgrading tectonic cluster, COuldn;t find a documentation on how to update the cluster, All of it refers to one-click update - but that's not available before 1.6.7
Also, I don't have operators enabled- From all of the documentation, it doesn't look like there is a way to enable operators on running cluster
## What you expected to happen?
Steps to upgrade tectonic cluster from 1.6.4 to 1.6.7

## How to reproduce it (as minimally and precisely as possible)?
This is documentation issue.

**Comment by sym3tri** [comment]
Sorry but clusters can only be upgraded if the operators were installed.
