### ISSUE TITLE
Kubernetes Baremetal HA

### ISSUE THREAD

**Issue by danehans** [coreos/tectonic-installer#222]
I have completed a bare-metal Kubernetes HA deployment using [Matchbox](https://github.com/coreos/matchbox). It's not self-hosted, but I can convert my work to self-hosted if that is necessary. Let me know if you would like me to submit a PR to document the setup and provide my example matchbox group, profiles and Ignition templates.

**Comment by sym3tri** [comment]
Thanks @danehans. Actually @dghubble is working on this from our side too and has begun working on https://github.com/coreos/terraform-provider-matchbox. Does your approach fit with this model?

**Comment by s-urbaniak** [comment]
@danehans matchbox support just landed in the installer, please have a look the sample configuration here https://github.com/coreos/tectonic-installer/blob/master/platforms/metal/terraform.tfvars.example.

Do you mind to give it a try and let us know what you think? I am aware we are still a bit weak on the documentation side of things, but this should improve quickly in the next iterations.

Until then closing this issue, as we have matchbox support now included.

**Comment by danehans** [comment]
@s-urbaniak testing terraform matchbox provider is on my todo list. I'll let you know how it goes. Thanks!
