### ISSUE TITLE
kubelet certificates in tectonic-system namespace

### ISSUE THREAD

**Issue by brancz** [coreos/tectonic-installer#223]
To be able to communicate with the kubelet on the secure port it expects requests to be done with a client certificate. This client certificate is currently in a `Secret` in the kube-system namespace called `kube-apiserver` and the certificates required are in the files `apiserver.crt` and `apiserver.key`.

For Prometheus to be able to scrape the kubelets via the secure port it is necessary to have access to those certificates.

My first idea would be to create an additional secret in the tectonic-system namespace called `kubelet-cert` with the files `kubelet.crt` and `kubelet.key`, then Prometheus can mount that secret and use it to authenticate with the kubelet.

Sounds plausible? The only downside I can see is that we need to make sure those Secrets are in sync, which could be done by the tectonic-prometheus-operator, but I would like to discuss here whether it should indeed be done by the tectonic-prometheus-operator and whether this `Secret` should initially even be created by the installer.

@alexsomesan @s-urbaniak @Quentin-M @sym3tri 

/cc @fabxc @mxinden

**Comment by sym3tri** [comment]
Duplicating the certs is not ideal.

Maybe @ericchiang has ideas?

**Comment by ericchiang** [comment]
Since we don't turn on kubelet authorization, if we give a client to prometheus we can't restrict it to just the metric endpoints. Prometheus would be able to execute arbitrary commands on any node via the exec endpoints with no revokability.

That sounds pretty bad. Why does it need to talk to the kubelet's secure port?

**Comment by brancz** [comment]
The metrics endpoint is targeted for removal from the insecure port, because the metrics contain sensitive information (and the insecure port may disappear for good at some point).

If there is authorization for the kubelet, why don't we turn it on and give Prometheus only access to the metrics endpoint? Sounds like the logical thing to do, or am I missing something?

As far as I'm aware Prometheus is the only reason to keep the insecure port enabled for tectonic clusters at this point.

**Comment by ericchiang** [comment]
> The metrics endpoint is targeted for removal from the insecure port

First I'm hearing of this. Where's that upstream discussion?

> If there is authorization for the kubelet, why don't we turn it on and give Prometheus only access to the metrics endpoint? Sounds like the logical thing to do, or am I missing something?

kubelet authorization requires an available API server, but the bootkube checkpointer currently uses the kubelet API to determine when to revive an API server. While the checkpointer depends on this we can't turn on authorization.

cc @derekparker @aaronlevy

**Comment by ericchiang** [comment]
> As far as I'm aware Prometheus is the only reason to keep the insecure port enabled for tectonic clusters at this point.

Our installer also uses this endpoint for progress info.

**Comment by sym3tri** [comment]
> Our installer also uses this endpoint for progress info.

Which is going away soon. See: #227

**Comment by ericchiang** [comment]
Just chatted with @aaronlevy about this. There's basically no way for the checkpointer to operate without talking to the kubelet API. I think we're going to have to keep kubelet authorization off until checkpointing gets upstreamed or we propose some sort of alternative authorization strategy that can be used without the API server being available.

**Comment by aaronlevy** [comment]
Well technically the checkpointer should be able to operate in the absence of an api-server (because one of the things it is checkpointing is the api-server). If it can't talk to the kubelet (because kubelet requires api-server for auth), then it can't determine if it should/should not start a checkpoint.

Other options might be to query the runtime interface directly to determine local state (rather than talking to kubelet) -- which now that we have CRI that might not be totally crazy...

**Comment by sym3tri** [comment]
moved internally
