### ISSUE TITLE
installer does not install tectonic services

### ISSUE THREAD

**Issue by tomdavidson** [coreos/tectonic-installer#2243]
## BUG REPORT

On tf apply I get the [failed partial run](https://coreos.com/tectonic/docs/latest/troubleshooting/installer-terraform.html) (everytime):

```sh
* module.tectonic-installer.module.workers.data.ignition_config.main: data.ignition_config.main: invalid file"7784cc756062e3bbde1d7d2edf8aa93fe7f3aee74fb73e439a2aa9cb6670615d", unknown file id
* module.tectonic-installer.module.etcd.data.ignition_config.etcd: data.ignition_config.etcd: invalid file "17e7617064374d8f51788a97e5b9df2508e8330a26fb990dc4858db92a1040e9", unknown file id
```

I run plan and apply again and all the resources get created, but the tectonic services do not get installed. The -con ELB is provisioned but "OutOfService"...

## Versions

* Tectonic version: 1.7.5
* Terraform version: 0.10.7
* Platform: AWS

## What happened?

There are no tectonic-system name space or console or identity installed.

## How to reproduce it (as minimally and precisely as possible)?

install via Terraform and verify the services:

```sh
$ kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.3.0.1     <none>        443/TCP   22s
$ kubectl -n kube-system get services
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
kube-dns   ClusterIP   10.3.0.10    <none>        53/UDP,53/TCP   23s
$ kubectl -n kube-public  get services
No resources found.
```

**Comment by squat** [comment]
@tomdavidson can you please share you `.tfvars` file? that will help us diagnose the issue. Also, the ELBs report out of service because the balanced services are failing their health-checks because they are not getting created during the bootstrapping process.

**Comment by tomdavidson** [comment]
Hello @squat 

holy john wayne in my absence it appears the node now active with the elb - took quite awhile. Now I have ingress but no healthy backend. I want to troubleshoot this direction then can recreate.

```sh
$ kubectl --namespace=tectonic-system get pods | grep CrashLoopBack
tectonic-console-2972301597-014c7                     0/1       CrashLoopBackOff   53         2h
tectonic-identity-4116333579-xvsrf                    0/1       CrashLoopBackOff   37         2h
tectonic-monitoring-auth-prometheus-965104485-rnj5s   0/1       CrashLoopBackOff   39         2h
```
Logs of the three and etcd are in this [gist](https://gist.github.com/tomdavidson/5cf1451429ec8aa85350f952ae340ec5)

I have a different set up because I am tring to ship the cluster not just use a one-off installer. I can sanitize `tf show` but but it is > 8k lines. 

The logs show the password hash is invalid. does the bring all the tectonic services down?

**Comment by tomdavidson** [comment]
It appears that it was only the malformed admin password (was not being fetched from S3 correctly) was bringing it all down. Would be nice if it was a bit more robust or this was included in the Triage.

I still get the partial run requiring the double plan/apply, but that is a different issue.
