### ISSUE TITLE
Azure Installation fail

### ISSUE THREAD

**Issue by jbucar** [coreos/tectonic-installer#2262]
## What keywords did you search in tectonic-installer issues before filing this one?

azure terraform platform_fault_domain_count

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
tectonic-1.7.5.1
* Terraform version (`terraform version`):
* Platform (aws|azure|openstack|metal):
azure

## What happened?

Installation fail on azure zone westus2

## What you expected to happen?

Installation ok

## How to reproduce it (as minimally and precisely as possible)?

Install a new cluster on westus2 zone

## Anything else we need to know?

This change fix the installation:

--- a/modules/azure/master-as/master.tf
+++ b/modules/azure/master-as/master.tf
@@ -3,7 +3,8 @@ resource "azurerm_availability_set" "tectonic_masters" {
   location            = "${var.location}"
   resource_group_name = "${var.resource_group_name}"
   managed             = true
-
+  platform_fault_domain_count = "2"
+  
   tags = "${merge(map(
     "Name", "${var.cluster_name}-masters",
     "tectonicClusterID", "${var.cluster_id}"),
diff --git a/modules/azure/worker-as/workers.tf b/modules/azure/worker-as/workers.tf
--- a/modules/azure/worker-as/workers.tf
+++ b/modules/azure/worker-as/workers.tf
@@ -3,6 +3,7 @@ resource "azurerm_availability_set" "tectonic_workers" {
   location            = "${var.location}"
   resource_group_name = "${var.resource_group_name}"
   managed             = true
+  platform_fault_domain_count = "2"
 
   tags = "${merge(map(
     "Name", "${var.cluster_name}-workers",

**Comment by mxinden** [comment]
@jbucar Would you mind putting your git diff in a proper [markdown code block](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)? With the interpreted version your changes are difficult to understand.

**Comment by jbucar** [comment]
Yes, sorry. The fix is hardcoded, but work on westus2

```
diff --git a/modules/azure/master-as/master.tf b/modules/azure/master-as/master.tf
--- a/modules/azure/master-as/master.tf
+++ b/modules/azure/master-as/master.tf
@@ -3,7 +3,8 @@ resource "azurerm_availability_set" "tectonic_masters" {
   location            = "${var.location}"
   resource_group_name = "${var.resource_group_name}"
   managed             = true
+  platform_fault_domain_count = "2"

   tags = "${merge(map(
     "Name", "${var.cluster_name}-masters",
     "tectonicClusterID", "${var.cluster_id}"),
diff --git a/modules/azure/worker-as/workers.tf b/modules/azure/worker-as/workers.tf
--- a/modules/azure/worker-as/workers.tf
+++ b/modules/azure/worker-as/workers.tf
@@ -3,6 +3,7 @@ resource "azurerm_availability_set" "tectonic_workers" {
   location            = "${var.location}"
   resource_group_name = "${var.resource_group_name}"
   managed             = true
+  platform_fault_domain_count = "2"
 
   tags = "${merge(map(
     "Name", "${var.cluster_name}-workers",
```

**Comment by mxinden** [comment]
@jbucar And in addition, if you don't mind, could you post your `terraform.tfvars` file here, so we can fully understand your infrastructure setup?

**Comment by jbucar** [comment]
@mxinden, sorry but I don't known what the state save, buy I can show the variables. It is 100% reproducible on westus2

**The terraform.tfvars are**
tectonic_azure_etcd_vm_size = "Standard_D2s_v3"
tectonic_azure_location = "westus2"
tectonic_azure_master_vm_size = "Standard_D2s_v3"
tectonic_azure_worker_storage_type = "Premium_LRS"
tectonic_azure_worker_vm_size = "Standard_D8s_v3"
tectonic_calico_network_policy = false
tectonic_cl_channel = "stable"
tectonic_cluster_cidr = "10.2.0.0/16"
tectonic_etcd_count = "0"
tectonic_experimental = true
tectonic_master_count = "3"
tectonic_service_cidr = "10.3.0.0/16"
tectonic_vanilla_k8s = false
tectonic_worker_count = "5"

**Comment by mxinden** [comment]
@jbucar According to the Azure [docs](https://docs.microsoft.com/en-us/rest/api/compute/availabilitysets/availabilitysets-create) the `platform_fault_domain_count` defaults to `3`. A wild guess from my side would be, that `3` is not supported on `westus2`. Would you mind testing this theory out?

**Comment by jbucar** [comment]
Yes, westus2 only support 2 (the error say that). I don't know if it is a bug in the installer or in terraform

**Comment by alexsomesan** [comment]
This PR attempts a generic fix for this issue: https://github.com/coreos/tectonic-installer/pull/2333

**Comment by justaugustus** [comment]
@jbucar -- are you still having issues with this?

**Comment by jbucar** [comment]
I can't test it now. I close it and reopen if necessary. Thanks!
