### ISSUE TITLE
Etcd-operator fail to create a new cluster

### ISSUE THREAD

**Issue by jbucar** [coreos/tectonic-installer#2263]
## What keywords did you search in tectonic-installer issues before filing this one?

etcd-operator azure cluster

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.7.5-1
* Terraform version (`terraform version`):
* Platform (aws|azure|openstack|metal):

## What happened?

Create a new etcd cluster. It does not deploy the new cluster.

## What you expected to happen?

Pods must be deployed and cluster initialized

## How to reproduce it (as minimally and precisely as possible)?

After installation from terraform scripts, create a new etcd cluster using tectonic-console/Open cloud services/Create etcd cluster, edit yaml, change name, create.
The resource is created, but no pod is deployed

## Anything else we need to know?

The tectonic installation does not include RBAC setup

**Comment by mxinden** [comment]
Am I right assuming that this is on platform `azure`?

- Can you give us more details in regards to the cluster like e.g. the `terraform.tfvars` file created by the installer.
- Can you check whether the `etcd-operator` is running and is healthy in the `tectonic-system` namespace? If so, can you post the logs of the pod here?

**Comment by jbucar** [comment]
**The terraform.tfvars are** 
  tectonic_azure_etcd_vm_size = "Standard_D2s_v3"
  tectonic_azure_location = "westus2"
  tectonic_azure_master_vm_size = "Standard_D2s_v3"
  tectonic_azure_worker_storage_type = "Premium_LRS"
  tectonic_azure_worker_vm_size = "Standard_D8s_v3"
  tectonic_calico_network_policy = false
  tectonic_cl_channel = "stable"
  tectonic_cluster_cidr = "10.2.0.0/16"
  tectonic_etcd_count = "0"
  tectonic_experimental = true
  tectonic_master_count = "3"
  tectonic_service_cidr = "10.3.0.0/16"
  tectonic_vanilla_k8s = false
  tectonic_worker_count = "5"

**The etcd-operator is running. The logs are**

time="2017-10-30T20:46:37Z" level=info msg="start watching at 69860" pkg=controller 
time="2017-10-30T20:48:28Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller 
time="2017-10-30T20:48:33Z" level=info msg="start watching at 69860" pkg=controller 
time="2017-10-30T20:50:12Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller 
time="2017-10-30T20:50:17Z" level=info msg="start watching at 69860" pkg=controller 
time="2017-10-30T20:52:00Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller 
time="2017-10-30T20:52:05Z" level=info msg="start watching at 69860" pkg=controller 
time="2017-10-30T20:53:29Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller 
time="2017-10-30T20:53:34Z" level=info msg="start watching at 69860" pkg=controller 
time="2017-10-30T20:55:15Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller 
time="2017-10-30T20:55:20Z" level=info msg="start watching at 69860" pkg=controller 
time="2017-10-30T20:56:59Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller 
time="2017-10-30T20:57:04Z" level=info msg="start watching at 69860" pkg=controller 
time="2017-10-30T20:58:38Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller

Before, and after cluster creation ...

**Comment by hacor** [comment]
Hello!
I'm having exactly the same issue on a Bare metal setup.
The etcd-operator pod in the tectonic-system namespace seems to be up and running:

```
$ kubectl get po -n tectonic-system
NAME                                                     READY     STATUS              RESTARTS   AGE
alertmanager-main-0                                      2/2       Running             4          21h
alertmanager-main-1                                      2/2       Running             4          21h
container-linux-update-agent-ds-1vf4v                    1/1       Running             2          21h
container-linux-update-agent-ds-b9l0j                    1/1       Running             2          21h
container-linux-update-agent-ds-bgs7w                    1/1       Running             2          21h
container-linux-update-agent-ds-g6hdg                    1/1       Running             2          21h
container-linux-update-agent-ds-w1c8v                    1/1       Running             1          21h
container-linux-update-operator-550222518-8kw2j          1/1       Running             3          21h
default-http-backend-2250489356-drfbv                    1/1       Running             1          21h
etcd-operator-1230499663-6xl86                           0/1       ContainerCreating   0          4s
grafana-3240502846-21vf4                                 2/2       Running             4          21h
kube-state-metrics-2949229022-tzhpz                      2/2       Running             4          21h
kube-version-operator-3610725188-08grm                   1/1       Running             3          21h
node-agent-6t6b8                                         1/1       Running             2          21h
node-agent-jtmv7                                         1/1       Running             2          21h
node-agent-qs4jk                                         1/1       Running             2          21h
node-agent-qv376                                         1/1       Running             1          21h
node-agent-wrsrt                                         1/1       Running             2          21h
node-exporter-25ntr                                      1/1       Running             1          21h
node-exporter-2xc01                                      1/1       Running             0          21h
node-exporter-m8jcs                                      1/1       Running             2          21h
node-exporter-mzjf3                                      1/1       Running             2          21h
node-exporter-wkkm0                                      1/1       Running             2          21h
prometheus-k8s-0                                         2/2       Running             4          21h
prometheus-operator-1603109940-4k4h3                     1/1       Running             2          21h
tectonic-channel-operator-1030110693-85vdz               1/1       Running             1          21h
tectonic-cluo-operator-2246913820-1bxmb                  1/1       Running             3          21h
tectonic-console-2972301597-419zr                        1/1       Running             1          21h
tectonic-console-2972301597-73zm0                        1/1       Running             1          21h
tectonic-identity-4116333579-779qb                       1/1       Running             4          21h
tectonic-identity-4116333579-c92nj                       1/1       Running             2          21h
tectonic-ingress-controller-6r85r                        1/1       Running             6          21h
tectonic-ingress-controller-h9g33                        1/1       Running             4          21h
tectonic-ingress-controller-hcm91                        1/1       Running             7          21h
tectonic-monitoring-auth-alertmanager-1771749323-5741q   1/1       Running             3          21h
tectonic-monitoring-auth-grafana-3925306851-cr0q9        1/1       Running             2          21h
tectonic-monitoring-auth-prometheus-3210287350-kvq5x     1/1       Running             3          21h
tectonic-prometheus-operator-3938336564-2bg92            1/1       Running             2          21h
tectonic-stats-emitter-2683569340-x0065                  2/2       Running             4          21h
```

The logs of this etcd-operator pod are:

```
$ kubectl -n tectonic-system logs -f etcd-operator-1230499663-6xl86
time="2017-11-03T12:31:25Z" level=info msg="etcd-operator Version: 0.5.0" 
time="2017-11-03T12:31:25Z" level=info msg="Git SHA: 257d52f" 
time="2017-11-03T12:31:25Z" level=info msg="Go Version: go1.8.1" 
time="2017-11-03T12:31:25Z" level=info msg="Go OS/Arch: linux/amd64" 
time="2017-11-03T12:31:43Z" level=info msg="Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"tectonic-system", Name:"etcd-operator", UID:"22518644-bfdb-11e7-b817-ae6c22933c6c", APIVersion:"v1", ResourceVersion:"280102", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' etcd-operator-1230499663-6xl86 became leader" 
time="2017-11-03T12:31:43Z" level=info msg="finding existing clusters..." pkg=controller 
time="2017-11-03T12:31:43Z" level=info msg="starts running from watch version: 280104" pkg=controller 
time="2017-11-03T12:31:43Z" level=info msg="start watching at 280104" pkg=controller 
time="2017-11-03T12:33:23Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller 
time="2017-11-03T12:33:28Z" level=info msg="start watching at 280104" pkg=controller 
time="2017-11-03T12:35:04Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller 
time="2017-11-03T12:35:09Z" level=info msg="start watching at 280104" pkg=controller 
time="2017-11-03T12:36:36Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller 
time="2017-11-03T12:36:41Z" level=info msg="start watching at 280104" pkg=controller 
```
The file which I tried to create is:

```
cat etcd-cluster.yaml 
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: appsynth
  namespace: default
spec:
  size: 3
  version: 3.1.4
```
But nothing happens further on...
```
kubectl get pods
No resources found.
```

If you need any more info let me know!

Best regards,

Hacor

**Comment by mxinden** [comment]
@jbucar Two things that come to my mind:

The etcd-operator only watches the namespace it is deployed in (See [docs](https://github.com/coreos/etcd-operator#limitations)). By default this is the `tectonic-system` namespace. When you create a new etcd-cluster via the UI, please make sure to set the namespace to `tectonic-system` or any other namespace where an etcd-operator is deployed.

In addition by default the Tectonic installer does not set up any persistent volumes. When you create an etcd-cluster via the UI in a k8s-cluster without storage setup, please make sure to remove the `spec/backup` section in the etcd-cluster yaml. 

Let me know if this helps.

**Comment by mxinden** [comment]
@hacor In your etcd-cluster config yaml you have the namespace `default` set. Is there an etcd-operator running in that namespace? (See details https://github.com/coreos/tectonic-installer/issues/2263#issuecomment-341769937)

**Comment by hacor** [comment]
@mxinden Thanks for the reply! Changing the namespace worked like a charm.
Sorry I overlooked!

Regards!

**Comment by mxinden** [comment]
@hacor Glad I could help. We are working on improving the UX in the Tectonic UI in this regards.

@jbucar I will close here. Please feel free to reopen the issue in case the proposed fix does not work for you.
