### ISSUE TITLE
Error: module.dns.data.openstack_dns_zone_v2.tectonic: Provider doesn't support data source: openstack_dns_zone_v2

### ISSUE THREAD

**Issue by stamak** [coreos/tectonic-installer#2269]
## What keywords did you search in tectonic-installer issues before filing this one?

```
* module.tectonic.template_dir.tectonic: file: open : no such file or directory in:

${base64encode(file(var.pull_secret_path))}
```

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): `wget https://releases.tectonic.com/releases/tectonic_1.7.5-tectonic.1.tar.gz`
* Terraform version (`terraform version`): Terraform v0.10.8
* Platform (aws|azure|openstack): openstack

## What happened?

```
terraform plan -var-file=build/${CLUSTER}/terraform.tfvars platforms/openstack/neutron

Error: module.tectonic.template_dir.tectonic: 1 error(s) occurred:

* module.tectonic.template_dir.tectonic: file: open : no such file or directory in:

${base64encode(file(var.pull_secret_path))}

```

## What you expected to happen?

Success

## How to reproduce it (as minimally and precisely as possible)?

Follow this howto https://coreos.com/tectonic/docs/latest/install/openstack/openstack-terraform.html

**Comment by mxinden** [comment]
@stamak Have you defined the path to your pull-secret in the `tectonic_pull_secret_path` variable in the `terraform.tfvars` file? (See [Customize the deployment/common Tectonic variables](https://github.com/coreos/tectonic-installer/blob/master/Documentation/variables/config.md))

**Comment by stamak** [comment]
@mxinden yes you are right - I missed it
thx

But now I have an another problem with dns 

```
terraform plan -var-file=build/${CLUSTER}/terraform.tfvars platforms/openstack/neutron

Error: module.dns.data.openstack_dns_zone_v2.tectonic: Provider doesn't support data source: openstack_dns_zone_v2
```

seems the problem with var *tectonic_base_domain*

I tried to leave as is - error, commented out - the same

I do not know what to put here for openstack?

**Comment by mxinden** [comment]
This depends on your DNS setup on Openstack, can you give me more details here? Leaving this empty is not an option for your platform, only for Azure.

**Comment by stamak** [comment]
@mxinden 

I have configured in my openstack such domain *openstacklocal*

Even if I provide it raises an error :(

```
terraform plan -var-file=build/${CLUSTER}/terraform.tfvars platforms/openstack/neutron
var.tectonic_base_domain
  The base DNS domain of the cluster. It must NOT contain a trailing period. Some
  DNS providers will automatically add this if necessary.

  Example: `openstack.dev.coreos.systems`.

  Note: This field MUST be set manually prior to creating the cluster.
  This applies only to cloud platforms.

  [Azure-specific NOTE]
  To use Azure-provided DNS, `tectonic_base_domain` should be set to `""`
  If using DNS records, ensure that `tectonic_base_domain` is set to a properly configured external DNS zone.
  Instructions for configuring delegated domains for Azure DNS can be found here: https://docs.microsoft.com/en-us/azure/dns/dns-delegate-domain-azure-dns

  Enter a value: openstacklocal


Error: module.dns.data.openstack_dns_zone_v2.tectonic: Provider doesn't support data source: openstack_dns_zone_v2

```

**Comment by lblackstone** [comment]
I dug into this yesterday and discovered that the Terraform Openstack provider currently doesn't support `openstack_dns_zone_v2` as a datasource. We are in the process of adding this feature to the provider, but it's broken on master right now.

As a workaround, you can change the behavior as seen in https://github.com/coreos/tectonic-installer/pull/2201, but the near-term goal is to fix the provider so that you aren't required to create a new zone for each cluster.

**Comment by lblackstone** [comment]
Here's the PR for the OpenStack provider: https://github.com/terraform-providers/terraform-provider-openstack/pull/145
