### ISSUE TITLE
version and document expected tfvars for AWS

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#230]
In order to maintain a contract with apps or users that provide a tfvars file. Anytime we make breaking changes to the expected variables, we need to change the version.

**Comment by sym3tri** [comment]
this will be docs for now

**Comment by philips** [comment]
We discussed this and the best way forward is to document it for now. Likely putting a version in the tfvars file that is advisory.

**Comment by alexsomesan** [comment]
Thinking more into this, do we want to have a version per specific cloud platform?

For example, with a global version scheme, when changing the vars specific to one cloud provider, we would have to bump version and affect every user of other platforms. This sounds quite inconvenient.

OTH, if we decide to version accounting for the cloud provider, we would only be bumping on specific implementation's version as long as the changes are contained, while changes to the common set of var would require bumping all versions.

Thoughts? @sym3tri @philips

**Comment by sym3tri** [comment]
@alexsomesan good point. Per provider seems easiest. These generated docs are a good start. Maybe we start munging these and version them into separate files?

https://github.com/coreos/tectonic-installer/tree/master/Documentation/variables

Keeping the example files in sync will also become a problem (see #153).

**Comment by s-urbaniak** [comment]
I am self-assigning this, as I discussed this initially with @alexsomesan. As of now I suggest to retain the file structure in https://github.com/coreos/tectonic-installer/tree/master/Documentation/variables as it already separates common configuration from platform-specific configuration.

Doing so I would insert introspectable `tectonic_config_version`, `tectonic_config_aws_version`, `tectonic_config_azure_version`, `tectonic_config_openstack_[neutron|nova]_version` in the corresponding `variables.tf` files. They would then simply appear in the generated doc files.

This should solve the versioning and has the benefit of being introspectable by using the tectonic console like:

```
$ echo "var.tectonic_config_version" | terraform console`
0.1
```
