### ISSUE TITLE
Dry run

### ISSUE THREAD

**Issue by ggreer** [coreos/tectonic-installer#232]
In the installer, both AWS cloudformation & baremetal let you do a "dry run", which generates assets but doesn't actually cause a cluster to be booted. We need an equivalent for AWS terraform.

**Comment by alexsomesan** [comment]
As much as I understood it, the dry-run feature in the current installer is supposed to produce the assets and cloud-formation template for later use / repeatable builds of the same config.

In Terraform, the templates are already available in the repository.

Does the dry-run then have the same significance in the terraform based installer?

**Comment by sym3tri** [comment]
@ggreer wouldn't the old installer "dry run" be the equivalent of this?

- download terraform files + terraform.tfvars
- `terraform plan`

**Comment by ggreer** [comment]
Closing because this doesn't require any terraform work.
