### ISSUE TITLE
Bare metal UEFI based iPXE does not recognize initrd

### ISSUE THREAD

**Issue by adarshaj** [coreos/tectonic-installer#2345]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): [1.7.5-tectonic.1](https://github.com/coreos/tectonic-installer/releases/tag/1.7.5-tectonic.1)
* Terraform version (`terraform version`): v0.10.4
* Platform (aws|azure|openstack|metal): metal

## What happened?
Certain machines with iPXE based boot fails, i.e., after loading kernel and initrd images, the system does not seem to proceed further and is stuck on terminal. I could later determine that it was only those which had UEFI boot based iPXE machines. Exactly similar issue was earlier filed in coreos too: https://github.com/coreos/bugs/issues/1239

## What you expected to happen?
System should proceed with normal boot and continue with installation process.

## How to reproduce it (as minimally and precisely as possible)?
I had a baremetal server which has UEFI based iPXE image, with iPXE version - 1.0.0+ (75254)

## Anything else we need to know?
The issue was resolved after manually editing the coreos-intall.json template on matchbox with the solution described in the comment https://github.com/coreos/bugs/issues/1239#issuecomment-268220659 which refers to original article here: http://ipxe.org/appnote/debian_preseed

**Comment by rushins** [comment]
basically the core.efi  is in the bios, however it will not deduct as first boot ,so you need to manually set the following . (this is my work around and worked for cluster) 
read this link and you get idea  about BIOS screen https://github.com/coreos/bugs/issues/1592

----------------------------------

1) Tectonic matchbox will install , so after install to disk - > reboot
2) when boot starts,  go to settings -  press (F1 ) 
– Boot Manager – Add boot option – EFI-SYSTEM – coreos – grub – x86_64-efi – core.efi – input the description (e.g. tectonicboot), commit changes 
3) back to boot manager – change boot order to have the name you set (e.g. tectonicboot) first, commit changes. 

After that reboots from local disk work fine and it will load the coreostectonic

BR
Rushi.

**Comment by adarshaj** [comment]
Thanks Rushi for the inputs, my setup fails at step 1. The kernel and initrd is downloaded from matchbox and the machine just gets stuck at the prompt (of live booted coreos). I solved it by following steps outlined in coreos/bugs#1239
