### ISSUE TITLE
Docs - Pin to git tag or release

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#235]
Current documentation has the users work off of the master branch. We should consider pulling a release bundle or specific git tag.

**Comment by robszumski** [comment]
I was fighting for this at first, but folks convinced me that the churn is master was more apt to solve problems than hurt. Are you seeing anything negative right now in the field, or mostly hedging bets @alekssaul?

**Comment by alekssaul** [comment]
Hi @robszumski ,

I noticed some differences when troubleshooting in the field, didn't seem like a breaking change but made troubleshooting a bit more confusing. 

Aren't we synching the docs? Meaning there may be a diff in docs hosted on the website vs the master?

**Comment by alekssaul** [comment]
Actually may have hit; https://github.com/coreos/tectonic-installer/issues/245

**Comment by robszumski** [comment]
@alekssaul correct, we are syncing them. so you can point folks towards a stable url if you'd like: https://coreos.com/tectonic/docs/1.5.6-tectonic.1/install/aws/aws-terraform.html

**Comment by robszumski** [comment]
er, but this just tells you to check out master, nevermind

**Comment by robszumski** [comment]
Docs are now pinned to public releases
