### ISSUE TITLE
Why is tectonic_dns_name specific to AWS and not prefixed tectonic_aws?

### ISSUE THREAD

**Issue by aknuds1** [coreos/tectonic-installer#2355]
Why is the `tectonic_dns_name` configuration variable not named `tectonic_aws_dns_name` as per the convention, considering it's AWS specific and not global? Maybe it should be global, I don't know, but it belongs to the AWS platform for now.

**Comment by sym3tri** [comment]
We'll consider this for the converged platform.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
