### ISSUE TITLE
Support existing resources in the Azure installer.

### ISSUE THREAD

**Issue by coresolve** [coreos/tectonic-installer#238]
The tectonic-installer for Azure:
- [ ] Must support existing Resource Groups
  - [x] An existing RG for the vnet module - PR: https://github.com/coreos/tectonic-installer/pull/242
  - [ ] An existing RG for the Master and Worker modules
- [ ] Must support existing network components.
  - [x] existing vnet - PR: https://github.com/coreos/tectonic-installer/pull/242
  - [x] existing DNS zone resource group - PR: https://github.com/coreos/tectonic-installer/pull/417
  - [x] existing subnet - PR: https://github.com/coreos/tectonic-installer/pull/550
  - [ ] existing Network Security Group - (**NSG's are currently only enabled for etcd, but not masters or workers**)
- [x] Must be able to work with internal / private network components (vnets/subnets)
- [ ] Must be able to work with internal LB's for etcd, tectonic console & k8s APIserver - (**WIP**)
- [ ] Must NOT to destroy those pre existing components on tear down.
- [ ] Must be able to deploy Nodes in a separate Created Resource Group.
- [ ] Compute should be deployable into a different resource group then networking components. This _could_ be related to above point "Must be able to deploy Nodes in a separate Created Resource Group."
- [x] Should be able to use the same subnet_id for each of the workers and masters.
- [ ] Must be able to do private DNS resolution or default to public / external DNS resolution if needed. A.K.A mirrored DNS. This is detailed in the overlapping Name Spaces in public & private zones section of http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html - (**Needs more input & discussion with Azure**)
- [ ] Must work with existing IAM contributor / role
- [ ] VHD storage should be able to leverage managed disks, and not only storage accounts -
( **Needs more input & discussion with Azure**)

**Comment by alexsomesan** [comment]
This should tick a few boxes: https://github.com/coreos/tectonic-installer/pull/242/

**Comment by metral** [comment]
@coresolve Please add the following items to the list:

For "Must support existing network componets":
- existing DNS Zone

For the general list:
- Must be able to do private DNS resolution or default to public / external DNS resolution if needed. Similar to: http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html
- Must be able to leverage all existing network components from **internal / private** vnets/subnets

**Comment by rajpolaris** [comment]
Azure managed disks were released in Feb 2017. They are like AWS EBS volumes. They are easier to manage. Terraform already has a provider for azure managed disk(https://www.terraform.io/docs/providers/azurerm/r/managed_disk.html). It will be great if you can support azure managed disks. You will no longer have to manage storage accounts.

**Comment by justaugustus** [comment]
Just opened #1542, which adds support for managed disks.
cc: @coresolve, @rajpolaris

**Comment by justaugustus** [comment]
@coresolve: We've solved the following:
* Must support existing Resource Groups
* Must support existing network components
* Must be able to deploy Nodes in a separate Created Resource Group
* Must work with existing IAM contributor / role
* VHD storage should be able to leverage managed disks, and not only storage accounts

Could you update the checklist?

**Comment by sym3tri** [comment]
@coresolve Closing this b/c it's pretty stale & hasn't been updated. Please create a new issue if there's anything left to be done.
