### ISSUE TITLE
DNS never resolves in container once it fails: reachabily test failed: no such host

### ISSUE THREAD

**Issue by lig** [coreos/tectonic-installer#2389]
I've faced this issue on tectonic_1.7.9-tectonic.1

The issue was discussed here https://github.com/jetstack/kube-lego/issues/162

and resolved here https://github.com/kubernetes/dns/issues/121

It looks like adding `- --no-negcache` to `dnsmasq` spec in `modules/bootkube/resources/manifests/kube-dns.yaml` will make no harm except resolving the issue.

**Comment by robszumski** [comment]
Can you verify that the flag solves your problem? You should be able to modify the DNS pod from the Console or kubectl.

**Comment by lig** [comment]
@robszumski I've modified the app. Got no immediate effect:(
The issue is still there for me. I believe this one could be closed for now. I'll try to isolate the issue and file a more detailed report later.

**Comment by sym3tri** [comment]
@lig I'll go ahead and close this. Feel free to reopen if you're still having issues.
