### ISSUE TITLE
networking: add canal option to our testing matrix

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#239]
With the recent bug found in flannel (https://github.com/coreos/flannel/issues/667) we should start introducing a testing matrix for the various networking systems.

This is a bug for adding canal to our testing options.

cc @tomdee @ethernetdan

**Comment by squat** [comment]
Since #780 landed today, we now perform basic Calico network policy testing on all PRs. Another issue #1402 proposes to expand that test to more thoroughly exercise the network policies.
