### ISSUE TITLE
Limit AWS AZs (keep etcd peers close)?

### ISSUE THREAD

**Issue by tomdavidson** [coreos/tectonic-installer#2400]
## FEATURE (support) REQUEST

I would like to use the tectonic networking (using AWS but will using VMWare too), but limit the number of AZ to two rather than three so I can keep nodes closer.  (If additional HA is needed, I would rather have multiple region).

There use to be a tectonic_aws_az_count var? Does this capability exists and is just not visible?

## Versions

* Tectonic version: 1.7.9
* Terraform version: 0.10.8
* Platform: AWS

**Comment by sym3tri** [comment]
We'll consider this for the converged platform.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
