### ISSUE TITLE
Tectonic Sandbox: tectonic-monitoring-auth-prometheus fails with status CrashLoopBackOff

### ISSUE THREAD

**Issue by jensens** [coreos/tectonic-installer#2428]
## Versions

* tectonic-sandbox-1.7.1-tectonic.2.zip 
* with Vagrant 2.01

## What happened?

When I try to not connect to https://console.tectonicsandbox.com/prometheus/ I get a 404

## What you expected to happen?

Have Prometheus up and running.

## How to reproduce it (as minimally and precisely as possible)?

* Install Vagrant 2.0.1 in Ubuntu
* Download and unzip above zip, cd into it.
* ``vagrant up --provider=virtualbox`` and wait a while.
* Go to browser, login to tectonic webinterface
* Select Menu Troubleshooting -> Prometheus

## Anything else we need to know?

Under Menu Pod looking at tectonic-monitoring-auth-prometheus-3826734937-2m44g I see a ``Status: CrashLoopBackOff`` while ``Log`` is empty.

I am not sure if this is the right place for the report, when not please point me to the right place.

**Comment by sym3tri** [comment]
Tectonic Sandbox is now deprecated. Please see https://www.openshift.com for Open Shift alternatives.
