### ISSUE TITLE
Feature request: 'Matchbox Credentials' validation

### ISSUE THREAD

**Issue by knweiss** [coreos/tectonic-installer#2435]
## Versions

* Tectonic version1.7.9-tectonic.1 (14478b4)
* Terraform version (`terraform version`): v0.10.7
* Platform: metal

## What happened?

I ran into two _minor_ validation issues in the Matchbox Credentials section of the installer that could be improved:

1. Accidentally, I pasted the matchbox TLS **server** certificate into the client certificate field. This cause the `tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage` matchbox error later on.
2. My matchbox client key starts with `-----BEGIN PRIVATE KEY-----` but the tectonic installer's regex expects e.g. `-----BEGIN RSA PRIVATE KEY-----`.

## What you expected to happen?

1. The installer could validate the "key usage" field of the provided certificate to make sure it can be used as a client certificate.  This would have caught the problem **much** earlier. (Of course, it was my fault...)
2. The installer should accept key files starting with `-----BEGIN PRIVATE KEY-----`, too.

## How to reproduce it (as minimally and precisely as possible)?

1. Provide a matchbox certificate without "TLS Web Client Authentication" key usage.
2. Provide a RSA key starting with `-----BEGIN PRIVATE KEY-----` and the installer's key validator won't accept it.

## Anything else we need to know?
Regarding 2) I've created the RSA key on CentOS 7.4 using
```
$ openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048  -out testkey
.......................................................+++
......+++
$ head -n 1 testkey
-----BEGIN PRIVATE KEY-----
```

**Comment by sym3tri** [comment]
Thanks for the suggestion, but now that we're integrating with Open Shift we won't be addressing this in this repo.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
