### ISSUE TITLE
Secure Kubelet HTTP server

### ISSUE THREAD

**Issue by alexsomesan** [coreos/tectonic-installer#247]
TBD

**Comment by aaronlevy** [comment]
Example on kubelet side: https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L176-L177

Example on api-server side: https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L176-L177

Note - this only sets up client cert validation - does not setup server certificate validation (e.g. api-server as client connecting to kubelet as server) - we need per-kubelet certs/identity before we can do that (so CN/SAN validates correctly)

**Comment by fabxc** [comment]
Is this a superset of #227? What else would it entail?

If this is a catch-all issue, we should list the blockers that came up in #223.

**Comment by s-urbaniak** [comment]
pinging @sym3tri to verify if this really needs to be tackled in the context of feature parity.

**Comment by sym3tri** [comment]
This only entails adding the extra flags to kubelet (1 flag) and api server (2 flags). These changes were already made to the old GUI installer, so yes it is part of feature parity.

**Comment by alexsomesan** [comment]
@sym3tri @aaronlevy This issue is super confusing!

The title talks about the kubelet HTTP server and Aaron also explains the issue caters to enabling CLIENT CERT AUTH for the KUBELET SERVER.
This translates into the following arguments to each component involved:
1. the API server:
   * --kubelet-client-certificate (already set [here](https://github.com/coreos/tectonic-installer/blob/master/modules/bootkube/resources/manifests/kube-apiserver.yaml#L41))
   * --kubelet-client-key (already set [here](https://github.com/coreos/tectonic-installer/blob/master/modules/bootkube/resources/manifests/kube-apiserver.yaml#L42))
2. the Kubelet:
   * --client-ca-file (already set [here](https://github.com/coreos/tectonic-installer/blob/master/modules/aws/ignition/resources/services/kubelet.service#L36))

All of these were already in place since a while ago. Does that mean the issue is non-existent?
Or is the actual issue slipping through the conversation?

Please shed some light here.

**Comment by sym3tri** [comment]
I didn't create the original issue so I can't speak to it's original intent. But if the flags are set then the security concerns are addressed. Feel free to close.

**Comment by alexsomesan** [comment]
OK. Just wanted to make sure I didn't misunderstand the problem or scope.
Looks to me like the issue is solved.
Going to close. If anyone has another position, feel free to reopen.
