### ISSUE TITLE
Should use upstream recommended admission controllers

### ISSUE THREAD

**Issue by aaronlevy** [coreos/tectonic-installer#249]
`--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota`

https://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-plug-ins-to-use

tracking for bootkube: https://github.com/kubernetes-incubator/bootkube/issues/438

**Comment by Quentin-M** [comment]
Addressed by https://github.com/coreos/tectonic-installer/pull/246.

**Comment by s-urbaniak** [comment]
#246 is merged, hence I am closing this issue.
