### ISSUE TITLE
Consolidate ignition templates / services (kubelet, etcd-member, etc)

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#252]
As we make fast iterations, discrepancies are being introduced across platforms in the ignition templates and services. This includes variable names, parameters, etc. This will soon enough become a nightmare to manage. We should try to consolidate these into a common module and make every platform use them.

This is also burdensome to simply edit/add stuff to each of them individually.

**Comment by sym3tri** [comment]
This is tracked in jira & currently being worked on.
