### ISSUE TITLE
AWS: Unable to secure cluster from 0.0.0.0/0 on any security groups

### ISSUE THREAD

**Issue by zonepalms91** [coreos/tectonic-installer#2534]
## What keywords did you search in tectonic-installer issues before filing this one?
Security, AWS, SG, ELB

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST
BUG

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): Any
* Terraform version (`terraform version`): 0.11
* Platform (aws|azure|openstack|metal):aws

## What happened?
When attempting to limit access to the ELBs used for public access to console and api from scanning from scripts anywhere, cluster becomes un-usable. Throws 502 bad gateway errors and cannot access console or api. 

## What you expected to happen?
Should be very simple to add in an IP and have access without having 0.0.0.0/0 > HTTP/HTTPS open everywhere. Also should limit SSH port access to inter-vpc always. having that open to 0.0.0.0/0 is also a major security issue.

## How to reproduce it (as minimally and precisely as possible)?
Install tectonic. Attempt to limit access to cluster by limiting SGs to non 0.0.0.0/0 rules. Cluster throws a 502 bad gateway when navigating to console. If limiting API SG, throws a auth token failure when logging in.

**Comment by enxebre** [comment]
Hey @zonepalms91 we currently support an internal cluster topology with restricted access, See https://coreos.com/tectonic/docs/latest/install/aws/requirements.html https://github.com/coreos/tectonic-installer/blob/master/platforms/aws/variables.tf#L122

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
