### ISSUE TITLE
terraform init of aws modules fails for free 10 cluster node (TYPE.NAME.ATTR)

### ISSUE THREAD

**Issue by sean-abbott** [coreos/tectonic-installer#2543]
## What keywords did you search in tectonic-installer issues before filing this one?
TYPE.NAME.ATTR

## Is this a BUG REPORT or FEATURE REQUEST?
bug report

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
1.7.9-tectonic.2
* Terraform version (`terraform version`):
```
$ terraform -version
Terraform v0.10.0
```

* Platform (aws|azure|openstack|metal):
aws

## What happened?
```
$ terraform init platforms/aws
Downloading modules...
Get: file:///home/sabbott/workspace/spikes/tectonic_1.7.9-tectonic.2/modules/container_linux
Get: file:///home/sabbott/workspace/spikes/tectonic_1.7.9-tectonic.2/modules/aws/vpc
Get: file:///home/sabbott/workspace/spikes/tectonic_1.7.9-tectonic.2/modules/aws/etcd
Get: file:///home/sabbott/workspace/spikes/tectonic_1.7.9-tectonic.2/modules/ignition
Error downloading modules: Error loading modules: module ignition_masters: Error loading .terraform/modules/b7861fcebb1c687e27ab953bae7dd1ec/etcd.tf: Error reading config for template_file[advertise_client_urls]: local.scheme: resource variables must be three parts: TYPE.NAME.ATTR in:

${local.scheme}://${var.etcd_advertise_name_list[count.index]}:2379
```

## What you expected to happen?
Terraform init to work as it did in https://coreos.com/tectonic/docs/latest/install/aws/aws-terraform.html

## How to reproduce it (as minimally and precisely as possible)?
```
curl -O https://releases.tectonic.com/releases/tectonic_1.7.9-tectonic.2.zip
unzip tectonic_1.7.9-tectonic.2.zip
cd  tectonic_1.7.9-tectonic.2
terraform init platforms/aws
```

## Anything else we need to know?
I wasn't able to use your sandbox trial route either....so far I can't try your product.

**Comment by enxebre** [comment]
Hey @sean-abbott I'm not able to reproduce this. Make sure you are using the terraform version bundled with the release. As pointed [here](https://coreos.com/tectonic/docs/latest/install/aws/aws-terraform.html)
```export PATH=$(pwd)/tectonic-installer/darwin:$PATH```
```tectonic-installer/darwin/terraform --version``` Terraform v0.10.7

**Comment by sym3tri** [comment]
Please reopen if you can provide details on how to reproduce.
