### ISSUE TITLE
ERRO[0011] Failed to handle HTTP Request 

### ISSUE THREAD

**Issue by MilenkoM** [coreos/tectonic-installer#2586]
## What keywords did you search in tectonic-installer issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

 FEATURE REQUEST

 I have problems with Tectonic AWS deployment.

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
Tectonic 1.7.9
* Terraform version (`terraform version`):
Terraform v0.11.1

* Platform (aws|azure|openstack|metal):
aws

## What happened?
This is what I have during the installation in my terminal

 ./installer 
Starting Tectonic Installer on 127.0.0.1:4444
WARN[0000] Tectonic license not found in /home/milenko/tectonic_1.7.9-tectonic.2/tectonic-installer/linux 
WARN[0000] Pull secret not found in /home/milenko/tectonic_1.7.9-tectonic.2/tectonic-installer/linux 
ERRO[0011] Failed to handle HTTP Request                 error=User: arn:aws:iam::577147542553:user/milenkomarkovic is not authorized to perform: route53:ListHostedZones method=POST remote addr=127.0.0.1:50998 request uri=/aws/zones

This is what I have at Networking installation step
![screenshot from 2017-12-18 08-44-04](https://user-images.githubusercontent.com/13464056/34103285-8cb26f06-e3ec-11e7-8dd9-bc828f273e19.png)
I can not eneter DNS subdomain and domain

## What you expected to happen?
Proper installation.

## How to reproduce it (as minimally and precisely as possible)?
I am on Ubuntu 16.04,I have AWS Route 53,registered Domain Name.

**Comment by sym3tri** [comment]
It looks like you don't have the proper IAM permissions setup for the account you are using to perform the installation with. 

See the list of required permissions in our docs:

https://coreos.com/tectonic/docs/latest/install/aws/requirements.html#privileges

Note the link to the IAM JSON policy doc, which contains `route53:ListHostedZones`

**Comment by MilenkoM** [comment]
Thanks,will take a look.

**Comment by MilenkoM** [comment]
aws iam put-role-policy --role-name tectonic-installer --policy-name TectonicInstallerPolicy --policy-document file://aws-sts-trust-policy.json

An error occurred (NoSuchEntity) when calling the PutRolePolicy operation: Role not found for tectonic-installer

any ideas why Role is not found?

**Comment by squat** [comment]
@MilenkoM the step _before_ putting the role policy involves creating the `tectonic-installer` role; please follow all the steps in the linked document.
