### ISSUE TITLE
Self-hosted etcd no longer supported?

### ISSUE THREAD

**Issue by lblackstone** [coreos/tectonic-installer#2589]
It looks like the option to run self-hosted etcd has [been removed](https://github.com/coreos/tectonic-installer/pull/2486/commits/c7a1835c293e7284134f25b899f2d335af98de57). 

Is the intent moving forward to only use external etcd for k8s clusters?

**Comment by squat** [comment]
Yes, self-hosed etcd has been removed for the time being for the purpose of improving stability. The intent is not to use external etcd but to rely on on-node etcd. @robszumski can provide more color.

**Comment by robszumski** [comment]
The overview of the plan:
 - external etcd: no changes to this
 - on-node etcd: bring the config of this under more active management by the cluster. this will be the default path.
 - self-hosted: investigate bringing this back once the upstream issues have been fixed that cause the instability

**Comment by lblackstone** [comment]
@robszumski @squat 

What's the status for on-node etcd now? AFAICT, it hasn't been implemented yet. Any idea when that feature will be ready?

**Comment by pierrebeaucamp** [comment]
I'd be interested to learn more about those instability issues. Is this just concerning etcd-operator itself? Does the following document omit anything important: https://github.com/radhikapc/tectonic-installer/blob/085d5e3b6a5014c50ee895cde969287710e533d9/Documentation/troubleshooting/etcd_failure_cases.md

**Comment by robszumski** [comment]
One of the main sources for instability is how the current model of Services tracks health endpoints and how that poorly interacts with the default Service pointing to the self-hosted API. This mostly affects [this bullet](https://github.com/radhikapc/tectonic-installer/blob/085d5e3b6a5014c50ee895cde969287710e533d9/Documentation/troubleshooting/etcd_failure_cases.md#api-server) @pierrebeaucamp 

The hope is that moving the new endpoint reconciler to Beta will mean we can start to enable it widely: https://github.com/kubernetes/kubernetes/issues/57617

**Comment by Quentin-M** [comment]
FWIW We've been running/upgrading/snapshotting our etcd clusters in production, as well as maintaining their reliability in the event of various failures using the [etcd-cloud-operator](https://github.com/Quentin-M/etcd-cloud-operator) at my current job.

**Comment by erasmus74** [comment]
So I'm going to bump this because https://github.com/kubernetes/kubernetes/issues/57617
is now merged. I really look forward to the work towards on-node and self-hosted. I can help, just need to point the way, I prefer to help with testing and such, as I'm not CLA'ed and don't honestly have experience with the underlying codebase.

**Comment by dbavatar** [comment]
Also bump: Interested in making this work, including contributing dev time. Anyone have fork(s) where they are working on it?
