### ISSUE TITLE
Re: Connecting to console

### ISSUE THREAD

**Issue by fii** [coreos/tectonic-installer#260]
Getting a 'unauthorised' error message trying to connect to the console . 

How do we connect plz ?

**Comment by fii** [comment]
ip-10-0-10-199 core # ./kubectl get pods --namespace=tectonic-system
NAME                                           READY     STATUS             RESTARTS   AGE
default-http-backend-1636328216-qd8b4          1/1       Running            0          51m
node-exporter-4j9j4                            1/1       Running            0          51m
node-exporter-5cvm5                            1/1       Running            0          51m
node-exporter-5pqzw                            1/1       Running            0          51m
node-exporter-fj1t2                            1/1       Running            0          51m
node-exporter-mr9jd                            1/1       Running            0          51m
node-exporter-xrv90                            1/1       Running            0          51m
prometheus-k8s-0                               2/2       Running            0          51m
prometheus-operator-3833970704-9k8s1           1/1       Running            0          51m
tectonic-console-3034694978-hzjkk              0/1       CrashLoopBackOff   19         51m
tectonic-console-3034694978-lzdcm              0/1       CrashLoopBackOff   19         51m
tectonic-identity-4277829508-x3mgm             0/1       CrashLoopBackOff   14         51m
tectonic-ingress-controller-1020431057-t89mr   1/1       Running            0          51m
tectonic-stats-emitter-558394209-kgptf         2/2       Running            0          51m
ip-10-0-10-199 core # 


Doesn't look like its starting ...

**Comment by fii** [comment]
ip-10-0-10-199 core # ./kubectl get pods --namespace=tectonic-system -l app=tectonic-console -o template --template="{{range.items}}{{.metadata.name}}{{end}}" | xargs -i{} ./kubectl port-forward {} 9000
Error from server (NotFound): pods "tectonic-console-3034694978-hzjkktectonic-console-3034694978-lzdcm" not found
ip-10-0-10-199 core # ./kubectl get pods --namespace=tectonic-system -l app=tectonic-console
NAME                                READY     STATUS             RESTARTS   AGE
tectonic-console-3034694978-hzjkk   0/1       CrashLoopBackOff   23         1h
tectonic-console-3034694978-lzdcm   0/1       CrashLoopBackOff   23         1h
ip-10-0-10-199 core #

**Comment by sym3tri** [comment]
What platform?

**Comment by fii** [comment]
I'm on Linux. Thanks .

**Comment by fii** [comment]
This was deployed to AWS using Terraform.

**Comment by s-urbaniak** [comment]
@fii sorry that the terraform scripts don't work for you. Do you mind to also post the log messages from the console? You can retrieve them using `kubectl -n tectonic-system logs tectonic-console-3034694978-hzjkk`

**Comment by fii** [comment]
@s-urbaniak 

[fii@dell tectonic-installer]$ kubectl get ns
NAME              STATUS    AGE
default           Active    7m
kube-system       Active    7m
tectonic-system   Active    2m
[fii@dell tectonic-installer]$ kubectl get pods --namespace=tectonic-system -l app=tectonic-console
NAME                                READY     STATUS    RESTARTS   AGE
tectonic-console-3034694978-430gz   1/1       Running   3          2m
tectonic-console-3034694978-crb9g   1/1       Running   4          2m
[fii@dell tectonic-installer]$ kubectl get pods --namespace=tectonic-system -l app=tectonic-console -o template --template="{{range.items}}{{.metadata.name}}{{end}}" | xargs -i{} kubectl port-forward {} 9000
Error from server (NotFound): pods "tectonic-console-3034694978-430gztectonic-console-3034694978-crb9g" not found
[fii@dell tectonic-installer]$ kubectl -n tectonic-system logs tectonic-console-3034694978-crb9g
2017/04/20 19:05:42 http: Provider config sync failed, retrying in 1s: invalid character '<' looking for beginning of value
2017/04/20 19:05:43 http: Provider config sync still failing, retrying in 2s: invalid character '<' looking for beginning of value
2017/04/20 19:05:45 http: Provider config sync still failing, retrying in 4s: invalid character '<' looking for beginning of value
2017/04/20 19:05:49 http: Provider config sync still failing, retrying in 8s: invalid character '<' looking for beginning of value
2017/04/20 19:05:57 http: Provider config sync still failing, retrying in 16s: invalid character '<' looking for beginning of value
2017/04/20 19:06:01 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.3.0.190:5557: i/o timeout"; Reconnecting to {tectonic-identity-api.tectonic-system.svc.cluster.local:5557 <nil>}
[fii@dell tectonic-installer]$ 

Apologies for the delay. Let me know if you need anything else .

**Comment by fii** [comment]
[fii@dell tectonic-installer]$ kubectl get pods --namespace=tectonic-system -l app=tectonic-console
NAME                                READY     STATUS             RESTARTS   AGE
tectonic-console-3034694978-430gz   0/1       CrashLoopBackOff   6          6m
tectonic-console-3034694978-crb9g   0/1       CrashLoopBackOff   6          6m
[fii@dell tectonic-installer]$

**Comment by fii** [comment]
New instructions  doesn't work either ,.... 


provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: eu-west-1

There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * template_folder.bootkube-bootstrap: Provider doesn't support resource: template_folder
ah well ...

**Comment by sym3tri** [comment]
@fii are you still having issues with your installation? Have you tried a newer version?

**Comment by sym3tri** [comment]
If you're still having issues you can try in https://github.com/coreos/tectonic-forum/issues
