### ISSUE TITLE
Question regarding VMWare config options

### ISSUE THREAD

**Issue by edevil** [coreos/tectonic-installer#2601]
## What keywords did you search in tectonic-installer issues before filing this one?

tectonic_vmware_etcd_ip, tectonic_vmware_master_ip, tectonic_vmware_worker_ip

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.7.9

## What happened?

The variables tectonic_vmware_etcd_ip, tectonic_vmware_master_ip, tectonic_vmware_worker_ip are supposed to be maps between node indexes and IPs, but in the examples a class C address is given. Example:

```
tectonic_vmware_etcd_ip = { "0" = "192.168.246.10/24" "1" = "192.168.246.11/24" "2" = "192.168.246.12/24" }
```

Shouldn't these be IP addresses instead of networks? If these are correct, which network are these?

Thanks.

**Comment by enxebre** [comment]
Hey @edevil `tectonic_vmware_etcd_ip` ("192.168.246.10/24") represents an IP address with its routing prefix. It's used for the [network config](https://coreos.com/os/docs/latest/network-config-with-networkd.html)[here](https://github.com/coreos/tectonic-installer/blob/master/modules/vmware/etcd/ignition.tf#L72)
A better name would be probably network tectonic_vmware_etcd_ip_address

**Comment by edevil** [comment]
I see, thanks!
