### ISSUE TITLE
on-premise DNS with self hosted Consul

### ISSUE THREAD

**Issue by vgkowski** [coreos/tectonic-installer#2674]
## What keywords did you search in tectonic-installer issues before filing this one?

consul DNS

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

Actual on premise deployment relies on public DNS services or custom internal ones. Public DNS services requires internet access from the cluster nodes and internal DNS requires an exposed API for Terraform consumption.
Sometimes none of these options are available. Consul is the only backend that have a Terraform provider (https://www.terraform.io/docs/providers/consul/index.html) and a DNS API.
I propose to allow the use of a self hosted Consul for on premise and closed network usage. A classical self hosting could be used : 
* bootstrap a temporary single node Consul (on one master or external node?)
* use it to fill the node IP/names via the Terraform Consul provider
* configure the DNS on each node to point to the Consul server
* after K8S bootstrap, self host a Consul cluster (3 nodes minimum)
* switch the DNS to this new Consul cluster
* destroy the temporary Consul server

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
* Terraform version (`terraform version`):
* Platform (aws|azure|openstack|metal):
Openstack and bare metal which are generally the on-premise options

## What you expected to happen?

I can start working on it and propose a PR if you agree on this functionality
## Anything else we need to know?

Question regarding CoreOS Vault operator. Is it running on Consul backend ? Is there any Consul operator which could help this new feature ?

**Comment by vgkowski** [comment]
Answering to myself : CoreOS Vault relies on the Etcd operator.

**Comment by sym3tri** [comment]
@vgkowski we've been discussing PowerDNS internally as a solution to this problem and already have reference implementations for it in some of the platforms. I'd take a look at that first before investing time in another implementation.

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
