### ISSUE TITLE
Not possible to configure cluster-domain via terraform

### ISSUE THREAD

**Issue by tobad357** [coreos/tectonic-installer#2717]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one:  FEATURE REQUEST
It would be great to be able to configure the cluster-domain when using
terraform to install on a cluster. currently the cluster-domain will always be "cluster.local"
However when running multiple clusters it would be great to be able to set the domain differently for different clusters

There are at least two places that this would need to change
1. "--cluster-domain=" flag for kubelet-wrapper would need to be configurable via tf variable
2. when generating the certs the domain would need to be changed

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
