### ISSUE TITLE
CA cert inclusion does not enumerate certs correctly

### ISSUE THREAD

**Issue by brianredbeard** [coreos/tectonic-installer#2778]
Certificates included in the option `tectonic_custom_ca_pem_list` are not enumerated correctly.

Files are (presently) all placed into a single CA file at the location `/etc/ssl/certs/custom_ca_certs.pem`.  In a previous commit ( cea31f6f551ff880993479ae686ea5de75025ba3 / [modules/aws/master-asg/ignition.tf][previous-ca]) these were placed in separate files, which is the correct behavior.   This leads me to believe the move to minimize the size of the user-data and migration to the use of S3 has lead to this regression.

This is due to the difference in how certificates are handled with OpenSSL versus the use of the file `/etc/ssl/certs/ca-certificates.crt` by Go.  

This is important because placing multiple certificates in a single file will fail to correctly hash them for anchoring in the directory `/etc/ssl/certs/`.

[previous-ca]: https://github.com/coreos/tectonic-installer/blob/cea31f6f551ff880993479ae686ea5de75025ba3/modules/aws/master-asg/ignition.tf#L87-L100

**Comment by brianredbeard** [comment]
This specifically seems to be caused by the difference in the embedding process used by machines where these files are retrieved via S3 ([cea31f6f551ff880993479ae686ea5de75025ba3?diff=split#diff-3d0ad8e933a701981a3f5b7704209c60R53](https://github.com/coreos/tectonic-installer/commit/cea31f6f551ff880993479ae686ea5de75025ba3?diff=split#diff-3d0ad8e933a701981a3f5b7704209c60R53)) versus where the files are fully serialized into the ignition file ([cea31f6f551ff880993479ae686ea5de75025ba3?diff=split#diff-f3dbed0a854bcf42775243e54dda3256R77](https://github.com/coreos/tectonic-installer/commit/cea31f6f551ff880993479ae686ea5de75025ba3?diff=split#diff-f3dbed0a854bcf42775243e54dda3256R77))

**Comment by sym3tri** [comment]
I believe @squat fixed this. If so please close.

**Comment by squat** [comment]
Correct. Closing.
