### ISSUE TITLE
Documentation: references to terraform-download, which no longer exists

### ISSUE THREAD

**Issue by oremj** [coreos/tectonic-installer#282]
As of 05096c0d403218b19af8f2a9bb62529340e15755 the documentation in the README and at https://coreos.com/tectonic/docs/latest/install/aws/aws-terraform.html is broken. Specifically, `make terraform-download` which is no longer a target.

**Comment by philips** [comment]
cc @robszumski

**Comment by robszumski** [comment]
Sorry @oremj there is a lot of churn in this repo at the moment. The plan to reference master to keep folks up with the latest is proving to be a not-so-great strategy. I'll bump the site with the latest terraform instructions from the repo.

**Comment by robszumski** [comment]
Updated docs should be headed live
