### ISSUE TITLE
tectonic installer issue on HP blades

### ISSUE THREAD

**Issue by rushins** [coreos/tectonic-installer#2843]
hello,

i have baremetal (HP blades) and having issues that blades are not getting booted from PXE.

i have Tectonic installer running, PXE server is setup . The same setup is working on physical servers and virtual but HP blades having issues since the blades use VLAN connectivity with HP chassis console.

Does anyone experience or try setup on HP blades 

BR
Rishi

**Comment by rushins** [comment]
i didnt' enough information. bascically i wantto make sure   PXE (DNS server) to work across VLANs, since the blades (HP server) on chassis is connected to a switch port which is trunked.

**Comment by sym3tri** [comment]
https://github.com/coreos/tectonic-forum/issues is a better place to ask questions. I'm going to close this since there's no specific issue to solve with the installer itself.
