### ISSUE TITLE
image from quay.io/brancz

### ISSUE THREAD

**Issue by ericchiang** [coreos/tectonic-installer#2874]
https://github.com/coreos/tectonic-installer/pull/2773 added a reference to the Quay repo `quay.io/brancz/kube-rbac-proxy` This isn't an image controlled by CoreOS or associated with a project like `quay.io/prometheus/*` or `quay.io/calico/*`.

Long term, we need to develop a whitelist about what organizations we allow external images from and criteria for those orgs. E.g. I couldn't tell you who formally owns the push process for `quay.io/kubernetes-ingress-controller/nginx-ingress-controller`.

Today, this seems like a bad practice to include images from individual developers.

cc @brancz

**Comment by ericchiang** [comment]
cc @nstielau @sym3tri

**Comment by brancz** [comment]
This was fixed in https://github.com/coreos/tectonic-installer/pull/2904

**Comment by ericchiang** [comment]
Awesome, thanks!
