### ISSUE TITLE
Installer UI: assets.zip cannot be extracted

### ISSUE THREAD

**Issue by alexsomesan** [coreos/tectonic-installer#297]
I went through the UI wizard to test the installer. At the end, I wanted to download the assets.

The zip file that I received will not extract cleanly.

Log attached: [assets-unzip.txt](https://github.com/coreos/tectonic-installer/files/947658/assets-unzip.txt)

/cc: @sym3tri @Quentin-M

**Comment by Quentin-M** [comment]
Did you use macOS's vanilla unzipper? I know it does not manage it super well yeah. Thought it'd be due to the symlinks and other craziness that terraform does in .terraform.

**Comment by alexsomesan** [comment]
Yeah, I just tried the Finder unzipping support and also the cli unzip that comes on the macOS

**Comment by alexsomesan** [comment]
BTW, I don't think we need to bundle the `.terraform` folder in the zip file. It only contains copies of the modules, and will be recreated by `make plan` or `make apply` if missing.
So someone trying to build using the cli from assets would not see any error.

**Comment by Quentin-M** [comment]
I think so too.

**Comment by alexsomesan** [comment]
That's what I was trying to say.

`get` is automated away in the makefile. When you do a `plan` or `apply`, it does a `get` for you automatically if that folder is missing. So no change in UX

**Comment by Quentin-M** [comment]
I can now reproduce with test data.

```
$ find .
/
/a
/a/b
/a/b/c
/a/b/c/config.tf -> ../../../foo
/foo

$ cat a/b/c/foo
123
```

It unzips into:
```
$ find .
/
/a
/a/b
/a/b/c
/a/b/c/config.tf -> 123?
/foo

$ cat a/b/c/foo
cat: a/b/c/foo: No such file or directory
```

**Comment by ggreer** [comment]
It looks like symlinks are using the content of the files as the paths. Super weird.

**Comment by Quentin-M** [comment]
Yeap, they write directly into the ZIP whatever file header they find on disk - and always write the content of that file. However, in the case of symlinks, the OS and unarchivers expect to find the link path.
