### ISSUE TITLE
data.aws_route53_zone.tectonic: multiple Route53Zone found please use vpc_id option to filter

### ISSUE THREAD

**Issue by ssunagari** [coreos/tectonic-installer#2971]
## What keywords did you search in tectonic-installer issues before filing this one?

multiple Route53Zone found

## Is this a BUG REPORT or FEATURE REQUEST?

I suppose mostly a FEATURE REQUEST but kind of a BUG REPORT

### Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
```
https://registry.terraform.io/modules/coreos/kubernetes/aws/1.8.4-tectonic.3
```

### Terraform version (`terraform version`):

```
0.10.8
```
### Platform (aws|azure|openstack|metal|vmware):

```
aws
```

### What happened?

on a terraform plan:

```
Error: Error refreshing state: 1 error(s) occurred:

* module.tectonic.module.dns.data.aws_route53_zone.tectonic: 1 error(s) occurred:

* module.tectonic.module.dns.data.aws_route53_zone.tectonic: data.aws_route53_zone.tectonic: multiple Route53Zone found please use vpc_id option to filter

```

### How to reproduce it (as minimally and precisely as possible)?

use a `tectonic_base_domain` that has multiple Route53 hosted zones

https://aws.amazon.com/route53/faqs/#create_multiple_hzs_for_same_domain
### Desired Feature
Add the ability to include VPC ID to the terraform data source filter, or better yet to specify directly which Zone ID should be used.

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
