### ISSUE TITLE
Cluster Settings doesn't show license

### ISSUE THREAD

**Issue by alexsomesan** [coreos/tectonic-installer#299]
Not sure if I'm doing something wrong here or there's actually a issue.
See screenshot. 

/cc: @sym3tri @ggreer 

<img width="2032" alt="screen shot 2017-04-21 at 21 05 57" src="https://cloud.githubusercontent.com/assets/1097371/25292686/8297da56-26d7-11e7-825e-ed22173ea361.png">

**Comment by ggreer** [comment]
Does the browser console show any js errors or bad http responses?

**Comment by alexsomesan** [comment]
I destroyed that cluster. Let me rebuild it.

**Comment by ggreer** [comment]
Will be fixed once https://github.com/coreos-inc/bridge/pull/1467 is in a release.

**Comment by sym3tri** [comment]
I just ran master and this worked fine. I'm guessing it was fixed in that merge. Reopen if you see again.
