### ISSUE TITLE
Tectonic UI: My Account shows "Error Loading Clients"

### ISSUE THREAD

**Issue by alexsomesan** [coreos/tectonic-installer#301]
Screenshot:

/cc @sym3tri @ggreer 
<img width="2032" alt="screen shot 2017-04-21 at 21 18 07" src="https://cloud.githubusercontent.com/assets/1097371/25293422/24a1a5cc-26db-11e7-93e6-117686fd0ed6.png">

**Comment by ggreer** [comment]
Similar to #299, does the browser console show any js errors or bad responses?

**Comment by amrutac** [comment]
@alexsomesan: Can you gist the response for <code>alex-test.k8s.somesan.de/tectonic/clients</code>? Also which image build of console are you using?

**Comment by sym3tri** [comment]
@amrutac @ggreer I'm still seeing this on latest master.

**Comment by chancez** [comment]
I also saw this and it was related to HTTP2/SPDY errors. I don't have logs, but may be able to get some in the next few days, but I believe this is pretty reproducible if someone needs logs sooner.

**Comment by amrutac** [comment]
Yeah, I saw it too, and then when I downloaded the kube config, I couldn't reproduce this error after
![screen shot 2017-04-26 at 9 52 58 am](https://cloud.githubusercontent.com/assets/523368/25446379/380adc76-2a66-11e7-94f6-3926c7ba447d.png)

**Comment by sym3tri** [comment]
works for me too now. please reopen if it re-appears.

**Comment by amrutac** [comment]
Reopening this since it is reproducible when you log into the console for the first time. Occurs because  if the user has no refresh tokens, dex doesn't have a client object for the user and returns an error. @rithujohn191 is fixing this so that it returns an empty list and the frontend can show the empty list.

**Comment by amrutac** [comment]
Fixed and verified
