### ISSUE TITLE
CentOS/RHEL: Run ignition from a container

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#303]
Much of the bring-up code for Tectonic Installer is done using Ignition configs. Instead of rewriting the configs for different platforms that say only support bash or cloud-config instead simply bootstrap off of one of these using a container image for Ignition instead.

```
docker run quay.io/philips/ignition
```

PR to ignition: https://github.com/coreos/ignition/pull/357

This crazy idea comes from the kubernetes-anywhere project.

**Comment by crawford** [comment]
As long as you are only using the "files" stage of Ignition, this will probably work. The "disks" stage is almost certainly going to conflict with what's already been mounted.

**Comment by philips** [comment]
@crawford yes, mostly just files is used here.

**Comment by sym3tri** [comment]
let's move this to the OS backlog if still desired.
