### ISSUE TITLE
Define Reboot Strategies 

### ISSUE THREAD

**Issue by geek876** [coreos/tectonic-installer#3057]
Hi,
With reference to https://coreos.com/os/docs/latest/update-strategies.html, how to set the 'Reboot Strategy' while setting up a Tectonic Kubernetes 1.8 Cluster ? I setup a cluster following https://coreos.com/tectonic/docs/latest/install/azure/azure-terraform.html. When I login via ssh to one of our workers, it says `Container Linux by CoreOS beta (1662.1.0)
Update Strategy: No Reboots
`

**Comment by sym3tri** [comment]
Rebooting is managed by an operator in Tectonic and the typical Container Linux reboot settings do not apply.
