### ISSUE TITLE
unable to uninstall EC2 machines -- lost installation folder (deleted by mistake)

### ISSUE THREAD

**Issue by 34code** [coreos/tectonic-installer#3105]
Any way to delete aws resources if I lost the installation folder? Killing EC2 machines just makes them restart since I believe something behind the scenes is working its magic.. which is great but not for me as I want to destroy this cluster ..

**Comment by squat** [comment]
@34code the Tectonic installer creates ASGs [0] to control the number of EC2 instances in the cluster. As soon as a master does, the master ASG boots a new master node. To destroy all infrastructure you must delete the ASGs and their profiles.

[0] https://docs.aws.amazon.com/autoscaling/ec2/userguide/AutoScalingGroup.html

**Comment by 34code** [comment]
@squat thanks! eventually figured it out..
