### ISSUE TITLE
Structure-check failure on master

### ISSUE THREAD

**Issue by ethernetdan** [coreos/tectonic-installer#311]
Master started failing this morning [with the error](https://jenkins-tectonic-installer-public.prod.coreos.systems/job/coreos%20-%20tectonic-installer/job/tectonic-installer/job/master/56/execution/node/23/log/):

```
+ make structure-check
Using build directory [/home/ubuntu/workspace/r_tectonic-installer_master-NS74XVJEPOD6YQLL5ZT2OOXK7PRAOSE6JZYTTZWEVU5Q62NIW6VQ/build/demo]
wrong files: config.tf platforms/aws/config.tf platforms/azure/config.tf platforms/metal/config.tf platforms/openstack/neutron/config.tf platforms/openstack/nova/config.tf
make: *** [structure-check] Error 1
```

@dghubble when you get a chance, could you PTAL?

/cc @Quentin-M

**Comment by s-urbaniak** [comment]
Fixed by #317
