### ISSUE TITLE
metal: Please support letting bare metal provisioner node also function as controller node

### ISSUE THREAD

**Issue by aknuds1** [coreos/tectonic-installer#3125]
### Environment
metal

### Desired Feature
Please add support for allowing bare metal provisioner nodes also join the cluster as controller nodes, for those cases where one only has a limited number of nodes on hand. This is an issue for me right now as I'm on a project where our client limits us to 3 machines, so we will only have 2 nodes available as controllers/workers.

**Comment by squat** [comment]
@aknuds1 what `provisioner` node? The node running dnsmasq/matchbox? We currently have no plan to add this functionality to the track-1 branch. It would be a considerable amount of work and we have quite a lot on our hands with the new workflow.

**Comment by aknuds1** [comment]
@squat Yes, that is the node I mean. Should I just close this issue?

**Comment by squat** [comment]
Yes, we should close this for now. However, we would be happy to accept a contribution to that end.
