### ISSUE TITLE
Remove DNS SRV discovery for etcd

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#318]
AWS[0] and Openstack[1] modules use DNS SRV records to form the etcd-cluster. Based on my understanding this limits the number of etcd (and tectonic) clusters to 1 per Domain Zone.

![image](https://cloud.githubusercontent.com/assets/11538902/25359922/1fa42324-2915-11e7-8ce3-86f60e9c3fb6.png)

[0] - https://github.com/coreos/tectonic-installer/blob/master/modules/aws/etcd/ignition.tf#L54
[1] - https://github.com/coreos/tectonic-installer/blob/master/modules/openstack/etcd/ignition.tf#L41

**Comment by xiang90** [comment]
why do we need to do discovery when we control the entire bootstrap process in the installer?

**Comment by sym3tri** [comment]
@xiang90 
I think we have to use SRV records with Terraform b/c there's no way for us to reference the IP addresses  of the nodes at provisioning time without creating a dependency cycle.

We need to address this somehow, otherwise users will not be able to create more than 1 cluster using the same hosted zone. For example this is impossible: `cluster1.example.com` and `cluster2.example.com`

For context see: https://github.com/coreos/tectonic-installer/blob/master/modules/aws/etcd/dns.tf

**Comment by alexsomesan** [comment]
We have experimented with generating static lists of nodes from Terraform (the same data that goes into the SRV records). This list would then be passed to etcd using --initial-cluster (for example using systemd env var files).

**Comment by sym3tri** [comment]
This is strange. I just booted a cluster and it didn't add any SRV records for my etcd node.

**Comment by alexsomesan** [comment]
Are you checking in the public or private zone?

SRV records are only created in the private R53 zone, as they are only
needed inside the VPC (for etcd initial bootstrapping).

This also improves security, since the etcd node records are only
resolvable from inside the VPC.

**Comment by sym3tri** [comment]
@alexsomesan ah. that makes sense. I was only looking at the public one.

**Comment by coresolve** [comment]
related https://github.com/coreos/tectonic-installer/issues/648

**Comment by Quentin-M** [comment]
I encountered this last week too. As far as I understand it. This is really only an issue if:
- You are not using self-hosted etcd
- You are not using a dedicated private zone

Is this correct?

**Comment by alexsomesan** [comment]
That's correct @Quentin-M

**Comment by alekssaul** [comment]
I believe also if you are using a public r53 zone.. not sure if we still have that option in 1.6

**Comment by hhoover** [comment]
This has impacted me this week - I'd love to have the option to use the public discovery service inside the installer (or at least a non-SRV method).

**Comment by sym3tri** [comment]
stale
