### ISSUE TITLE
Custom additional ignition config via terraform.tfvars for baremetal, openstack and vmware.

### ISSUE THREAD

**Issue by RonnyMaas** [coreos/tectonic-installer#3210]
## What keywords did you search in tectonic-installer issues before filing this one?
ignition

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: FEATURE REQUEST

## Versions
>= 1.8.9

### Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
```
enter text here
```

### Terraform version (`terraform version`):

```
enter text here
```
### Platform (aws|azure|openstack|metal|vmware):

```
enter text here
```

### What happened?

```
enter text here
```

### What you expected to happen?

```
enter text here
```

### How to reproduce it (as minimally and precisely as possible)?

```
enter text here
```

### Anything else we need to know?
```
enter text here
```

### References

```
enter text here
```

### Environment

```
bare metal, openstack, vmware
```
### Desired Feature
```
enter text here
```

### Other Information
```
enter text here
```

**Comment by RonnyMaas** [comment]
Somehow, lost my feature request description. So I will write it here again.

I would like to be able to add custom ignition data with a new var that can be used to add/append custom config to default ignition data from the default vars in terraform.tfvars.

For example a here document var with ignition data and/or ignition includes that can be appended to the default generated ignition data used to bootstrap an instance/vm/host.

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
