### ISSUE TITLE
Failed Units: 1   bootkube.service

### ISSUE THREAD

**Issue by yunxiaoge** [coreos/tectonic-installer#3217]
localhost:tectonic-sandbox-1.7.5-tectonic.1 vagrant$ vagrant ssh c1
Last login: Sun Apr 29 06:59:11 UTC 2018 from 10.0.2.2 on ssh
Container Linux by CoreOS beta (1465.3.0)
Update Strategy: No Reboots
Failed Units: 1
  bootkube.service

=====================
core@c1 ~ $ systemctl status bootkube
● bootkube.service - Bootstrap a Kubernetes cluster
   Loaded: loaded (/etc/systemd/system/bootkube.service; disabled; vendor preset
   Active: failed (Result: exit-code) since Sun 2018-04-29 07:27:18 UTC; 30min a
  Process: 1105 ExecStart=/usr/bin/bash /opt/tectonic/bootkube.sh (code=exited, 
 Main PID: 1105 (code=exited, status=1/FAILURE)
      CPU: 4.562s

Apr 29 07:27:17 c1.tectonicsandbox.com bash[1105]: [ 1695.588613] bootkube[5]: E
Apr 29 07:27:17 c1.tectonicsandbox.com bash[1105]: [ 1695.588854] bootkube[5]: E
Apr 29 07:27:17 c1.tectonicsandbox.com bash[1105]: [ 1695.588981] bootkube[5]: T
Apr 29 07:27:17 c1.tectonicsandbox.com bash[1105]: [ 1695.590236] bootkube[5]: E
Apr 29 07:27:17 c1.tectonicsandbox.com bash[1105]: [ 1695.591587] bootkube[5]: E
Apr 29 07:27:17 c1.tectonicsandbox.com bash[1105]: [ 1695.592281] bootkube[5]: A
Apr 29 07:27:18 c1.tectonicsandbox.com systemd[1]: bootkube.service: Main proces
Apr 29 07:27:18 c1.tectonicsandbox.com systemd[1]: Failed to start Bootstrap a K
Apr 29 07:27:18 c1.tectonicsandbox.com systemd[1]: bo

**Comment by sym3tri** [comment]
Tectonic Sandbox is now deprecated. We suggest you explore Open Shift and it's alternatives for local evaluation and development.

https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
