### ISSUE TITLE
Kubernetes tectonic 1.10?

### ISSUE THREAD

**Issue by abh** [coreos/tectonic-installer#3223]
Do you have a public roadmap for when 1.10 will come out?

(Other issues have references from months ago about a forthcoming test release)

**Comment by abh** [comment]
Eh, this should have been in [tectonic-forum](/coreos/tectonic-forum/issues), sorry!

The feature I was after was installing [stash](https://appscode.com/products/stash/) for backing up volumes, and it requires the extended API server (roughly as described in [this issue](https://github.com/appscode/voyager/issues/890) though it's for another product).

**Comment by robszumski** [comment]
There is no concrete timeline for Kubernetes 1.10. We are balancing time between integration work into OpenShift and continuing to update Tectonic to keep clusters secure and functioning well.

**Comment by rushins** [comment]
any update on 1.10 release from tectonic

**Comment by rushins** [comment]
hello any news on tectonic kubernetes 1.10 release ?

**Comment by whindes** [comment]
bump... security hole in kubernetes 1.0-1.9 .  We need kubernetes 1.10 now and I am not sure if anything will be updating in this repo it seems.  [https://access.redhat.com/security/vulnerabilities/3716411](url)  Please advise.  EDIT:  Updated repo 1 day after this post - https://github.com/coreos/tectonic-installer/releases/tag/1.9.6-tectonic.2
