### ISSUE TITLE
Always cleanup resources after smoke

### ISSUE THREAD

**Issue by ethernetdan** [coreos/tectonic-installer#335]
We should be running `make destroy` after every smoke test run. Jenkins has a mechanism to enforce this through the `post` [functionality of Pipelines](https://jenkins.io/doc/pipeline/tour/post/).

We need to figure out a way to share the cluster state directory between steps so it's accessible in `post`.

**Comment by ethernetdan** [comment]
Work started in #331

**Comment by s-urbaniak** [comment]
Fixed by #331
