### ISSUE TITLE
don't include logs directory in assets.zip for manual install

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#351]
Some strange error logs show up there. Unsure how these get generated but they are not useful.

**Comment by Quentin-M** [comment]
I believe it is mainly because get/plan are executed. It is not necessary as I [commented](https://github.com/coreos-inc/tectonic/pull/1710) earlier.

**Comment by sym3tri** [comment]
Makes sense. Can we just omit that directory when downloading for manual install? 

This is very low priority.
