### ISSUE TITLE
GUI: provide a way to get a kubeconfig for troubleshooting installation

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#356]
If you go thru the GUI flow and everything is good, you'll get to the step where it says: "Starting Tectonic console", which could end up never working for various reasons. If this step were to silently fail there is now way for the user to debug what has happened. We don't generate the kubeconfig or document how to get it. You can only download the assets once the install has completed successfully.

**Comment by tlwu2013** [comment]
Hi @kyoto ,

Please see attached latest mocks for "Console startup failed case".

There are three of them:
1. **2.4_Starting_Tectonic_failed__ver3.3.png**:
--> look-n-feel

2. **2.4_Starting_Tectonic_failed__ver3.3__redline.png** 
--> see notes for more info

3. **2.4_Starting_Tectonic_failed__ver3.3__spacing.png**
--> see spacing info

Please ping me for any question you have, thanks!
Tony

**2.4_Starting_Tectonic_failed__ver3.3.png**:
![2 4_starting_tectonic_failed__ver3 3](https://user-images.githubusercontent.com/5903705/28588797-91f7d6ce-7130-11e7-8c89-ad1b8e365a36.png)

**2.4_Starting_Tectonic_failed__ver3.3__redline.png** 
![2 4_starting_tectonic_failed__ver3 3__redline](https://user-images.githubusercontent.com/5903705/28588805-962fe98e-7130-11e7-8fb4-fc0176ec690c.png)

**2.4_Starting_Tectonic_failed__ver3.3__spacing.png**
![2 4_starting_tectonic_failed__ver3 3__spacing](https://user-images.githubusercontent.com/5903705/28588789-8d7224b0-7130-11e7-9d47-a90473bed9c2.png)

**Comment by tlwu2013** [comment]
And here's the mock for showing the flow:
![installer__starting-tectonic-screens__ after_terraform_success](https://user-images.githubusercontent.com/5903705/28588883-d59b1896-7130-11e7-831e-02ac154b4c28.png)

**Comment by kyoto** [comment]
Blocked on #1192

**Comment by sym3tri** [comment]
@kyoto unblocked now that #1192 has merged?

**Comment by kyoto** [comment]
@sym3tri Yes, unblocked now. I have started working on this.
