### ISSUE TITLE
GUI: Last screen of installer has outdated links

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#357]
kubectl link is outdated: https://kubernetes.io/docs/user-guide/prereqs/
should be: https://kubernetes.io/docs/tasks/kubectl/install/

---

"deploy your app" link is broken & getting redirected: https://coreos.com/tectonic/docs/latest/usage/first-app.html
should be: https://coreos.com/tectonic/docs/latest/tutorials/

**Comment by tlwu2013** [comment]
Per discussed, please see attached screenshot:

* Update "kubectl link" to "Configuring credentials" on CoreOS tutorial / doc site for specific steps to download kubectl / kubectl-config in Tectonic Console.
https://coreos.com/tectonic/docs/latest/tutorials/first-app.html#configuring-credentials

* Update "deploy your app" link to "Deploying a simple application" on CoreOS tutorial / doc site
https://coreos.com/tectonic/docs/latest/tutorials/first-app.html#deploying-a-simple-application

<img width="1225" alt="external_links _installation_complete_screen__0428_2017" src="https://cloud.githubusercontent.com/assets/5903705/25549276/d130ecfe-2c25-11e7-8071-530cc1f84ddf.png">

PR created: 
https://github.com/coreos/tectonic-installer/pull/425

**Comment by amrutac** [comment]
Closed in https://github.com/coreos/tectonic-installer/pull/425
