### ISSUE TITLE
etcd AWS node names should be suffixed with "-etcd"

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#362]
Same as how we do with "-master" and "-worker".

**Comment by xiang90** [comment]
are we going to support dedicated etcd nodes? if so, we should also taint them.

**Comment by sym3tri** [comment]
@xiang90 sure, but that is a separate issue. This pertains to the static etcd AWS nodes, not registered as kubernetes nodes.

**Comment by xiang90** [comment]
oh. ok. can you make this issue clear? changing node to aws-node? i thought it is kube-node. thanks.
