### ISSUE TITLE
GUI: Submit doesn't work if terraform isn't installed

### ISSUE THREAD

**Issue by pst** [coreos/tectonic-installer#371]
![screenshot from 2017-04-26 16-52-26](https://cloud.githubusercontent.com/assets/253456/25441336/33aa88e8-2aa2-11e7-83c4-fc42484ab21b.png)

**Comment by sym3tri** [comment]
Note: this won't be an issue when downloading a release tarball b/c it will include a build of TF in the same directory.

Eventually it'd be nice to vendor TF directly into the installer.

**Comment by pst** [comment]
I built the installer myself indeed. Can I build my own release tarball somehow?

**Comment by sym3tri** [comment]
@pst there are scripts in https://github.com/coreos/tectonic-installer/tree/master/installer/scripts/release but they are not well documented (on our todo list).

**Comment by pst** [comment]
I see, so if the release will not have this issue I assume we can close this issue.
