### ISSUE TITLE
kubelet: use quay.io for pause container

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#379]
To stay consistent with hyperkube, etc we should put all required containers into quay.

This is a kubelet flag:

```
      --pod-infra-container-image string                        The image whose network/ipc namespaces containers in each pod will use. (default "gcr.io/google_containers/pause-amd64:3.0")
```

cc @eddieesquivel @alekssaul

**Comment by sym3tri** [comment]
moved to https://github.com/coreos/tectonic-installer/issues/463 to capture them all

**Comment by philips** [comment]
cc @colhom

**Comment by philips** [comment]
@sym3tri this one is a little different because it is also about changing kubelet flags.

**Comment by sym3tri** [comment]
Yeah I know, but part of the same bigger story
