### ISSUE TITLE
Support customers with Proxy

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#38]
- Bootkube script curls to 127.0.0.1, no_proxy variable needs to specify 127.0.0.1
- Customers MITM SSL connectivity, need to trust their cert bundle (ex: copy to /etc/ssl/certs and run update-ca-certs script)
- All systemd units need environment variables (http_proxy, https_proxy, no_proxy)
- Openstack metadata service needs to be included in no_proxy
- /etc/environment should contain environmental variables  (http_proxy, https_proxy, no_proxy)

**Comment by sym3tri** [comment]
related: https://github.com/coreos/tectonic-forum/issues/89#issuecomment-289451564

**Comment by janwillies** [comment]
At least on AWS, `bootkube` needs modifications to talk to the AWS API (https://github.com/kubernetes-incubator/bootkube/issues/556)

**Comment by alekssaul** [comment]
@sym3tri , we've using that method in the field with success. Seems to be the cleanest method so far, to allow provisioning of the cluster. Few other changes at Tectonic level are required. Namely; CLUO, KVO, TVO and stats emiter need proxy variables as well.

@janwillies , I've personally only used it on Baremetal and VMware environments. Default bootkube uses `render` whereas Tectonic uses `bootkube start` . Tectonic also has separation of temp api plane manifests vs permanent control plane manifests under bootkube modules, so you may have better luck. 

Please note that CoreOS doesn't support Tectonic clusters that have modified API server manifests, and can't guarantee in-place upgrades will not break changes made to API pods or the cluster as a whole.

**Comment by sym3tri** [comment]
tracking internally now

**Comment by edevil** [comment]
So, just to make this clear, it is possible to install tectonic behind a corporate proxy by altering a dozen files (is there a list somewhere?) BUT we loose the support from CoreOS?

**Comment by sym3tri** [comment]
Hi @edevil,
There have been some workarounds attempted in the past like what's described above but we don't have any official solution yet. It is however on our roadmap.

**Comment by knweiss** [comment]
@sym3tri Missing web proxy support is also a big problem for my current tectonic evaluation. See

- https://github.com/coreos/tectonic-forum/issues/235
- https://github.com/coreos/tectonic-forum/issues/234
- https://github.com/coreos/tectonic-forum/issues/223

Wouldn't it make sense to reopen this issue until this is not fixed?

**Comment by sym3tri** [comment]
We're working on this with the next version of the installer that will be integrating Tectonic with Open Shift, but will not be adding this feature to this repository. We'll post a link to the new repo in the README once it's ready.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
