### ISSUE TITLE
kube-flannel: use quay.io

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#382]
We are trying to make it easier to track all of the container images that we rely on (see #379) so we can eventually create a tool to push all pre-reqs into an offline container registry.

Besides #379 we also rely on DockerHub for kube-flannel. Can we create an alternative against quay.io for this? https://github.com/coreos/tectonic-installer/blob/3ac7f7519ee071f04e621a4ae38ca0e88b8f82c3/modules/bootkube/resources/manifests/kube-flannel.yaml

cc @eddieesquivel @alekssaul

**Comment by alekssaul** [comment]
How about; https://quay.io/repository/prometheus/busybox ?

**Comment by sym3tri** [comment]
moved to https://github.com/coreos/tectonic-installer/issues/463 to capture them all
