### ISSUE TITLE
AWS: Support multiple worker ASGs

### ISSUE THREAD

**Issue by joshrosso** [coreos/tectonic-installer#387]
Tectonic-Terraform installations only support 1 worker Autoscaling groups (ASGs). Users may desire having multiple ASGs utilized in their Tectonic cluster(s).

The use of multiple ASGs allows them to:
- Provide isolation via specific security group / subnet settings on select nodes
- Have specific nodes be of a different instance type, dedicated to the ASG
- Scale certain groups of nodes independently when using an ASG aware autoscaler

**Comment by krish7919** [comment]
We have a need to run a cluster with different instance types for different kinds of services.

Is someone actively looking into this?

I might be interested in developing this further otherwise.

**Comment by sym3tri** [comment]
@krish7919 we are aware of the desire and would like to support exactly that. But first we're making some changes to the way the installer works to be generally more flexible. This is a goal, but will take a little time.

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
