### ISSUE TITLE
Support for .gov and china regions

### ISSUE THREAD

**Issue by eddieesquivel** [coreos/tectonic-installer#389]
Hi Team, .gov and china don't have route 53 available. I'd like to be able to reference a route53 outside of those regions so that we can get Tectonic installed. If you have questions around this feature please let me know, I can reach out to the respective customers to grab more requirements.

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
