### ISSUE TITLE
Validate cluster name during input

### ISSUE THREAD

**Issue by pst** [coreos/tectonic-installer#398]
I used a rather long name. Unfortunately it only fails when I try to submit. I think it would be better if it was validated in the form already.

```
1 error(s) occurred:

* module.masters.aws_elb.api-internal: "name" cannot be longer than 32 characters: "new-installer-test-gui-api-internal"
```

**Comment by s-urbaniak** [comment]
Closing this in favor of #413 being a duplicate.
