### ISSUE TITLE
all: introduce concept of platform version

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#40]
Problem: After deploying an infrastructure for Kubernetes a user may need help debugging something or upgrading. But, infrastructure is a tricky thing because there are a lot of moving parts that will be deployed by this Platform SDK.

Solution: Introduce a Platform SDK version. 

- [ ] Introduce a version and changelog to https://github.com/coreos-inc/tectonic-platform-sdk/blob/master/Documentation/generic-platform.md
- [ ] Start tagging/labelling resources in the cloud provider
- [ ] Label all nodes in kubernetes

**Comment by s-urbaniak** [comment]
This relates to #309. I am leaving this open as it generally lists a few good ideas to be taken into account for this specification.

**Comment by sym3tri** [comment]
moving internally
