### ISSUE TITLE
tectonic/bootkube: dubious etcd-quorum-read setting

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/tectonic-installer#400]
We set `--etcd-quorum-read=true` in https://github.com/coreos/tectonic-installer/blob/13b8f66fabbdce4ca3096f994a093a1fa5ba24b0/modules/bootkube/resources/manifests/kube-apiserver.yaml#L37 to fix 404s we got from TPRs after creation. After setting this value we still got 404s, so we implemented a basic reconciliation loop in `tectonic.sh` because those were actually caused by an implementation detail in not-yet-up-to-date caches of api-server instances in the HA-setup.

After investigation I am of the opinion that this setting is wrong, or at least unnecessary, and vote for removing it as I believe the k8s api server is able to handle stale reads from etcd.

@aaronlevy @xiang90 do you mind to shed some light about the recommended setting here and ramifications?

**Comment by aaronlevy** [comment]
In prior testing this has always been needed - otherwise you could get into states where one component gets a different response than another (data has not replicated across all members yet). But I 100% defer to @xiang90 on this.

**Comment by xiang90** [comment]
We should always set `--etcd-quorum-read=true`. Allowing to set is to `false` is just for users who only set up 1 member etcd cluster. Moreover, even for 1 node cluster, we still suggest to set this to true (we might make the flag takes no effect for etcd3 backend).

TPR are created async as far as I can tell. So setting etcd-q-r is irrelevant to it.

**Comment by s-urbaniak** [comment]
Thanks a lot for the recommendation! I will also therefore open a pull
request upstream, since I believe this setting defaults to false in the
api-server.
