### ISSUE TITLE
Use new tag format for 1.6

### ISSUE THREAD

**Issue by bison** [coreos/tectonic-installer#402]
We should use the new tag format for 1.6 clusters. Instead of tagging things with `KubernetesCluster = ${cluster_name}` use `kubernetes.io/cluster/${cluster_name} = {owned,shared}`. See: https://github.com/kubernetes/kubernetes/pull/41695

**Comment by Quentin-M** [comment]
@sym3tri PR is https://github.com/coreos/tectonic-installer/pull/469, by @s-urbaniak.
