### ISSUE TITLE
GUI: clicking back after install results in infinite spinners

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#404]
I clicked 'go back' hoping I could still destroy my cluster from the GUI, instead all I see is:

![screenshot from 2017-04-27 11-29-14](https://cloud.githubusercontent.com/assets/224222/25498444/d39d8644-2b3c-11e7-88ec-9e52fd42bfcd.png)

1. Bug: We should either remove the 'go back' link, or enable this screen to persist its state.
2. As a user I want an easy way to destroy my cluster from the GUI _after_ install succeeds.

**Comment by ggreer** [comment]
I'm pretty sure https://github.com/coreos/tectonic-installer/pull/620 fixed this.

**Comment by sym3tri** [comment]
will try to reproduce

**Comment by sym3tri** [comment]
unable to reproduce
