### ISSUE TITLE
Infinite loop in wait_for_tpr_available due to http 404s

### ISSUE THREAD

**Issue by zendeavor** [coreos/tectonic-installer#405]
Using the linux tectonic installer on a bare metal setup left me hung up on this near-final step.

hyperkube is listening on 127.0.0.1:8080, and curl receives http 200 from 127.0.0.1:8080/apis/. Any further descent returns 404s, so `wait_for_tpr_available` never breaks the loop.

**Comment by s-urbaniak** [comment]
@zendeavor thanks for your report. Can you provide a little more context, like log outputs and the current state of deployed pods while being in the crash loop?

/cc @dghubble

**Comment by zendeavor** [comment]
I would be glad to if I had found any! Watching `journalctl -u bootkube -fex` results in printing `Apr 28 01:25:38 controller.local bootkube-start[1464]: Waiting for third-party resource definitions...` in 3-second intervals. 

Are there any particular logs or journals that would be more helpful?

**Comment by coresolve** [comment]
on one of the controller nodes. If you can run `rkt list` and then `sudo rkt enter <uuid of the hyperkube pod that is running`
from there you can run `kubectl get pods --all-namespaces`

**Comment by zendeavor** [comment]
Closing this because I am opening a new issue against version 1.6.2 with what appears to be a different bug.

This one may not be fixed yet, but in that case I'll actually remember to come back and re-open this one.
