### ISSUE TITLE
AWS: better handling of long ELB names

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#413]
My apply run failed because my internal API ELB's name was longer than 32 characters. Seems like we should either:

1. truncate the name automatically, at risk of collisions
2. validate and warn in the UI

I favor #1, since the name I entered wasn't particularly long and will probably be hit often-ish.

**Comment by ggreer** [comment]
The frontend limits cluster names to 28 chars max. Just FYI, this is what the user sees when they use a cluster name with >19 characters:

![screen shot 2017-05-03 at 13 22 10](https://cloud.githubusercontent.com/assets/200121/25679872/c13d7c18-3003-11e7-9986-44dc338b4d4d.png)


    3 error(s) occurred:

    * module.masters.aws_elb.api-external: "name" cannot be longer than 32 characters: "testing-long-cluster-name-api-external"
    * module.masters.aws_elb.api-internal: "name" cannot be longer than 32 characters: "testing-long-cluster-name-api-internal"
    * module.masters.aws_elb.console: "name" cannot be longer than 32 characters: "testing-long-cluster-name-console"

I think the real fix is to not create super-long elb names.

**Comment by Quentin-M** [comment]
Can truncate the cluster name using something like:

```
${replace(var.tectonic_cluster_name, "/(.{0,20})(.*)/", "$1")}
```

**Comment by ggreer** [comment]
Alright, now master supports names up to 28 chars and we correctly validate the length & restrictions in the UI.
