### ISSUE TITLE
Allow contributions that are not generic

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#430]
I propose creating a `contrib` folder and contribution guidelines/framework that can be useful to the community. This would be very helpful for on-premise users that can have various different IPAM, LoadBalancer, Firewall solutions. 

User story; I am using a DNS solution that is supported by Terraform. I would like to use DNS provider along with the openstack deployment to enhance my tectonic deployment experience.

**Comment by philips** [comment]
This seems like a reasonable idea. As long as we create a policy of contrib deprecation after say 6 months of merging. Either it merges into the mainline as a feature or we drop it.
