### ISSUE TITLE
AWS: Better naming for resources

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#435]
We need better naming for all the resources like: subnets, security groups, etc... 

Today it's really hard to manage and know which resource belongs to which cluster (i.e. use `mycluster-worker-subnet-1` instead of them all having the same name `mycluster`).

**Comment by s-urbaniak** [comment]
while naming is an orthogonal issue, I believe that https://github.com/coreos/tectonic-installer/pull/776 already helps.

I will iterate through all created resources and apply the following scheme:

```
<clustername>-<resource_type>[-<instance_count>]
```

**Comment by alexsomesan** [comment]
May I argue that adding the type of the resource to the name could be a bit redundant?

Type is usually inferred by the way the resource is accessed:
- in terraform fully qualified resource names include type: `module.vpc.aws_subnet.worker_subnet`
- in the AWS cli, the operation encodes the type to be accessed: `aws ec2 describe-subnets`
- AWS client libraries encode resource type in the method name: `ec2_client.DescribeSubnets()`

**Comment by s-urbaniak** [comment]
@alexsomesan the referencing PR #807 doesn't change the naming scheme, just adds some missing tags on created resources. I agree that the resource type doesn't need to be part of the name.
