### ISSUE TITLE
AWS: `terraform destroy` uses whatever region in your env

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#447]
The following can lead to confusing/devastating outcomes:

1. Do some other random Terraform work and set your AWS Region env var to `region A`
1. Install with GUI installer into AWS `region B`
1. Attempt to destroy cluster created in previous step using CLI

Since we don't store the region in the TF state, TF will attempt to use `region A`. A user would expect it to use `region B`.

**Comment by s-urbaniak** [comment]
There is unfortunately not much we can do on the terraform side of things, as this variable is not configurable withing `*.tf` files.

**Comment by sym3tri** [comment]
I think we need to make it a variable in the tfvars file and stop relying on the environment variable. It causes way too much confusion and everyone that's tested it so far gets this wrong.

**Comment by robszumski** [comment]
Can we somehow log the non-secret bits of the credentials it is at least trying to use?

**Comment by sym3tri** [comment]
@robszumski in this case *we* is the maintainers of Terraform

**Comment by chancez** [comment]
https://www.terraform.io/docs/providers/aws/#example-usage makes it seem like this is doable. Do we not control the definition of the `aws` provider block, even after we unfork it?

**Comment by Quentin-M** [comment]
We will discuss this tomorrow at the eng sync.

**Comment by Quentin-M** [comment]
We already are using a vanilla TerraForm. There's no fork.

**Comment by s-urbaniak** [comment]
Whops, ignore my comments above, it seems we can indeed preset the region as documented in https://www.terraform.io/docs/providers/aws/#example-usage, great catch @chancez!
