### ISSUE TITLE
TLS support for self-hosted etcd

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#458]

**Comment by xiang90** [comment]
xref: https://github.com/coreos/etcd-operator/issues/1010

**Comment by s-urbaniak** [comment]
@sym3tri I am concerned by the deadline of this issue, as upstream has not released TLS support yet. Can you give me some hint what I can do in up-front here?

**Comment by xiang90** [comment]
It is about 1-2 weeks away from getting this done in the upstream etcd operator.

**Comment by Quentin-M** [comment]
dup of https://github.com/coreos/tectonic-installer/issues/1113.
