### ISSUE TITLE
Bare-Metal UI Cleanup

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#461]
Overall usability.

@ggreer please fill out details here.

**Comment by ggreer** [comment]
There's still lots of low-hanging fruit in the baremetal UI flow, but I think it'd be best to create specific issues for those things. eg: making masters/workers lists in the UI instead of "enter number of masters" then clicking next and getting that many inputs.

**Comment by ggreer** [comment]
#603 fixes a lot of this.

**Comment by sym3tri** [comment]
@kyoto can handle this one

**Comment by Quentin-M** [comment]
@ggreer Is there any other UI cleanup we want to do here? Can we close that one?

**Comment by Quentin-M** [comment]
I haven't heard anything from either the UI team or from the product team (asked offline) regarding to further cleanup. Closing. Feel free to open specific issues if needed.
