### ISSUE TITLE
GUI: Make destroying clusters way easier

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#462]
This needs a concrete plan before we can execute, but this needs to be easier for GUI users.

**Comment by ggreer** [comment]
https://github.com/coreos/tectonic-installer/pull/442 helped a ton, though exposing previously-created clusters in the UI is another can of worms.

**Comment by robszumski** [comment]
Two parts of this:

### Tell you that we've saved state

Now that we're saving state automatically, it's not a critical that you manually download it. We can minimize the visual hierarchy of the existing buttons, and instead inform you of the location on disk.

 - downplay the existing "save assets" buttons
 - output file path (maybe on the submit step?)
 - update manual instructions after you provide config but not submit. output the file path here too.
 - docs on what is in the state file? are there secrets?
 - docs on how to store the state file

### Add option to delete via GUI

Allow a user to provide a state file, and have the installer remove the cluster. Output is identical to the progress we already have to destroying a cluster. This would be a top-level action at the beginning, when you open the installer.

question: when we store session info in the browser, can we list out all of the clusters that have been booted with this computer? Use this to populate a list of clusters to destroy? We would have to verify that the files still exist on disk where we put them.

 - add option in beginning. complete list is:
   - install with GUI
   - install with CLI
   - destroy existing cluster
 - screen to input the state
   - is this a path on disk?
   - do you upload the directory?
   - if the directory contains incorrect absolute paths, can we correct them for you automatically?
 - screen to check state

**Comment by meghanschofield** [comment]
#### Chose Installation Type - starting screen / default state
- Two paths a default for installing new, and choosing your platform (matches the current drop down) 
- Another for destroying an existing or partly made cluster. 

![installer_version](https://cloud.githubusercontent.com/assets/3373315/26079905/4338575a-3979-11e7-80a6-55ee8d738f15.png)

#### Choose Installaion type - destroy a cluster

- Pre-populate a drop down of existing clusters to destroy (talking with @ggreer this may not be easy, but is doable! It'd make this option pretty easy!)
- If for some reason the user can't find the cluster they need to destroy in the drop down, then we give them an option to upload. There is a text link to initiate an update of a cluster config file. 

![installation type_destroy cluster](https://cloud.githubusercontent.com/assets/3373315/26081353/40bc6af6-397f-11e7-9ff0-cb62337dfbe2.png)

A few things to note - new updates:
- Now with a CoreOS topper and a few bits from the nav. 
- Tectonic docs link is included in the nav
- Version is revealed in the nav bar, top right
- Data collection note lives at the bottom, on all pages. 

I'll make an issue to call this stuff out separate from this.

**Comment by ggreer** [comment]
To destroy a cluster, you need the following artifacts:

- The tfvars used to create the cluster. (currently in assets)
- The terraform modules & templates used to create the cluster. (currently in assets)
- The tfstate file. (currently in assets)
- The environment variables set by the backend (eg: AWS credentials). **This is currently not saved anywhere by the installer**
- The *exact* version of terraform that was used to create the cluster. Newer versions of terraform are unlikely to work. This is also not currently saved in assets, but it is bundled with the installer.

**Comment by sym3tri** [comment]
moved to PROD-230
