### ISSUE TITLE
Consolidate all images to quay.io

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#463]
Images we don't manage should be mirrored to quay.io. Currently not on quay.io:

- [ ] busybox (via flannel: https://github.com/coreos/tectonic-installer/blob/3ac7f7519ee071f04e621a4ae38ca0e88b8f82c3/modules/bootkube/resources/manifests/kube-flannel.yaml)
- [ ] gcr.io/google_containers/pause
- [ ] gcr.io/google_containers/heapster
- [ ] gcr.io/google_containers/addon-resizer
- [ ] gcr.io/google_containers/nginx-ingress-controller
- [ ] gcr.io/google_containers/k8s-dns-kube-dns-amd64
- [ ] gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64
- [ ] gcr.io/google_containers/k8s-dns-sidecar-amd64

**Comment by philips** [comment]
cc @colhom

**Comment by colhom** [comment]
related #779

**Comment by Quentin-M** [comment]
We now have an intern working on integrating Quay Security Scanning / [Clair](https://github.com/coreos/clair) with Tectonic. Every images that come from Quay will be supported.

**Comment by Quentin-M** [comment]
We will need an automated job to do that.

**Comment by sym3tri** [comment]
moved: https://coreosdev.atlassian.net/browse/INST-192
