### ISSUE TITLE
azure: etcd machines are on the Internet and the VMs have a static password

### ISSUE THREAD

**Issue by colemickens** [coreos/tectonic-installer#464]
If I'm reading the Terraform correctly, this is putting etcd on the Internet. Is this intentional? Why public over an internal LB for etcd?

https://github.com/coreos/tectonic-installer/blob/master/modules/azure/etcd/lb.tf#L14

Also, is it intentional that the admin password is hardcoded? Is that just for ease of access since SSH isn't exposed to the internet for those machines?

https://github.com/coreos/tectonic-installer/blob/9bdb83ee488c798ee1760dd3ff3854fd3be86179/modules/azure/etcd/etcd.tf#L33

**Comment by s-urbaniak** [comment]
@colemickens The current state of the azure platform is work-in-progress. We plan to stabilize this platforms more. As far as I see @metral and @sozercan working on improving it gradually already.
