### ISSUE TITLE
GUI: Improve license upload

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#470]
The installer refers to "coreos-license.txt" when it is downloaded from the account site as "tectonic-license.txt".

The placeholder text is very confusing, as it looks like the required info is there. This text color needs to be lightened to make it more clear. I think we're using browser defaults, but you can also [customize it](https://stackoverflow.com/questions/2610497/change-an-html5-inputs-placeholder-color-with-css) to #AAAAAA per mocks.

**Comment by ggreer** [comment]
Fixed in #578.
