### ISSUE TITLE
Re-implement smoke tests for bare-metal

### ISSUE THREAD

**Issue by dghubble** [coreos/tectonic-installer#479]
Tectonic is using a new Jenkins and terraform now. The previous Tectonic Bare-Metal GUI smoke tests cannot run.

- [x] jenkins-tectonic-installer has multiple bare-metal executors
- [x] smoke tests run `terraform apply` metal configs on every PR

**Comment by Quentin-M** [comment]
Waiting on https://github.com/coreos/tectonic-installer/pull/521.

**Comment by Quentin-M** [comment]
Fixed, hence closing.
