### ISSUE TITLE
Move all the scripting from the jenkinsfile into a bash script or Makefile

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#485]
Right now it is a pain to reproduce Jenkins builds locally.

All of this logic should be executable locally:
https://github.com/coreos/tectonic-installer/blob/master/Jenkinsfile

**Comment by squat** [comment]
Almost all of this was addressed by https://github.com/coreos/tectonic-installer/pull/930. Will look into cleaning more today.

**Comment by Quentin-M** [comment]
I feel like this is pretty much done as of today. https://github.com/coreos/tectonic-installer/pull/1085 will help further with the initial goal of this issue.
