### ISSUE TITLE
Standardize labels for k8s/tectonic components

### ISSUE THREAD

**Issue by aaronlevy** [coreos/tectonic-installer#489]
There are quite a few variations of how we are identifying applications by label: "app", "k8s-app", "k8s-addon", "operator", "component". This could make inspecting cluster state difficult later on -- we should try and standardize how we identify applications we are managing.

It looks like upstream somewhat standardizes on two sets of identifiers, a "control-plane" component, and addon applications.

**For control-plane:**

```
tier=control-plane
component=kube-scheduler
```
[example](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest#L199-L202)

**For addons:**

```
k8s-app=kube-dns
```
[example](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kubedns-controller.yaml.base#L26)
Note: the other labels are for addon-manager which we do not use (one of which is [deprecated](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/kube-addons.sh#L44-L48) anyway)

## Proposal:

We standardize on the same labels as upstream.

For the core k8s components (etcd, api, scheduler, controller-manager, proxy) we use the `tier`/`component` label keys.

For all other applications we use `k8s-app`.

**Comment by philips** [comment]
There has been some talk of creating a k8s.io/labels project. If someone wants to take that on upstream.

**Comment by philips** [comment]
Overall this makes sense to me.

A lingering concern in my mind is using k8s-app in such a way that would conflict with a change upstream.

**Comment by aaronlevy** [comment]
Couple clarifying points:

kube-proxy would get `tier=node` (all other core components are `tier=control-plane`)

We could also add the `tier` to tectonic components (`tier=monitoring` for example).

@philips we could do k8s-app for upstream addons (dns, heapster, HPA, etc.) but use `tectonic-app` for all others?

Ref: upstream change: https://github.com/kubernetes/kubernetes/pull/24293

**Comment by sym3tri** [comment]
SGTM
Need to validate with @xiang90 and @fabxc that labels are not relied on by etcd or Prometheus operators first.

**Comment by sym3tri** [comment]
@aaronlevy do you also want to label ConfigMaps & Secrets etc? Or just DaemonSets and Deployments and Services? Or all of the things?

**Comment by aaronlevy** [comment]
Another option to mitigate conflicts would be doing something like `component=coreos.com/prometheus` that way we're namespacing the value but keeping a consistent key.

However, it's also worthwhile to note that labels are namespaced -- so we may be able to make some assumptions about what exists (or could conflict) with a label in `kube-system` and `tectonic-system`.

One more note - `k8s-app` seems a little redundant and maybe we wholesale replace it with `component=` even for upstream addons (this just means we need to make sure to keep correct label when updating manifests). It seems k8s-app might be an older vestige anyway (but maybe need to confirm): https://github.com/kubernetes/kubernetes/issues/21267#issuecomment-185236752

So that would mean my proposal would be:

use the key `component=` for identifying the application (I don't have strong opinions about needing a prefix for our components, but assuming we "own" `kube-system` and `tectonic-system` might be enough?)

Tier would be optional to define - if we thought it might have value. e.g.:

```
kubectl get pods -l 'tier in (control-plane, monitoring)'
```

**Comment by aaronlevy** [comment]
@sym3tri I think if a configMap / secret directly maps to a component, it would make sense to have that consistency, no?

**Comment by aaronlevy** [comment]
Also cc @derekparker @yifan-gu @diegs for thoughts on KVO/TCO/lifecycle side

**Comment by aaronlevy** [comment]
From grepping the kubernetes code-base, the one issue with existing addons (heapster, dns, et-al) is that the e2e tests expect the `k8s-app` label. So just to keep our lives simpler for e2e tests passing, lets leave those alone but use `component` for everything we control.

**Comment by fabxc** [comment]
This should not break us yet but is relevant for changes we additions we are about to make.
@brancz

**Comment by brancz** [comment]
I have actually taken this [upstream](https://github.com/kubernetes/kubernetes/issues/42887) before, I'd be happy to get any standardization we can, what that looks like at the end doesn't really matter to us. This would require us to change the labeling of the node-exporter as we deploy it currently, but other than that it's not very invasive.

Note that some components such as the [rescheduler](https://github.com/kubernetes/contrib/blob/master/rescheduler/rescheduler.go#L142) somewhat rely on the k8s-app label.

**Comment by aaronlevy** [comment]
Seems like the rescheduler relies on it for metrics: https://github.com/kubernetes/contrib/blob/a7a8d35c6b6bfacb500368e974f1cb56fa0706c4/rescheduler/rescheduler.go#L141-L145

I also don't have strong feelings about the key itself -- I just would like there to be some consistency.

Do we just go for `k8s-app` across the board?

**Comment by aaronlevy** [comment]
fwiw I'll bring bootkube inline with whatever is decided upon here. Almost anything is better than 6 different keys.

**Comment by hongchaodeng** [comment]
@aaronlevy 

Does it mean we need to add labels to self hosted etcd pods:
```
tier=control-plane
component=kube-etcd
```

**Comment by aaronlevy** [comment]
@hongchaodeng I've reversed my thoughts on this -- for the path of least resistance I'm now advocating that we just use `k8s-app=foo` for the label to identify a component.

This is because e2e tests expect this for some addons, and rescheduler also expects this for metrics. If we introduce a different label it means we have to use `k8s-app` for some components and ours for others -- which doesn't get us much in my option.

**Comment by aaronlevy** [comment]
@hongchaodeng it looks like etcd-operator expects `app=etcd` (from a quick grep). So the change would hypothetically be changing that to `k8s-app` for consistency. Not necessarily a deal-breaker (and I'd still prefer we try for as much consistency as possible).

**Comment by hongchaodeng** [comment]
> etcd-operator expects app=etcd

That's etcd-operator's internal logic.

> So the change would hypothetically be changing that to k8s-app for consistency.

We could just add a new set of labels. It's orthogonal.

**Comment by aaronlevy** [comment]
I guess in etcd's case, yes that's true (because pods being directly managed by etcd-operator, not deployment/replicaset). When you change the selector on deployments -- things can get a little wonky / in the past this has lead to orphaned pods during updates (and why I'd rather not introduce many changes here).

**Comment by Quentin-M** [comment]
@aaronlevy @philips @sym3tri If it needs to happen TODAY for the release, can we all agree on a scheme?

- What do we use for bootkube manifests? Here is what we currently have:
```
kube-apiserver: {tier: control-plane, component: kube-apiserver}
kube-controller-manager: {tier: control-plane, component: kube-controller-manager}
kube-scheduler: {tier: control-plane, component: kube-scheduler}
kube-proxy: {tier: node, component: kube-proxy}
kube-dns: {k8s-app: kube-dns, kubernetes.io/cluster-service: "true", kubernetes.io/name: "KubeDNS"}
kube-flannel: {tier: node, app: flannel}
pod-checkpointer: {tier: control-plane, component: pod-checkpointer}
etcd-operator: {k8s-app: etcd-operator}
kenc: {tier: control-plane, component: kube-etcd-network-checkpointer}
bootstrap-etcd: {k8s-app: boot-etcd}
```

Notably, notice the inconsistency on kube-flannel (tier, app).

- What do we use for Tectonic manifests? Here is what we currently have:
```
tectonic-console: {app: tectonic-console, component: ui}
container-linux-update-operator: {app: container-linux-update-operator}
heapster (kube-system!): {k8s-app: heapster, kubernetes.io/cluster-service: "true"}
tectonic-identity: {app: tectonic-identity, component: identity}
tectonic-ingress-controller: {app: tectonic-lb, component: ingress-controller, type: nginx}
tectonic-ingress (ingress type): {}
default-http-backend: {app: default-http-backend}
tectonic-stats-emitter: {app: tectonic-stats-emitter, component: stats-emitter}
node-exporter: {app: node-exporter}
prometheus-operator: {operator: prometheus}
kube-version-operator: {k8s-app: kube-version-operator}
node-agent: {k8s-app: node-agent}
tectonic-channel-operator: {k8s-app: tectonic-channel-operator}
tectonic-prometheus-operator: {k8s-app: tectonic-prometheus-operator}
```

These are just the statically declared manifests. Probably have some others that I missed and that are created by operators (kube-etcd, prometheus, ...). And then there is all the services and ConfigMaps too, TPRs, etc..

**Comment by aaronlevy** [comment]
Is there any objection to just using `k8s-app`?

**Comment by Quentin-M** [comment]
Please see https://github.com/coreos/tectonic-installer/pull/517 and my comment above.

**Comment by aaronlevy** [comment]
I'm fine with all bootkube assets using `k8s-app`. For tectonic it looks like they're already mostly `app` and `k8s-app` already -- so it would just be changing `app` to `k8s-app`. Then for prometheus-operator we could be additive: `k8s-app=prometheus-operator, operator:prometheus` but I'd defer on that

**Comment by sym3tri** [comment]
@euank will changing labels affect any of the CLUO stuff?

**Comment by euank** [comment]
CLUO uses `app` as an identifying field right now for the managed agents, so that would have to be renamed/migrated to `k8s-app` during an upgrade. That shouldn't be any real problem.

Changing the label on the operator deployment itself won't make any difference to it.

**Comment by hongchaodeng** [comment]
@aaronlevy 
Is it final that all core components will have `k8s-app` label?

**Comment by aaronlevy** [comment]
@hongchaodeng that looks to be the plan.

**Comment by aaronlevy** [comment]
@hongchaodeng but changing for etcd operator might be more risky for existing clusters -- so if you need to leave it, not a huge deal (I'm just hoping we reduce the label skew as much as we can, but doesn't have to be 100%)

**Comment by pbx0** [comment]
@aaronlevy So I think either we can change the etcd-operator, vendor it into bootkube, release, use that in Tectonic before submitting the label change PR or we can just let etcd pods be an outlier for now and not chance the label selector on that service file.

**Comment by aaronlevy** [comment]
It wouldn't matter if we vendored it - the thing creating the pods is the operator running in the cluster.

I don't think the change will make it in prior to the release - so maybe we just leave etcd out

**Comment by pbx0** [comment]
Oh true, OK will drop any change to etcd pods for now.

**Comment by hongchaodeng** [comment]
@aaronlevy @pbx0 
It doesn't have to change in etcd operator.
There is an option to set custom labels for etcd pods: [code link](https://github.com/coreos/etcd-operator/blob/8345fe07fe703411227fb193641178e0532946b7/pkg/spec/cluster.go#L123).

**Comment by aaronlevy** [comment]
@hongchaodeng is that additive to the labels already applied? e.g. would we end up with:

```
app=etcd
k8s-app=etcd
```

Or does that override the labels?

**Comment by hongchaodeng** [comment]
@aaronlevy 
It's merge.
merge strategy:
- If it's "app", "etcd_*", the TPR spec will be rejected.
- otherwise, merge custom labels onto existing labels.

So it will end up with both.

**Comment by sym3tri** [comment]
fixed in https://github.com/coreos/tectonic-installer/pull/517
