### ISSUE TITLE
Use cluster name in generated kubeconfig contexts/cluster

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#512]
Currently generated kubeconfigs use generic names like "local" instead of the cluster name given. This makes it very tough to know what credentials go to specific clusters.

cc: @soggiest

**Comment by soggiest** [comment]
This will be beneficial for users who are building out multiple clusters. We're already experiencing users who have to shift their kubectl context frequently. Having kubeconfig name it's context appropriately will save these users the step of renaming their context's manually and avoid confusion in the future for those users who might just be getting into a multi-cluster kubernetes environment.

**Comment by sym3tri** [comment]
this is done now
