### ISSUE TITLE
document how to run each platform using the Tectonic installer

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#52]
Due by 3/24. Docs should be in this repo somewhere.

Will essentially be:
- download installer
- create a `config.json` file & fill it out
- run with special subcommand, something like `./installer asset-gen --platform=azure --input=config.json`
- `cp assets.zip` into sdk folder
- `unzip assets.zip`
- run `./terraform apply`

**Comment by s-urbaniak** [comment]
@sym3tri Closing this issue as things have moved on far since it was created. Feel free to reopen/create a new issue if anything is missing.
