### ISSUE TITLE
ETCD Self-hosted Operator doesn't use custom cluster CIDRs

### ISSUE THREAD

**Issue by soggiest** [coreos/tectonic-installer#535]
Version: 1.6.2
Installation Method: AWS Terraform

Expected Results: If non-standard Pod and Service CIDRs are entered into the Web UI the self-hosted ETCD operator would create the ETCD services using the defined CIDR to determine the proper ClusterIP of the service.

Observed Results: When non-standard Pod and Service CIDR's are entered into the Web UI the self-hosted ETCD operator attempts to create the ETCD service using a default value for the ClusterIP of `10.3.0.15`
```
May 03 23:43:52 ip-10-252-227-66 bash[6936]: [ 1670.453676] bootkube[5]: E0503 23:43:52.116072       5 create.go:34] Error creating assets: error when creating "/assets/manifests/etcd-service.yaml": Service "etcd-service" is invalid: spec.clusterIP: Invalid value: "10.3.0.15": provided IP is not in the valid range
May 03 23:43:52 ip-10-252-227-66 bash[6936]: [ 1670.453941] bootkube[5]: Error creating assets: error when creating "/assets/manifests/etcd-service.yaml": Service "etcd-service" is invalid: spec.clusterIP: Invalid value: "10.3.0.15": provided IP is not in the valid range
May 03 23:43:52 ip-10-252-227-66 bash[6936]: [ 1670.454225] bootkube[5]: NOTE: Bootkube failed to create some cluster assets. It is important that manifest errors are resolved and resubmitted to the apiserver.
May 03 23:43:52 ip-10-252-227-66 bash[6936]: [ 1670.454495] bootkube[5]: For example, after resolving issues: kubectl create -f <failed-manifest>
```

Additional Info:
 "podCIDR": "172.16.0.0/16",
 "serviceCIDR": "192.168.128.0/20",

**Comment by s-urbaniak** [comment]
If the user enters a custom service CIDR, then we need to handle this the same way as `tectonic_kube_apiserver_service_ip` and `tectonic_kube_dns_service_ip`, namely choosing some value from the custom CIDR for `tectonic_kube_etcd_service_ip`.
