### ISSUE TITLE
Installation hangs on null_resource.kubeconfig

### ISSUE THREAD

**Issue by leader716** [coreos/tectonic-installer#537]
When attempting to run through the installation process on some bare metal hosts. I run into the issue where the installation process would hang on the null_resource.kubeconfig.* step and it would timeout after an hour. I know that during this process, this is when the installer is waiting for the host installation to complete. Once complete the kubeconfig is copied to the hosts via ssh.

It appears that the installer can't connect to the hosts via ssh. On the Container Linux host I can see auth failures repeated until the process times out. In my configuration file, I have provided a public key and i can ssh to the hosts after the process times out.

**Comment by dghubble** [comment]
Is this with the graphical installer or running terraform apply manually? What's your local SSH key setup?

In the graphical installer, terraform runs in it's own env and we fixed an issue to pass SSH_AUTH_SOCK (Yubikeys, etc.). Otherwise, I believe terraform looks for common key locations. What version of this repo did you try?

**Comment by leader716** [comment]
I was running terraform manually. I am able to ssh directly to the servers using the public key/private key properly. I was using the latest master.

**Comment by dghubble** [comment]
If you run `ssh-add -L` do you see your public key? If not, https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

**Comment by coreypobrien** [comment]
It appears Terraform uses ssh-agent, so if it isn't configured or available, the only options attempted are the `password` or `private_key` provided in the `connection` block. The key lookups that the openssh client does (e.g. `~/.ssh/id_rsa`) don't happen.

PR https://github.com/coreos/tectonic-installer/pull/625 adds an optional variable to specify the `private_key` in cases where ssh-agent isn't available.

**Comment by steigr** [comment]
I had the same problem (using GUI installer). I got rid of it by removing all unneeded identities from the ssh-agent instance. (`ssh-add -D; ssh-add ~/.ssh/id_ed25519`)

**Comment by zendeavor** [comment]
Confirming this issue affected me as well. I wasn't running ssh-agent at all, so once I started it up on the system from where I'm running the tectonic installer and pointed it toward my key, kubeconfig was able to do its work.

**Comment by robszumski** [comment]
Added a tracking issue for documentation improvements here: https://github.com/coreos/tectonic-installer/issues/1078

We can keep this open until that lands.

**Comment by alexandrufulop** [comment]
more clear info here: https://github.com/coreos/tectonic-installer/issues/1078

**Comment by dghubble** [comment]
Closing as #1078 documents this as a requirement.
