### ISSUE TITLE
docs: guide for jumping from GUI to CLI for AWS

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#552]
Guide users on how to use the GUI as a config generator, but then use the CLI to complete the installation. We will link to this guide on the "manual boot" screen that you can select instead of submitting your config.

Topics:
 - download assets
 - set up env vars, path, etc
 - terraform plan
 - terraform apply
 - access the cluster
 - link to destroy docs

**Comment by zbwright** [comment]
The ask is to generate a doc that users can access after having walked through Tectonic Installer to the Submit page. Using the GUI as a config generator is just an opening sentence. This doc will explain how to do the things listed above.
Link out from here: 
![installer-submit](https://cloud.githubusercontent.com/assets/9601502/25758951/5a641aa0-3185-11e7-879b-281ca6f5a706.png)

**Comment by robszumski** [comment]
Quick correction, you actually get linked out from this screen, which is where you land after clicking the link:

![image](https://cloud.githubusercontent.com/assets/755540/25818321/1a45534c-33df-11e7-87b2-62438472b225.png)

**Comment by sym3tri** [comment]
Need to include a blurb about what type of changes we support in the product:
Only changes to underlying infrastructure only... changes to Kubernetes manifests or Tectonic components run in the cluster are not supported.

**Comment by ggreer** [comment]
Now that #633 has been merged, it looks like this:
![screen shot 2017-05-10 at 11 14 45](https://cloud.githubusercontent.com/assets/200121/25914100/ef1d6288-3571-11e7-8b8f-7771f9443034.png)

The link is to https://coreos.com/tectonic/docs/latest/install/aws/manual-boot

**Comment by robszumski** [comment]
@ggreer with a `.html` on the end?

**Comment by robszumski** [comment]
This doc merged in https://github.com/coreos/tectonic-installer/issues/594
