### ISSUE TITLE
Add Kubernetes client into progress screen to track pod/component statuses

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#561]
Give more rich feedback about when containers are downloading and launching.

**Comment by amrutac** [comment]
Blocked on https://github.com/coreos/tectonic-installer/issues/726

**Comment by robszumski** [comment]
I thought this was going to hit the Kubernetes API for this info, not rely on log parsing, hence not blocked on #726?

**Comment by Quentin-M** [comment]
@robszumski Correct.

**Comment by Quentin-M** [comment]
I just assigned this one to @LyonesGamer as a first project since this is pretty independent and contains both frontend / backend work. @kans and myself can guide/help on frontend / backend respectively!

**Comment by Quentin-M** [comment]
As mentioned offline, the general idea is to split the "Waiting for Console" spinner into several spinners for individual components.

- we can provide you a list of pods / resources we'd like to monitor when you get there
- you will have to implement a backend API endpoint to monitor these pods / resources
- this endpoint will need both the Kubernetes API address (available from the Terraform variables for instance) and the kubeconfig (available in the executor's folder) to be able to query the resources
- the frontend will have to periodically call this new backend API and update the spinners 

This is an example that uses the Kubernetes client in Go to list the pods https://github.com/coreos/tectonic-installer/blob/63d5148/tests/smoke/cluster_test.go#L37. There are many examples out there (e.g. in our operators!).

**Comment by robszumski** [comment]
From the UX side, @tlwu2013 will attach mocks to this issue shortly

**Comment by sym3tri** [comment]
@LyonesGamer I thought this merged. Please close if complete.

**Comment by LyonesGamer** [comment]
@sym3tri It has not yet merged. It is still waiting review, and is still blocked on a different PR that has not yet merged. #1192
