### ISSUE TITLE
Add progress bars to progress screen

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#562]
For the apply step, this will be timed to the average deploy time and stop at 80% if we run over. This is because Terraform gives us no status info.

For downloading and starting pods, we will use the embedded Kubernetes (https://github.com/coreos/tectonic-installer/issues/561) client to measure progress.

**Comment by sym3tri** [comment]
@robszumski this will be hard b/c avg deploy time will vary depending on many variables, like region, instance type, internet connection, etc.

**Comment by meghanschofield** [comment]
The progress bar is 4px tall, with rounded ends. 

<img width="785" alt="screen shot 2017-06-22 at 3 07 15 pm" src="https://user-images.githubusercontent.com/3373315/27459107-7b45fffc-5761-11e7-96ac-06e18e284e4e.png">

Green = #2FC98E  
Gray = #E5E5E5

Placment:
<img width="857" alt="screen shot 2017-06-22 at 3 10 35 pm" src="https://user-images.githubusercontent.com/3373315/27459129-9073825a-5761-11e7-9f9b-7016bc449350.png">

The bar moves to the active step:
<img width="462" alt="screen shot 2017-06-22 at 3 45 04 pm" src="https://user-images.githubusercontent.com/3373315/27459184-ccd4c5ce-5761-11e7-948b-af7c696ace0d.png">

Ping me with questions! I'm happy to add callouts or explain behavior if it's unclear.
