### ISSUE TITLE
Tectonic installer should recommend etcd configuration based on etcd upstream hardware recommendation docs

### ISSUE THREAD

**Issue by chancez** [coreos/tectonic-installer#563]
The etcd team has published recommended specs for etcd nodes and disks: 
 https://coreos.com/etcd/docs/latest/op-guide/hardware.html which the installer should use.

The installer should link to this doc, and probably recommend good defaults based on the number of nodes in the cluster. If the user knows how many pods they'll be running they can read the doc to determine the best configuration as well. Maybe the installer could have the number of pods as an optional field to be used when setting default values.

I think it may also be a good idea to link to the document in the example tfvars files as a comment. If a user is changing the values post-install, or if they're running Terraform directly, then this ensure's they will see this doc and may choose to use it as a guideline for making their changes.

**Comment by sym3tri** [comment]
/cc @robszumski 

There are a few things we should potential do here (in order of effort):
1. Link to etcd docs in TF comments
1. Link to etcd docs from Tectonic docs
1. Link to etcd docs in installer GUI
1. Add contextual clues in the GUI for recommended production configurations (master/etcd node count, instance types, disk types, etc)

**Comment by robszumski** [comment]
Executing on 1-3 seems like a no brainer

**Comment by amrutac** [comment]
@robszumski: Should   [this](https://coreos.com/etcd/docs/latest/op-guide/hardware.html) go on the nodes definition page?

**Comment by robszumski** [comment]
@amrutac yeah, under the etcd section of you choose to boot those as VMs. We can pair on the text/placement when you are ready to pick this up.

**Comment by Quentin-M** [comment]
See https://github.com/coreos/tectonic-installer/pull/1145

**Comment by amrutac** [comment]
Completed in https://github.com/coreos/tectonic-installer/pull/1145
