### ISSUE TITLE
all: have flag to enable self-hosted etcd

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#57]
Once https://github.com/coreos-inc/tectonic-installer/pull/31 merges we should have a `tectonic_` flag to enable self-hosted etcd.

Thoughts @Quentin-M ?

**Comment by sym3tri** [comment]
done in https://github.com/coreos/tectonic-installer/pull/135

**Comment by wking** [comment]
Support was removed in #2648 (for anyone else digging through the Git history trying to figure out where this feature went ;).
