### ISSUE TITLE
Ship tectonic-monitoring 1.2.0

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#579]
https://github.com/kubernetes/kube-state-metrics

In the 0.5 release, the ability to track labels on pods and other objects was added:

```
Add label metrics for Pods, Nodes and Services.
```

This will help us power use-cases like chargeback.

**Comment by fabxc** [comment]
kube-state-metrics 0.5 will be part of the iteration of the monitoring subsystem.

**Comment by brancz** [comment]
yes already in progress https://github.com/coreos-inc/tectonic-prometheus-operator/pull/49 should go out in the upcoming days

**Comment by sym3tri** [comment]
Is there explicit work required for the installer, or just bump the prom operator?

**Comment by brancz** [comment]
Once we finalize the tectonic-monitoring 1.2.0 we'll sync the manifests in this repo, so no explicit work needed.

**Comment by sym3tri** [comment]
OK, I'll rename the issue to reflect that.

**Comment by sym3tri** [comment]
@fabxc @brancz How close is this? Will it be ready for us to test on Thursday? Friday is code freeze.

**Comment by brancz** [comment]
@sym3tri we sadly had a few set-backs namely https://github.com/coreos/prometheus-operator/pull/367 and https://github.com/prometheus/prometheus/pull/2731. We plan on releasing both today and then hopefully by the time you get to the office in SF we have the PR out to the tectonic-installer :wink: .

**Comment by brancz** [comment]
@sym3tri see https://github.com/coreos-inc/tectonic-prometheus-operator/pull/49.
