### ISSUE TITLE
By default set ":focus" on the first input field on every page, and pre populate user's ClusterName in DNS field.

### ISSUE THREAD

**Issue by tlwu2013** [coreos/tectonic-installer#589]
This is the issue ported from "Tectonic Issue #237": UI should clearly indicate what are required fields
https://github.com/coreos-inc/tectonic-issues/issues/237#issuecomment-299341439

In our internal discussions, since most of the input fields of Tectonic Installer are required, we therefore don’t call them out specifically.

To address the issue in #237, two things could help alleviate the problem:

**1. Place ":focus" on the first input field of the page.** 
       (this applies to all the Installer screens and all kinds of fields, such as "radio button", etc.)

**2. Populate user's "ClusterName" as domain name.**

See attached mock for details, thanks!
![may_8th_2017 _networking___default_focused_on_first_input_fields](https://cloud.githubusercontent.com/assets/5903705/25825326/80d5c0e8-33f7-11e7-9368-3e18b50f1a94.png)

**Comment by ggreer** [comment]
Default DNS was added in https://github.com/coreos/tectonic-installer/pull/615

**Comment by amrutac** [comment]
This has been implemented. Closing this
