### ISSUE TITLE
nightly builds & tests with latest bootkube master builds

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#597]

**Comment by Quentin-M** [comment]
This will be handled by the automation team.

**Comment by mxinden** [comment]
@Quentin-M Who is the automation team? Do you mean @cpanato and me?

**Comment by Quentin-M** [comment]
@mxinden That'd be me starting ~August.

**Comment by sym3tri** [comment]
@Quentin-M @mxinden closingthis out. @Quentin-M can you put into your backlog?

**Comment by Quentin-M** [comment]
@sym3tri Already.
