### ISSUE TITLE
integrate a testing plan to make adding new platforms easier

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#6]
It would be very helpful if we started to test the OpenStack and other installs on every merge of Tectonic. As we plan to add more platforms and expand platforms over the coming weeks this data will be useful as we try and define the overall architecture.

cc @ethernetdan @pbx0 @marineam

**Comment by mxinden** [comment]
Adding new platforms and maintaining existing once in terms of testing will be improved by #1445. If there are no objections I suggest closing here, once #1445 is merged.
