### ISSUE TITLE
terraform: upstream custom plugins

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#60]
Currently we rely on two custom plugins to Terraform, we need to upstream them ASAP.

- [x] [template_folder](https://github.com/coreos/terraform/commit/49250aaebcce191571a881374ea1a91500be61e7)
- [x] [localfile](https://github.com/hashicorp/terraform/pull/12757) adds the ability to provision files locally.

**Comment by philips** [comment]
@Quentin-M Can we set a deadline for this? I am thinking we should try and get all of the custom terraform plugins into upstream by April 20th, and if we can't get them in we need to find an alternative like generated terraform.

Having our tool require a patched Terraform will hurt adoption.

WDYT?

**Comment by Quentin-M** [comment]
- https://github.com/hashicorp/terraform/pull/12757
- https://github.com/hashicorp/terraform/pull/13652

**Comment by Quentin-M** [comment]
This is tracked by https://www.pivotaltracker.com/story/show/143699581.

**Comment by philips** [comment]
localfile is now merged.

**Comment by rmenn** [comment]
thanks for getting this out to terraform, template_folder is also merged

**Comment by sym3tri** [comment]
@Quentin-M both were merged. Reopen if I'm missing something.
