### ISSUE TITLE
Display container linux version on cluster settings page when up to date

### ISSUE THREAD

**Issue by rithujohn191** [coreos/tectonic-installer#619]
![screenshot from 2017-05-09 15-55-17](https://cloud.githubusercontent.com/assets/3858939/25876918/13b72fb8-34d5-11e7-8456-33803eed1f8a.png)

It would be nice for the user to be able to see the Container Linux version being used on the Cluster Settings page even when the version is the "latest". Displaying it on this screen would save the user the trouble of going to the node details page to figure out what version they are at.

**Comment by sym3tri** [comment]
This is a Console issue, not an installer issue.

@rithjohn191 can you please move to the other issue tracker?
