### ISSUE TITLE
Service IP addresses should use `cidrhost(tectonic_service_cidr, …)`

### ISSUE THREAD

**Issue by ggreer** [coreos/tectonic-installer#642]
`tectonic_kube_apiserver_service_ip`, `tectonic_kube_etcd_service_ip`, and `tectonic_kube_dns_service_ip` should all use [cidrhost()](https://www.terraform.io/docs/configuration/interpolation.html#cidrhost-iprange-hostnum-) instead of hard-coded default values.

Currently, the user must change all of those values if they want to use a different service cidr. Also, the frontend must calculate all those values.

**Comment by s-urbaniak** [comment]
This fall in the bucket "how much logic do we want in the tf templates", but I agree that is a neat idea.

**Comment by sym3tri** [comment]
Asking users to update these IPs manually is a recipe for frustration.
There's no current use-case for needing to override them. This I agree,
let's just do it in the templates unless there's a compelling reason not
to.

**Comment by alexsomesan** [comment]
This is a cool idea and should not be a complicated change.

@sym3tri The point @ggreer is trying to make is it actually would not require users to change anything in the template. It would just compute them when they are not provided in tfvars (like we do with subnets today). I think that's a neat usability improvement. It would unclutter the tfvars too.

**Comment by sym3tri** [comment]
I know. I was agreeing with him ;)

**Comment by alexsomesan** [comment]
Oh well, I guess I need to pay closer attention :) Sorry for causing confusion.
