### ISSUE TITLE
Terraform should bcrypt adminPassword

### ISSUE THREAD

**Issue by ggreer** [coreos/tectonic-installer#643]
Currently, the user has to provide the bcrypted, base64-encoded password. We also have to calculate this in the GUI. Doing this in terraform would make for a better experience for users.

**Comment by sym3tri** [comment]
Unfortunately that feature doesn't exist in Terraform Upstream. We could add it but it might take some time.

**Comment by ggreer** [comment]
OK. Until then, we can do it in JS.

**Comment by sym3tri** [comment]
@ggreer we have someone who will be adding this upstream soon.

**Comment by sym3tri** [comment]
Upstream PR https://github.com/hashicorp/terraform/pull/14725

**Comment by radeksimko** [comment]
Just FYI - the linked PR was just merged and will be part of 0.9.7 release.

**Comment by sym3tri** [comment]
@radeksimko Nice! Thanks for the update.

**Comment by Quentin-M** [comment]
Upstream was validated, the backend change can happen very quickly.

**Comment by Quentin-M** [comment]
It will take another 3 weeks for Terraform 0.9.10 to be released, which is likely be the next version we use. Pushing for now.

**Comment by radeksimko** [comment]
@Quentin-M there are no more `0.9` releases planned at this point. The next planned release is `0.10.0beta1`, but the `bcrypt` function was already released in 0.9.7 as mentioned in the changelog: https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#097-june-7-2017

**Comment by Quentin-M** [comment]
I guess that is what I meant, 0.10, not 0.9 :) Thanks for reaching out!

For what it's worth, we do not plan to update to 0.9.7 nor 0.9.8 as they both suffer from a [regression](https://github.com/hashicorp/terraform/issues/15177) in `template_file`, which we use quite a bit.

**Comment by radeksimko** [comment]
Understood, sorry for the regression. 🙈 

Just in case you missed this - there's a blogpost about planned changes which may affect you in 0.10:
https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/

**Comment by Quentin-M** [comment]
Thanks a lot! Truly appreciate it!
