### ISSUE TITLE
Terraform created a private route53 hosted zone, breaking DNS for other EC2 instances

### ISSUE THREAD

**Issue by rhenretta** [coreos/tectonic-installer#648]
I just installed 1.6.2 in AWS, and terraform created a 2nd hosted zone (private) for our domain, which caused our other EC2 instances to not be able to resolve hostnames defined in the original public hosted zone for the same domain name.  I was able to fix this by deleting the private hosted zone, and I don't see any obvious impact to the kubernetes cluster, but this has me concerned.  Is this expected behavior?

**Comment by coresolve** [comment]
From: http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html
```
Public and Private Hosted Zones that Have Overlapping Name Spaces
When you have private and public hosted zones that have overlapping name spaces, such as example.com and accounting.example.com, and users are logged into an EC2 instance in an Amazon VPC that you have associated with the private hosted zone, here's how Amazon EC2 handles DNS queries:

Amazon EC2 evaluates whether the name of the private hosted zone matches the domain name in the request, such as accounting.example.com. A match is defined as either of the following:

An identical match
The name of the private hosted zone is a parent of the domain name in the request. For example, suppose the domain name in the request is the following:
seattle.accounting.example.com
The following hosted zones match because they're parents of seattle.accounting.example.com:
accounting.example.com
example.com
If there's no matching private hosted zone, then Amazon EC2 forwards the request to a public DNS resolver, and your request is resolved as a regular DNS query.

If there's a private hosted zone name that matches the domain name in the request, the hosted zone is searched for a resource record set that matches the domain name and DNS type in the request, such as an A record for accounting.example.com.

Note
If there's a matching private hosted zone but there's no resource record set that matches the domain name and type in the request, Amazon EC2 doesn't forward the request to a public DNS resolver. Instead, it returns NXDOMAIN to the client.
```

**Comment by rhenretta** [comment]
The note is where the problem came in.  By creating the private zone, AWS ignored all the DNS records in the public zone inside my vpc.  So using tectonic to create the cluster inside an existing vpc just became very dangerous for all other resources in that vpc.

**Comment by coresolve** [comment]
Agreed I just pulled it in here for reference.

**Comment by s-urbaniak** [comment]
As discussed with @alexsomesan we will add the possibility to "bring-your-own" private zone instead of always creating one.

Suggested variable name: `tectonic_aws_external_private_zone`.

**Comment by evfurman** [comment]
+1 for this. At this point it's the only thing that's preventing us from completely transitioning to the terraform deploy. Do we have an ETA on when this would be merged?
