### ISSUE TITLE
add security vulnerability reporting doc

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#658]
This should go somewhere.

From an old closed PR:

```
##  Reporting a security vulnerability

Due to their public nature, GitHub and mailing lists are not appropriate places for reporting vulnerabilities. Please refer to CoreOS's [security disclosure][disclosure] process when reporting issues that may be security related.
 
[disclosure]: https://coreos.com/security/disclosure/
```

**Comment by zbwright** [comment]
@sym3tri which PR, please? I'd like to take a look at it to refresh my memory on this.

**Comment by zbwright** [comment]
I would like to add this to the CONTRIBUTING.md for all projects. thoughts?

**Comment by sym3tri** [comment]
@zbwright there are a lot of projects. Maybe just add to https://github.com/coreos/template-project for now. But I'd defer to @philips for approval on that.

**Comment by zbwright** [comment]
How about there and tectonic-installer?

**Comment by philips** [comment]
@zbwright if you add it to https://github.com/coreos/template-project/blob/master/CONTRIBUTING.md we can pull it into all of the projects.

**Comment by zbwright** [comment]
question: I think the materials already contained in this template should be re-organized slightly, and some headers changed. Will that break existing things?

**Comment by zbwright** [comment]
https://github.com/coreos/template-project/pull/10

**Comment by sym3tri** [comment]
@zbwright looks like the template one is good to merge. Please copy over to here once it is.

**Comment by sym3tri** [comment]
Should be ok WRT breakage.

**Comment by zbwright** [comment]
hey @sym3tri I don't know what you mean by 'copy it over to here'.

**Comment by sym3tri** [comment]
@zbwright once this merges: https://github.com/coreos/template-project/pull/10

You can copy the changes from here: 
https://github.com/coreos/template-project/blob/master/CONTRIBUTING.md

to here:
https://github.com/coreos/tectonic-installer/blob/master/CONTRIBUTING.md

**Comment by zbwright** [comment]
part 1 complete - changes added to template-project https://github.com/coreos/template-project/pull/10
part 2 in a PR: https://github.com/coreos/tectonic-installer/pull/1019

**Comment by Quentin-M** [comment]
This is completed! Thank you!
