### ISSUE TITLE
Build broken with Terraform 0.9.5?

### ISSUE THREAD

**Issue by aknuds1** [coreos/tectonic-installer#663]
I just installed Terraform 0.9.5 (on OS X), and the build seems to break due to the new version being stricter than before.

Trying to build master, I see these errors:

    $ CLUSTER=demo PLATFORM=aws make plan
    Error asking for user input: 2 error(s) occurred:

    * module.vpc.var.worker_azs: At column 15, line 1: true and false expression types must match; have type string and type unknown in:

    ${ split("|", "${length(keys(var.tectonic_aws_worker_custom_subnets))}" > 0 ?
        join("|", keys(var.tectonic_aws_worker_custom_subnets)) :
        join("|", data.aws_availability_zones.azs.names)
      )}
    * module.vpc.var.master_azs: At column 15, line 1: true and false expression types must match; have type string and type unknown in:

    ${ split("|", "${length(keys(var.tectonic_aws_master_custom_subnets))}" > 0 ?
        join("|", keys(var.tectonic_aws_master_custom_subnets)) :
        join("|", data.aws_availability_zones.azs.names)
      )}

I see a bunch more errors of this kind in my digitalocean branch actually. Any ideas as for how to fix them?

**Comment by s-urbaniak** [comment]
I can reproduce this locally. Apparently LHS and RHS types in expressions must match but terraform does not recognize the types.

**Comment by s-urbaniak** [comment]
Just as a side-note: I expect this to happen more often, as with every terraform release we had to catch up/adapt the templates.

**Comment by sym3tri** [comment]
Makes sense, but for now with the official release we are pinned to 0.9.4 and make no guarantees the installer will work with any other version.

**Comment by s-urbaniak** [comment]
xref: #687

**Comment by aknuds1** [comment]
Figure we might as well close this one.
