### ISSUE TITLE
AWS: Support bringing your own IAM policy

### ISSUE THREAD

**Issue by joshrosso** [coreos/tectonic-installer#666]
## Story

Users may desire to specify the exact AWS policy associated with their worker and controller roles. This would provide an alternative to having Tectonic create them for each new cluster.

User's may prefer an externally managed policy for:
- Ability to reuse a universal controller/worker policy across clusters
  -- Has its trade-offs
- Ability to restrict worker/controller right beyond what tectonic sets
- Ability to allow for workers/controllers to have more rights. e.g. if they want pods to be able to assume the default role and expect more privileges than tectonic would add to its policy by default.

**Comment by sym3tri** [comment]
We also have a need for this with our automated testing

**Comment by alexsomesan** [comment]
didn't mean to close this, not sure what happened
