### ISSUE TITLE
Support customizable worker defaults (e.g. default taint / affinity rules) on groups of nodes

### ISSUE THREAD

**Issue by joshrosso** [coreos/tectonic-installer#668]
## Story

Users may desire to have default configuration options for how nodes (or groups of nodes) come online in a tectonic cluster. 2 examples are taints and/or affinity rules wished to be default on nodes (or categories of nodes (e.g. ASGs)).

This is especially helpful if:
- Specific nodes should be used exclusively when security is a concern
- Specific nodes are gpu capable for high-compute scenarios

> This requirement comes from the notion of having different 'categories' of nodes via ASGs in AWS. I'm unaware whether this is universal among cloud providers. From the AWS perspective, relates to https://github.com/coreos/tectonic-installer/issues/387.

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
