### ISSUE TITLE
Use Prometheus Operator 0.7+ in Tectonic

### ISSUE THREAD

**Issue by joshrosso** [coreos/tectonic-installer#670]
## Story

Currently we use prom operator [0.6.0](https://github.com/coreos/tectonic-installer/blob/1.6.2-tectonic.1/installer/assets/monitoring/prometheus-operator.yaml#L15-L20). Due to breaking TPR changes, we cannot upgrade the prom operator without breaking certain tectonic features. 

Some users have a dependency on 0.7+ as they were using that prometheus operator before CoreOS made the transition from standard Prometheus deployments to the Operator.

This issue is the track the progress of this upgrade.

**Comment by fabxc** [comment]
Tectonic 1.6.2 ships with the operator version 0.8.2.
Can you confirm this is resolved with that Tectonic release?

**Comment by sym3tri** [comment]
I think this is solved. @joshrosso please reopen if not.
