### ISSUE TITLE
Support canal as a Tectonic-native networking option

### ISSUE THREAD

**Issue by joshrosso** [coreos/tectonic-installer#671]
## Story

Users would like the ability to add calico in a mode where it enforces [k8s NetworkPolicies](https://kubernetes.io/docs/concepts/services-networking/networkpolicies) nativly.

There are some questions around how this should be done.

1. How should the kubelet be configured in order to accept necessary cni binaries? (https://github.com/kubernetes-incubator/bootkube/issues/405)
2. Is self-host calico stable running in etcd-less mode
3. Can calico be removed from a cluster without breaking all networking (e.g. felix ip table alterations are cleaned up / gc'd)

**Comment by joshrosso** [comment]
Relates to: https://github.com/coreos/tectonic-installer/issues/694, but this ticket implies an option to enable Calico (canal) in the installer.

**Comment by sym3tri** [comment]
this was added some time ago
