### ISSUE TITLE
Docs: baremetal release cert-gen script location change

### ISSUE THREAD

**Issue by alekssaul** [coreos/tectonic-installer#672]
Documentation in: https://coreos.com/tectonic/docs/1.6.2-tectonic.1/install/bare-metal/index.html#matchbox
points to https://coreos.com/matchbox/docs/latest/deployment.html#coreos for matchbox install documenatation. [Generate Certs Section](https://coreos.com/matchbox/docs/latest/deployment.html#generate-tls-credentials) of the page specifies `examples/etc/matchbox/cert-gen` as the location of the script. With matchbox 0.6 the location of the script is moved to `scripts/tls/cert-gen`

![image](https://cloud.githubusercontent.com/assets/11538902/26008774/33839462-3714-11e7-9130-6e80822462ce.png)

**Comment by zbwright** [comment]
hey @alekssaul - I'll update, if you confirm that these are the only changes required, please:

Otherwise, generate a self-signed ca.crt, a server certificate (server.crt, server.key), and client credentials (client.crt, client.key) with the scripts/tls/cert-gen script. Export the DNS name or IP (discouraged) of the provisioner host.

$ cd scripts/tls
# DNS or IP Subject Alt Names where matchbox can be reached
$ export SAN=DNS.1:matchbox.example.com,IP.1:192.168.1.42
$ ./cert-gen

**Comment by alekssaul** [comment]
thanks @zbwright , the rest looks good to me. Since the documentation instructs the user to change the directory to where `cert-gen.sh` script is.. the files are generated in that path. Next steps such as `sudo cp ca.crt server.crt server.key /etc/matchbox/` will work as is, since the cert files will be generated in the working folder.

**Comment by zbwright** [comment]
that's what I thought. thank you, sir, for confirming.

**Comment by zbwright** [comment]
https://github.com/coreos/matchbox/pull/521

**Comment by alekssaul** [comment]
@zbwright & @dghubble : One other thing I just noticed is that. [Tectonic Baremetal Documentation](https://coreos.com/tectonic/docs/latest/install/bare-metal/) points to upstream [Matchbox] Documentation(https://coreos.com/matchbox/docs/latest/deployment.html). 

Upstream Matchbox documentation is not Tectonic specific and on [CoreOS section](https://coreos.com/matchbox/docs/latest/deployment.html#coreos) calls for
 ```shell
$ sudo cp contrib/systemd/matchbox-on-coreos.service /etc/systemd/system/matchbox.service
```
matchbox on coreos systemd Unit does not have Matchbox RPC settings. The end user should be using matchbox-on-tectonic.service instead. 

Using the CoreOS specific systemd unit, end user will run into; https://github.com/coreos/terraform-provider-matchbox/issues/6

**Comment by dghubble** [comment]
Read a little further in Tectonic docs: "Be sure to enable the gRPC API and use the TLS generation script to create server and client certificates. This can be done following the "Customization" and "Generate TLS" sections."

**Comment by dghubble** [comment]
https://github.com/coreos/matchbox/pull/524 updates the docs, but keeps local/source examples working.

**Comment by dghubble** [comment]
Re-opening until docs are fixed on the site
