### ISSUE TITLE
Complete smoke test matrix for AWS

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#678]
To cover the major installation options.

- [ ] etcd: BYO
- [x] etcd: self-hosted (incl when experimental flag is on)
- [ ] VPC: existing (public)
- [x] ~~VPC: existing (private)~~
- [x] CA: provide own
- [x] master count: 1
- [ ] custom Pod/Service CIDR

Edit: Let's tackle private cluster a separate story

**Comment by sym3tri** [comment]
@ethernetdan how's this going?

**Comment by Quentin-M** [comment]
I feel like ` VPC: existing (public)` is covered implicitly by `VPC: existing (private)`.

**Comment by Quentin-M** [comment]
Porting this to the next spring, alongside with the QA automation (see Master Plan).

**Comment by robszumski** [comment]
@Quentin-M we have run into things like https://github.com/coreos/tectonic-installer/issues/1096 that show the need for this testing

**Comment by sym3tri** [comment]
@mxinden please track any remaining details from this in Jira
