### ISSUE TITLE
Console has three JS errors after idling on node detail page

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#679]
After idling for a bit on a Node Detail page, I see the following JS errors:

![image](https://cloud.githubusercontent.com/assets/755540/26018967/12702a70-3727-11e7-84f5-57dc221ebcd8.png)

![image](https://cloud.githubusercontent.com/assets/755540/26018997/36092a68-3727-11e7-9a07-f07ef8a57733.png)

![image](https://cloud.githubusercontent.com/assets/755540/26019009/4788564c-3727-11e7-8526-ae805c42c473.png)

**Comment by amrutac** [comment]
I wasn't able to reproduce this on my cluster. Are you able to consistently reproduce this on every cluster or is this one seen on any specific cluster.

**Comment by sym3tri** [comment]
closing b/c not reproducible and also this is a Console issue, not installer.
