### ISSUE TITLE
Provide Docker image of current `master` of installer

### ISSUE THREAD

**Issue by mxinden** [coreos/tectonic-installer#689]
I am using the Tectonic installer in our CI pipeline of the Tectonic Prometheus operator and (in the future) the Prometheus Operator. In order to do that I have to compile the installer and its front-end first which I am doing with the `quay.io/coreos/tectonic-builder:v1.7` image.

We are already compiling the installer in the CI pipeline of the Tectonic installer. I would propose building a Docker image with terraform and the compiled binaries as a step of the pipeline so anyone can just go ahead and start her cluster without any dependencies by using the `quay.io/coreos/tectonic-installer-dev:master` image,

What do you think? If you aggree I would go ahead and create a PR. (I would replace the current top level `Dockerfile` if it is not needed anymore.)

/CC @s-urbaniak we already dicussed this. I am creating this in case somebody is already working on it or has a better idea.

**Comment by Quentin-M** [comment]
Hi!

I am not against this, I think your use-case is a legit reason to do so. 
Unsure about the repository name though.
We also plan to do nightly builds asap actually.

**Comment by sym3tri** [comment]
@mxinden would the latest nightly build be sufficient, or would you need master for your case?

**Comment by mxinden** [comment]
@Quentin-M @sym3tri Both are fine. I would prefer `master` as it would probably enable us to trace integration issues even more granular, but it probably doesn't really matter for us.

@Quentin-M Can you suggest an alternative repository name? The `-dev` would emphasize that it is not a release repository.

**Comment by Quentin-M** [comment]
I am just afraid it won't be evident that the `-dev` one has a build inside it, while the other one is simply the environment.

Each PR / master merge should leave the artifact(s) (tarball, binaries..) available in Jenkins ([example](https://jclouds.ci.cloudbees.com/job/jclouds-2.0.x-branch/56/org.apache.jclouds$jclouds-all/)) so they can be referenced/used by others at any time. Nightly builds would not really differ from regular builds in that sense but only by the set of tests ran against them.

Not sure of the exact timeline here though.

**Comment by mxinden** [comment]
@sym3tri Whats the timeline for the nightly builds?

@Quentin-M What is `quay.io/coreos/tectonic-installer` currently used for? Last update was 2 month ago.

@sym3tri @Quentin-M You both seem to be agreeing to the basic idea. I would suggest I will go ahead and add this for `master` which can then be replaced once nightly builds are in place. What do you think?

Happy to help with the nightly builds as well. Let me know.

**Comment by Quentin-M** [comment]
> @Quentin-M What is quay.io/coreos/tectonic-installer currently used for? Last update was 2 month ago.

It is not used anymore - it was actually used to store builds. We suggest we re-use that repository for what you are asking!

Sure! Thanks!
