### ISSUE TITLE
OIDC refresh tokens not refreshing properly

### ISSUE THREAD

**Issue by soggiest** [coreos/tectonic-installer#691]
Version: 1.5.5.2

Expected Result: OIDC refresh tokens would refresh properly allowing kubeconfig data to be valid for longer than a day.

Observed results: OIDC refresh tokens are not refreshing properly forcing users to re-download kubeconfig files to access their clusters from kubectl. 

Errors observed:
From kubectl:
`Unable to connect to the server: could not refresh token: invalid character '<' looking for beginning of value`

From Tectonic-Identity Pod: 
```
time="2017-05-12T10:08:30Z" level=error msg="failed to get refresh token: not found" 
time="2017-05-12T10:15:43Z" level=error msg="failed to get refresh token: not found" 
```

**Comment by rithujohn191** [comment]
Versions on Dex prior to 2.3.0 https://github.com/coreos/dex/releases/tag/v2.3.0 has some know issues with refreshing tokens. Please confirm which version of dex they are using

**Comment by rithujohn191** [comment]
Spoke offline confirmed they are using a very old version of dex. Recommended that they upgrade to fix the token refreshing issue

**Comment by robszumski** [comment]
Closing, please re-open if needed

**Comment by rithujohn191** [comment]
@soggiest could you please confirm that upgrading dex solved the issue?

**Comment by soggiest** [comment]
We're still seeing this issue despite upgrading to 1.5.7 and the latest version of Dex

**Comment by rithujohn191** [comment]
Hi @soggiest please send details of the exact issues you are facing. Is it still the same issue with the refresh token? And is v2.4.1 being used?

**Comment by soggiest** [comment]
Tectonic Version: 1.5.7
Dex Version: 2.4.1

Relevant Identity pod log entries:
```
time="2017-05-22T09:34:21Z" level=error msg="failed to get refresh token: not found" 
time="2017-05-22T11:08:04Z" level=info msg="keys expired, rotating" 
```
```
time="2017-05-22T08:03:08Z" level=error msg="refresh token with id ic3525guthe4yoo5yx6ssdcivu claimed twice" 
```

**Comment by soggiest** [comment]
Upgrading to Tectonic 1.6 and the latest version of Dex has resolved this issue.
