### ISSUE TITLE
Add Calico network policy support

### ISSUE THREAD

**Issue by aaronlevy** [coreos/tectonic-installer#694]
This should be "policy-only" support (leaving flannel as the pod-network provider).

See: Calico policy-only documentation here:

http://docs.projectcalico.org/v2.2/getting-started/kubernetes/installation/hosted/kubernetes-datastore/

@abhinavdahiya is going to pick this up. I'll assign once he's part of the org.

/cc @joshrosso @yifan-gu

xref: https://github.com/kubernetes-incubator/bootkube/issues/513

**Comment by joshrosso** [comment]
@aaronlevy @abhinavdahiya 

Will this implementation be etcd-less?

**Comment by philips** [comment]
Yes.

**Comment by philips** [comment]
@joshrosso yes, this will be etcd-less. That is a hard requirement.

**Comment by joshrosso** [comment]
@caseydavenport Is there a rough estimate on when [etcd-less calico will support advanced policy features](https://github.com/projectcalico/canal/issues/70#issuecomment-299597923)?

Per @philips comment, our usage in tectonic will be quite limited without all the egress, etc support we get with the etcd-based calico today.

Thanks in advanced!

**Comment by lxpollitt** [comment]
If you want all the advance features of Calico policy then you will need to use Calico in etcd mode.  Either sharing the k8s etcd cluster (which is what most users choose to do today) or using a second etcd cluster (typically self hosted, using host networking).  

We do plan to add full Calico policy via TPRs at some point, but that is likely not until Q3 timeframe.

**Comment by rithujohn191** [comment]
Please add a smoke test to verify that the calico network policy works using apply. You can modify one of the existing tests to do this. CC @squat

**Comment by squat** [comment]
fixed by #780. closing
