### ISSUE TITLE
Master ASG Race Condition

### ISSUE THREAD

**Issue by rmenn** [coreos/tectonic-installer#695]
The init assets defined in the script here - https://github.com/coreos/tectonic-installer/blob/master/modules/aws/ignition/resources/init-assets.sh could lead to a race condition, the script takes care of the first bootstrap but does not consider nodes being terminated and replaced by the ASG. During which the sort function could fail to result in the same result as the initial master node selection.

**Comment by philips** [comment]
The root cause here is that we blindly sort the list of ASG members and pick the top one: https://github.com/coreos/tectonic-installer/blob/master/modules/aws/ignition/resources/init-assets.sh#L22

So, the race is I scale the ASG up, there are `i-b`, `i-c`, `i-d` instances already in the cluster and the new ASG member is `i-a`. In this case `i-a` will think it is "first" and launch bootkube. Oops!

**Comment by s-urbaniak** [comment]
So after brainstorming with @alexsomesan we came up with three possible solutions:

1. Distribute `kubeconfig` using ignition and try to `kubectl cluster-info` from within `init-assets.sh`. If it succeeds, one can assume that there is a working cluster, hence we can bail out.
1. Actually a `curl -k https://{cluster_name}-api.{base_domain}` should be enough and we should get back an `Unauthorized` which is already a pretty strong indicator to bail out and assume there is a working API server and cluster.
1. Check the load balancer instance healths. If at least one instance is "InService", bail out as this is already an indicator that the api server is running. `aws elb describe-instance-health --load-balancer-name sur-api-internal | jq -r '[ .InstanceStates[] | select(.State | contains("InService")) ] | length > 1'
`.

Solution 1. seems the most heavy weight. the `aws_cli` image most probably doesn't contain `kubectl` so we need to provide it somehow. Also distributing `kubeconfig` via ignition seems burdensome.

Solution 2. seems lightweight while solution 3. seems the most robust.

Having said that all of the above solutions suffer from one edge case: While installing tectonic there is a periods of time where bootkube downloads api server images or transitions to the actual api server, hence none of the instances will be "InService". When the user at this very moment scales up, the race happens again.

I believe that scaling up during installing is good compromise to live with without involving distributed locking, hence I'll implement solution 3. and set up a PR for this.

/cc @sym3tri @robszumski

**Comment by sym3tri** [comment]
Won't solution 3 lead to false negatives depending on the ELB health
timeout settings?

**Comment by robszumski** [comment]
Number 3 is also tied to what you can introspect from a cloud provider, which won't work for bare metal, VMware, etc. Wouldn't it be best to have the same solution for consistency across platforms?

**Comment by alexsomesan** [comment]
@sym3tri That possiblity exists, but can only occur when no API server process exists anymore. Did you mean false positives during initial boostrapping or during a scale up / down operation?

**Comment by sym3tri** [comment]
I meant initial bootstrapping. For example:
- T1: 1st node detects ELB is unhealthy, runs bootkube. 
- T2: 2nd node detects ELB is unhealthy (1st node is actually ready but ELB health check interval has not elapsed yet so ELB still reports unhealthy).
- T3: 2nd node tries to run bootkube too.

**Comment by alexsomesan** [comment]
@sym3tri 
The ELB health barrier is going to complement the current instance ID based election process.
Only the instance with the lowest ID would attempt to run bootkube.
With the ELB check, we're addressing the scenario when another instance with a lower ID shows up later in time, after bootkube has been started.

So the scenario looks something like this, for the first bootstrap:
```
-------------------------------------------------------------------------------|
Time   |      instance-id-100     |   instance-id-200   |     instance-id-300  |
-------------------------------------------------------------------------------|
  T1   | checks if lowest id      | checks if lowest id | checks if lowest id  |
       | positive - goes on       | negative - stops    | negative - stops     |
  T2   | checks ELB unhealthy     | no op               | no op                |
       | positive - RUNS BOOTKUBE | no op               | no op                |--------------------------
       | no op                    | no op               | no op                |     instance-id-99      | <- starts up after initial
       | no op                    | no op               | no op                |--------------------------    set of masters, has lower id
  T3   | no op                    | no op               | no op                | checks if lowest id     |
       | no op                    | no op               | no op                | positive - goes on      |  <- this is where we 
       | no op                    | no op               | no op                | checks ELB unhealthy    |     currently fail to stop
       | no op                    | no op               | no op                | negative - stops        |
```

**Comment by rmenn** [comment]
The ASG description gives the status if an instance is in service. https://github.com/coreos/tectonic-installer/blob/master/modules/aws/ignition/resources/init-assets.sh#L20

But i do have `health_check_type = "ELB"` set on the ASG, so im not sure if that changes the behavior. 

The LIfeCycleState in the response should be enough? As in if you have even one server `InService` we should be able to trust that the master is running. Thoughts?

**Comment by alexsomesan** [comment]
@rmenn We're not relying on the ASG health report for this feature. We will actually describe the ELB and look at every instance's individual state. It's independent of having `health_check_type` set on ASG. If at least one instance shows up as `InService` in the ELB, then we consider the cluster to have been already bootstrapped.

**Comment by alexsomesan** [comment]
@robszumski We actually are doing that with this statement: https://github.com/coreos/tectonic-installer/blob/master/config.tf#L11

It specifies which version of TF can run the templates. It will err out before anything else if there's a version conflict.

**Comment by sym3tri** [comment]
@alexsomesan ah ok. I see.

Super edge-case: 

_While_ the API Server is completely down (unhealthy in ELB) for an update or some random reason, masters auto-scale up AND the new instance ID is lower than the others.
