### ISSUE TITLE
GUI - nav bar updates

### ISSUE THREAD

**Issue by meghanschofield** [coreos/tectonic-installer#699]
- Now with a CoreOS topper and a few bits from the nav. 
- Tectonic docs link is included in the nav (this is different from our marketing site nav. I'm including two elements that match but have revealed the specific link for Tectonic Docs that'll take users to the main installer docs page!) 
- The Installer Version is revealed in the nav bar, top right (outlined here: https://github.com/coreos/tectonic-installer/issues/364)
- Data collection note lives at the bottom, on all pages. 
  -- 20px from the bottom of the window
  -- text color #d9d9d9

![installation type_destroy cluster](https://cloud.githubusercontent.com/assets/3373315/26081740/28a24c9a-3981-11e7-87a3-471efc431e22.png)

How does this look @robszumski ?

**Comment by amrutac** [comment]
@meghanschofield: Can you please provide more details about the `Products` and `Open Source` dropdowns?

**Comment by meghanschofield** [comment]
Yup! Those are the same nav items, with the same drop downs as https://coreos.com/

<img width="403" alt="screen shot 2017-05-26 at 5 10 35 pm" src="https://cloud.githubusercontent.com/assets/3373315/26516115/4732611e-4236-11e7-8460-4ea2436ea6f8.png">
<img width="502" alt="screen shot 2017-05-26 at 5 10 40 pm" src="https://cloud.githubusercontent.com/assets/3373315/26516116/483e60d0-4236-11e7-80d7-0aae8f8fe5a7.png">

Does that help?
