### ISSUE TITLE
setup initial integration test job in CI

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#703]
Should run as triggered and nightly.

Should include upstream k8s conformance tests using:
quay.io/coreos/kube-conformance

**Comment by sym3tri** [comment]
Some work was already done here: https://github.com/coreos/tectonic-installer/pull/680

**Comment by Quentin-M** [comment]
The job is now working properly! 👏
Simply need to add the automatic trigger and Slack notifications.

**Comment by rithujohn191** [comment]
This is runs as a nightly job on jenkins.
