### ISSUE TITLE
Remove windows folder from release tarball

### ISSUE THREAD

**Issue by alexsomesan** [coreos/tectonic-installer#704]
Currently the installer release tarball bundles a windows folder under ./tectonic-installer.
This location only contains the windows terraform binary but not an installer binary, so it's a bit confusing.

I suggest to remove it from the tarball until we can officially support windows.

**Comment by zbwright** [comment]
let me know when this will happen, please. there's doc that needs to be edited as well.

**Comment by robszumski** [comment]
@zbwright You can go ahead and start the doc changes, as Windows is already non-functional

**Comment by zbwright** [comment]
kk. thank you.

**Comment by zbwright** [comment]
https://github.com/coreos/tectonic-installer/pull/709
