### ISSUE TITLE
create consistent etcd endpoints object

### ISSUE THREAD

**Issue by fabxc** [coreos/tectonic-installer#706]
From within the k8s cluster, it should be possible to know about all of its etcd nodes in a unified way. Regardless on whether its a self-hosted or custom external etcd cluster.

This is helpful for applications such Prometheus to implement functionality around etcd without leaking details of the specific setup further down. 
A pair of well-known Kubernetes Service+Endpoints objects should be all that is needed.

@alexsomesan @s-urbaniak

**Comment by fabxc** [comment]
@alexsomesan is it possible to get this into the next release?

**Comment by alexsomesan** [comment]
I'll have at it today.
If it gets merged by Friday it will be in the next release.
