### ISSUE TITLE
use systemd-journal-gatewayd to render installation debug logs

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/tectonic-installer#726]
As proposed by the honorable @brianredbeard there seems to be a nice way to stream journal events via http(s) which could be potentially fetched by the installer:

https://www.freedesktop.org/software/systemd/man/systemd-journal-gatewayd.service.html

We have everything at hand to configure a secure stream of logging events using this tool. On the frontend side we could split this stream even into different outputs:

- kubelet service logs
- bootkube service logs
- tectonic service logs

/cc @ggreer @sym3tri @robszumski @Quentin-M @alexsomesan

**Comment by robszumski** [comment]
Getting more robust status output of things post boot is a goal from the UX team. Logs like this would help, as well as embedding a Kubernetes client to introspect the pod statuses (https://github.com/coreos/tectonic-installer/issues/561)

**Comment by s-urbaniak** [comment]
After gathering some feedback, I would also like to summarize a couple of concerns/open questions:

- This tool does not provide authentication
- Some concerns expressed by @lucab regarding the general usage adoption of this tool
- Actually some components do not provide very meaningful log output without deep k8s knowledge, like the bootkube and kubelet service.

Possible fallback
- Reinvent the wheel using https://github.com/coreos/go-systemd (if necessary)

**Comment by brianredbeard** [comment]
This does tease out some of the generally unhelpful nature of a lot of the
log messages (bordering on log spam) and the vast majority of what is being
output is neither helpful nor actionable.

I'm saddened to see that (digging in further) the tool was never extended
by the systemd maintainers to support any kind of auth.  Apparently they
got as far as syslog and shrugged.

**Comment by amrutac** [comment]
@s-urbaniak: What's the status on this? I was looking into the UI implementation story https://github.com/coreos/tectonic-installer/issues/561 and was wondering if this is ready to be implemented in the UI.

**Comment by s-urbaniak** [comment]
@amrutac Unfortunately we didn't do any work on this due to other priorities, namely AWS stabilization/Azure/testing.

**Comment by amrutac** [comment]
OK, thanks for the update!
