### ISSUE TITLE
Consolidate Makefiles

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#731]
Currently we have 3 Makefiles:

1. In the root
2. Under `/installer`. 
3. Under `/installer/frontend`. 

We should clean this up and consolidate everything into the root Makefile. This is to avoid confusion and avoid potential circular dependencies (which have already arisen). Also the `/installer` one references scripts above its CWD which is difficult to manage.

We even have Makefiles calling bash scripts calling other Makefiles.

**Comment by brianredbeard** [comment]
Ideally these should not actually be consolidated, but should correctly link each other so that only singular components can be called.

**Comment by brianredbeard** [comment]
To the point of Makefiles calling bash scripts calling other Makefiles, that *is* sub-optimal behavior and makes it harder to troubleshoot with `make -d`.

**Comment by Quentin-M** [comment]
My understanding is that the team is pretty satisfied with the way it is right now (it evolved and got fixed a lot pretty much naturally) - at least for now. We might close this? @squat Thoughts?

**Comment by squat** [comment]
I agree. Geoff eliminated the one in `installer/frontend` and I also just recently removed a makefile for `installer/tests` and consolidated it so we do have fewer makefiles now than before. We can close this for now IMO.
