### ISSUE TITLE
Install kube-ca on all nodes

### ISSUE THREAD

**Issue by everett-toews** [coreos/tectonic-installer#736]
It would be useful and convenient to have the [kube-ca created in the bootkube module](https://github.com/coreos/tectonic-installer/blob/543387fe0e69a47c2caf94e6408df18abac63aa3/modules/bootkube/assets_tls.tf#L22-L41) to be present on all nodes. Then it could be used as a CA for any other services running on the nodes that require trust.

My understanding is that it would need to be copied to `/etc/ssl/certs/` followed by a `sudo update-ca-certificates` on each node.

**Comment by brianredbeard** [comment]
Having the private key on all of the nodes for the CA is an extreme security risk and will nullify the ability to trust the authority.

**Comment by everett-toews** [comment]
I completely agree. 

To clarify, I wasn't suggesting putting the private key of the CA on all of the nodes. 

I was suggesting putting the public CA certificate on all of the nodes. 

To be precise, it's the file generated at [this step](https://github.com/coreos/tectonic-installer/blob/543387fe0e69a47c2caf94e6408df18abac63aa3/modules/bootkube/assets_tls.tf#L48-L51). It's the same public CA cert that's distributed in the kubeconfig file [here](https://github.com/coreos/tectonic-installer/blob/543387fe0e69a47c2caf94e6408df18abac63aa3/modules/bootkube/assets.tf#L57).

Unless I'm missing some detail, kube-ca is a public CA cert that's meant to be shared as you would any public CA cert already found in `/etc/ssl/certs/` on Container Linux.

**Comment by everett-toews** [comment]
Fixed by https://github.com/coreos/tectonic-installer/pull/2362
