### ISSUE TITLE
Minimize the number of hardcoded values

### ISSUE THREAD

**Issue by brianredbeard** [coreos/tectonic-installer#739]
Across the repository there are a number of values which are hard coded (and conflicting) leading to issues doing builds.  Using `TERRAFORM_VERSION` as an example:

```
Dockerfile:3:ENV TERRAFORM_VERSION=0.9.4
images/tectonic-builder/Dockerfile:23:ENV TERRAFORM_VERSION="0.8.8"
installer/scripts/release/common.env.sh:25:TERRAFORM_BIN_VERSION=0.9.4
```
This leads to a situation where the `tectonic-builder` image currently cannot be used to build the repository.

As the repository is using `make`, it should probably be defined through the use of actual environment variables or a single common file which is sourced. 

Affects (at a minimum):
 #687 
 #745

**Comment by Quentin-M** [comment]
The image CAN be used, and in fact IS used by Jenkins. The Dockerfile here is simply not up to date. `quay.io/coreos/tectonic-builder:v1.7` includes Terraform v0.9.4. Terraform v0.8.8 is not compatible.

**Comment by Quentin-M** [comment]
I want to get to the point where every single builds are made in that container and it'd be the single point of truth for building - and outputs the right binaries. It would limit lots of issues with local Go deps for instance and discrepancy between dev/test/release envs.

**Comment by Quentin-M** [comment]
As mentioned IRL, this technical debt will, for the big part, be tackled by the upcoming release automation work.

**Comment by sym3tri** [comment]
I think we've addressed most of these and will continue to do so in the converged platform
