### ISSUE TITLE
docs: guidelines for modifications and editing of provided modules

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#742]
Folks want to modify stuff, which is great, but we need to explicitly say what can't be modified and how to accomplish a successful modification. I propose a high level outline that can be fleshed out:

- Machine level
  - What is _never_ safe to modify
    - kubelet configuration, including CNI
  - What is always safe to modify
    - Container Linux channels
  - What you can modify, but must manage on own
    - changes to Ignition profiles, such as networking, mounting storage, etc
    - ideally these changes make it back into the product
    - still feeling out how you do the git merge between a new release and your fork
- Kubernetes level
  - What is _never_ safe to modify
    - any manifests in `kube-system` or `tectonic-system`
    - default RBAC roles
  - What is always safe to modify
    - your pods/deployments/etc
    - adding namespaces
    - add RBAC roles

That's a quick brain dump, I'm sure there is more. The goal is to get something down on paper, and expand out as we get experience merging and maintaining customizations over time.

**Comment by robszumski** [comment]
As part of this was can cover the idea expressed in https://github.com/coreos/tectonic-installer/issues/430

**Comment by zbwright** [comment]
let's do this:
1) keep the (generic) CONTRIBUTING.md file at the top level, and add a section specific to Tectonic Installer that links out to a xxx file in the contrib directory. (name TBD. Modifying Tectonic Installer?)
2) create a more specific file within this directory, that outlines mods specific to TI, that includes both Brandon's comment (>6 months gets dropped) and Rob's info listed above.
3) start to build out additional pages within this repo that address specific topics, as outlined by Aleks' comments. I think Aleks or Rob can best provide the topics for these pages: group by cloud provider? by add-on? by what?

does that work?

**Comment by robszumski** [comment]
> start to build out additional pages within this repo

Sounds good as long as these land in `/Documentation` so we can get them synced to the site.

**Comment by sym3tri** [comment]
Also worth noting that using "alpha features" via existing beta/stable APIs (even on users's own resources) is discouraged in production and we cannot guarantee they will survive an upgrade.

**Comment by zbwright** [comment]
and another note from @robszumski: Step one to supporting customers changes to the terraform modules/configs/manifests is identifying what is safe to change, and what will break our updates.

**Comment by zbwright** [comment]
I think we should add *why* the listed changes aren't safe. Just a sentence on each one should do it. I've tried to add what I could.

https://github.com/coreos/tectonic-installer/pull/789

**Comment by robszumski** [comment]
Fixed in https://github.com/coreos/tectonic-installer/pull/789
