### ISSUE TITLE
docs: call out our supported Terraform version more explictly

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#745]
Addresses https://github.com/coreos/tectonic-forum/issues/122

Two places where we it probably makes sense to mention this:

 - add to the list of prereqs, note the version, and the fact that we cover using it later in the doc
 - under `Initialize and configure Terraform`, again mention the version and note that this is what this step accomplishes

**Comment by zbwright** [comment]
@joshix is there any method in place whereby we track all the pages that need to be touched when a version number increments? (It's easy enough for me to add this, but I want to get it set up to be tracked, if such a thing exists.)

**Comment by alexsomesan** [comment]
@robszumski We actually are doing that with this statement: https://github.com/coreos/tectonic-installer/blob/master/config.tf#L11

It specifies which version of TF can run the templates. It will err out before anything else if there's a version conflict.

**Comment by alexsomesan** [comment]
A good thing would be to extract from there and template into the docs.

**Comment by robszumski** [comment]
@zbwright I think the typical thing that the engineers do is run a grep/sed/find-and-replace across the codebase

**Comment by zbwright** [comment]
version number is already called out in the ReadMe. I'll add it to the installer docs as well.

**Comment by zbwright** [comment]
https://github.com/coreos/tectonic-installer/pull/811

**Comment by aknuds1** [comment]
Speaking of which, it's only possible to build Tectonic Installer with the unreleased version 0.9.6 of Terraform, right? I was caught unawares by this - have only used official Terraform releases so far - do I need to install Terraform from their master branch?

**Comment by alexsomesan** [comment]
Right now yes.

The next Tectonic release will include a Terraform binary that includes all
the required fixes from upstream.

**Comment by aknuds1** [comment]
@alexsomesan Thanks for the heads up. Does this mean the required Terraform binary will be part of the repository, or just the release archive?

**Comment by alexsomesan** [comment]
It will just be in the release archive, alongside the Tectonic installer
binary.

**Comment by robszumski** [comment]
@aknuds1 More info here: https://github.com/coreos/tectonic-installer/blob/7641fcabb099db6c84bbaa10e98a417c588d58ba/Documentation/troubleshooting/known-issues.md#issues-running-multiple-terraform-commands It's a really unfortunate upstream Terraform bug :/

**Comment by aknuds1** [comment]
So in general I can download the required Terraform binary from your [forked repo](https://github.com/coreos/terraform/releases)?

**Comment by robszumski** [comment]
@aknuds1 yes for now. Hope to get back to unmodified upstream once 0.9.6 comes out. Our goal is always upstream unless we run into blockers like this.

**Comment by aknuds1** [comment]
@robszumski Thanks, good to know!

**Comment by zbwright** [comment]
https://github.com/coreos/tectonic-installer/pull/811

**Comment by robszumski** [comment]
Update on this: we are now back to unforked Terraform and are merging changes to make the required version of Terraform listed beside the release notes for the next release.
