### ISSUE TITLE
pin etcd operator to master nodes

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#746]
Same as was done in bootkube already.

https://github.com/kubernetes-incubator/bootkube/pull/512/files

**Comment by alexsomesan** [comment]
This seems to be in place: https://github.com/coreos/tectonic-installer/blob/master/modules/bootkube/resources/experimental/manifests/etcd-operator.yaml#L28

Should we close it?

**Comment by alexsomesan** [comment]
Found the PR: https://github.com/coreos/tectonic-installer/pull/748

closing this.
