### ISSUE TITLE
Proposal: Allow pods to use rbd volumes (Rook/Ceph support)

### ISSUE THREAD

**Issue by lblackstone** [coreos/tectonic-installer#754]
I'm using [Rook](https://github.com/rook/rook), and am running into [this issue](https://github.com/rook/rook/issues/423). I'm proposing that the kubelet settings in the installer be updated as described in [these instructions](https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubelet-wrapper.md#allow-pods-to-use-rbd-volumes) (required change copied below).

```
[Service]
Environment=KUBELET_IMAGE_TAG=v1.5.4_coreos.0
Environment="RKT_RUN_ARGS=--volume modprobe,kind=host,source=/usr/sbin/modprobe \
  --mount volume=modprobe,target=/usr/sbin/modprobe \
  --volume lib-modules,kind=host,source=/lib/modules \
  --mount volume=lib-modules,target=/lib/modules \
  --uuid-file-save=/var/run/kubelet-pod.uuid"
...
```

I have confirmed that Rook works with this change in place on the metal and OpenStack installers.

**Comment by s-urbaniak** [comment]
Generally I have no concerns of getting this in, @alexsomesan any objections?

**Comment by alexsomesan** [comment]
I am not familiar with how Rook integrates into K8S.
Looks harmless to me, but I would also appreciate an opinion from @aaronlevy as to potential hidden conflicts this might lead to.

**Comment by alexsomesan** [comment]
@lpabon could also have some input here

**Comment by lpabon** [comment]
@alexsomesan @s-urbaniak Looks good to me, but we should probably generalize this with iSCSI and Ceph as [shown](https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubelet-wrapper.md#allow-pods-to-use-rbd-volumes)

**Comment by coresolve** [comment]
This is a pattern needed for more generic iscsi integration as well. We have a prospect that is very interested in using iscsi.

**Comment by alekssaul** [comment]
Looks like adding below to kubelet should cover all use cases.
```
Environment="RKT_RUN_ARGS=--volume modprobe,kind=host,source=/usr/sbin/modprobe \
  --mount volume=modprobe,target=/usr/sbin/modprobe \
  --volume lib-modules,kind=host,source=/lib/modules \
  --volume iscsiadm,kind=host,source=/usr/sbin/iscsiadm \
  --mount volume=iscsiadm,target=/usr/sbin/iscsiadm \
  --mount volume=lib-modules,target=/lib/modules \
  --uuid-file-save=/var/run/kubelet-pod.uuid"
```
I hear the need from BM and VMware users as well. I imagine ceph/rook maybe deployed on various platforms, but iscsi is probably not likely to be deployed on cloud environments. 

Does it make sense to update kubelet for all platforms the same way?

**Comment by robszumski** [comment]
Bump on this.

**Comment by philips** [comment]
We need to fix the kernel to load these modules correctly. It would be really really really ideal if we disallow the init_module syscall from all containers generally.

**Comment by kokhang** [comment]
I have submitted a PR to relax the modprobe shell out command. It nows warns if it fails. https://github.com/kubernetes/kubernetes/pull/46016

With this change, you should not need to add the volume mounting to the container.

**Comment by tobad357** [comment]
Is there any expected timeline for the iscsi part to be fixed as we would like to do a test with tectonic

**Comment by andrewwebber** [comment]
@lblackstone I have been using the above work around on CoreOS on 1.5+ and dynamic storage provisioning with RBD volumes working perfectly

@philips Currently, for me, mounting RDB volumes on 1.6.4+coreos.0 on CoreOS is broken even with the work around flags, probably due to the changes addressed in the pending merge request.
```golang
rbd.go:408] rbd: failed to setup mount /var/lib/kubelet/pods/5518dec9-54dc-11e7-8cd9-1803733f6dbf/volumes/kubernetes.io~rbd/pvc-3efebd28-54dc-11e7-8cd9-1803733f6dbf rbd: failed to modprobe rbd error:exit status 1
```

@lblackstone Are there currently any 1.6.4 work arounds?

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
