### ISSUE TITLE
Document how to add a controller on bare metal

### ISSUE THREAD

**Issue by zbwright** [coreos/tectonic-installer#758]
notes: 
- This issue was originally filed by Josh Wood.
- edrooth says: boot controller, manually expand etcd peer group
- joshix asks: So: We follow the existing steps in bare metal scaling, then label the new node a controller?
Then, separately the issue of whether you want to scale etcd cluster too. Manually member-add &c.(?)

Ed's not sure if it's easily doable yet, and asks for @dghubble to chime in.

**Comment by dghubble** [comment]
Controllers are listed just like workers https://github.com/coreos/tectonic-installer/blob/master/platforms/metal/variables.tf#L119

* tectonic_metal_controller_names
* tectonic_metal_controller_domains
* tectonic_metal_controller_macs

If self-hosted etcd is enabled (experimental), just add the new controller name, fully qualified domain, and MAC address to the lists and re-run `terraform apply`. PXE boot the new machine.

If the etcd cluster is run on controllers (i.e. not self-hosted etcd), you can do the same thing, but the controller will not become an etcd peer as that would require reconfiguring the other etcd peers. Either mask `etcd-member` (if you don't care about adding an etcd peer, you just want another controller) or add the new machine to the previous etcd cluster - etcd docs cover this and its a manual process.
