### ISSUE TITLE
Docs: What am I building and what will it cost.

### ISSUE THREAD

**Issue by coresolve** [coreos/tectonic-installer#760]
Docs needs to describe clearly what is being built given the defaults provided. 

How much is this going to cost per month? 

A prospect wants a clear understanding of this early in the docs. 

This was a source of friction before spinning up a demo environment.

**Comment by sym3tri** [comment]
Could be helpful:
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/price-changes.html

**Comment by brianredbeard** [comment]
@sym3tri that will be helpful, but without (at a minimum) a list of:

1) resources per controller
1) resources per worker
1) number of ELBs needed (both static and per service)
1) number of EIPs needed per node/service/etc

This will be impossible to calculate.

**Comment by alexsomesan** [comment]
Quick breakdown of things that generate cost, with AWS in mind:

* `m` number of master nodes (minimum 1, usually equal to number of AZs) - cost depends on instance type
* `n` number of worker nodes (minimum 0) - cost dependent on instance type
* `m + n` number of EBS volumes, one for each node, by default 30Gb each
* `a` number of NAT gateways (maximum as many as region AZs, minimum as many as worker AZs)
* `3` ELBs (API internal, API external, Ingress) - cost depends on traffic through the ELBs 
* `1` S3 bucket, for assets - 
* `2` Route53 zones (one public & one private) - cost depends on number of queries

Additional cost will be incurred by network traffic to and from the Internet, such as downloading container images.

**Comment by mkorejo** [comment]
Just price out 3-5 prototypical stacks, like x-small (single node for demos/PoCs), small (1 master, 1 worker), medium (3 masters, 3 workers), large, and x-large. Establish some reference points and just put those in the docs.

**Comment by sym3tri** [comment]
@mkorejo I like that idea. Thanks for the suggestion. We'll explore that.
