### ISSUE TITLE
support spot instances fleets on aws

### ISSUE THREAD

**Issue by elipapa** [coreos/tectonic-installer#768]
It would be great to leverage spot fleets for certain instance pools. This will help support batch/scalable work loads. It wouldn't have to involve master nodes.

**Comment by alexsomesan** [comment]
@elipapa Thanks for raising the issue. We've had this on our minds as well, but priorities went to stabilising the new installer for the existing use cases first. However, this is a valid use case and demand from users is going to help prioritise it.

**Comment by joshrosso** [comment]
I am currently working on a PR to add this functionality.

**Comment by AndriiOmelianenko** [comment]
@joshrosso hello, could you please let me know what's the status of it?

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
