### ISSUE TITLE
Support for User provided Custom CA trust

### ISSUE THREAD

**Issue by everydaynerd** [coreos/tectonic-installer#774]
Our organization is currently using AWS as a cloud provider.  Along with public certificates, we also use an internal CA which is not trusted by default.  We need our custom internal CA to be trusted for Kubernetes to use container images in our private registry.

**Comment by brianredbeard** [comment]
Just to clarify, are you looking to be able to just anchor your existing public CA (e.g. the cluster wide equivalent of dropping a cert with the corresponding hash into `/etc/pki/tls/certs` or `/etc/ssl/certs`) ?

I ask because depending on the specific need/workflow there are a number of ways this can get solved (some with way more usefulness in  the long run).

**Comment by everydaynerd** [comment]
I believe putting in /etc/ssl/certs would do the trick.  Our workaround was to put the cert in `/etc/docker/certs.d/quay-enterprise.FQDN.internal/ca.crt` but if the OS trusted the root from /etc/ssl/certs, I think this would resolve the issue.

**Comment by sym3tri** [comment]
Currently being addressed in https://github.com/coreos/tectonic-installer/pull/1811

**Comment by bodgit** [comment]
Not sure if this is exactly the same issue, but I've started playing with the installer now that it has HTTP proxy support however the proxy in question performs SSL/TLS intercept by default which means all of the SSL/TLS certificates end up being issued by an internal CA. Being able to include this CA certificate into the installer so it gets placed in the standard `/etc/ssl/certs` store would be super useful. For now, I will see if I can exempt the installer from the intercept policy to get things further along. However I will also want to be able to use container images from an internal registry (which by coincidence also has a certificate signed by the same CA) and isn't accessed through the proxy either so if putting it in `/etc/ssl/certs` makes it work for everything, that's great.

**Comment by sym3tri** [comment]
This feature was added in a previous release.
