### ISSUE TITLE
Gui installer should be smarter about dns check.

### ISSUE THREAD

**Issue by coresolve** [coreos/tectonic-installer#782]
Going through the tectonic ui installer for aws.
It wasn't clear that the zone I am asked for needs to be configured to be publicly available. 
A simple test to make sure the zone is publicly available. 
dig NS ${tectonic_base_domain}
If this doesn't return don't try to resolve the hostname of the console. Error on the zone not being available.

**Comment by alekssaul** [comment]
I believe that could miss the cases where customer types something like; example.com which will be public, but not controlled by their route53 .

I believe we also support non-public DNS zones for completely private installs.

**Comment by robszumski** [comment]
@alekssaul where do they type this out? Isn't it a dropdown that is pre-populated? Unless you mean type that out as a subdomain like `example.com.foobar.com`?

**Comment by alekssaul** [comment]
Hi @robszumski ,

GUI pulls it from Route53 zones list; 
![image](https://cloud.githubusercontent.com/assets/11538902/26362295/7fabe0fc-3fab-11e7-8559-863a9db1f1ef.png)

You can create a public Route53 domain object in AWS without it being actual live public zone. As an example I've created microsoft.com in R53

![image](https://cloud.githubusercontent.com/assets/11538902/26362369/b367c1e0-3fab-11e7-936a-9158b2c8075e.png)

One way to validate it may be to lookup the nameservers for a domain and compare it to records route53
```
nslookup 
> set type=NS
> se.k8s.work
Server:		10.0.2.3
Address:	10.0.2.3#53

Non-authoritative answer:
se.k8s.work	nameserver = ns-1265.awsdns-30.org.
se.k8s.work	nameserver = ns-1541.awsdns-00.co.uk.
se.k8s.work	nameserver = ns-498.awsdns-62.com.
se.k8s.work	nameserver = ns-873.awsdns-45.net.

Authoritative answers can be found from:
```
![image](https://cloud.githubusercontent.com/assets/11538902/26362582/6862787e-3fac-11e7-8020-ddb9835ef8e2.png)

**Comment by sym3tri** [comment]
> It wasn't clear that the zone I am asked for needs to be configured to be publicly available.

By default yes, but if you check "internal cluster" then it's not required to be public.
