### ISSUE TITLE
aws: route table association should to be configurable

### ISSUE THREAD

**Issue by colhom** [coreos/tectonic-installer#787]
When launching a cluster into an existing VPC but creating new subnets, it would be useful to be able to specify which route table in the existing VPC the subnets should attach to. Something like:

```
tectonic_aws_external_vpc_id = "vpc-xxxx"

// tectonic_aws_master_custom_subnets = ""
tectonic_aws_master_route_table = "rtb-xxxx"

// tectonic_aws_worker_custom_subnets = ""
tectonic_aws_worker_route_table = "rtb-yyyy"
```

**Comment by edevenport** [comment]
@colhom I have been looking into this issue and I was wondering if you could clarify something. You mentioned launching into an `existing VPC` and creating new subnets. However, the installer flow requires the user to select existing subnets when provisioning into an existing (public or private) VPC. In this situation, the subnets should already have proper route tables assigned as they need to be public and/or private subnets.

When `Create a new VPC` is selected, then corresponding subnets are also created. In this scenario, existing master and worker route tables could potentially be selected for the new subnets. If this the behavior you would like to see?

If I misunderstanding, can you explain the use case?

**Comment by sym3tri** [comment]
I think @edevenport is correct and there is nothing to be done here.
