### ISSUE TITLE
Update operator installation UI

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#794]
Changes:
 - update label to `Automated Updates`
 - update label to `Enable one-click updates for Tectonic, etcd, Prometheus` (16px)
 - update help text to `Use for non-production clusters` (13px muted)

![experimental-change](https://cloud.githubusercontent.com/assets/755540/26271342/64af484c-3cb9-11e7-95b6-3894ce90cc47.png)

**Comment by sym3tri** [comment]
Slight change on this. Checkbox should be defaulted to **off** and text should be "Only use with non-production clusters"
