### ISSUE TITLE
Update all docs to latest Tectonic version

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#795]
Anything referencing version: `1.6.2-tectonic.1` should be changed to `1.6.4-tectonic.1`.

But do not merge until https://github.com/coreos/tectonic-installer/pull/792 lands.

**Comment by zbwright** [comment]
@sym3tri - version updates are being handled as part of the publication process - cc'ing (and assigning) @joshix until I know how to do it myself.

**Comment by sym3tri** [comment]
@zbwright We just search through the docs and manually updated them.
```bash
grep -r "1.6.2-tectonic.1" .
```

**Comment by sym3tri** [comment]
fixed in https://github.com/coreos/tectonic-installer/pull/871
