### ISSUE TITLE
bootkube.service is marked as failed on ssh

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#797]
If a machine in a 3+ node cluster isn't selected as the special bootstrap node the bootkube service will fail. However, it should simply exit with a 0 status and be OK.

Actual output:

```
$ ssh some-master-node
Container Linux by CoreOS stable (1353.7.0)
Update Strategy: No Reboots
Failed Units: 1
  bootkube.service
```

Expected output:

```
$ ssh some-master-node
Container Linux by CoreOS stable (1353.7.0)
Update Strategy: No Reboots
```

**Comment by zendeavor** [comment]
It should exit 0 and be ok, but this assumes that whatever error causing it to fail is not actually a failure state and only marked as such by an improper exit code.

Does `systemctl status bootkube` have anything useful to say? I've hit on a bootkube.service failure now and am curious if this is the same issue.

**Comment by zendeavor** [comment]
After reading this again with a fresher mind, I see that your issue is related to a master node which is not the bootstrap system for the install process. I think that eliminates the possibility that my issue is related to this one in those terms.

**Comment by squat** [comment]
Thanks, @philips. This issue was duped and is now being tracked in #1155.
