### ISSUE TITLE
Net partition between kubelet and API server causes etcd pod eviction; cluster dips below quorum

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#798]
**Problem:** If multiple master node kubelet's gets networked partitioned from the API server then the nodes will go NotReady. Within 5 minutes etcd pods launched by the etcd Operator are evicted by the Controller Manager on these nodes. This causes etcd to go read-only AFTER the network partition ends.

Why does etcd go read-only AFTER the network partition ends? Because the controller manager connects to the API server on the POD network it is telling te kubelet, which is partitioned, to delete etcd pods which are still operating just fine. Once the kubelet partition ends it connects to the API server, finds that it should delete its pods, and happily nukes the cluster.

NOTE: It is important that the network partition ends AT THE SAME TIME for all kubelets. Otherwise the etcd Operator can recover the deletion event for each kubelet in time to not lose qurorum. 

**Root Cause:** The Controller Manager evicts pods, even really important ones, under network partition by default.

**Steps to reproduce:**

1. Install Kubernetes on AWS with experimental Operators, 3 masters, wait for cluster to come up fully
2. ssh into 2 or more of the master machines and run `sudo iptables -A OUTPUT -p tcp --dport 443  -j DROP`
3. Wait about 5 minutes
4. etcd pods will get deleted by controller manager (see screenshot)
5. QUICKLY ssh into 2 or more of the master machines and run `sudo iptables -D OUTPUT -p tcp --dport 443  -j DROP`

<img width="1418" alt="screen shot 2017-05-19 at 7 33 57 pm" src="https://cloud.githubusercontent.com/assets/33544/26272436/ecfe3ca4-3ccc-11e7-8df8-7d5ebb6f6f54.png">

**Comment by philips** [comment]
xref Found https://github.com/kubernetes-incubator/bootkube/issues/534 as another red herring issue.

**Comment by chancez** [comment]
I believe TaintBasedEvictions are the correct feature for handling this, and I filed an issue about it relating to this problem today: https://github.com/coreos/etcd-operator/issues/1117

**Comment by coresolve** [comment]
Earlier today we saw a similar failure on Scott Sumners cluster. In this case the only interesting thing in the log was around not finding the pid for containerd.
```
go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/3b60d2f8-3a57-11e7-ad41-0a486cf2b908-secrets" (spec.Name: "secrets") pod "3b60d2f8-3a57-11e7-ad41-0a486cf2b908" (UID: "3b60d2f8-3a57-11e7-ad
go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/a672f202-3a57-11e7-8d6e-06a35e5fddbc-default-token-dptch" (spec.Name: "default-token-dptch") pod "a672f202-3a57-11e7-8d6e-06a35e5fddbc" (UID
nux.go:638] error opening pid file /run/docker/libcontainerd/docker-containerd.pid: open /run/docker/libcontainerd/docker-containerd.pid: no such file or directory
nux.go:638] error opening pid file /run/docker/libcontainerd/docker-containerd.pid: open /run/docker/libcontainerd/docker-containerd.pid: no such file or directory
an't process config file "/etc/kubernetes/manifests/kube-system-pod-checkpointer-mn1x9.json": /etc/kubernetes/manifests/kube-system-pod-checkpointer-mn1x9.json: read '', but couldn't parse as pod(Object 'Kind'
an't process config file "/etc/kubernetes/manifests/kube-system-pod-checkpointer-mn1x9.json": /etc/kubernetes/manifests/kube-system-pod-checkpointer-mn1x9.json: read '', but couldn't parse as pod(Object 'Kind'
an't process config file "/etc/kubernetes/manifests/kube-system-pod-checkpointer-mn1x9.json": /etc/kubernetes/manifests/kube-system-pod-checkpointer-mn1x9.json: read '', but couldn't parse as pod(Object 'Kind'
```

It seems things are working okay and then they aren't at exactly this time. The docker daemon logs are decidedly unhelpful here. They have a gap for this time period and don't show the daemon restarting or anything.
