### ISSUE TITLE
Destroy deletes Azure DNS Zone

### ISSUE THREAD

**Issue by ethernetdan** [coreos/tectonic-installer#799]
When performing a destroy on an Azure cluster the DNS zone that is used for the cluster is deleted. This behavior was surprising to me since the only option is to provide an existing DNS zone and this could be unnecessarily destructive to user configuration.

**Comment by philips** [comment]
cc @metral ?

**Comment by metral** [comment]
I think this is related to a bug that I introduced with regards to when/how DNS zones are created and destroyed. I opened up https://github.com/coreos/tectonic-installer/pull/803 which should fix it.

It reintroduces the `tectonic_azure_create_dns_zone` variable and makes `tectonic_azure_use_custom_fqdn` be `false` by default, and optional - this may have been `true` in your attempts @ethernetdan, and inadvertently affecting your usage.

Could you try on my PR with `tectonic_azure_create_dns_zone` set to `false` `tectonic_azure_use_custom_fqdn` set to `false` (if not already), and your existing DNS zone to see see if preserving the zone as expected? Note if `tectonic_azure_create_dns_zone` is false, the A records should already exist in the DNS zone, as Tectonic won't create it.

Also, What are your tfvars?

**Comment by ethernetdan** [comment]
@metral: will try again today. I was using the Azure [example file at the time](https://github.com/coreos/tectonic-installer/blob/0960fbf/examples/terraform.tfvars.azure).

**Comment by squat** [comment]
@metral is this still an issue? I saw your PR landed. If no longer an issue, please close

**Comment by metral** [comment]
I don't believe it is. `tectonic_azure_use_custom_fqdn` no longer exists and Azure has changed quite a bit since. I'm fine closing this issue.

**Comment by squat** [comment]
Thanks, closing for now.
