### ISSUE TITLE
Move adding SSH key to Azure steps

### ISSUE THREAD

**Issue by ethernetdan** [coreos/tectonic-installer#800]
While the [Azure installation guide](https://github.com/coreos/tectonic-installer/blob/master/Documentation/install/azure/azure-terraform.md) mentions that using SSH agent with a private key added that corresponds to the given public key is required it does it in a note the end after the installation steps:
```
make sure the SSH key specifyied in the tfvars file is also added to the SSH agent on the machine running terraform. Without this, terraform is not able to SSH copy the assets and start bootkube. Also make sure that the SSH known_hosts file doesn't have old records of the API DNS name (fingerprints will not match).
``` 

This should be added to the installation steps for clarity.

**Comment by philips** [comment]
Can you write a PR for this @ethernetdan ?

**Comment by ethernetdan** [comment]
Will do

**Comment by snsumner** [comment]
I hit the identical issue when testing 1.6.4 RC7 on Bare Metal install.  Really need to specifically explain that the ssh key needs to be loaded into ssh-agent on the same machine you run the installer.  I used this link to learn how to do it on OSX: https://apple.stackexchange.com/questions/48502/how-can-i-permanently-add-my-ssh-private-key-to-keychain-so-it-is-automatically

**Comment by snsumner** [comment]
Another suggestion is within the UI installer before they proceed with the actual deployment there should be a safe guard where it checks that ssh-agent is running and a key is loaded.  Duffie had me run ssh-add -L to verify my key was there and it matched my ~/.ssh/id_rsa file.

**Comment by justaugustus** [comment]
#1480 updated docs to include notes about `ssh-agent`. We might be able to close this.
