### ISSUE TITLE
Deploy 3 instance Alertmanager cluster

### ISSUE THREAD

**Issue by fabxc** [coreos/tectonic-installer#804]
We want to deploy a 3 instance Alertmanager setup to be used by Tectonic's cluster level alerting as well as all alerts from custom Prometheus servers in the general case.

Typically, the resource requirements are quite low as they do not receive excessive amounts of traffic. We expect about 50-100MB per instance but have to get some numbers on how far this grows under different loads.

This would be part the monitoring stack via tectonic-prometheus-operator.

**Comment by s-urbaniak** [comment]
I am unsure of the concrete action item here, but generally we don't impose the minimum of 3 nodes of users, but rather at minimum one master and one worker node (this would of course not be a production setup, but rather for demo purposes only).

Can you elaborate what needs to be done in terms of templating/backend/frontend for the tectonic installer?

**Comment by fabxc** [comment]
It's more of an FYI as there was a recent misunderstanding that this was going to be added. As this directly results in manifests added to the installer (by team-monitoring), I figured it's a relevant place to note it.

I'll also add a few things to pivotal over the next days – but frankly, I'm still not 100% sure what goes where :)

Given that any real cluster has at least 3 nodes, this is no real blocker.
