### ISSUE TITLE
Bad DNS records with mismatching public and private zones

### ISSUE THREAD

**Issue by bison** [coreos/tectonic-installer#809]
I have a cluster installed into an existing VPC with `tectonic_aws_external_vpc_public` set to `false`.

I'm also setting `tectonic_aws_external_private_zone` to an existing private Route 53 zone. My private zone uses a different TLD than the public zone because I don't want to have to mirror all the records between the two. So the zones for the VPC looks something like:

Public: `us-west-1.example.net`
Private: `us-west-1.example.internal`

I have `tectonic_base_domain` set to `us-west-1.example.net`.

Given this configuration, I get no records in the public zone, and in the private zone I get records like: `cluster-api.us-west-1.example.net.us-west-1.example.internal`

I would like to be able to just tell the installer which zone ID to use for records and not have it infer whether a private or public zone should be used.

**Comment by sym3tri** [comment]
This should be resolved once this lands https://github.com/coreos/tectonic-installer/pull/788. Let me know if that's not sufficient for some reason.

Also you _MUST_ use the same TLD for internal and external if you use both otherwise Dex issuer URLs will not match.

**Comment by bison** [comment]
Ah, yeah. That UI will help. This was just me being confused by the naming. Now it's obvious that I can just set `tectonic_aws_external_private_zone` to a public zone if I choose.

Thanks!
