### ISSUE TITLE
Porting to DigitalOcean - how to test?

### ISSUE THREAD

**Issue by aknuds1** [coreos/tectonic-installer#814]
I've [partially ported](https://github.com/aknuds1/tectonic-installer/tree/digitalocean) Tectonic Installer to DigitalOcean, how should I write tests for my implementation?

**Comment by sym3tri** [comment]
Hi @aknuds1. Thanks for the contributions. You could follow the AWS tests as a reference for now. 

We're doing a lot of active work on our CI system right now, so it's probably easiest to come up with something that can be built and run locally in isolation from the other tests for now. Then we can later integrate that into our Jenkins pipeline.

1st thing I'd do is create a usable tfvars to boot a cluster (ideally multiple files that together cover most of the install options), something like :
https://github.com/coreos/tectonic-installer/blob/master/test/aws.tfvars

Then you can verify that our sanity tests pass, see: https://github.com/coreos/tectonic-installer/tree/master/installer/tests/sanity

For reference those are invoked via Jenkins now (but all that code should move into a Makefile or something else)
https://github.com/coreos/tectonic-installer/blob/master/Jenkinsfile#L49-L96

So in the end it could be:
- Instructions on how to run tests
- A local flow like `make test-digital-ocean` or a bash script or something that validates a clusters can boot & all sanity tests pass.

Once all that is done we can wire it up to Jenkins.

**Comment by aknuds1** [comment]
Thanks much @sym3tri! Will try when I have the opportunity, your suggested approach sounds sensible and your Jenkins refactoring (move into build scripts) is what I used to do when I wrote administrated this CI :D

**Comment by aknuds1** [comment]
@sym3tri What number should I use for `$NODE_COUNT` when running the sanity test?

**Comment by sym3tri** [comment]
It should just be the total number of k8s nodes (masters + workers), not including any dedicated etcd nodes if you're using them. It's for a test that just validates we can `kubectl get nodes` and the expected number comes back with "ready" status.

**Comment by sym3tri** [comment]
@aknuds1 let's move this to: https://github.com/coreos/tectonic-installer/issues/820
