### ISSUE TITLE
add basic tests for DigitalOcean

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#820]
Migrated from: https://github.com/coreos/tectonic-installer/issues/814 as a more result oriented issue.
Is also part of #144.

We need an isolated way to boot a DigitalOcean cluster, and run sanity tests against it.

Integrating into the Jenkins pipeline is out of scope for this issue.

**Comment by aknuds1** [comment]
See my (WIP) [PR](https://github.com/coreos/tectonic-installer/pull/604).
