### ISSUE TITLE
AWS: terraform is erroneously creating public hosted zones

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#821]
When our CI tests run for some reason it now creates duplicate _public_ hosted zones. This causes any subsequent run of CI to fail due to the zone already existing.

Possibly related to:
https://github.com/coreos/tectonic-installer/pull/664

**Comment by s-urbaniak** [comment]
The referenced PR creates a private zone only, iff `tectonic_aws_external_private_zone` is set to empty string.

More formally [`vpc_id`](https://github.com/coreos/tectonic-installer/pull/664/files#diff-89fde7522b851315557843f65db8222bR8) is specified in the created zone, which creates a private zone according to https://www.terraform.io/docs/providers/aws/r/route53_zone.html#vpc_id.

I can dig into the terraform source code of the route53_zone resource to check how it behaves if `vpc_id` is empty string.

**Comment by sym3tri** [comment]
Changing to P1 b/c haven't been able to reproduce this. Need to figure out where those public zones (now deleted) came from in our account.

**Comment by Quentin-M** [comment]
I don't see a single duplicated public zone. Closing. Feel free to re-open if necessary.
