### ISSUE TITLE
ensure tests cleanup anytime 'terraform apply' fails

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#822]
Anytime `terraform plan` or `terraform apply` or smoke tests fail, we need to ensure `terraform destroy` always runs.

**Comment by squat** [comment]
I think we can now confirm this is working as desired. After fixing #819 with #823 we can see that even after plan or apply fail Jenkins will still run the destroy step, which is configured to run `always`. The test output for that PR shows that destroy still ran: https://jenkins-tectonic-installer.prod.coreos.systems/blue/organizations/jenkins/coreos%20-%20tectonic-installer%2Ftectonic-installer/detail/PR-823/9/pipeline. I think we can close this now.
