### ISSUE TITLE
etcd network checkpointer should only be installed if self-hosted etcd is being used

### ISSUE THREAD

**Issue by aaronlevy** [coreos/tectonic-installer#824]
This shouldn't be installed by default: https://github.com/coreos/tectonic-installer/blob/master/modules/bootkube/resources/manifests/kenc.yaml

**Comment by sym3tri** [comment]
Looks like that manifest needs to move to:
https://github.com/coreos/tectonic-installer/tree/master/modules/bootkube/resources/experimental/bootstrap-manifests

**Comment by aaronlevy** [comment]
I believe this would actually go in https://github.com/coreos/tectonic-installer/tree/master/modules/bootkube/resources/experimental/manifests
