### ISSUE TITLE
Protect Nodes from low memory using eviction thresholds

### ISSUE THREAD

**Issue by ethernetdan** [coreos/tectonic-installer#832]
It is currently possible for Pods running on a Node to consume available memory which can cause a Node to lockup.

We should add [eviction thresholds](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-thresholds) to our Kubelet configuration so that when memory usage threatens the health of the Node, the Kubelet can start evicting Pods to protect itself. A threshold can be configured based on percentage, ie. `memory.available<5%`.

To recreate:
* Provision cluster
* Load a single Node with many high memory Pods

**Comment by ethernetdan** [comment]
Note: kubelets have a default eviction threshold of `memory.available<100Mi`

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
