### ISSUE TITLE
Failed to start tectonic.service: Unit tectonic.service not found.

### ISSUE THREAD

**Issue by zendeavor** [coreos/tectonic-installer#840]
On a baremetal installation. Is tectonic.service meant to be on the host system, or inside one of its containers?

```
null_resource.bootstrap (remote-exec): Connecting to remote host via SSH...
null_resource.bootstrap (remote-exec):   Host: controller.cluster
null_resource.bootstrap (remote-exec):   User: core
null_resource.bootstrap (remote-exec):   Password: false
null_resource.bootstrap (remote-exec):   Private key: false
null_resource.bootstrap (remote-exec):   SSH Agent: true
null_resource.bootstrap (remote-exec): Connected!
null_resource.bootstrap (remote-exec): Failed to start tectonic.service: Unit tectonic.service not found.
Error applying plan:

1 error(s) occurred:

* null_resource.bootstrap: 1 error(s) occurred:

* Script exited with non-zero exit status: 5
```

**Comment by zendeavor** [comment]
Simply copying the [tectonic.service](https://github.com/coreos/tectonic-installer/blob/562c513b6e91b35fe36ffda168dd16f44dfaf05a/modules/tectonic/resources/tectonic.service) into `/etc/systemd/system` on the controller/master allows this process to complete, but I'm quickly met with an error from the `bootkube.service`.

**Comment by s-urbaniak** [comment]
Closing in favor of #846

**Comment by rushins** [comment]
hello 

i had to happen to hit same error in HP DL 380 G7 model with tectonic 1.7.3. i hit first tectonic.console, so i copied from another cluster which has the same release and it passed to next step then i hit bootkube.service , so i copied the file from the other cluster and repeated terraform but installation never completed however bootkube is running active but no ETCD on the master ? 

any clue what could be the bottleneck of the solution.
