### ISSUE TITLE
Console should not run on port 80 if possible

### ISSUE THREAD

**Issue by diegs** [coreos/tectonic-installer#847]
Currently the console listens on port 80 (https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/manifests/console/deployment.yaml#L42). It is behind a service (https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/manifests/console/service.yaml) also exposing 80.

Listening on a low port requires running the pod as root or granting it `CAP_NET_BIND_SERVICE`. Would it be possible to run the console pod on a non-privileged port such as 8080 and then just set that `targetPort` in the service?

cc @amrutac @aaronlevy @sym3tri

**Comment by diegs** [comment]
Update: I was mistaken, adding `CAP_NET_BIND_SERVICE` doesn't appear to work. We will have to change the port if we want to run this as non-root.

**Comment by sym3tri** [comment]
AFAIK there's no reason to use port 80 on the pod itself. Should be an easy change.
