### ISSUE TITLE
Pod Checkpointer container name should match daemonset name

### ISSUE THREAD

**Issue by diegs** [coreos/tectonic-installer#848]
By convention (and to allow for updates with the KVO) the daemonset name and primary container name should match.

Currently the pod checkpointer daemonset name is `pod-checkpointer` but the container is `checkpoint`.

**Comment by sym3tri** [comment]
@diegs are you going to pick this up, or should someone else?

**Comment by sym3tri** [comment]
disregard. just saw https://github.com/coreos/tectonic-installer/pull/844

**Comment by diegs** [comment]
Re-opening. This is unable to be updated in the KVO due to a daemonset update bug. We need to resolve https://github.com/coreos-inc/kube-version-operator/issues/150 first and then we can move forward with this.

**Comment by diegs** [comment]
Fixed in #928
