### ISSUE TITLE
Tectonic identity liveness probe timeout limit is too low

### ISSUE THREAD

**Issue by rithujohn191** [coreos/tectonic-installer#849]
BUG REPORT 

What happened? https://github.com/coreos/tectonic-forum/issues/126

What you expected to happen? tectonic identity currently has its liveliness probe timeout set to 1s https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/manifests/identity/deployment.yaml#L57. We should increase this value to avoid false health check failure. Also since Dex is expected to be HA we should increase replica count to 2

**Comment by sym3tri** [comment]
Should be a quick & easy change

**Comment by diegs** [comment]
Is this going into 1.6.4? If so I need to write a migration for it.

**Comment by rithujohn191** [comment]
@sym3tri that's your call

**Comment by squat** [comment]
@diegs no need to write a migration, just update the manifest and create a mapping, right?

**Comment by diegs** [comment]
Yes, I just meant that I need to include this change in the KVO (I'm trying to cut that release...)
