### ISSUE TITLE
R53 RecordSets not being cleaned up on destroy

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#850]
I have not rigorously validated this, but it seems that when running `terraform destroy` the R53 RecordSets created by Terraform are not deleted and are left dangling on the Hosted Zone.

Need to see if we can reproduce this, then root-cause the issue if it's true. If it's really a bug it's likely in upstream Terraform.

**Comment by Quentin-M** [comment]
Withy the number of deployments we do each day, wouldn't we have more records in our main testing zone?

**Comment by sym3tri** [comment]
Need to verify if this is actually an issue or not. If so we need to find the root cause.

**Comment by jasminSPC** [comment]
@sym3tri were you able to reproduce this issue? I tried several times to replicate the behaviour but no luck. 

For a moment I thought it was happening but there was a staled Hosted Zone from a unsuccessful attempt.

**Comment by sym3tri** [comment]
no, closing for now. thanks for investigating.
