### ISSUE TITLE
Add an easy way to specify OS image ID

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#864]
Today users can only specify "alpha", "beta", or "stable" for the Container Linux channel. There is no way to pin to a specific AMI.

**Comment by squat** [comment]
This also applies to Azure.

**Comment by s-urbaniak** [comment]
just one thought from my side: As soon as we pin to a specific AMI version, we should also disable CLUO deployment such that the pinned AMI version is not updated immediately. The deployment manifest would still be present in `assets.zip` such that the user still can redeploy CLUO to kick off the update process.

**Comment by squat** [comment]
@s-urbaniak very good call; otherwise this would all be in vain.

**Comment by sym3tri** [comment]
should be covered by: https://coreosdev.atlassian.net/browse/INST-120 now
