### ISSUE TITLE
"Next Step" button grayed out on SSH page.

### ISSUE THREAD

**Issue by rithujohn191** [coreos/tectonic-installer#869]
BUG REPORT

Tectonic version: Latest build off master

Platform (bare-metal, AWS, local VMs): AWS

What happened: On the SSH Key it seems to pick the first SSH key on the list by default but the "Next Step" button is grayed out. It requires me to hit refresh the keys explicitly and pick one from the drop down list for the "Next Step" button to turn green again

What you expected to happen: If a SSH key is picked it should let me hit "Next Step". It would also be nice if the ssh keys were listed in alphabetical order in the drop down list.

How to reproduce it (as minimally and precisely as possible): Pull from master to get latest and go through install steps.

**Comment by ggreer** [comment]
Fixed in https://github.com/coreos/tectonic-installer/pull/863
