### ISSUE TITLE
kube-controller-manager pod should get deployed in the docker host network

### ISSUE THREAD

**Issue by harsh-px** [coreos/tectonic-installer#880]
## What keywords did you search in tectonic-installer issues before filing this one?
kube-controller-manager, hostNetwork, host network

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

The kubernetes-controller-manager pod spec does not have `hostNetwork:true` set which results in kube-controller-manager getting deployed in the docker `none` network. 

This breaks plugins in the kubernetes ecosystem who expect to be in the same docker network as the kubernetes-controller-manager. In this particular case, the [Portworx](https://portworx.com/) volume plugin failed.

The official recommended [spec](https://kubernetes.io/docs/admin/high-availability/kube-controller-manager.yaml) on the [Building High-Availability Clusters](https://kubernetes.io/docs/admin/high-availability/) page also has `hostNetwork:true` set.

## Versions
* Tectonic version: [1.6.2-tectonic.1](https://github.com/coreos/tectonic-installer/releases/tag/1.6.2-tectonic.1)
* Terraform version (`terraform version`): 0.9.4
* Platform: aws

## What happened?
kube-controller-manager pod got deployed in the docker `none` network.

## What you expected to happen?
kube-controller-manager pod should get deployed in the docker `host` network.

## How to reproduce it (as minimally and precisely as possible)?

1. Deploy kuberentes 1.6 using tectonic on aws
2. ssh into the kubernetes master instance and run `docker network inspect none`. The kube-controller-manager pod will be one of the containers in this network.

## Anything else we need to know?
I compared the kube-controller-manager pod spec with other standard kubernetes install methods like [kubeadm](https://kubernetes.io/docs/getting-started-guides/kubeadm/) and [kops](https://github.com/kubernetes/kops) and they set `hostNetwork:true`

**Comment by sym3tri** [comment]
Do you know specifics on why those plugins require host networking for the controller manager?

We have moved away from allowing anything to communicate with control-plane components over insecure ports. I assume other tooling still use host networking b/c it's "the way it's always been" for a while, not because it is recommended for HA.

**Comment by harsh-px** [comment]
The controller manager invokes the portworx native volume driver at http://localhost:9001 for creating volumes. Here [is the actual code](https://github.com/kubernetes/kubernetes/blob/release-1.6/pkg/volume/portworx/portworx_util.go#L155) from the kubernetes repo. As a consequence, controller manager needs to be on the host network to be able to make this call.

**Comment by steigr** [comment]
Mr. Harsh - are you still there?

I've got another (more scalable) workaround, but it is a little bit more complex than running kube-controller-master within host network namespace:

At first I'm starting another container aside the kube-CM container, which have:
- namespace of kube-CM
- dns-resolver of the host
- spec.nodeName of the hosting k8s-node
- thus kube-controller-manager may issue request to localhost:9001
- the proxy forwards this to the currently hosting node

The additional container:
```
spec:
  template:
    spec:
      containers:
      - name: px-api-proxy
        image: 'steigr/px-api-proxy:latest'
        env:
          - name: PX_LOCAL_NODE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
```

kubectl -n kube-system patch deployment kube-controller-manager -p '{"spec":{"template":{"spec":{"containers":[]}}}}'

The following script builds the docker container, which forwards 9001/tcp to $PX_LOCAL_NODE:
```
( docker build -t ${tag:=$(whoami)/px-api-proxy} - && docker push $tag ) <<'__dockerfile'
from alpine
run  apk add --no-cache socat \
 &&  rm -rf /var/cache/apk/* \
 &&  { \
  echo '#!/bin/sh'; \
  echo 'exec socat tcp-listen:9001,reuseport,reuseaddr,bind=127.0.0.1,fork tcp:$PX_LOCAL_NODE:9001'; \
 } | install -m 0755 /dev/stdin /bin/px-api-proxy
entrypoint ["px-api-proxy"]
__dockerfile
```

Update kube-controller-manager deployment ( add px-api-proxy container):
```
kubectl -n kube-system get deployment kube-controller-manager -o json \
| jq --argjson proxy '
{
	"env":[
		{
			"name":"PX_LOCAL_NODE",
			"valueFrom":{
				"fieldRef":{
					"apiVersion":"v1",
					"fieldPath":"spec.nodeName"
				}
			}
		}
	],
	"image":"steigr/px-api-proxy:latest",
	"name":"px-api-proxy"
}' \
'. * {
	spec:{
		template:{
			spec:{
				containers: (.spec.template.spec.containers + [$proxy])
			}
		}
	}
}' \
| kubectl -n kube-system update deployment kube-controller-manager -f -
```

It has the advantage of running muliple kube-CM pods on the same node (e.g. single-master-node-deployment with multiple kube-controller-manager replicas) without running into port conflicts.

I guess this workaround is in contraposition to @sym3tri but more suitable that moving kube-CM out of its network namespace.

**Comment by harsh-px** [comment]
Agree with @sym3tri 's explanation. Plugins should not depend on host network for functionality.
