### ISSUE TITLE
Display a picker from Container Linux versions on bare-metal

### ISSUE THREAD

**Issue by dghubble** [coreos/tectonic-installer#887]
## FEATURE REQUEST

The Container Linux version to PXE boot and install is picked behind the scenes by interrogating the Matchbox http endpoint to get the list of cached versions it holds and selecting the highest version. https://github.com/coreos/tectonic-installer/blob/master/installer/api/api.go#L93

It would be nice to surface the versions listing from the JSON response as a UI picker.

This would also solve a few edge cases:

* If no cached versions are available, user cannot proceed.
* User wants to choose a specific CL version
* Its opaque to the user how CL versions are picked. They discover it when the cluster comes up.

cc @ggreer @kans

**Comment by sym3tri** [comment]
closing b/c of https://github.com/coreos/tectonic-installer/issues/1209

**Comment by dghubble** [comment]
Its perfectly fine to always use stable, as proposed in #1209. Terraform inputs must currently provide the version number to use as well so that the correct PXE image and install image can be referenced. Right now this is done behind the scenes by interrogating Matchbox about what versions it has and the picker was proposed.

Given the new direction, you might switch the numeric version to just be "current" and change references to be sure the right file is in place (since Tectonic is always using the cached images).

**Comment by dghubble** [comment]
Actually, let's move the entire discussion to one place as #1209
