### ISSUE TITLE
kube-apiserver constantly logs TLS handshake errors

### ISSUE THREAD

**Issue by ggreer** [coreos/tectonic-installer#893]
Even when my tectonic console comes up successfully, I see constant TLS handshake errors in kube-apiserver. Here's the output of `kubectl --kubeconfig=generated/auth/kubeconfig logs kube-apiserver-xmqwb --namespace=kube-system -f`: 

https://gist.github.com/ggreer/42a7cc780bf52a2ec7dcb0cfa1569338

And here's the output of `kubectl --kubeconfig=generated/auth/kubeconfig get pods --all-namespaces`:
https://gist.github.com/ggreer/2a4444ff187bd79acdb061a064c2092d

I've since deleted the cluster those logs came from, but I can reproduce this 100% of the time. I have no idea if it's "normal" or bad.

**Comment by philips** [comment]
this is "normal" and due to ELB health checking :( :( :(

**Comment by Quentin-M** [comment]
Addressed by https://github.com/coreos/tectonic-installer/pull/964.
