### ISSUE TITLE
fix outdated doc about VPC peering

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#897]
This is not accurate:
https://coreos.com/tectonic/docs/latest/install/aws/troubleshooting.html#vpc-peering-not-supported

VPC peering should be fine, but there are certain cases where it will not work. We need to document the details about what to avoid when peering VPCs instead of blanketly stating it is not supported.

Basically this:
Pod & Service CIDRs are configurable in Tectonic/Kubernetes but cannot overlap with any other routable IP ranges in your network, this includes IP ranges of peered VPCs or Pod/Service CIDRs of other Kubernetes/Tectonic clusters on the same network.

Also we should remove the link to that blog post since it is no longer accurate.

Please work with @bison and @colhom for any further technical details on the docs.

**Comment by colhom** [comment]
related #787 - the hard restriction is that the Pod,Service and Instance CIDRs cannot intersect with ranged of peered VPC, but only if the `pcx` interface for that peering connection is in the route table the Kubernetes subnets are attached to. It's actually fine to have the Pod and Service CIDRs overlap with a peered VPC, as long as that `pcx` device isn't in the route table attached to the Kubernetes subnets.

**Comment by zbwright** [comment]
https://github.com/coreos/tectonic-installer/pull/1041
