### ISSUE TITLE
installer: submit GA events per page

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#904]
Feature request:

Right now platforms share some URLs and not others, which makes it hard to construct a funnel between pages. Let's add an event on each "next" click with:

category: metal, aws, etc
label: next on `pagetitle`
action: click

**Comment by robszumski** [comment]
Going to re-open this, I had added `next on <pagetitle>` but Github stripped out the page title part because it looked like an HTML tag. Updated above.

Can we update to send the page title?

**Comment by Quentin-M** [comment]
Addressed by #1110!
