### ISSUE TITLE
Docs: Review and edit all uninstall docs.

### ISSUE THREAD

**Issue by zbwright** [coreos/tectonic-installer#908]
With the new Terraform installer, old 'Uninstall' docs are out of date. They should be reviewed and updated.

Two to start:
https://github.com/coreos/tectonic-installer/Documentation/install/aws/uninstall.html 
https://github.com/coreos/tectonic-installer/Documentation/install/bare-metal/uninstall.md

**Comment by joshix** [comment]
The correct links to these that you want are, respectively:
* https://github.com/coreos/tectonic-installer/blob/master/Documentation/install/aws/uninstall.md
* https://github.com/coreos/tectonic-installer/blob/master/Documentation/install/bare-metal/uninstall.md

It's not that either of these uninstall.md documents are out of date.

It is that the delete step inline in *-terraform.md should be replaced with a link to the complete uninstall document.

**Comment by zbwright** [comment]
I understand - but I haven't reviewed the uninstall (or the scale) docs recently. I should take a look.

**Comment by zbwright** [comment]
this one is now complete. closing.
