### ISSUE TITLE
Terraform apply fails when creating clusters with any uppercase characters

### ISSUE THREAD

**Issue by ggreer** [coreos/tectonic-installer#919]
Here's the error message one gets when creating a cluster named "Testing123":

![screen shot 2017-05-26 at 18 37 39](https://cloud.githubusercontent.com/assets/200121/26516874/93fc6ed4-4242-11e7-8265-b91f76633a34.png)

```
Error applying plan:

1 error(s) occurred:

* aws_s3_bucket.tectonic: 1 error(s) occurred:

* aws_s3_bucket.tectonic: Error validating S3 bucket name: only lowercase alphanumeric characters and hyphens allowed in "aTesting123-3ea47e666300875c989a4e95acf743d9"
```

**Comment by squat** [comment]
Ha well good to know that or suspicions about uppercase names failing were correct and there were no magic to-lowers anywhere in the js/go

**Comment by squat** [comment]
following up from offline: let's enforce lowercase chars only in cluster name on the frontend

**Comment by ggreer** [comment]
Not sure if this issue needs to remain open. The "fix" was to disallow uppercase in cluster names. The old cloudformation installer supported this, but I think it will be a lot of work to fix the terraform scripts to support such names.

**Comment by sym3tri** [comment]
@ggreer I'm going to close for now. I just wanted to make sure we catch this in the UI. Thanks for getting it addressed quickly.
