### ISSUE TITLE
S3 download failure causes cluster bootstrap failure

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#924]
If the init-assets unit fails (due to an S3 download error), it causes a cascading failure to the other dependent units: bootkube & tectonic.

#796 documents the issue well, but it's unclear if that is a complete fix.

**Comment by squat** [comment]
#796 is not a complete fix. The configuration in it is actually invalid, but even if it *were* valid downstream services would not be restarted after an initial failure of the init-assets service.
