### ISSUE TITLE
API server fails to start when bootstrapping cluster

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#926]
There have been various reports of this during installation. It seems to occur semi-frequently but we've thus far been unable to consistently reproduce.

/cc @ggreer @kans please add any additional details.

**Comment by kans** [comment]
The init-assets service is the only known cause atm.  I hope to have a PR by eod.

**Comment by diegs** [comment]
Assigning to @kans because this doesn't appear to be a bootkube issue ATM.

Please feel free to assign back to me if you encounter any bootkube-related failure modes.

**Comment by sym3tri** [comment]
sounds like this may just be a dupe of #924

**Comment by kans** [comment]
partially addressed by #937 #947 #946

**Comment by sym3tri** [comment]
closing b/c dupe of #924
