### ISSUE TITLE
azure: put masters and workers into AvailabilitySets and ScaleSets

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#93]
ScaleSets currently cannot attach different disks to different virtual machines. This means that Kubernetes persistent volumes will not work with our setup for multi-machine.

To fix this we need to offer the ability to spin-up via AvailabilitySets instead. Should we create a separate module if someone wants to use AvailabilitySets vs ScaleSets similar to how you do with AWS?

cc @alexsomesan

**Comment by alekssaul** [comment]
Also mentioned in : #163

**Comment by s-urbaniak** [comment]
upstream limitation of cloud-provider integration: https://github.com/kubernetes/kubernetes/issues/40913

**Comment by discordianfish** [comment]
So I'm trying this right now, but not sure that the cloud-provider integration even works with availability sets. Let's see.
