### ISSUE TITLE
node iPXE boot fails with "Could not select: Exec format error (http://ipxe.org/23008001)"

### ISSUE THREAD

**Issue by sdanieru** [coreos/tectonic-installer#932]
BUG REPORT

## Versions

* Tectonic version
tectonic-1.6.2-tectonic.1.tar.gz
* Terraform version (`terraform version`):
? - whatever tectonic-1.6.2 is pointing at?
* Platform (aws|azure|openstack|metal):
VirtualBox

## What happened?
I'm attempting to deploy a test k8s cluster w/ tectonic-installer into VirtualBox for eval purposes; after environment is setup and I've launched tectonic GUI installer (web interface), when I startup the nodes for PXE boot, they die when attempting to run the image they just pulled from matchbox. Please see image attachment for VM's stdout when attempting boot.

It may be useful to note that for DHCP/TFTP on my virtual network in VirtualBox, I'm running the dnsmasq container.

I can also add that I've verified matchbox is setup and working per verification steps here:
https://coreos.com/matchbox/docs/latest/deployment.html#verify

## What you expected to happen?
The nodes properly startup via iPXE so tectonic can provision them and install the k8s cluster.

## How to reproduce it (as minimally and precisely as possible)?
Follow the baremetal instructions here:
https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html

The matchbox setup instructions here:
https://coreos.com/matchbox/docs/latest/deployment.html#coreos

And setup dnsmasq for DHCP/TFTP w/ the instructions found here:
https://coreos.com/matchbox/docs/latest/network-setup.html#coreosdnsmasq

## Anything else we need to know?
![screenshot from 2017-05-30 15-38-46](https://cloud.githubusercontent.com/assets/18471926/26606962/50fc3300-4551-11e7-978a-62de5cd23a45.png)

**Comment by Quentin-M** [comment]
Hi,

Virtualbox's default iPXE ROM does not support bzImage, which is required by CoreOS because initramfs is distributed as a cpio.bz.

Here is a ROM you can use with virtio-net and that includes all the required components: https://github.com/Quentin-M/coreos-baremetal-mac/blob/master/assets/virtio-net.rom. The difficulty with building your own image is that the space made available by VirtualBox is very limited (0xE000 bytes).

Use the following command to configure VirtualBox to using that ROM:
```
VBoxManage setextradata global VBoxInternal/Devices/pcbios/0/Config/LanBootRom virtio-net.rom
```

**Comment by Perdjesk** [comment]
An alternative of using a virtio-net adapter is installing the VirtualBox Extension Pack and use an Intel card.

**Comment by Quentin-M** [comment]
That is correct. Thanks for adding this to the conversation.

Last year, Virtualbox's Intel e1000 cards were buggy on macOS (at least) and would hang / reset every few seconds due to a bug in the TCP Checksum offloading. We had to disable TSO, GSO and GRO manually to make them work. This issue has been resolved since then. 

PXE was insanely slow when I tried - but I believe this could have been due that particular bug and could be a non-issue now!

**Comment by arahayrabedian** [comment]
@sdanieru i had the same issue - turns out i was on virtualbox 4.3.  Upgrade + virtualbox extensions seemed to work (though it seems to use PXE instead of iPXE, didn't investigate that yet.)

**Comment by mwthink** [comment]
I've been experiencing this same issue. I think @Quentin-M got to the meat of the problem, explaining that VirtualBox's iPXE ROM does not support bzImage and you can replace that ROM with a compatible one.

After reading @arahayrabedian's comment, I realized that this was a situation I found myself in earlier where I was PXE booting fine, then I had some (unrelated) VBox issues which I resolved with a VBox reinstall. To bring some clarity to this topic (For anyone who finds this page later and/or wants to do something regarding this), here's the rundown regarding the VBox PXE ROM. 

Tested on MacOS VirtualBox 5.1.22 (Latest as of writing). Both instances using the default Intel PRO/1000 (82540EM) network card.

|   | Bare VirtualBox | /w ExtensionPack |
| ------------- | ------------- | ------------- |
| **Boot ROM**  | [iPXE 1.0.0+](http://ipxe.org)  | Intel UNDI PXE-2.1 |
| **Features**  | Basic iPXE abilities  | Bare-bones PXE |

Installing the extension pack is a downgrade as far as the network boot ROM is concerned. The extension pack ROM is almost 20 years old. 

As far as Tectonic/Matchbox go, just insure your DHCP settings are configured to boot both native iPXE and upgrade-from PXE and you should be fine regardless of which ROM you are using.

**Comment by sym3tri** [comment]
I'm going to close this out b/c it seems like a driver issue. Also I'd recommend trying our [Tectonic Sandbox](https://coreos.com/tectonic/sandbox) instead if you're interested in running on Vagrant/VirtualBox.
