### ISSUE TITLE
Odd permissions set on detect-master.sh, s3-puller.sh, & init-assets.sh

### ISSUE THREAD

**Issue by ggreer** [coreos/tectonic-installer#933]
When you create a cluster, you get some really weird permissions on some of the shell scripts. Here's the first master in a brand new cluster:

![screen shot 2017-05-30 at 16 34 35](https://cloud.githubusercontent.com/assets/200121/26609441/e904580e-4555-11e7-8ed6-c58a2d915080.png)

I'm pretty sure we don't want these permissions. The only reason stuff comes up is because we specify the shell in the various systemd units. (`ExecStart=/usr/bin/bash /opt/tectonic/init-assets.sh`)

**Comment by diegs** [comment]
Fixed in #936
