### ISSUE TITLE
terraform re apply creates infrastructure that will conflict with itself.

### ISSUE THREAD

**Issue by coresolve** [coreos/tectonic-installer#943]
## Versions
1.6.2
* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
* Terraform version (`terraform version`):
* Platform (aws|azure|openstack|metal):

## What happened?
Leveraging the ui we ran into a iam permissions problem. We fixed the permissions and hit reapply in the ui. 

This spun up brand new infra that conflicted on things like the s3 bucket naming.

## What you expected to happen?
It would leverage the existing tfstate file and reapply rather than creating a new directory and infrastructure.

## How to reproduce it (as minimally and precisely as possible)?
Install via the ui and re apply.

**Comment by coresolve** [comment]
@colhom @grantliu @jnevelson

**Comment by coresolve** [comment]
@robszumski

**Comment by eddieesquivel** [comment]
@robszumski I just ran into this on an internal cluster.

**Comment by rithujohn191** [comment]
Please could you add more steps on how we can reproduce this?

**Comment by eddieesquivel** [comment]
@rithujohn191 Yes! Here are steps:

I had existing iam roles that conflicted with a fresh terraform install/apply. Most likely from a previously failed deletion. After the apply complained about the roles existing it stops the apply. I deleted the iam roles and did a re-apply and TF complained about things it had created during the apply previously.

Error applying plan:

6 error(s) occurred:

* module.workers.aws_iam_instance_profile.worker_profile: 1 error(s) occurred:

* aws_iam_instance_profile.worker_profile: Error creating IAM instance profile se-cluster-worker-profile: EntityAlreadyExists: Instance Profile se-cluster-worker-profile already exists.
	status code: 409, request id: c319157b-667f-11e7-b2bc-c757bd196036
* module.masters.aws_elb.console: 1 error(s) occurred:

* aws_elb.console: DuplicateLoadBalancerName: Load Balancer named se-cluster-con already exists and it is configured with different parameters.
	status code: 400, request id: d40052e7-667f-11e7-a814-fbbeccc4e1c7
* module.masters.aws_elb.api-external: 1 error(s) occurred:

* aws_elb.api-external: DuplicateLoadBalancerName: Load Balancer named se-cluster-ext already exists and it is configured with different parameters.
	status code: 400, request id: d3d8a637-667f-11e7-a2e3-a31dc03e93b9
* module.masters.aws_elb.api-internal: 1 error(s) occurred:

* aws_elb.api-internal: DuplicateLoadBalancerName: Load Balancer named se-cluster-int already exists and it is configured with different parameters.
	status code: 400, request id: d3d96989-667f-11e7-a2e3-a31dc03e93b9
* module.masters.aws_iam_instance_profile.master_profile: 1 error(s) occurred:

* aws_iam_instance_profile.master_profile: Error creating IAM instance profile se-cluster-master-profile: EntityAlreadyExists: Instance Profile se-cluster-master-profile already exists.
	status code: 409, request id: c2cd17ce-667f-11e7-b581-e51e36ee5d0a
* aws_s3_bucket.tectonic: 1 error(s) occurred:

* aws_s3_bucket.tectonic: Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
	status code: 409, request id: 42CDBB0203A0E3D0, host id: X6TEnB6+gq4luUGS4loNjo6szhRA+uIsV8SXOoFfZufV2H1iw7Nl3fxHtgAc07edx2m+ESYC4cc=

**Comment by coresolve** [comment]
This is a diff problem. In your case you needed to cleanly delete the infra before creating new stuff. 

The UI bug was that it would create a new cluster and disregard the previous state file. This has been fixed by @quentin and @ggreer

**Comment by sym3tri** [comment]
Closing b/c @coresolve says it's resolved.
