### ISSUE TITLE
terraform destroy fails randomly on CI

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/tectonic-installer#951]
The following CI test failure appeared now two times as seen in https://github.com/coreos/tectonic-installer/pull/935#issuecomment-305206098 and https://github.com/coreos/tectonic-installer/pull/751#issuecomment-305529391.
```
15:06:29 1 error(s) occurred:
15:06:29 
15:06:29 * module.vpc.aws_internet_gateway.igw (destroy): 1 error(s) occurred:
15:06:29 
15:06:29 * aws_internet_gateway.igw: Error waiting for internet gateway (igw-748c5d13) to detach: couldn't find resource (31 retries)
15:06:29 
```

@alexsomesan any idea which edge case this could hit?

**Comment by ggreer** [comment]
Duplicate of #949, right?

**Comment by s-urbaniak** [comment]
ah right, closing in favor of #949
