### ISSUE TITLE
Installer fails when tectonic_pull_secret_path is unset, even if tectonic_vanilla_k8s = true

### ISSUE THREAD

**Issue by discordianfish** [coreos/tectonic-installer#960]
## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1d5e973
* Terraform version (`terraform version`): Terraform v0.9.7-dev (08c672ca1ef2e9750000fad114720744639de8b6+CHANGES)
* Platform (aws|azure|openstack|metal): azure

## What happened?
I've set tectonic_vanilla_k8s = true to create a new cluster but didn't specify `tectonic_pull_secret_path` nor `tectonic_license_path`. After `make apply` the cluster comes up, but the installer fails due to tectonic.service failing with these errors:

```
Jun 02 15:55:57 tectonic-master-000000 bash[3744]: [ 1152.209026] hyperkube[5]: The Secret "coreos-pull-secret" is invalid: data[.dockerconfigjson]: Invalid value: "<secret contents redacted>": unexpected end of JSON input

Jun 02 15:55:57 tectonic-master-000000 bash[3744]: [ 1152.210871] hyperkube[5]: kubectl failed, retrying in 5 seconds
Jun 02 15:56:02 tectonic-master-000000 bash[3744]: [ 1157.211320] hyperkube[5]: kubectl failed, giving up
Jun 02 15:56:03 tectonic-master-000000 systemd[1]: tectonic.service: Main process exited, code=exited, status=1/FAILURE
Jun 02 15:56:03 tectonic-master-000000 systemd[1]: Failed to start Bootstrap a Tectonic cluster.
Jun 02 15:56:03 tectonic-master-000000 systemd[1]: tectonic.service: Unit entered failed state.
Jun 02 15:56:03 tectonic-master-000000 systemd[1]: tectonic.service: Failed with result 'exit-code'.
```
## What you expected to happen?
I expected the installer to not install any tectonic components that require a license or pull secret.

## How to reproduce it (as minimally and precisely as possible)?
I haven't tried but assume this can be reproduced by using the sample azure config and setting `tectonic_vanilla_k8s = true`.

**Comment by discordianfish** [comment]
Looks like the k8s expects a valid json file for `kubernetes.io/dockerconfigjson` but without setting `tectonic_pull_secret_path` the installer generates this which can't get applied:
```
{
  apiVersion: v1,
  kind: Secret,
  type: kubernetes.io/dockerconfigjson,
  metadata: { 
    namespace: tectonic-system,
    name: coreos-pull-secret
  },
  data: { 
    ".dockerconfigjson": ""
  }
}
```

As a workaround, specifying any valid docker config should work.

**Comment by lblackstone** [comment]
I fixed the same issue in a couple of the other installers previously. The linked PR should solve clear this up for the remaining installers.

**Comment by s-urbaniak** [comment]
good catch, thanks for the report! we mainly use the vanilla flag for testing on AWS right now, but it makes total sense to catch up with the other platforms too.
