### ISSUE TITLE
Allow `make plan|apply` without building installer for vanilla k8s

### ISSUE THREAD

**Issue by discordianfish** [coreos/tectonic-installer#961]
The `plan` and `apply` Makefile targets don't require(*) the tectonic installer ("that thing in `install/`") but specify it is as dependency anyway. This is especially a problem since building the frontend isn't cheap and has a few external dependencies (like yarn).

It would be nice to remove that dependency. I'm not sure where exactly install/ is needed but with some clarification I can submit a PR.

*) At least not for vanilla k8s

**Comment by Quentin-M** [comment]
Hey,

In the case of the bare-metal platform, it does: the Tectonic Installer is used to serve the [matchbox-provider](https://github.com/coreos/terraform-provider-matchbox) [[1]](https://github.com/coreos/tectonic-installer/blob/master/terraformrc.example). You may however manually install the provider.

**Comment by discordianfish** [comment]
@Quentin-M Not sure yet how (yay Makefiles!), but would you accept a PR to make the dependency optional if PLATFORM!=metal? Or some other ideas how to make this more reusable?

**Comment by Quentin-M** [comment]
Sure thing, any contribution is more than welcomed!
I would be happy to review it.

**Comment by sym3tri** [comment]
Seems like this won't be happening and we've removed the ability to do "vanilla k8s" installs.
