### ISSUE TITLE
tectonic identity static password validation timeout

### ISSUE THREAD

**Issue by colhom** [coreos/tectonic-installer#978]
Raising the cost when generating admin console passwords with `bcrypt-tool` results in increased runtime for bcrypt password generation and validation. For instance, generating a hash with `-cost=15` results in `POST identity/auth/local` call taking 30 seconds. Much higher than that, and the call will HTTP timeout regularly with no log output or indication of error.

We should make sure that users do not supply a password hash to tectonic-identity that takes excessively long to validate against- probably somewhere around the default of `-cost=10` would be ideal.

Related #643

\cc @ericchiang

**Comment by colhom** [comment]
Also related: https://github.com/coreos/dex/issues/962

**Comment by ericchiang** [comment]
Can this be documentation instead of strict enforcement?

**Comment by colhom** [comment]
Yeah, that would be good catch-all for now.

**Comment by sym3tri** [comment]
moved internally
