### ISSUE TITLE
resource names should have consistent delimiters

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/tectonic-installer#993]
Currently we have a mix of dashes `-` and underscores `_` for resource names. We should make this consistent.

**Comment by jasminSPC** [comment]
@s-urbaniak `_` more commonly used than `-` so should we stick to underscore?

**Comment by justaugustus** [comment]
@jasminSPC I spoke to @s-urbaniak about this last week and the preference was toward hyphens.

**Comment by jasminSPC** [comment]
@justaugustus So variables like
```
variable "master_az_count" {
  type = "string"
}
```

Should become 
```
variable "master-az-count" {
  type = "string"
}
```
Is this correct?

**Comment by edevenport** [comment]
@jasminSPC We agreed during the last meeting that we should use underscores since this remains consistent with Terraform resource and variable names.

**Comment by edevenport** [comment]
AWS, Acure, OpenStack, and Bare Metal provider templates have been updated and all PRs merged.
