### ISSUE TITLE
Get automated smoke tests working for Azure

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#997]
This is 1st priority before doing work on the actual code.

Don't want these tests to interfere with the other stable platforms until Azure itself becomes stable. But need a way to run these in an automated fashion via Jenkins (nightly, or trigger?). Once Azure is stable we can run on every PR just like AWS.

**Comment by Quentin-M** [comment]
Linking associated PR: https://github.com/coreos/tectonic-installer/pull/1070

**Comment by Quentin-M** [comment]
The current status is that the smoke tests are basically written - and are currently showing red. Alex has been working hard on revamping the Azure provider in order to get these tests to pass and support the features we expect it to have for the Beta graduation (e.g. swappable DNS).

**Comment by s-urbaniak** [comment]
addressed in #1154

**Comment by sym3tri** [comment]
@s-urbaniak @mxinden you guys ok to close this out now?

**Comment by mxinden** [comment]
@sym3tri Yes, sorry for missing this.
