### ISSUE TITLE
Automated Hyperkube Tests

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#998]
We should be running nightly or triggered tests of the installer with the latest Hyperkube images using the latest version of the installer.

**Comment by sym3tri** [comment]
Hey @mxinden,
@alexsomesan will sync with you on details for this next week.

**Comment by mxinden** [comment]
@sym3tri Sounds good. @alexsomesan Let me know when it works best for you.

**Comment by Quentin-M** [comment]
Half-sprint status: Max was OOO last week and therefore this was not started yet.
I highly suggest taking a look at https://jenkins-kube-lifecycle.prod.coreos.systems/view/tectonic-kvo/, as well as our current jobs on https://jenkins-tectonic-installer.prod.coreos.systems/.

**Comment by Quentin-M** [comment]
@alexsomesan Will you be able to sync with @mxinden early this week? Is there any other information you need to get started?

**Comment by mxinden** [comment]
@Quentin-M Thanks for the infos. Can you give me access to the `jenkins-kube-lifecycle`? I will try to sync later tonight with Alex, after the Meetup in Hamburg.

**Comment by Quentin-M** [comment]
@mxinden Thanks! I should have given you access using your `@coreos.com` e-mail address just now.

**Comment by mxinden** [comment]
@Quentin-M @sym3tri Status Update: I am currently working with Alex on making the hyperkube image configurable (See PR #1200). I will create an additional Jenkins job that either periodically polls for changes on the hyperkube quay repo or gets triggered via Quay hooks . I will add a parameter to our main pipeline specifying the hyperkube image, which is then propagated to the tests accordingly. This enables the new job to trigger the main pipeline with the newest hyperkube image via the `build` step. In the long run we can extend this by additional parameters / external dependencies of the tectonic-installer.

This involves quite a lot of changes in our existing bash scripts. Thereby I would like to do a little spike on possible testing frameworks / test grids for our meeting on Thursday first.

What do you think?

/CC @alexsomesan

**Comment by Quentin-M** [comment]
PR #1200 scares me a bit as it adds a lot of complexity across the repository. Couldn't `sed` be used instead to simply match and replace hyperkube's version?

The bash scripts have been pretty hard to maintain for the team during the past weeks. I would try to avoid introducing lots of complexity in there, unless strictly necessary.

In Thursday meeting, we will discuss the possibility of replacing these bash scripts with Go code for cluster provisioning and smoke testing, which would definitely help your case!

**Comment by mxinden** [comment]
For documentation purposes: #1200 is closed. This issue depends on #1445, which I would like to focus on first.

**Comment by sym3tri** [comment]
@mxinden I'm closing this out. Can you please make sure any ongoing/remaining work is tracked in jira?

**Comment by mxinden** [comment]
@sym3tri Will do, thanks.
